In [3]:
import os
import requests
import time

from dotenv import load_dotenv

In [4]:
# Loading the .env file from one folder above notebooks.
# Grab the value stored in STATS_API_KEY
load_dotenv("../.env")

stats_api_key = os.getenv("STATS_API_KEY")

print("TheStatsAPI key loaded:", stats_api_key is not None)

TheStatsAPI key loaded: True

In [5]:
# Instead of repeating the url, we store it as BASE_URL
BASE_URL = "https://api.thestatsapi.com/api/football"

# Our version of authentication.
headers = {
    "Authorization": f"Bearer {stats_api_key}"
}

In [6]:
# We're packaging what we did yesterday into one reusable function
# Later we will be able to request and the function will handle everything and convert JSON response.
def get_api_data(url, max_retries = 5):
    wait_time = 5

    for attempt in range(max_retries):
        try:
            response = requests.get(
                url,
                headers = headers,
                timeout = 30
            )

        except requests.exceptions.RequestException as e:
            print(
                f"Connection error: {e}."
                f"Waiting {wait_time} seconds before retry "
                f"{attempt + 1}/{max_retries}..."
            )

        if response.status_code == 200:
            return response.json()

        if response.status_code == 429:
            print(
                f"Rate limit reached. "
                f"Waiting {wait_time} seconds before retry "
                f"{attempt + 1}/{max_retries}"
            )

            time.sleep(wait_time)
            wait_time *= 2
            continue

        print("Request failed:", response.status_code)
        print(response.text[:500])
        return None

    print("Request failed after maximum retries.")
    return None


# This whole process is called exponential backoff. 
# We don't want to keep retrying because this will lead to incomplete data.
# We want each match to be saved in one single try, not multiple retries.

In [7]:
# This function takes a match ID and builds the correct endpoint URL.
# The URL is then sent through the get_api_data function we created.
def get_match_details(match_id):
    url = f"{BASE_URL}/matches/{match_id}"
    return get_api_data(url)

In [8]:
match_id = "mt_511976372"

# Takes a match ID and returns a clean match record.
match_details = get_match_details(match_id)

print(match_details)

{'data': {'id': 'mt_511976372', 'competition_id': 'comp_3039', 'competition_name': 'Premier League', 'season_id': 'sn_8406098', 'matchday': 1, 'stage_name': None, 'group_label': None, 'status': 'finished', 'utc_date': '2026-08-21T19:00:00.000Z', 'home_team': {'id': 'tm_9145', 'name': 'Arsenal'}, 'away_team': {'id': 'tm_2954', 'name': 'Coventry City'}, 'score': {'home': 3, 'away': 0, 'final_score': None, 'regulation': {'home': 3, 'away': 0}, 'after_extra_time': None, 'penalty_shootout': None, 'went_to_extra_time': False, 'went_to_penalties': False, 'winner': 'home', 'half_time_home': 2, 'half_time_away': 0}, 'venue': {'name': 'Emirates Stadium', 'city': 'London'}, 'is_neutral': False, 'referee': {'id': 'ref_72946204', 'name': 'Thomas Bramall'}, 'odds_available': True, 'live_odds_available': False, 'xg_available': True}}

In [9]:
# Let's clean up our output so it's not just one messy Python dictionary.
match = match_details["data"]

print("Competition:", match["competition_name"])
print("Matchday:", match["matchday"])
print("Date:", match["utc_date"])
print("Home team:", match["home_team"]["name"])
print("Away team:", match["away_team"]["name"])
print("Score:", match["score"]["home"], "-", match["score"]["away"])
print("Venue:", match["venue"]["name"])
print("Referee:", match["referee"]["name"])
print("xG available:", match["xg_available"])
print("Odds available:", match["odds_available"])

Competition: Premier League
Matchday: 1
Date: 2026-08-21T19:00:00.000Z
Home team: Arsenal
Away team: Coventry City
Score: 3 - 0
Venue: Emirates Stadium
Referee: Thomas Bramall
xG available: True
Odds available: True

In [10]:
# Creating a function that retrieves statistics given a specific Match ID.
def get_match_statistics(match_id):
    url = f"{BASE_URL}/matches/{match_id}/stats"
    return get_api_data(url)

In [11]:
match_statistics = get_match_statistics(match_id)
print(match_statistics.keys())

dict_keys(['data'])

In [12]:
# Cleaning up our match statistics
# Going from a messy Python dictionary to a clean format.

stats = match_statistics["data"]

print("Possession:", stats["overview"]["ball_possession"]["all"])
print("xG:", stats["overview"]["expected_goals"]["all"])
print("Shots:", stats["overview"]["total_shots"]["all"])
print("Shots on target:", stats["overview"]["shots_on_target"]["all"])
print("Passes:", stats["overview"]["passes"]["all"])
print("Corners:", stats["overview"]["corner_kicks"]["all"])

Possession: {'home': 64, 'away': 36}
xG: {'home': 1.88, 'away': 0.2}
Shots: {'home': 20, 'away': 4}
Shots on target: {'home': 6, 'away': 1}
Passes: {'home': 616, 'away': 347}
Corners: {'home': 8, 'away': 2}

In [13]:
# Creating a function to retrieve team lineups
def get_match_lineups(match_id):
    url = f"{BASE_URL}/matches/{match_id}/lineups"
    return get_api_data(url)

In [14]:
# Testing lineups function
match_lineups = get_match_lineups(match_id)
print(match_lineups.keys())

dict_keys(['data'])

In [15]:
# Cleaning our lineup dictionary
lineups = match_lineups["data"]

print("Home team:", lineups["home"]["name"])
print("Home formation:", lineups["home"]["formation"])
print("Away team:", lineups["away"]["name"])
print("Away formation:", lineups["away"]["formation"])

Home team: Arsenal
Home formation: 4-3-3
Away team: Coventry City
Away formation: 4-3-3

In [16]:
# Used to show not just the team formation, but the specific players in the lineup.
for player in lineups["home"]["starting_xi"]:
    print(
        player["jersey_number"],
        "-",
        player["name"],
        "-",
        player["position"]
    )

1 - David Raya - G
3 - Cristhian Mosquera - D
4 - Ben White - D
6 - Gabriel Magalhães - D
33 - Riccardo Calafiori - D
8 - Martin Ødegaard - M
41 - Declan Rice - M
49 - Myles Lewis-Skelly - M
7 - Bukayo Saka - F
17 - Christos Tzolis - F
29 - Kai Havertz - F

In [17]:
# Creating a function to retrieve specific player's match stats.
def get_match_player_stats(match_id):
    url = f"{BASE_URL}/matches/{match_id}/player-stats"
    return get_api_data(url)

In [18]:
# Testing match player stats function.
match_player_stats = get_match_player_stats(match_id)
print(match_player_stats.keys())

dict_keys(['data'])

In [19]:
# Retrieving a team's players and looking at their match stats.
player_stats = match_player_stats["data"]

for player in player_stats:
    if player["team_id"] == "tm_9145" and player["started"]:
        print(
            player["player_name"],
            "- Rating:", player["rating"],
            "- Minutes:", player["minutes_played"]
        )

Riccardo Calafiori - Rating: 7.41 - Minutes: 81
Gabriel Magalhães - Rating: 6.09 - Minutes: 90
Ben White - Rating: 8.19 - Minutes: 90
Cristhian Mosquera - Rating: 7.1 - Minutes: 90
Myles Lewis-Skelly - Rating: 7.2 - Minutes: 90
Martin Ødegaard - Rating: 8.76 - Minutes: 76
Bukayo Saka - Rating: 7.69 - Minutes: 68
Kai Havertz - Rating: 7.93 - Minutes: 90
Christos Tzolis - Rating: 7.2 - Minutes: 76
David Raya - Rating: 7.36 - Minutes: 90
Declan Rice - Rating: 7.67 - Minutes: 68

In [20]:
# Creating a function to retrieve shotmaps
def get_match_shotmap(match_id):
    url = f"{BASE_URL}/matches/{match_id}/shotmap"
    return get_api_data(url)

In [21]:
match_shotmap = get_match_shotmap(match_id)
print(match_shotmap.keys())

dict_keys(['match_id', 'event', 'data', 'np_xg_summary', 'meta'])

In [22]:
# Cleaning up our shotmap dictionary.
shots = match_shotmap["data"]

for shot in shots[:5]:
    print(
        shot["minute"],
        "-",
        shot["player_name"],
        "-",
        shot["team_name"],
        "- x:", shot["x"],
        "- y:", shot["y"],
        "- Result:", shot["result"],
        "- xG:", shot["expected_goals"]
    )

5 - Christos Tzolis - Arsenal - x: 15.8 - y: 42 - Result: miss - xG: 0.09
7 - Bukayo Saka - Arsenal - x: 9.2 - y: 58.2 - Result: block - xG: 0.1
8 - Christos Tzolis - Arsenal - x: 15.5 - y: 49.5 - Result: save - xG: 0.08
9 - Declan Rice - Arsenal - x: 28.2 - y: 33.9 - Result: miss - xG: 0.02
13 - Loum Tchaouna - Coventry City - x: 28.4 - y: 64.9 - Result: block - xG: 0.01

In [23]:
# Creating event timeline function.
def get_match_events(match_id):
    url = f"{BASE_URL}/matches/{match_id}/timeline"
    return get_api_data(url)

In [24]:
# Testing our event timeline function.
match_events = get_match_events(match_id)
print(match_events.keys())

dict_keys(['data', 'meta'])

In [25]:
# Testing to see how data is structured, we don't make to make any assumptions.
events_data = match_events["data"]
print(type(events_data))
print(events_data.keys())

<class 'dict'>
dict_keys(['match_id', 'coverage', 'events'])

In [26]:
# Creating a shorter and more readable match timeline.
events = match_events["data"]["events"]

for event in events:
    if event["type"] in ["goal", "yellow_card", "red_card", "substitution"]:
        print(
            event["minute"],
            " -",
            event["type"],
            "-",
            event["team"]["name"] if event["team"] else None,
            "-",
            event["player"]["name"] if event["player"] else None
        )

15  - goal - Arsenal - Kai Havertz
23  - goal - Arsenal - Bukayo Saka
27  - yellow_card - Coventry City - Caleb Yirenkyi
34  - yellow_card - Arsenal - Gabriel Magalhães
49  - goal - Arsenal - Martin Ødegaard
62  - substitution - Coventry City - Victor Torp
68  - substitution - Arsenal - Noni Madueke
68  - substitution - Arsenal - Martín Zubimendi
70  - substitution - Coventry City - Jack Rudoni
70  - substitution - Coventry City - Taiwo Awoniyi
76  - substitution - Arsenal - Mikel Merino
76  - substitution - Arsenal - Eberechi Eze
81  - substitution - Arsenal - Piero Hincapié
82  - substitution - Coventry City - Gustavo Hamer

In [27]:
# Creating a function to retrieve match odds
def get_match_odds(match_id):
    url = f"{BASE_URL}/matches/{match_id}/odds"
    return get_api_data(url)

In [28]:
# Testing our odds function
match_odds = get_match_odds(match_id)
print(match_odds.keys())

dict_keys(['data'])

In [29]:
# Now that we have seen that all our URL endpoints are working, we combine all of our helper functions into one single MASTER function that can retrieve all our info with one request.

def get_full_match_data(match_id):
    return {
        "details": get_match_details(match_id),
        "statistics": get_match_statistics(match_id),
        "lineups": get_match_lineups(match_id),
        "player_stats": get_match_player_stats(match_id),
        "shotmap": get_match_shotmap(match_id),
        "events": get_match_events(match_id),
        "odds": get_match_odds(match_id)
    }

In [30]:
# Testing out our MASTER function
full_match_data = get_full_match_data(match_id)
print(full_match_data.keys())

dict_keys(['details', 'statistics', 'lineups', 'player_stats', 'shotmap', 'events', 'odds'])

In [31]:
get_full_match_data("mt_511976372")

Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5

{'details': {'data': {'id': 'mt_511976372',
   'competition_id': 'comp_3039',
   'competition_name': 'Premier League',
   'season_id': 'sn_8406098',
   'matchday': 1,
   'stage_name': None,
   'group_label': None,
   'status': 'finished',
   'utc_date': '2026-08-21T19:00:00.000Z',
   'home_team': {'id': 'tm_9145', 'name': 'Arsenal'},
   'away_team': {'id': 'tm_2954', 'name': 'Coventry City'},
   'score': {'home': 3,
    'away': 0,
    'final_score': None,
    'regulation': {'home': 3, 'away': 0},
    'after_extra_time': None,
    'penalty_shootout': None,
    'went_to_extra_time': False,
    'went_to_penalties': False,
    'winner': 'home',
    'half_time_home': 2,
    'half_time_away': 0},
   'venue': {'name': 'Emirates Stadium', 'city': 'London'},
   'is_neutral': False,
   'referee': {'id': 'ref_72946204', 'name': 'Thomas Bramall'},
   'odds_available': True,
   'live_odds_available': False,
   'xg_available': True}},
 'statistics': {'data': {'match_id': 'mt_511976372',
   'overview': {'ball_possession': {'all': {'home': 64, 'away': 36},
     'first_half': {'home': 66, 'away': 34},
     'second_half': {'home': 63, 'away': 37}},
    'expected_goals': {'all': {'home': 1.88, 'away': 0.2},
     'first_half': {'home': 1.32, 'away': 0.04},
     'second_half': {'home': 0.56, 'away': 0.16}},
    'big_chances': {'all': {'home': 1, 'away': 1},
     'first_half': {'home': 1, 'away': 0},
     'second_half': {'home': 0, 'away': 1}},
    'total_shots': {'all': {'home': 20, 'away': 4},
     'first_half': {'home': 10, 'away': 2},
     'second_half': {'home': 10, 'away': 2}},
    'shots_on_target': {'all': {'home': 6, 'away': 1},
     'first_half': {'home': 3, 'away': 0},
     'second_half': {'home': 3, 'away': 1}},
    'goalkeeper_saves': {'all': {'home': 1, 'away': 2},
     'first_half': {'home': 0, 'away': 0},
     'second_half': {'home': 1, 'away': 2}},
    'corner_kicks': {'all': {'home': 8, 'away': 2},
     'first_half': {'home': 5, 'away': 1},
     'second_half': {'home': 3, 'away': 1}},
    'fouls': {'all': {'home': 10, 'away': 13},
     'first_half': {'home': 6, 'away': 7},
     'second_half': {'home': 4, 'away': 6}},
    'yellow_cards': {'all': {'home': 1, 'away': 1},
     'first_half': {'home': 1, 'away': 1},
     'second_half': {'home': 0, 'away': 0}},
    'red_cards': {'all': None, 'first_half': None, 'second_half': None},
    'passes': {'all': {'home': 616, 'away': 347},
     'first_half': {'home': 301, 'away': 159},
     'second_half': {'home': 315, 'away': 188}},
    'accurate_passes': {'all': {'home': 565, 'away': 271},
     'first_half': {'home': 275, 'away': 116},
     'second_half': {'home': 290, 'away': 155}},
    'tackles': {'all': {'home': 9, 'away': 4},
     'first_half': {'home': 5, 'away': 1},
     'second_half': {'home': 4, 'away': 4}},
    'free_kicks': {'all': {'home': 13, 'away': 10},
     'first_half': {'home': 7, 'away': 6},
     'second_half': {'home': 6, 'away': 4}}},
   'shots': {'total_shots': {'all': {'home': 20, 'away': 4},
     'first_half': {'home': 10, 'away': 2},
     'second_half': {'home': 10, 'away': 2}},
    'shots_on_target': {'all': {'home': 6, 'away': 1},
     'first_half': {'home': 3, 'away': 0},
     'second_half': {'home': 3, 'away': 1}},
    'shots_off_target': {'all': {'home': 6, 'away': 2},
     'first_half': {'home': 3, 'away': 1},
     'second_half': {'home': 3, 'away': 1}},
    'blocked_shots': {'all': {'home': 8, 'away': 1},
     'first_half': {'home': 4, 'away': 1},
     'second_half': {'home': 4, 'away': 0}},
    'shots_inside_box': {'all': {'home': 10, 'away': 1},
     'first_half': {'home': 6, 'away': 0},
     'second_half': {'home': 4, 'away': 1}},
    'shots_outside_box': {'all': {'home': 10, 'away': 3},
     'first_half': {'home': 4, 'away': 2},
     'second_half': {'home': 6, 'away': 1}},
    'hit_woodwork': {'all': {'home': 0, 'away': 0},
     'first_half': {'home': 0, 'away': 0},
     'second_half': {'home': 0, 'away': 0}}},
   'attack': {'big_chances_missed': {'all': {'home': 0, 'away': 1},
     'first_half': {'home': 0, 'away': 0},
     'second_half': {'home': 0, 'away': 1}},
    'touches_in_penalty_area': {'all': {'home': 36, 'away': 3},
     'first_half': None,
     'second_half': None},
    'fouled_in_final_third': {'all': {'home': 2, 'away': 2},
     'first_half': {'home': 1, 'away': 1},
     'second_half': {'home': 2, 'away': 1}},
    'offsides': {'all': {'home': 5, 'away': 0},
     'first_half': {'home': 3, 'away': 0},
     'second_half': {'home': 2, 'away': 0}}},
   'passes': {'accurate_passes': {'all': {'home': 565, 'away': 271},
     'first_half': {'home': 275, 'away': 116},
     'second_half': {'home': 290, 'away': 155}},
    'throw_ins': {'all': {'home': 11, 'away': 7},
     'first_half': {'home': 4, 'away': 3},
     'second_half': {'home': 7, 'away': 4}},
    'accurate_crosses': {'all': {'home': 1, 'away': 1},
     'first_half': {'home': 1, 'away': 0},
     'second_half': {'home': 0, 'away': 1}},
    'accurate_long_balls': {'all': {'home': 21, 'away': 32},
     'first_half': {'home': 10, 'away': 15},
     'second_half': {'home': 11, 'away': 17}},
    'final_third_entries': {'all': {'home': 57, 'away': 57},
     'first_half': {'home': 22, 'away': 34},
     'second_half': {'home': 35, 'away': 23}}},
   'duels': {'duels_won_percentage': {'all': {'home': 52, 'away': 48},
     'first_half': {'home': 53, 'away': 47},
     'second_half': {'home': 52, 'away': 48}},
    'dispossessed': {'all': {'home': 1, 'away': 3},
     'first_half': {'home': 1, 'away': 2},
     'second_half': {'home': 1, 'away': 1}},
    'dribbles_percentage': {'all': {'home': 4, 'away': 3},
     'first_half': {'home': 2, 'away': 1},
     'second_half': {'home': 2, 'away': 2}},
    'ground_duels_percentage': {'all': {'home': 26, 'away': 17},
     'first_half': {'home': 14, 'away': 7},
     'second_half': {'home': 12, 'away': 10}},
    'aerial_duels_percentage': {'all': {'home': 11, 'away': 17},
     'first_half': {'home': 6, 'away': 11},
     'second_half': {'home': 5, 'away': 6}}},
   'defending': {'tackles': {'all': {'home': 9, 'away': 4},
     'first_half': {'home': 5, 'away': 1},
     'second_half': {'home': 4, 'away': 4}},
    'tackles_won_percentage': {'all': {'home': 6, 'away': 2},
     'first_half': {'home': 3, 'away': 1},
     'second_half': {'home': 3, 'away': 2}},
    'interceptions': {'all': {'home': 5, 'away': 9},
     'first_half': {'home': 3, 'away': 2},
     'second_half': {'home': 2, 'away': 7}},
    'clearances': {'all': {'home': 24, 'away': 30},
     'first_half': {'home': 10, 'away': 15},
     'second_half': {'home': 14, 'away': 15}},
    'ball_recoveries': {'all': {'home': 44, 'away': 42},
     'first_half': {'home': 22, 'away': 18},
     'second_half': {'home': 22, 'away': 24}}},
   'goalkeeping': {'saves': {'all': {'home': 1, 'away': 2},
     'first_half': {'home': 0, 'away': 0},
     'second_half': {'home': 1, 'away': 2}},
    'goal_kicks': {'all': {'home': 5, 'away': 6},
     'first_half': {'home': 1, 'away': 3},
     'second_half': {'home': 4, 'away': 3}},
    'goals_prevented': {'all': {'home': 0.04, 'away': -0.56},
     'first_half': None,
     'second_half': None},
    'high_claims': {'all': {'home': 0, 'away': 1},
     'first_half': None,
     'second_half': None}},
   'np_expected_goals': {'all': {'home': 1.8, 'away': 0.28},
    'first_half': {'home': 1.29, 'away': 0.04},
    'second_half': {'home': 0.51, 'away': 0.24}}}},
 'lineups': {'data': {'match_id': 'mt_511976372',
   'confirmed': True,
   'home': {'id': 'tm_9145',
    'name': 'Arsenal',
    'formation': '4-3-3',
    'starting_xi': [{'id': 'pl_13486574',
      'name': 'David Raya',
      'position': 'G',
      'jersey_number': 1},
     {'id': 'pl_19350393',
      'name': 'Cristhian Mosquera',
      'position': 'D',
      'jersey_number': 3},
     {'id': 'pl_61926368',
      'name': 'Ben White',
      'position': 'D',
      'jersey_number': 4},
     {'id': 'pl_96242662',
      'name': 'Gabriel Magalhães',
      'position': 'D',
      'jersey_number': 6},
     {'id': 'pl_96369277',
      'name': 'Riccardo Calafiori',
      'position': 'D',
      'jersey_number': 33},
     {'id': 'pl_13495135',
      'name': 'Martin Ødegaard',
      'position': 'M',
      'jersey_number': 8},
     {'id': 'pl_08343894',
      'name': 'Declan Rice',
      'position': 'M',
      'jersey_number': 41},
     {'id': 'pl_25832289',
      'name': 'Myles Lewis-Skelly',
      'position': 'M',
      'jersey_number': 49},
     {'id': 'pl_45126714',
      'name': 'Bukayo Saka',
      'position': 'F',
      'jersey_number': 7},
     {'id': 'pl_72792553',
      'name': 'Christos Tzolis',
      'position': 'F',
      'jersey_number': 17},
     {'id': 'pl_45857110',
      'name': 'Kai Havertz',
      'position': 'F',
      'jersey_number': 29}],
    'substitutes': [{'id': 'pl_9898384',
      'name': 'Kepa Arrizabalaga',
      'position': 'G',
      'jersey_number': 13},
     {'id': 'pl_30434127',
      'name': 'Piero Hincapié',
      'position': 'D',
      'jersey_number': 5},
     {'id': 'pl_29771630',
      'name': 'Eberechi Eze',
      'position': 'M',
      'jersey_number': 10},
     {'id': 'pl_97242494',
      'name': 'Ethan Nwaneri',
      'position': 'M',
      'jersey_number': 22},
     {'id': 'pl_13349471',
      'name': 'Mikel Merino',
      'position': 'M',
      'jersey_number': 23},
     {'id': 'pl_30477667',
      'name': 'Martín Zubimendi',
      'position': 'M',
      'jersey_number': 36},
     {'id': 'pl_64932349',
      'name': 'Max Dowman',
      'position': 'M',
      'jersey_number': 56},
     {'id': 'pl_84500047',
      'name': 'Viktor Gyökeres',
      'position': 'F',
      'jersey_number': 14},
     {'id': 'pl_30476420',
      'name': 'Noni Madueke',
      'position': 'F',
      'jersey_number': 20}]},
   'away': {'id': 'tm_2954',
    'name': 'Coventry City',
    'formation': '4-3-3',
    'starting_xi': [{'id': 'pl_13149796',
      'name': 'Carl Rushworth',
      'position': 'G',
      'jersey_number': 19},
     {'id': 'pl_45761686',
      'name': 'Jay DaSilva',
      'position': 'D',
      'jersey_number': 3},
     {'id': 'pl_96911189',
      'name': 'Bobby Thomas',
      'position': 'D',
      'jersey_number': 4},
     {'id': 'pl_61062555',
      'name': 'Aurèle Amenda',
      'position': 'D',
      'jersey_number': 24},
     {'id': 'pl_57964143',
      'name': 'Milan van Ewijk',
      'position': 'D',
      'jersey_number': 27},
     {'id': 'pl_5435116',
      'name': 'Matt Grimes',
      'position': 'M',
      'jersey_number': 6},
     {'id': 'pl_02935210',
      'name': 'Caleb Yirenkyi',
      'position': 'M',
      'jersey_number': 8},
     {'id': 'pl_08977832',
      'name': 'Frank Onyeka',
      'position': 'M',
      'jersey_number': 16},
     {'id': 'pl_45499401',
      'name': 'Loum Tchaouna',
      'position': 'M',
      'jersey_number': 18},
     {'id': 'pl_29752791',
      'name': 'Brandon Thomas-Asante',
      'position': 'M',
      'jersey_number': 23},
     {'id': 'pl_08558182',
      'name': 'Ellis Simms',
      'position': 'F',
      'jersey_number': 9}],
    'substitutes': [{'id': 'pl_1574416',
      'name': 'Ben Wilson',
      'position': 'G',
      'jersey_number': 13},
     {'id': 'pl_61594438',
      'name': 'Liam Kitching',
      'position': 'D',
      'jersey_number': 15},
     {'id': 'pl_57446118',
      'name': 'Joel Latibeaudiere',
      'position': 'D',
      'jersey_number': 22},
     {'id': 'pl_45280168',
      'name': 'Jack Rudoni',
      'position': 'M',
      'jersey_number': 5},
     {'id': 'pl_30410482',
      'name': 'Tatsuhiro Sakamoto',
      'position': 'M',
      'jersey_number': 7},
     {'id': 'pl_45144065',
      'name': 'Josh Eccles',
      'position': 'M',
      'jersey_number': 28},
     {'id': 'pl_29797965',
      'name': 'Victor Torp',
      'position': 'M',
      'jersey_number': 29},
     {'id': 'pl_45858279',
      'name': 'Gustavo Hamer',
      'position': 'M',
      'jersey_number': 38},
     {'id': 'pl_0975219',
      'name': 'Taiwo Awoniyi',
      'position': 'F',
      'jersey_number': 14}]}}},
 'player_stats': {'data': [{'player_id': 'pl_57964143',
    'player_name': 'Milan van Ewijk',
    'team_id': 'tm_2954',
    'club_team_id': None,
    'position': 'D',
    'rating': 5.18,
    'started': True,
    'played': True,
    'minutes_played': 90,
    'passing': {'total_passes': 19,
     'accurate_passes': 14,
     'key_passes': 0,
     'assists': 0,
     'total_crosses': 0,
     'accurate_crosses': 0,
     'total_long_balls': 2,
     'accurate_long_balls': 0},
    'shooting': {'goals': 0,
     'total_shots': 0,
     'shots_on_target': 0,
     'shots_off_target': 0,
     'blocked_shots': 0,
     'big_chances_created': 0,
     'expected_goals': 0,
     'expected_assists': 0.01,
     'np_expected_goals': 0},
    'duels': {'duel_won': 1,
     'duel_lost': 4,
     'aerial_won': 0,
     'challenge_lost': 0,
     'won_contest': 0,
     'dispossessed': 1},
    'defending': {'tackles': 1,
     'interceptions': 1,
     'clearances': 3,
     'ball_recoveries': 3},
    'goalkeeping': {'saves': 0},
    'general': {'touches': 32,
     'fouls': 2,
     'was_fouled': 0,
     'offsides': 0,
     'yellow_cards': 0,
     'red_cards': 0,
     'possession_lost': 8,
     'player_subbed_on': None,
     'player_subbed_off': None}},
   {'player_id': 'pl_29752791',
    'player_name': 'Brandon Thomas-Asante',
    'team_id': 'tm_2954',
    'club_team_id': None,
    'position': 'M',
    'rating': 6.58,
    'started': True,
    'played': True,
    'minutes_played': 70,
    'passing': {'total_passes': 10,
     'accurate_passes': 6,
     'key_passes': 0,
     'assists': 0,
     'total_crosses': 1,
     'accurate_crosses': 0,
     'total_long_balls': 1,
     'accurate_long_balls': 0},
    'shooting': {'goals': 0,
     'total_shots': 0,
     'shots_on_target': 0,
     'shots_off_target': 0,
     'blocked_shots': 0,
     'big_chances_created': 0,
     'expected_goals': 0,
     'expected_assists': 0.02,
     'np_expected_goals': 0},
    'duels': {'duel_won': 4,
     'duel_lost': 5,
     'aerial_won': 2,
     'challenge_lost': 1,
     'won_contest': 0,
     'dispossessed': 0},
    'defending': {'tackles': 0,
     'interceptions': 4,
     'clearances': 1,
     'ball_recoveries': 1},
    'goalkeeping': {'saves': 0},
    'general': {'touches': 21,
     'fouls': 0,
     'was_fouled': 2,
     'offsides': 0,
     'yellow_cards': 0,
     'red_cards': 0,
     'possession_lost': 6,
     'player_subbed_on': 'pl_45280168',
     'player_subbed_off': None}},
   {'player_id': 'pl_02935210',
    'player_name': 'Caleb Yirenkyi',
    'team_id': 'tm_2954',
    'club_team_id': None,
    'position': 'M',
    'rating': 6.32,
    'started': True,
    'played': True,
    'minutes_played': 62,
    'passing': {'total_passes': 13,
     'accurate_passes': 10,
     'key_passes': 0,
     'assists': 0,
     'total_crosses': 0,
     'accurate_crosses': 0,
     'total_long_balls': 0,
     'accurate_long_balls': 0},
    'shooting': {'goals': 0,
     'total_shots': 0,
     'shots_on_target': 0,
     'shots_off_target': 0,
     'blocked_shots': 0,
     'big_chances_created': 0,
     'expected_goals': 0,
     'expected_assists': 0,
     'np_expected_goals': 0},
    'duels': {'duel_won': 1,
     'duel_lost': 2,
     'aerial_won': 1,
     'challenge_lost': 0,
     'won_contest': 0,
     'dispossessed': 0},
    'defending': {'tackles': 0,
     'interceptions': 0,
     'clearances': 0,
     'ball_recoveries': 3},
    'goalkeeping': {'saves': 0},
    'general': {'touches': 15,
     'fouls': 2,
     'was_fouled': 0,
     'offsides': 0,
     'yellow_cards': 1,
     'red_cards': 0,
     'possession_lost': 3,
     'player_subbed_on': 'pl_29797965',
     'player_subbed_off': None}},
   {'player_id': 'pl_08977832',
    'player_name': 'Frank Onyeka',
    'team_id': 'tm_2954',
    'club_team_id': None,
    'position': 'M',
    'rating': 6.58,
    'started': True,
    'played': True,
    'minutes_played': 90,
    'passing': {'total_passes': 22,
     'accurate_passes': 16,
     'key_passes': 0,
     'assists': 0,
     'total_crosses': 0,
     'accurate_crosses': 0,
     'total_long_balls': 4,
     'accurate_long_balls': 4},
    'shooting': {'goals': 0,
     'total_shots': 0,
     'shots_on_target': 0,
     'shots_off_target': 0,
     'blocked_shots': 0,
     'big_chances_created': 0,
     'expected_goals': 0,
     'expected_assists': 0,
     'np_expected_goals': 0},
    'duels': {'duel_won': 2,
     'duel_lost': 4,
     'aerial_won': 0,
     'challenge_lost': 1,
     'won_contest': 0,
     'dispossessed': 0},
    'defending': {'tackles': 1,
     'interceptions': 3,
     'clearances': 0,
     'ball_recoveries': 5},
    'goalkeeping': {'saves': 0},
    'general': {'touches': 29,
     'fouls': 3,
     'was_fouled': 1,
     'offsides': 0,
     'yellow_cards': 0,
     'red_cards': 0,
     'possession_lost': 7,
     'player_subbed_on': None,
     'player_subbed_off': None}},
   {'player_id': 'pl_45499401',
    'player_name': 'Loum Tchaouna',
    'team_id': 'tm_2954',
    'club_team_id': None,
    'position': 'M',
    'rating': 6.58,
    'started': True,
    'played': True,
    'minutes_played': 82,
    'passing': {'total_passes': 30,
     'accurate_passes': 22,
     'key_passes': 0,
     'assists': 0,
     'total_crosses': 2,
     'accurate_crosses': 0,
     'total_long_balls': 2,
     'accurate_long_balls': 0},
    'shooting': {'goals': 0,
     'total_shots': 2,
     'shots_on_target': 0,
     'shots_off_target': 1,
     'blocked_shots': 1,
     'big_chances_created': 0,
     'expected_goals': 0.04,
     'expected_assists': 0.02,
     'np_expected_goals': 0.04},
    'duels': {'duel_won': 4,
     'duel_lost': 5,
     'aerial_won': 1,
     'challenge_lost': 0,
     'won_contest': 1,
     'dispossessed': 1},
    'defending': {'tackles': 0,
     'interceptions': 0,
     'clearances': 3,
     'ball_recoveries': 5},
    'goalkeeping': {'saves': 0},
    'general': {'touches': 44,
     'fouls': 1,
     'was_fouled': 2,
     'offsides': 0,
     'yellow_cards': 0,
     'red_cards': 0,
     'possession_lost': 13,
     'player_subbed_on': 'pl_45858279',
     'player_subbed_off': None}},
   {'player_id': 'pl_61062555',
    'player_name': 'Aurèle Amenda',
    'team_id': 'tm_2954',
    'club_team_id': None,
    'position': 'D',
    'rating': 6.71,
    'started': True,
    'played': True,
    'minutes_played': 90,
    'passing': {'total_passes': 33,
     'accurate_passes': 28,
     'key_passes': 0,
     'assists': 0,
     'total_crosses': 0,
     'accurate_crosses': 0,
     'total_long_balls': 11,
     'accurate_long_balls': 8},
    'shooting': {'goals': 0,
     'total_shots': 0,
     'shots_on_target': 0,
     'shots_off_target': 0,
     'blocked_shots': 0,
     'big_chances_created': 0,
     'expected_goals': 0,
     'expected_assists': 0.01,
     'np_expected_goals': 0},
    'duels': {'duel_won': 1,
     'duel_lost': 3,
     'aerial_won': 1,
     'challenge_lost': 0,
     'won_contest': 0,
     'dispossessed': 0},
    'defending': {'tackles': 0,
     'interceptions': 0,
     'clearances': 6,
     'ball_recoveries': 4},
    'goalkeeping': {'saves': 0},
    'general': {'touches': 43,
     'fouls': 1,
     'was_fouled': 0,
     'offsides': 0,
     'yellow_cards': 0,
     'red_cards': 0,
     'possession_lost': 5,
     'player_subbed_on': None,
     'player_subbed_off': None}},
   {'player_id': 'pl_5435116',
    'player_name': 'Matt Grimes',
    'team_id': 'tm_2954',
    'club_team_id': None,
    'position': 'M',
    'rating': 7.36,
    'started': True,
    'played': True,
    'minutes_played': 90,
    'passing': {'total_passes': 56,
     'accurate_passes': 50,
     'key_passes': 0,
     'assists': 0,
     'total_crosses': 3,
     'accurate_crosses': 0,
     'total_long_balls': 3,
     'accurate_long_balls': 0},
    'shooting': {'goals': 0,
     'total_shots': 0,
     'shots_on_target': 0,
     'shots_off_target': 0,
     'blocked_shots': 0,

In [32]:
# Automating pulling match IDs
# No more hard coding specific matches.

def get_season_matches(competition_id, season_id):
    url = (
        f"{BASE_URL}/matches"
        f"?competition_id={competition_id}"
        f"&season_id={season_id}"
    )

    return get_api_data(url)

In [33]:
# Testing getting season matches function.
season_matches = get_season_matches(
    "comp_3039",
    "sn_8406098"
)

print(season_matches.keys())

dict_keys(['data', 'meta'])

In [34]:
# Looking to see how many matches were returned from the URL
print("Matches returned:", len(season_matches["data"]))
print("Meta:", season_matches["meta"])

Matches returned: 20
Meta: {'page': 1, 'per_page': 20, 'total': 50, 'total_pages': 3}

In [35]:
for match in season_matches["data"][:10]:
    print(
        match["id"],
        "-",
        match["matchday"],
        "-",
        match["home_team"]["name"],
        "vs",
        match["away_team"]["name"],
        "-",
        match["status"]
    )

mt_988360482 - 5 - Fulham vs Manchester United - scheduled
mt_899742694 - 5 - Bournemouth vs Liverpool - scheduled
mt_733622110 - 5 - Nottingham Forest vs Coventry City - scheduled
mt_899744220 - 5 - Newcastle United vs Hull City - scheduled
mt_377400558 - 5 - Manchester City vs Sunderland - scheduled
mt_644011884 - 5 - Leeds United vs Crystal Palace - scheduled
mt_200193806 - 5 - Everton vs Ipswich Town - scheduled
mt_155834755 - 5 - Brighton & Hove Albion vs Arsenal - scheduled
mt_155833448 - 5 - Tottenham Hotspur vs Aston Villa - scheduled
mt_733621034 - 5 - Brentford vs Chelsea - scheduled

In [36]:
# Building pagination, each page fits 20 matches, we currently have a total of 50, so we need 3 pages
def get_all_season_matches(competition_id, season_id):
    all_matches = []

    # We start at page 1 and adds the matches into our array: all_matches
    page = 1

    while True:
        url = (
            f"{BASE_URL}/matches"
            f"?competition_id={competition_id}"
            f"&season_id={season_id}"
            f"&page={page}"
        )

        response = get_api_data(url)

        if response is None:
            break

        # extend() function takes all the matches from that page and adds them to our master list
        all_matches.extend(response["data"])

        # API told us there are 3 pages, so Python will separate into 20 matches in the first 2 pages, then 10 in the last page and then combine them into one list of 50 matches.
        if page >= response["meta"]["total_pages"]:
            break

        page += 1

        # Gives the API a pause so we don't hit a rate limit.
        time.sleep(1)

    return all_matches

In [37]:
# Testing our match getting function
all_season_matches = get_all_season_matches(
    "comp_3039",
    "sn_8406098"
)

print("Total matches collected:", len(all_season_matches))

Total matches collected: 50

In [38]:
# Our function is showing us finished AND future scheduled matches
# We want to separate matches that have already finished and the ones that haven't been played yet.

finished_matches = [
    match for match in all_season_matches
    if match["status"] == "finished"
]

scheduled_matches = [
    match for match in all_season_matches
    if match["status"] == "scheduled"
]

print("Finished matches:", len(finished_matches))
print("Scheduled matches:", len(scheduled_matches))

Finished matches: 15
Scheduled matches: 35

In [39]:
# Let's take a look at the finished matches.

for match in finished_matches:
    print(
        match["matchday"],
        "-",
        match["home_team"]["name"],
        "vs",
        match["away_team"]["name"],
        "-",
        match["score"]["home"],
        "-",
        match["score"]["away"]
    )

2 - Tottenham Hotspur vs Newcastle United - 0 - 2
2 - Coventry City vs Hull City - 0 - 1
2 - Bournemouth vs Everton - 1 - 1
2 - Liverpool vs Nottingham Forest - 2 - 2
2 - Crystal Palace vs Manchester City - 1 - 4
1 - Fulham vs Chelsea - 2 - 3
1 - Newcastle United vs Liverpool - 2 - 2
1 - Manchester City vs Bournemouth - 2 - 1
1 - Brighton & Hove Albion vs Aston Villa - 4 - 0
1 - Brentford vs Tottenham Hotspur - 3 - 0
1 - Ipswich Town vs Sunderland - 2 - 1
1 - Everton vs Crystal Palace - 2 - 0
1 - Nottingham Forest vs Leeds United - 0 - 1
1 - Hull City vs Manchester United - 2 - 0
1 - Arsenal vs Coventry City - 3 - 0

In [40]:
# Create a lighter function to inspect past matches (historical modeling)

def get_model_match_data(match_id):
    full_data = {}

    full_data["details"] = get_match_details(match_id)
    time.sleep(2)

    full_data["statistics"] = get_match_statistics(match_id)
    time.sleep(2)

    full_data["lineups"] = get_match_lineups(match_id)
    time.sleep(2)

    full_data["player_stats"] = get_match_player_stats(match_id)
    time.sleep(2)

    full_data["odds"] = get_match_odds(match_id)

    missing = [
        section
        for section, value in full_data.items()
        if value is None
    ]

    if missing:
        print("Incomplete match data. Missing:", missing)
        return None

    return full_data

In [41]:
# Testing our function on one completed match.
test_model_data = get_model_match_data(finished_matches[0]["id"])
print(test_model_data.keys())

dict_keys(['details', 'statistics', 'lineups', 'player_stats', 'odds'])

In [42]:
# Saving our matches

import json
from pathlib import Path

In [43]:
RAW_MATCH_DIR = Path("../data/raw/matches")
RAW_MATCH_DIR.mkdir(parents = True, exist_ok = True)
print(RAW_MATCH_DIR)

..\data\raw\matches

In [44]:
# Creating a function that saves the match into the correct folder.

def save_match_data(match_id, match_data, save_dir):
    # Creating the filename.
    file_path = save_dir / f"{match_id}.json"

    # We open the file and write (w)
    # utf-8 makes sure special characters are also stored.
    with open(file_path, "w", encoding = "utf-8") as f:
        # match_data is a Python dictionary, so json.dump takes it and writes it into a .json file.
        json.dump(match_data, f, indent = 2, ensure_ascii = False)

    return file_path

In [45]:
# Save our first match

test_match_id = finished_matches[0]["id"]

saved_path = save_match_data(
    test_match_id,
    test_model_data,
    RAW_MATCH_DIR / "2026_27"
)

print("Saved to:", saved_path)

Saved to: ..\data\raw\matches\2026_27\mt_644018139.json

In [46]:
# Automating the entire saving matches process.

# Going through every finished match in our list.
for match in finished_matches:
    match_id = match["id"]
    file_path = RAW_MATCH_DIR / "2026_27" / f"{match_id}.json"

    # If the match has already been saved, we skip that match.
    if file_path.exists():
        print("Skipping:", match_id, "- already saved")
        continue

    # If the match doesn't already exist, we save the match.
    print(
        "Collecting:",
        match["home_team"]["name"],
        "vs",
        match["away_team"]["name"]
    )

    # Pulls the model data
    match_data = get_model_match_data(match_id)

    # Saves the data
    if match_data is not None:
        save_match_data(
            match_id, 
            match_data,
            RAW_MATCH_DIR / "2026_27"
        )
        
        print("Saved:", match_id)

    # 2 second pause to avoid hitting the rate limit.
    time.sleep(2)

Skipping: mt_644018139 - already saved
Collecting: Coventry City vs Hull City
Saved: mt_155834351
Collecting: Bournemouth vs Everton
Saved: mt_377405071
Collecting: Liverpool vs Nottingham Forest
Saved: mt_022587842
Collecting: Crystal Palace vs Manchester City
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
Saved: mt_988360616
Skipping: mt_022587821 - already saved
Skipping: mt_644018143 - already saved
Skipping: mt_511976717 - already saved
Skipping: mt_644018124 - already saved
Skipping: mt_988360680 - already saved
Skipping: mt_644018510 - already saved
Skipping: mt_466259151 - already saved
Skipping: mt_899742430 - already saved
Skipping: mt_022587983 - already saved
Skipping: mt_511976372 - already saved

In [47]:
# Let's check if everything was saved properly

for file_path in RAW_MATCH_DIR.glob("*.json"):
    with open(file_path, "r", encoding = "utf-8") as f:
        data = json.load(f)

    missing = [
        section
        for section, value in data.items()
        if value is None
    ]

    if missing:
        print(file_path.name, "- MISSING:", missing)
    else:
        print(file_path.name, "- COMPLETE")

In [48]:
import pandas as pd

In [49]:
# A JSON file might be too nested for machine learning purposes.
# This function takes a JSON dictionary and turns it into something flat where each match becomes a row in our future dataset.
def extract_match_row(match_data):
    details = match_data["details"]["data"]
    stats = match_data["statistics"]["data"]
    lineups = match_data["lineups"]["data"]

    return {
        "match_id": details["id"],
        "date": details["utc_date"],
        "matchday": details["matchday"],

        "home_team": details["home_team"]["name"],
        "away_team": details["away_team"]["name"],

        "home_goals": details["score"]["home"],
        "away_goals": details["score"]["away"],

        "home_xg": stats["overview"]["expected_goals"]["all"]["home"],
        "away_xg": stats["overview"]["expected_goals"]["all"]["away"],

        "home_shots": stats["overview"]["total_shots"]["all"]["home"],
        "away_shots": stats["overview"]["total_shots"]["all"]["away"],

        "home_shots_on_target": stats["overview"]["shots_on_target"]["all"]["home"],
        "away_shots_on_target": stats["overview"]["shots_on_target"]["all"]["away"],

        "home_possession": stats["overview"]["ball_possession"]["all"]["home"],
        "away_possession": stats["overview"]["ball_possession"]["all"]["away"],

        "home_passes": stats["overview"]["passes"]["all"]["home"],
        "away_passes": stats["overview"]["passes"]["all"]["away"],

        "home_corners": stats["overview"]["corner_kicks"]["all"]["home"],
        "away_corners": stats["overview"]["corner_kicks"]["all"]["away"],

        "home_formation": lineups["home"]["formation"],
        "away_formation": lineups["away"]["formation"],

        "winner": details["score"]["winner"]
    }

In [50]:
# Now each row will correspond to a JSON file

match_rows = []

for file_path in (RAW_MATCH_DIR / "2026_27").glob("*.json"):
    with open(file_path, "r", encoding = "utf-8") as f:
        match_data = json.load(f)

    row = extract_match_row(match_data)
    match_rows.append(row)


matches_df = pd.DataFrame(match_rows)

In [51]:
# Inspecting our match-level DataFrame
print(matches_df.shape)
matches_df.head()

(15, 22)

,match_id,date,matchday,home_team,away_team,home_goals,away_goals,home_xg,away_xg,home_shots,...,away_shots_on_target,home_possession,away_possession,home_passes,away_passes,home_corners,away_corners,home_formation,away_formation,winner
0,mt_022587821,2026-08-24T19:00:00.000Z,1,Fulham,Chelsea,2,3,1.33,2.24,14,...,6,62,38,639,394,6,4,4-2-3-1,3-4-3,away
1,mt_022587842,2026-08-29T11:30:00.000Z,2,Liverpool,Nottingham Forest,2,2,1.61,2.30,13,...,3,70,30,625,281,3,5,4-2-3-1,3-4-2-1,draw
2,mt_022587983,2026-08-22T11:30:00.000Z,1,Hull City,Manchester United,2,0,1.26,1.81,8,...,5,29,71,253,654,1,6,3-4-2-1,4-2-3-1,home
3,mt_155834351,2026-08-29T14:00:00.000Z,2,Coventry City,Hull City,0,1,1.28,0.73,11,...,2,69,31,570,262,6,2,4-2-3-1,5-4-1,away
4,mt_377405071,2026-08-29T14:00:00.000Z,2,Bournemouth,Everton,1,1,2.14,1.72,17,...,7,59,41,444,312,10,7,4-2-3-1,4-2-3-1,draw

In [52]:
# Check to see if all our variables have the correct data type.
matches_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   match_id              15 non-null     str
 1   date                  15 non-null     str
 2   matchday              15 non-null     int64
 3   home_team             15 non-null     str
 4   away_team             15 non-null     str
 5   home_goals            15 non-null     int64
 6   away_goals            15 non-null     int64
 7   home_xg               15 non-null     float64
 8   away_xg               15 non-null     float64
 9   home_shots            15 non-null     int64
 10  away_shots            15 non-null     int64
 11  home_shots_on_target  15 non-null     int64
 12  away_shots_on_target  15 non-null     int64
 13  home_possession       15 non-null     int64
 14  away_possession       15 non-null     int64
 15  home_passes           15 non-null     int64
 16  away_passes           15 non-null     int64
 17  home_corners          15 non-null     int64
 18  away_corners          15 non-null     int64
 19  home_formation        15 non-null     str
 20  away_formation        15 non-null     str
 21  winner                15 non-null     str
dtypes: float64(2), int64(13), str(7)
memory usage: 2.7 KB

In [53]:
# We see if there are any null valuables in our columns.
matches_df.isnull().sum()

match_id                0
date                    0
matchday                0
home_team               0
away_team               0
home_goals              0
away_goals              0
home_xg                 0
away_xg                 0
home_shots              0
away_shots              0
home_shots_on_target    0
away_shots_on_target    0
home_possession         0
away_possession         0
home_passes             0
away_passes             0
home_corners            0
away_corners            0
home_formation          0
away_formation          0
winner                  0
dtype: int64

In [54]:
matches_df["date"] = pd.to_datetime(matches_df["date"], utc = True)
matches_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   match_id              15 non-null     str
 1   date                  15 non-null     datetime64[us, UTC]
 2   matchday              15 non-null     int64
 3   home_team             15 non-null     str
 4   away_team             15 non-null     str
 5   home_goals            15 non-null     int64
 6   away_goals            15 non-null     int64
 7   home_xg               15 non-null     float64
 8   away_xg               15 non-null     float64
 9   home_shots            15 non-null     int64
 10  away_shots            15 non-null     int64
 11  home_shots_on_target  15 non-null     int64
 12  away_shots_on_target  15 non-null     int64
 13  home_possession       15 non-null     int64
 14  away_possession       15 non-null     int64
 15  home_passes           15 non-null     int64
 16  away_passes           15 non-null     int64
 17  home_corners          15 non-null     int64
 18  away_corners          15 non-null     int64
 19  home_formation        15 non-null     str
 20  away_formation        15 non-null     str
 21  winner                15 non-null     str
dtypes: datetime64[us, UTC](1), float64(2), int64(13), str(6)
memory usage: 2.7 KB

In [55]:
# Moving from raw data to processed data.
PROCESSED_DIR = Path("../data/processed")
PROCESSED_DIR.mkdir(parents = True, exist_ok = True)

In [56]:
processed_file = PROCESSED_DIR / "matches.csv"

matches_df.to_csv(
    processed_file,

    # Prevents pandas from adding unnecessary columns containing 0,1,2,3,..
    index = False
)

print("Saved to:", processed_file)

Saved to: ..\data\processed\matches.csv

In [57]:
# Moving onto historical data (Past seasons)
PREMIER_LEAGUE_ID = "comp_3039"

SEASONS = {
    "2026_27": "sn_8406098",
    "2025_26": "sn_6125938",
    "2024_25": "sn_3057848",
    "2023_24": "sn_606923",
    "2022_23": "sn_654318",
    "2021_22": "sn_699021",
    "2020_21": "sn_477656"
}

In [78]:
collect_season_baseline_data(
    "2022_23",
    finished_2022_23
)

[1/380] Collecting: Leicester City vs West Ham United
Saved: mt_587295251
[2/380] Collecting: Southampton vs Liverpool
Saved: mt_259612629
[3/380] Collecting: Crystal Palace vs Nottingham Forest
Saved: mt_360843842
[4/380] Collecting: Leeds United vs Tottenham Hotspur
Saved: mt_621306309
[5/380] Collecting: Everton vs Bournemouth
Saved: mt_018450452
[6/380] Collecting: Manchester United vs Fulham
Saved: mt_360843821
[7/380] Collecting: Arsenal vs Wolverhampton
Saved: mt_976139140
[8/380] Collecting: Brentford vs Manchester City
Saved: mt_259612672
[9/380] Collecting: Aston Villa vs Brighton & Hove Albion
Saved: mt_193081068
[10/380] Collecting: Chelsea vs Newcastle United
Saved: mt_742967950
[11/380] Collecting: Manchester United vs Chelsea
Saved: mt_250997231
[12/380] Collecting: Brighton & Hove Albion vs Manchester City
Saved: mt_978662909
[13/380] Collecting: Newcastle United vs Leicester City
Saved: mt_012881773
[14/380] Collecting: Manchester City vs Chelsea
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_742967995
[15/380] Collecting: Brighton & Hove Albion vs Southampton
Saved: mt_018450491
[16/380] Collecting: West Ham United vs Leeds United
Saved: mt_976139136
[17/380] Collecting: Nottingham Forest vs Arsenal
Saved: mt_742967906
[18/380] Collecting: Wolverhampton vs Everton
Saved: mt_621306353
[19/380] Collecting: Bournemouth vs Manchester United
Saved: mt_587295246
[20/380] Collecting: Fulham vs Crystal Palace
Saved: mt_259612608
[21/380] Collecting: Liverpool vs Aston Villa
Saved: mt_193081056
[22/380] Collecting: Tottenham Hotspur vs Brentford
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_587295298
[23/380] Collecting: Newcastle United vs Brighton & Hove Albion
Saved: mt_581778662
[24/380] Collecting: Leicester City vs Liverpool
Saved: mt_978021401
[25/380] Collecting: Arsenal vs Brighton & Hove Albion
Saved: mt_018450410
[26/380] Collecting: Brentford vs West Ham United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_834578599
[27/380] Collecting: Everton vs Manchester City
Saved: mt_405724769
[28/380] Collecting: Manchester United vs Wolverhampton
Saved: mt_976139119
[29/380] Collecting: Southampton vs Fulham
Saved: mt_834578555
[30/380] Collecting: Chelsea vs Nottingham Forest
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_360843887
[31/380] Collecting: Aston Villa vs Tottenham Hotspur
Saved: mt_018450447
[32/380] Collecting: Crystal Palace vs Bournemouth
Saved: mt_259612657
[33/380] Collecting: Leeds United vs Newcastle United
Saved: mt_587295289
[34/380] Collecting: Nottingham Forest vs Southampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_193081513
[35/380] Collecting: Brighton & Hove Albion vs Everton
Saved: mt_199119933
[36/380] Collecting: Fulham vs Leicester City
Saved: mt_193081049
[37/380] Collecting: West Ham United vs Manchester United
Saved: mt_621306405
[38/380] Collecting: Newcastle United vs Arsenal
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_834578522
[39/380] Collecting: Liverpool vs Brentford
Saved: mt_018450203
[40/380] Collecting: Wolverhampton vs Aston Villa
Saved: mt_976139101
[41/380] Collecting: Manchester City vs Leeds United
Saved: mt_405724641
[42/380] Collecting: Tottenham Hotspur vs Crystal Palace
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_259612025
[43/380] Collecting: Bournemouth vs Chelsea
Saved: mt_360843722
[44/380] Collecting: Brighton & Hove Albion vs Manchester United
Saved: mt_366338425
[45/380] Collecting: Manchester City vs West Ham United
Saved: mt_833885764
[46/380] Collecting: Liverpool vs Fulham
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_011004914
[47/380] Collecting: Arsenal vs Chelsea
Saved: mt_250381296
[48/380] Collecting: Leicester City vs Everton
Saved: mt_976139898
[49/380] Collecting: Liverpool vs Tottenham Hotspur
Saved: mt_360843744
[50/380] Collecting: Newcastle United vs Southampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_405724628
[51/380] Collecting: Fulham vs Manchester City
Saved: mt_834578967
[52/380] Collecting: Manchester United vs Aston Villa
Saved: mt_976139846
[53/380] Collecting: Bournemouth vs Leeds United
Saved: mt_405724686
[54/380] Collecting: Brighton & Hove Albion vs Wolverhampton
Saved: mt_976139820
[55/380] Collecting: Brentford vs Nottingham Forest
Saved: mt_742967390
[56/380] Collecting: Crystal Palace vs West Ham United
Saved: mt_193081584
[57/380] Collecting: Tottenham Hotspur vs Manchester United
Saved: mt_018450227
[58/380] Collecting: Southampton vs Bournemouth
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_834578906
[59/380] Collecting: Everton vs Newcastle United
Saved: mt_976139889
[60/380] Collecting: Manchester City vs Arsenal
Saved: mt_621306459
[61/380] Collecting: Chelsea vs Brentford
Saved: mt_587295138
[62/380] Collecting: West Ham United vs Liverpool
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_621306434
[63/380] Collecting: Nottingham Forest vs Brighton & Hove Albion
Saved: mt_976139873
[64/380] Collecting: Leeds United vs Leicester City
Saved: mt_259612062
[65/380] Collecting: Aston Villa vs Fulham
Saved: mt_193081561
[66/380] Collecting: Wolverhampton vs Crystal Palace
Saved: mt_587295126
[67/380] Collecting: Newcastle United vs Tottenham Hotspur
Saved: mt_193081557
[68/380] Collecting: Bournemouth vs West Ham United
Saved: mt_621306421
[69/380] Collecting: Brentford vs Aston Villa
Saved: mt_259612058
[70/380] Collecting: Liverpool vs Nottingham Forest
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_360843766
[71/380] Collecting: Crystal Palace vs Everton
Saved: mt_018450280
[72/380] Collecting: Leicester City vs Wolverhampton
Saved: mt_587295179
[73/380] Collecting: Fulham vs Leeds United
Saved: mt_976139864
[74/380] Collecting: Arsenal vs Southampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_360843777
[75/380] Collecting: Leeds United vs Liverpool
Saved: mt_018450275
[76/380] Collecting: Nottingham Forest vs Manchester United
Saved: mt_360843700
[77/380] Collecting: West Ham United vs Arsenal
Saved: mt_742967314
[78/380] Collecting: Manchester City vs Leicester City
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_621306418
[79/380] Collecting: Tottenham Hotspur vs Bournemouth
Saved: mt_405724042
[80/380] Collecting: Wolverhampton vs Brentford
Saved: mt_742967323
[81/380] Collecting: Everton vs Fulham
Saved: mt_587295163
[82/380] Collecting: Southampton vs Crystal Palace
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_259612036
[83/380] Collecting: Chelsea vs Brighton & Hove Albion
Saved: mt_405724021
[84/380] Collecting: Aston Villa vs Newcastle United
Saved: mt_621306200
[85/380] Collecting: Liverpool vs Arsenal
Saved: mt_976139791
[86/380] Collecting: Leeds United vs Crystal Palace
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_621306299
[87/380] Collecting: Southampton vs Manchester City
Saved: mt_193081545
[88/380] Collecting: Wolverhampton vs Chelsea
Saved: mt_259612520
[89/380] Collecting: Leicester City vs Bournemouth
Saved: mt_193081919
[90/380] Collecting: Tottenham Hotspur vs Brighton & Hove Albion
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_976139738
[91/380] Collecting: Fulham vs West Ham United
Saved: mt_193081974
[92/380] Collecting: Aston Villa vs Nottingham Forest
Saved: mt_742967457
[93/380] Collecting: Brentford vs Newcastle United
Saved: mt_834578307
[94/380] Collecting: Manchester United vs Everton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_834578924
[95/380] Collecting: Manchester United vs Brentford
Saved: mt_011532204
[96/380] Collecting: West Ham United vs Newcastle United
Saved: mt_366417742
[97/380] Collecting: Chelsea vs Liverpool
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_833709977
[98/380] Collecting: Leicester City vs Aston Villa
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_622094409
[99/380] Collecting: Leeds United vs Nottingham Forest
Saved: mt_255170013
[100/380] Collecting: Bournemouth vs Brighton & Hove Albion
Saved: mt_833709944
[101/380] Collecting: Everton vs Tottenham Hotspur
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_976139726
[102/380] Collecting: Newcastle United vs Manchester United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_834578368
[103/380] Collecting: West Ham United vs Southampton
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_405724018
[104/380] Collecting: Chelsea vs Aston Villa
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_405724076
[105/380] Collecting: Nottingham Forest vs Wolverhampton
Saved: mt_193081983
[106/380] Collecting: Arsenal vs Leeds United
Rate limit reached. Waiting 5 seconds before retry 1/5
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_587295831
[107/380] Collecting: Crystal Palace vs Leicester City
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_405724087
[108/380] Collecting: Bournemouth vs Fulham
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_259612573
[109/380] Collecting: Brighton & Hove Albion vs Brentford
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_018450141
[110/380] Collecting: Manchester City vs Liverpool
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_259612515
[111/380] Collecting: Arsenal vs Crystal Palace
Saved: mt_976139779
[112/380] Collecting: Chelsea vs Everton
Saved: mt_621306244
[113/380] Collecting: Southampton vs Tottenham Hotspur
Saved: mt_018450132
[114/380] Collecting: Wolverhampton vs Leeds United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_193081901
[115/380] Collecting: Aston Villa vs Bournemouth
Saved: mt_621306233
[116/380] Collecting: Brentford vs Leicester City
Saved: mt_742967430
[117/380] Collecting: Nottingham Forest vs Newcastle United
Saved: mt_259612551
[118/380] Collecting: Southampton vs Brentford
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_588986891
[119/380] Collecting: Brighton & Hove Albion vs Crystal Palace
Saved: mt_977370737
[120/380] Collecting: Newcastle United vs Wolverhampton
Saved: mt_405724059
[121/380] Collecting: Manchester United vs Southampton
Saved: mt_744135051
[122/380] Collecting: West Ham United vs Aston Villa
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_360843667
[123/380] Collecting: Fulham vs Arsenal
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_976139763
[124/380] Collecting: Crystal Palace vs Manchester City
Saved: mt_742967413
[125/380] Collecting: Everton vs Brentford
Saved: mt_621306222
[126/380] Collecting: Leeds United vs Brighton & Hove Albion
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_405724005
[127/380] Collecting: Leicester City vs Chelsea
Saved: mt_587295875
[128/380] Collecting: Tottenham Hotspur vs Nottingham Forest
Saved: mt_018450170
[129/380] Collecting: Bournemouth vs Liverpool
Saved: mt_018450805
[130/380] Collecting: Brentford vs Fulham
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_011945353
[131/380] Collecting: Liverpool vs Manchester United
Saved: mt_622849590
[132/380] Collecting: Nottingham Forest vs Everton
Saved: mt_360843606
[133/380] Collecting: Southampton vs Leicester City
Saved: mt_621306288
[134/380] Collecting: Chelsea vs Leeds United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_405724544
[135/380] Collecting: Wolverhampton vs Tottenham Hotspur
Saved: mt_976139692
[136/380] Collecting: Arsenal vs Bournemouth
Saved: mt_193081315
[137/380] Collecting: Brighton & Hove Albion vs West Ham United
Saved: mt_360843035
[138/380] Collecting: Aston Villa vs Crystal Palace
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_405724522
[139/380] Collecting: Manchester City vs Newcastle United
Saved: mt_193841117
[140/380] Collecting: Liverpool vs Wolverhampton
Saved: mt_977303400
[141/380] Collecting: Arsenal vs Everton
Saved: mt_255131722
[142/380] Collecting: Tottenham Hotspur vs Chelsea
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_834578484
[143/380] Collecting: Crystal Palace vs Liverpool
Saved: mt_621306106
[144/380] Collecting: Bournemouth vs Manchester City
Saved: mt_621306150
[145/380] Collecting: West Ham United vs Nottingham Forest
Saved: mt_976139631
[146/380] Collecting: Leicester City vs Arsenal
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_193081389
[147/380] Collecting: Leeds United vs Southampton
Saved: mt_834578472
[148/380] Collecting: Everton vs Aston Villa
Saved: mt_259612985
[149/380] Collecting: Fulham vs Wolverhampton
Saved: mt_587295732
[150/380] Collecting: Tottenham Hotspur vs West Ham United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_360843023
[151/380] Collecting: Manchester United vs Leicester City
Saved: mt_833290662
[152/380] Collecting: Newcastle United vs Liverpool
Saved: mt_193081373
[153/380] Collecting: Wolverhampton vs Bournemouth
Saved: mt_742967262
[154/380] Collecting: Brighton & Hove Albion vs Fulham
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_405724511
[155/380] Collecting: Brentford vs Crystal Palace
Saved: mt_018450893
[156/380] Collecting: Chelsea vs Southampton
Saved: mt_976139648
[157/380] Collecting: Nottingham Forest vs Manchester City
Saved: mt_405724588
[158/380] Collecting: Everton vs Leeds United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_587295741
[159/380] Collecting: Aston Villa vs Arsenal
Saved: mt_976139627
[160/380] Collecting: Arsenal vs Manchester City
Saved: mt_744963232
[161/380] Collecting: Liverpool vs Everton
Saved: mt_621306139
[162/380] Collecting: Manchester City vs Aston Villa
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_976139616
[163/380] Collecting: Leeds United vs Manchester United
Saved: mt_018450834
[164/380] Collecting: Bournemouth vs Newcastle United
Saved: mt_193081364
[165/380] Collecting: Crystal Palace vs Brighton & Hove Albion
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Incomplete baseline data. Missing: ['statistics']
Not saved because data was incomplete: mt_834578408
[166/380] Collecting: Leicester City vs Tottenham Hotspur
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_621306195
[167/380] Collecting: Fulham vs Nottingham Forest
Saved: mt_259612979
[168/380] Collecting: Southampton vs Wolverhampton
Saved: mt_360843082
[169/380] Collecting: Arsenal vs Brentford
Saved: mt_259612963
[170/380] Collecting: West Ham United vs Chelsea
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_360843014
[171/380] Collecting: Manchester United vs Leeds United
Saved: mt_744035677
[172/380] Collecting: Tottenham Hotspur vs Manchester City
Saved: mt_976139680
[173/380] Collecting: Nottingham Forest vs Leeds United
Saved: mt_742967297
[174/380] Collecting: Newcastle United vs West Ham United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_834578457
[175/380] Collecting: Manchester United vs Crystal Palace
Saved: mt_977606768
[176/380] Collecting: Wolverhampton vs Liverpool
Saved: mt_018450842
[177/380] Collecting: Aston Villa vs Leicester City
Saved: mt_834578496
[178/380] Collecting: Brentford vs Southampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_621306143
[179/380] Collecting: Brighton & Hove Albion vs Bournemouth
Saved: mt_193081398
[180/380] Collecting: Everton vs Arsenal
Saved: mt_193081351
[181/380] Collecting: Chelsea vs Fulham
Saved: mt_259612952
[182/380] Collecting: Fulham vs Tottenham Hotspur
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_360843068
[183/380] Collecting: Arsenal vs Manchester United
Saved: mt_400968181
[184/380] Collecting: Manchester City vs Wolverhampton
Saved: mt_405724566
[185/380] Collecting: Leeds United vs Brentford
Saved: mt_976139669
[186/380] Collecting: Crystal Palace vs Newcastle United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_193081337
[187/380] Collecting: Southampton vs Aston Villa
Saved: mt_742967236
[188/380] Collecting: West Ham United vs Everton
Saved: mt_018450821
[189/380] Collecting: Leicester City vs Brighton & Hove Albion
Saved: mt_018450818
[190/380] Collecting: Bournemouth vs Nottingham Forest
Saved: mt_259612991
[191/380] Collecting: Liverpool vs Chelsea
Saved: mt_587295717
[192/380] Collecting: Manchester City vs Tottenham Hotspur
Saved: mt_977138681
[193/380] Collecting: Crystal Palace vs Manchester United
Saved: mt_588451392

In [64]:
matches_2022_23 = season_2022_23_matches["data"]

finished_2022_23 = [
    match for match in matches_2022_23
    if match["status"] == "finished"
]

print("Finished matches:", len(finished_2022_23))

test_match = finished_2022_23[0]

print("Test match ID:", test_match["id"])
print(
    test_match["home_team"]["name"],
    "vs",
    test_match["away_team"]["name"]
)

Finished matches: 20
Test match ID: mt_587295251
Leicester City vs West Ham United

In [91]:
# Testing on a past season to see if all matches are returned to us from the API.
# For a completed season, the total amount of games is 380.
matches_2025_26 = get_all_season_matches(
    PREMIER_LEAGUE_ID,
    SEASONS["2025_26"]
)

print("Matches found:", len(matches_2025_26))

Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
Matches found: 380

In [92]:
from collections import Counter

status_counts = Counter(
    match["status"] for match in matches_2025_26
)

print(status_counts)

Counter({'finished': 380})

In [ ]:
# Used as a sanity check to make sure we have pulled matches from the correct season (2025-26)
for match in matches_2025_26[:5]:
    print(
        match["matchday"],
        "-",
        match["home_team"]["name"],
        "vs",
        match["away_team"]["name"],
        "-",
        match["status"]
    )

38 - West Ham United vs Leeds United - finished
38 - Tottenham Hotspur vs Everton - finished
38 - Sunderland vs Chelsea - finished
38 - Fulham vs Newcastle United - finished
38 - Nottingham Forest vs Bournemouth - finished

In [86]:
# Creating a historical collector.
def get_baseline_match_data(match_id):
    match_data = {}

    match_data["details"] = get_match_details(match_id)
    time.sleep(2)

    match_data["statistics"] = get_match_statistics(match_id)
    time.sleep(2)

    match_data["odds"] = get_match_odds(match_id)

    # Details are required because we need the actual match/result.
    if match_data["details"] is None:
        print("Missing match details. Skipping:", match_id)
        return None

    # Statistics and odds can be missing and will be handled later as NaN.
    missing = [
        section
        for section in ["statistics", "odds"]
        if match_data[section] is None
    ]

    if missing:
        print("Saving with missing sections:", missing)

    return match_data

In [76]:
# Creating folders for each season.
SEASON_DIRS = {}

# Looping through the seasons we listed earlier.
# Then creating a path for each season
for season_name in SEASONS:
    season_dir = RAW_MATCH_DIR / season_name
    season_dir.mkdir(parents = True, exist_ok = True)
    SEASON_DIRS[season_name] = season_dir

print(SEASON_DIRS)

{'2026_27': WindowsPath('../data/raw/matches/2026_27'), '2025_26': WindowsPath('../data/raw/matches/2025_26'), '2024_25': WindowsPath('../data/raw/matches/2024_25'), '2023_24': WindowsPath('../data/raw/matches/2023_24'), '2022_23': WindowsPath('../data/raw/matches/2022_23'), '2021_22': WindowsPath('../data/raw/matches/2021_22'), '2020_21': WindowsPath('../data/raw/matches/2020_21')}

In [74]:
# Building a collector for the historical seasons.

def collect_season_baseline_data(season_name, matches):
    season_dir = SEASON_DIRS[season_name]

    total_matches = len(matches)

    # Adds a progress counter, just to keep track of how many matches are left to save.
    for i, match in enumerate(matches, start = 1):
        match_id = match["id"]
        file_path = season_dir / f"{match_id}.json"

        # The collrector is resumable, so if it stops collecting today, you can continue collecting tomorrow.
        if file_path.exists():
            print(f"[{i}/{total_matches}] Skipping {match_id} - already saved")
            continue

        print(
            f"[{i}/{total_matches}] Collecting:",
            match["home_team"]["name"],
            "vs",
            match["away_team"]["name"]
        )

        match_data = get_baseline_match_data(match_id)

        if match_data is not None:
            with open(file_path, "w", encoding = "utf-8") as f:
                json.dump(match_data, f, indent = 2, ensure_ascii = False)

            print("Saved:", match_id)
        else:
            print("Not saved because data was incomplete:", match_id)

        time.sleep(5)

In [ ]:
# Testing to see if the historical seasons collector works.
collect_season_baseline_data(
    "2025_26",
    matches_2025_26[:3]
)

[1/3] Collecting: West Ham United vs Leeds United
Saved: mt_838955396
[2/3] Collecting: Tottenham Hotspur vs Everton
Saved: mt_363788671
[3/3] Collecting: Sunderland vs Chelsea
Saved: mt_626433243

In [101]:
# Testing the collector on 3 matches worked, so we can get rid of the [:3] limit.
collect_season_baseline_data(
    "2025_26",
    matches_2025_26
)

1/380] Skipping mt_838955396 - already saved
2/380] Skipping mt_363788671 - already saved
3/380] Skipping mt_626433243 - already saved
4/380] Skipping mt_404677066 - already saved
5/380] Skipping mt_010244121 - already saved
6/380] Skipping mt_585122817 - already saved
7/380] Skipping mt_979811780 - already saved
8/380] Skipping mt_252066552 - already saved
9/380] Skipping mt_191500998 - already saved
10/380] Skipping mt_747399440 - already saved
11/380] Skipping mt_377685036 - already saved
12/380] Skipping mt_626433281 - already saved
13/380] Skipping mt_191500937 - already saved
14/380] Skipping mt_363788668 - already saved
15/380] Skipping mt_838955330 - already saved
16/380] Skipping mt_404677000 - already saved
17/380] Skipping mt_010244118 - already saved
18/380] Skipping mt_585122886 - already saved
19/380] Skipping mt_626433224 - already saved
20/380] Skipping mt_838955483 - already saved
21/380] Skipping mt_899285792 - already saved
22/380] Skipping mt_010244187 - already saved
23/380] Skipping mt_979811703 - already saved
24/380] Skipping mt_585122865 - already saved
25/380] Skipping mt_363788656 - already saved
26/380] Skipping mt_747399273 - already saved
27/380] Skipping mt_626433212 - already saved
28/380] Skipping mt_838955345 - already saved
29/380] Skipping mt_838955329 - already saved
30/380] Skipping mt_404677099 - already saved
31/380] Skipping mt_010244270 - already saved
32/380] Skipping mt_191500310 - already saved
33/380] Skipping mt_404677524 - already saved
34/380] Skipping mt_363788030 - already saved
35/380] Skipping mt_747399419 - already saved
36/380] Skipping mt_585122169 - already saved
37/380] Skipping mt_252066927 - already saved
38/380] Skipping mt_252066591 - already saved
39/380] Skipping mt_747399425 - already saved
40/380] Skipping mt_404677055 - already saved
41/380] Skipping mt_191500946 - already saved
42/380] Skipping mt_626433168 - already saved
43/380] Skipping mt_404678116 - already saved
44/380] Skipping mt_979811804 - already saved
45/380] Skipping mt_404677022 - already saved
46/380] Skipping mt_010244800 - already saved
47/380] Skipping mt_010244159 - already saved
48/380] Skipping mt_979811694 - already saved
49/380] Skipping mt_010243991 - already saved
50/380] Skipping mt_585122894 - already saved
51/380] Skipping mt_252066510 - already saved
52/380] Skipping mt_010243938 - already saved
53/380] Skipping mt_747395050 - already saved
54/380] Skipping mt_252067872 - already saved
55/380] Skipping mt_404678180 - already saved
56/380] Skipping mt_191506707 - already saved
57/380] Skipping mt_979812419 - already saved
58/380] Skipping mt_979812440 - already saved
59/380] Skipping mt_191506768 - already saved
60/380] Skipping mt_626439594 - already saved
61/380] Skipping mt_252067861 - already saved
62/380] Skipping mt_010243947 - already saved
63/380] Skipping mt_838955372 - already saved
64/380] Skipping mt_626439532 - already saved
65/380] Skipping mt_404678175 - already saved
66/380] Skipping mt_747399462 - already saved
67/380] Skipping mt_191500989 - already saved
68/380] Skipping mt_979812483 - already saved
69/380] Skipping mt_979811731 - already saved
70/380] Skipping mt_252067808 - already saved
71/380] Skipping mt_747395095 - already saved
72/380] Skipping mt_191500540 - already saved
73/380] Skipping mt_010244105 - already saved
74/380] Skipping mt_252066037 - already saved
75/380] Skipping mt_838955923 - already saved
76/380] Skipping mt_363788750 - already saved
77/380] Skipping mt_626433488 - already saved
78/380] Skipping mt_404677044 - already saved
79/380] Skipping mt_363788623 - already saved
80/380] Skipping mt_209226608 - already saved
81/380] Skipping mt_979811748 - already saved
82/380] Skipping mt_404677011 - already saved
83/380] Skipping mt_010244193 - already saved
84/380] Skipping mt_252066585 - already saved
85/380] Skipping mt_585122832 - already saved
86/380] Skipping mt_191500973 - already saved
87/380] Skipping mt_363788614 - already saved
88/380] Skipping mt_626433250 - already saved
89/380] Skipping mt_838955308 - already saved
90/380] Skipping mt_252066579 - already saved
91/380] Skipping mt_585122841 - already saved
92/380] Skipping mt_626433295 - already saved
93/380] Skipping mt_010244134 - already saved
94/380] Skipping mt_363788607 - already saved
95/380] Skipping mt_585122759 - already saved
96/380] Skipping mt_404677088 - already saved
97/380] Skipping mt_979811727 - already saved
98/380] Skipping mt_191500964 - already saved
99/380] Skipping mt_252066538 - already saved
100/380] Skipping mt_252066563 - already saved
101/380] Skipping mt_838955357 - already saved
102/380] Skipping mt_585122828 - already saved
103/380] Skipping mt_979811716 - already saved
104/380] Skipping mt_010244142 - already saved
105/380] Skipping mt_363788682 - already saved
106/380] Skipping mt_626433239 - already saved
107/380] Skipping mt_404677077 - already saved
108/380] Skipping mt_191500951 - already saved
109/380] Skipping mt_747399497 - already saved
110/380] Skipping mt_153746445 - already saved
111/380] Skipping mt_979811792 - already saved
112/380] Skipping mt_585122853 - already saved
113/380] Skipping mt_252066526 - already saved
114/380] Skipping mt_838955384 - already saved
115/380] Skipping mt_191500915 - already saved
116/380] Skipping mt_747399436 - already saved
117/380] Skipping mt_404678420 - already saved
118/380] Skipping mt_363788635 - already saved
119/380] Skipping mt_626433206 - already saved
120/380] Skipping mt_838950699 - already saved
121/380] Skipping mt_404678464 - already saved
122/380] Skipping mt_363781316 - already saved
123/380] Skipping mt_979812949 - already saved
124/380] Skipping mt_747395705 - already saved
125/380] Skipping mt_626439652 - already saved
126/380] Skipping mt_010243040 - already saved
127/380] Skipping mt_585124545 - already saved
128/380] Skipping mt_191506166 - already saved
129/380] Skipping mt_252067267 - already saved
130/380] Skipping mt_838950853 - already saved
131/380] Skipping mt_585124584 - already saved
132/380] Skipping mt_252067295 - already saved
133/380] Skipping mt_747395734 - already saved
134/380] Skipping mt_979812982 - already saved
135/380] Skipping mt_363781303 - already saved
136/380] Skipping mt_010243083 - already saved
137/380] Skipping mt_838950828 - already saved
138/380] Skipping mt_404678498 - already saved
139/380] Skipping mt_626439626 - already saved
140/380] Skipping mt_191506199 - already saved
141/380] Skipping mt_028480912 - already saved
142/380] Skipping mt_747395677 - already saved
143/380] Skipping mt_585124958 - already saved
144/380] Skipping mt_191506881 - already saved
145/380] Skipping mt_404678210 - already saved
146/380] Skipping mt_363781441 - already saved
147/380] Skipping mt_252067182 - already saved
148/380] Skipping mt_979812907 - already saved
149/380] Skipping mt_010243551 - already saved
150/380] Skipping mt_838950760 - already saved
151/380] Skipping mt_732927026 - already saved
152/380] Skipping mt_838950793 - already saved
153/380] Skipping mt_747395655 - already saved
154/380] Skipping mt_363781486 - already saved
155/380] Skipping mt_252067107 - already saved
156/380] Skipping mt_404678204 - already saved
157/380] Skipping mt_626439092 - already saved
158/380] Skipping mt_585124925 - already saved
159/380] Skipping mt_010243520 - already saved
160/380] Skipping mt_979812329 - already saved
161/380] Skipping mt_465754107 - already saved
162/380] Skipping mt_010243904 - already saved
163/380] Skipping mt_979812372 - already saved
164/380] Skipping mt_979812361 - already saved
165/380] Skipping mt_747395644 - already saved
166/380] Skipping mt_404678252 - already saved
167/380] Skipping mt_626439080 - already saved
168/380] Skipping mt_585124962 - already saved
169/380] Skipping mt_191506843 - already saved
170/380] Skipping mt_747395622 - already saved
171/380] Skipping mt_747395039 - already saved
172/380] Skipping mt_979812436 - already saved
173/380] Skipping mt_363781218 - already saved
174/380] Skipping mt_252067829 - already saved
175/380] Skipping mt_838950677 - already saved
176/380] Skipping mt_747395006 - already saved
177/380] Skipping mt_626439553 - already saved
178/380] Skipping mt_363781287 - already saved
179/380] Skipping mt_404678169 - already saved
180/380] Skipping mt_404678127 - already saved
181/380] Skipping mt_626435851 - already saved
182/380] Skipping mt_979814024 - already saved
183/380] Skipping mt_191507476 - already saved
184/380] Skipping mt_838956269 - already saved
185/380] Skipping mt_191507460 - already saved
186/380] Skipping mt_010249730 - already saved
187/380] Skipping mt_010249745 - already saved
188/380] Skipping mt_979814043 - already saved
189/380] Skipping mt_838956203 - already saved
190/380] Skipping mt_626435898 - already saved
191/380] Skipping mt_191507405 - already saved
192/380] Skipping mt_626435820 - already saved
193/380] Skipping mt_010249729 - already saved
194/380] Skipping mt_979814081 - already saved
195/380] Skipping mt_626435846 - already saved
196/380] Skipping mt_010249713 - already saved
197/380] Skipping mt_979814012 - already saved
198/380] Skipping mt_838956254 - already saved
199/380] Skipping mt_191507459 - already saved
200/380] Skipping mt_838956292 - already saved
201/380] Skipping mt_979814067 - already saved
202/380] Skipping mt_191507493 - already saved
203/380] Skipping mt_191507434 - already saved
204/380] Skipping mt_979814078 - already saved
205/380] Skipping mt_010249784 - already saved
206/380] Skipping mt_838956227 - already saved
207/380] Skipping mt_626435889 - already saved
208/380] Skipping mt_010249772 - already saved
209/380] Skipping mt_838956248 - already saved
210/380] Skipping mt_626435815 - already saved
211/380] Skipping mt_209363267 - already saved
212/380] Skipping mt_626439604 - already saved
213/380] Skipping mt_010243001 - already saved
214/380] Skipping mt_191506188 - already saved
215/380] Skipping mt_191506111 - already saved
216/380] Skipping mt_979814006 - already saved
217/380] Skipping mt_626439663 - already saved
218/380] Skipping mt_838950870 - already saved
219/380] Skipping mt_585124596 - already saved
220/380] Skipping mt_838950886 - already saved
221/380] Skipping mt_732455509 - already saved
222/380] Skipping mt_626439638 - already saved
223/380] Skipping mt_191506177 - already saved
224/380] Skipping mt_363781327 - already saved
225/380] Skipping mt_010243097 - already saved
226/380] Skipping mt_404678489 - already saved
227/380] Skipping mt_585124513 - already saved
228/380] Skipping mt_747395793 - already saved
229/380] Skipping mt_838950809 - already saved
230/380] Skipping mt_979812914 - already saved
231/380] Skipping mt_641836814 - already saved
232/380] Skipping mt_404678451 - already saved
233/380] Skipping mt_747395721 - already saved
234/380] Skipping mt_838950832 - already saved
235/380] Skipping mt_363781375 - already saved
236/380] Skipping mt_010243019 - already saved
237/380] Skipping mt_252067250 - already saved
238/380] Skipping mt_979812968 - already saved
239/380] Skipping mt_585124561 - already saved
240/380] Skipping mt_626439685 - already saved
241/380] Skipping mt_191506144 - already saved
242/380] Skipping mt_363781432 - already saved
243/380] Skipping mt_838950776 - already saved
244/380] Skipping mt_010243502 - already saved
245/380] Skipping mt_979812330 - already saved
246/380] Skipping mt_747395600 - already saved
247/380] Skipping mt_626439054 - already saved
248/380] Skipping mt_252067123 - already saved
249/380] Skipping mt_404678226 - already saved
250/380] Skipping mt_585124936 - already saved
251/380] Skipping mt_747395633 - already saved
252/380] Skipping mt_191506867 - already saved
253/380] Skipping mt_252067168 - already saved
254/380] Skipping mt_585124983 - already saved
255/380] Skipping mt_979812384 - already saved
256/380] Skipping mt_363781417 - already saved
257/380] Skipping mt_404678279 - already saved
258/380] Skipping mt_010243537 - already saved
259/380] Skipping mt_838950759 - already saved
260/380] Skipping mt_626439048 - already saved
261/380] Skipping mt_027927049 - already saved
262/380] Skipping mt_626439565 - already saved
263/380] Skipping mt_838950742 - already saved
264/380] Skipping mt_363781465 - already saved
265/380] Skipping mt_191506895 - already saved
266/380] Skipping mt_252067190 - already saved
267/380] Skipping mt_404678291 - already saved
268/380] Skipping mt_747395611 - already saved
269/380] Skipping mt_585124351 - already saved
270/380] Skipping mt_979812308 - already saved
271/380] Skipping mt_838950666 - already saved
272/380] Skipping mt_252067813 - already saved
273/380] Skipping mt_585124346 - already saved
274/380] Skipping mt_363781276 - already saved
275/380] Skipping mt_010243910 - already saved
276/380] Skipping mt_585124315 - already saved
277/380] Skipping mt_010243952 - already saved
278/380] Skipping mt_191506714 - already saved
279/380] Skipping mt_585124337 - already saved
280/380] Skipping mt_363781242 - already saved
281/380] Skipping mt_469165990 - already saved
282/380] Skipping mt_585123649 - already saved
283/380] Skipping mt_252068388 - already saved
284/380] Skipping mt_252068377 - already saved
285/380] Skipping mt_747390109 - already saved
286/380] Skipping mt_404671919 - already saved
287/380] Skipping mt_747390153 - already saved
288/380] Skipping mt_363782510 - already saved
289/380] Skipping mt_404671974 - already saved
290/380] Skipping mt_585123623 - already saved
291/380] Skipping mt_585123614 - already saved
292/380] Skipping mt_252068366 - already saved
293/380] Skipping mt_363782563 - already saved
294/380] Skipping mt_404671901 - already saved
295/380] Skipping mt_585123682 - already saved
296/380] Skipping mt_747390132 - already saved
297/380] Skipping mt_363782585 - already saved
298/380] Skipping mt_747390194 - already saved
299/380] Skipping mt_252068300 - already saved
300/380] Skipping mt_404671962 - already saved
301/380] Skipping mt_375612438 - already saved
302/380] Skipping mt_252068399 - already saved
303/380] Skipping mt_747390141 - already saved
304/380] Skipping mt_747390117 - already saved
305/380] Skipping mt_363782504 - already saved
306/380] Skipping mt_585123671 - already saved
307/380] Skipping mt_363782552 - already saved
308/380] Skipping mt_404671997 - already saved
309/380] Skipping mt_585123668 - already saved
310/380] Skipping mt_404671958 - already saved
311/380] Skipping mt_747395760 - already saved
312/380] Skipping mt_252068333 - already saved
313/380] Skipping mt_747395776 - already saved
314/380] Skipping mt_585124557 - already saved
315/380] Skipping mt_363781348 - already saved
316/380] Skipping mt_252067212 - already saved
317/380] Skipping mt_363781331 - already saved
318/380] Skipping mt_010243058 - already saved
319/380] Skipping mt_404678446 - already saved
320/380] Skipping mt_252067281 - already saved
321/380] Skipping mt_363376157 - already saved
322/380] Skipping mt_979812923 - already saved
323/380] Skipping mt_252067206 - already saved
324/380] Skipping mt_838950865 - already saved
325/380] Skipping mt_404678415 - already saved
326/380] Skipping mt_747395759 - already saved
327/380] Skipping mt_626439691 - already saved
328/380] Skipping mt_191506100 - already saved
329/380] Skipping mt_363781380 - already saved
330/380] Skipping mt_010243025 - already saved
331/380] Skipping mt_010243074 - already saved
332/380] Skipping mt_979812971 - already saved
333/380] Skipping mt_252067239 - already saved
334/380] Skipping mt_585124572 - already saved
335/380] Skipping mt_747395742 - already saved
336/380] Skipping mt_838950894 - already saved
337/380] Skipping mt_404678402 - already saved
338/380] Skipping mt_191506133 - already saved
339/380] Skipping mt_363781354 - already saved
340/380] Skipping mt_626439610 - already saved
341/380] Skipping mt_979812396 - already saved
342/380] Skipping mt_191506878 - already saved
343/380] Skipping mt_363781428 - already saved
344/380] Skipping mt_838950787 - already saved
345/380] Skipping mt_404678247 - already saved
346/380] Skipping mt_747395666 - already saved
347/380] Skipping mt_626439003 - already saved
348/380] Skipping mt_585124997 - already saved
349/380] Skipping mt_252067171 - already saved
350/380] Skipping mt_010243598 - already saved
351/380] Skipping mt_252067156 - already saved
352/380] Skipping mt_585124919 - already saved
353/380] Skipping mt_747395699 - already saved
354/380] Skipping mt_010243515 - already saved
355/380] Skipping mt_191506850 - already saved
356/380] Skipping mt_838950705 - already saved
357/380] Skipping mt_404678285 - already saved
358/380] Skipping mt_979812313 - already saved
359/380] Skipping mt_626439031 - already saved
360/380] Skipping mt_363781470 - already saved
361/380] Skipping mt_010331117 - already saved
362/380] Skipping mt_191506839 - already saved
363/380] Skipping mt_363781453 - already saved
364/380] Skipping mt_010243573 - already saved
365/380] Skipping mt_404678148 - already saved
366/380] Skipping mt_252067135 - already saved
367/380] Skipping mt_838950688 - already saved
368/380] Skipping mt_979812497 - already saved
369/380] Skipping mt_585124974 - already saved
370/380] Skipping mt_838950734 - already saved
371/380] Skipping mt_747395067 - already saved
372/380] Skipping mt_626439509 - already saved
373/380] Skipping mt_585124398 - already saved
374/380] Skipping mt_838950655 - already saved
375/380] Skipping mt_191506771 - already saved
376/380] Skipping mt_363781221 - already saved
377/380] Skipping mt_838950600 - already saved
378/380] Skipping mt_191506756 - already saved
[379/380] Collecting: Aston Villa vs Newcastle United
Saved: mt_626439541
[380/380] Collecting: Liverpool vs Bournemouth
Saved: mt_585124389

In [102]:
# Verify the 2025/26 season folder has 380 JSON files.
season_2025_dir = SEASON_DIRS["2025_26"]
saved_files = list(season_2025_dir.glob("*.json"))

print("Saved matches:", len(saved_files))

Saved matches: 380

In [103]:
# Perform an integrity check
# Making sure every JSON file contains the sections we want to look at

incomplete_files = []

for file_path in SEASON_DIRS["2025_26"].glob("*.json"):
    with open(file_path, "r", encoding = "utf-8") as f:
        data = json.load(f)

    missing = [
        section
        for section in ["details", "statistics", "odds"]
        if data.get(section) is None
    ]

    if missing:
        incomplete_files.append((file_path.name, missing))

print("Total files:", 380)
print("Incomplete files:", len(incomplete_files))

if incomplete_files:
    for file_name, missing in incomplete_files:
        print(file_name, "- MISSING:", missing)
else:
    print("All 2025/26 files are complete.")

Total files: 380
Incomplete files: 0
All 2025/26 files are complete.

In [104]:
# Now collecting historical data from the 2024/25 season
matches_2024_25 = get_all_season_matches(
    PREMIER_LEAGUE_ID,
    SEASONS["2024_25"]
)

print("Matches found:", len(matches_2024_25))

Matches found: 381

In [105]:
# Our last cell returned 381 matches, so we have to check for any duplicates

status_counts_2024_25 = Counter(
    match["status"] for match in matches_2024_25
)

print(status_counts_2024_25)

Counter({'finished': 380, 'postponed': 1})

In [106]:
match_ids_2024_25 = [
    match["id"]
    for match in matches_2024_25
]

print("Total matches:", len(match_ids_2024_25))
print("Unique match IDs:", len(set(match_ids_2024_25)))

Total matches: 381
Unique match IDs: 381

In [107]:
for match in matches_2024_25:
    if match["status"] != "finished":
        print(
            match["id"],
            match["matchday"],
            match["home_team"]["name"],
            "vs",
            match["away_team"]["name"],
            "-",
            match["status"]
        )

mt_408687117 37 Manchester City vs Bournemouth - postponed

In [109]:
# We found the duplicate record, let's see if the match ID shows that it was finished
for match in matches_2024_25:
    if (
        match["home_team"]["name"] == "Manchester City"
        and match["away_team"]["name"] == "Bournemouth"
    ):
        print(
            match["id"],
            "- Matchday:", match["matchday"],
            "- Status:", match["status"]
        )

mt_838200836 - Matchday: 37 - Status: finished
mt_408687117 - Matchday: 37 - Status: postponed

In [110]:
# Creating a clean list
# Removing the postoned match ID

matches_2024_25_clean = [
    match
    for match in matches_2024_25
    if match["status"] == "finished"
]

print("Original matches:", len(matches_2024_25))
print("Finished matches:", len(matches_2024_25_clean))

Original matches: 381
Finished matches: 380

In [111]:
# Run the collector function for the 2024/25 season.

collect_season_baseline_data(
    "2024_25",
    matches_2024_25_clean
)

[1/380] Collecting: Fulham vs Manchester City
Saved: mt_745359007
[2/380] Collecting: Tottenham Hotspur vs Brighton & Hove Albion
Saved: mt_361718222
[3/380] Collecting: Nottingham Forest vs Chelsea
Saved: mt_629493559
[4/380] Collecting: Southampton vs Arsenal
Saved: mt_745359056
[5/380] Collecting: Liverpool vs Crystal Palace
Saved: mt_830905606
[6/380] Collecting: Wolverhampton vs Brentford
Saved: mt_972821420
[7/380] Collecting: Newcastle United vs Everton
Saved: mt_257076862
[8/380] Collecting: Manchester United vs Aston Villa
Saved: mt_196560708
[9/380] Collecting: Ipswich Town vs West Ham United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_830905650
[10/380] Collecting: Bournemouth vs Leicester City
Saved: mt_629493534
[11/380] Collecting: Manchester City vs Bournemouth
Saved: mt_838200836
[12/380] Collecting: Crystal Palace vs Wolverhampton
Saved: mt_972821362
[13/380] Collecting: Brighton & Hove Albion vs Liverpool
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_196560835
[14/380] Collecting: Arsenal vs Newcastle United
Saved: mt_408687292
[15/380] Collecting: Brentford vs Fulham
Saved: mt_629493086
[16/380] Collecting: Leicester City vs Ipswich Town
Saved: mt_013234948
[17/380] Collecting: West Ham United vs Nottingham Forest
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_584142326
[18/380] Collecting: Everton vs Southampton
Saved: mt_745359612
[19/380] Collecting: Chelsea vs Manchester United
Saved: mt_972821301
[20/380] Collecting: Aston Villa vs Tottenham Hotspur
Saved: mt_361718233
[21/380] Collecting: Liverpool vs Arsenal
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_830905678
[22/380] Collecting: Tottenham Hotspur vs Crystal Palace
Saved: mt_584142964
[23/380] Collecting: Nottingham Forest vs Leicester City
Saved: mt_013234903
[24/380] Collecting: Manchester United vs West Ham United
Saved: mt_745359071
[25/380] Collecting: Newcastle United vs Chelsea
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_584142352
[26/380] Collecting: Bournemouth vs Aston Villa
Saved: mt_196560713
[27/380] Collecting: Wolverhampton vs Brighton & Hove Albion
Saved: mt_257076130
[28/380] Collecting: Southampton vs Manchester City
Saved: mt_408687141
[29/380] Collecting: Fulham vs Everton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_629493505
[30/380] Collecting: Ipswich Town vs Brentford
Saved: mt_013234954
[31/380] Collecting: Crystal Palace vs Nottingham Forest
Saved: mt_257076819
[32/380] Collecting: Chelsea vs Liverpool
Saved: mt_584142391
[33/380] Collecting: Brighton & Hove Albion vs Newcastle United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_361718244
[34/380] Collecting: West Ham United vs Tottenham Hotspur
Saved: mt_408687128
[35/380] Collecting: Brentford vs Manchester United
Saved: mt_196560784
[36/380] Collecting: Arsenal vs Bournemouth
Saved: mt_584142347
[37/380] Collecting: Everton vs Ipswich Town
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_972821498
[38/380] Collecting: Leicester City vs Southampton
Saved: mt_257076825
[39/380] Collecting: Aston Villa vs Fulham
Saved: mt_584142338
[40/380] Collecting: Manchester City vs Wolverhampton
Saved: mt_972821437
[41/380] Collecting: Nottingham Forest vs Brentford
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_972821446
[42/380] Collecting: Liverpool vs Tottenham Hotspur
Saved: mt_013234931
[43/380] Collecting: Bournemouth vs Manchester United
Saved: mt_408687170
[44/380] Collecting: Wolverhampton vs Leicester City
Saved: mt_830905667
[45/380] Collecting: Brighton & Hove Albion vs West Ham United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_629493593
[46/380] Collecting: Newcastle United vs Ipswich Town
Saved: mt_408687186
[47/380] Collecting: Southampton vs Fulham
Saved: mt_745359090
[48/380] Collecting: Chelsea vs Everton
Saved: mt_196560761
[49/380] Collecting: Arsenal vs Crystal Palace
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_361718211
[50/380] Collecting: Manchester City vs Aston Villa
Saved: mt_257076883
[51/380] Collecting: Tottenham Hotspur vs Nottingham Forest
Saved: mt_361718288
[52/380] Collecting: Leicester City vs Liverpool
Saved: mt_629493094
[53/380] Collecting: Manchester United vs Wolverhampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_972821319
[54/380] Collecting: Ipswich Town vs Arsenal
Saved: mt_196560807
[55/380] Collecting: Fulham vs Chelsea
Saved: mt_830905755
[56/380] Collecting: Aston Villa vs Newcastle United
Saved: mt_408687275
[57/380] Collecting: Everton vs Manchester City
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_830905700
[58/380] Collecting: Brentford vs Brighton & Hove Albion
Saved: mt_745359695
[59/380] Collecting: Crystal Palace vs Bournemouth
Saved: mt_629493032
[60/380] Collecting: West Ham United vs Southampton
Saved: mt_013234992
[61/380] Collecting: Newcastle United vs Crystal Palace
Saved: mt_257077070
[62/380] Collecting: Bournemouth vs Fulham
Saved: mt_973123668
[63/380] Collecting: Newcastle United vs Manchester United
Saved: mt_257076108
[64/380] Collecting: Wolverhampton vs Tottenham Hotspur
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_361718487
[65/380] Collecting: Liverpool vs West Ham United
Saved: mt_972821383
[66/380] Collecting: Chelsea vs Ipswich Town
Saved: mt_745359639
[67/380] Collecting: Arsenal vs Brentford
Saved: mt_830905799
[68/380] Collecting: Southampton vs Aston Villa
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_013234547
[69/380] Collecting: Nottingham Forest vs Everton
Saved: mt_584142915
[70/380] Collecting: Brighton & Hove Albion vs Leicester City
Saved: mt_361718476
[71/380] Collecting: Manchester City vs Crystal Palace
Saved: mt_196560856
[72/380] Collecting: Leicester City vs Newcastle United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_746956221
[73/380] Collecting: Manchester United vs Manchester City
Saved: mt_972821374
[74/380] Collecting: Tottenham Hotspur vs Southampton
Saved: mt_629493041
[75/380] Collecting: Fulham vs Liverpool
Saved: mt_830905733
[76/380] Collecting: Brentford vs Chelsea
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
Saved: mt_745359624
[77/380] Collecting: Aston Villa vs Nottingham Forest
Saved: mt_361718460
[78/380] Collecting: West Ham United vs Bournemouth
Saved: mt_013234510
[79/380] Collecting: Ipswich Town vs Wolverhampton
Saved: mt_257076157
[80/380] Collecting: Crystal Palace vs Brighton & Hove Albion
Saved: mt_408687254
[81/380] Collecting: Everton vs Arsenal
Saved: mt_629493028
[82/380] Collecting: Chelsea vs Tottenham Hotspur
Saved: mt_361718405
[83/380] Collecting: Liverpool vs Everton
Saved: mt_584142973
[84/380] Collecting: Newcastle United vs Brentford
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_196560890
[85/380] Collecting: Manchester City vs Leicester City
Saved: mt_013234585
[86/380] Collecting: Southampton vs Crystal Palace
Saved: mt_830905744
[87/380] Collecting: Brighton & Hove Albion vs Aston Villa
Saved: mt_013234579
[88/380] Collecting: Bournemouth vs Ipswich Town
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_629493560
[89/380] Collecting: Nottingham Forest vs Manchester United
Saved: mt_257076196
[90/380] Collecting: Wolverhampton vs West Ham United
Saved: mt_745359643
[91/380] Collecting: Arsenal vs Fulham
Saved: mt_196560849
[92/380] Collecting: Leicester City vs Manchester United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_361711783
[93/380] Collecting: Fulham vs Tottenham Hotspur
Saved: mt_584144122
[94/380] Collecting: Arsenal vs Chelsea
Saved: mt_361711774
[95/380] Collecting: Bournemouth vs Brentford
Saved: mt_013233224
[96/380] Collecting: Manchester City vs Brighton & Hove Albion
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_745355352
[97/380] Collecting: Ipswich Town vs Nottingham Forest
Saved: mt_408688671
[98/380] Collecting: Everton vs West Ham United
Saved: mt_257077065
[99/380] Collecting: Southampton vs Wolverhampton
Saved: mt_830905722
[100/380] Collecting: West Ham United vs Newcastle United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_196566554
[101/380] Collecting: Manchester United vs Arsenal
Saved: mt_408688607
[102/380] Collecting: Tottenham Hotspur vs Bournemouth
Saved: mt_745355347
[103/380] Collecting: Chelsea vs Leicester City
Saved: mt_830900946
[104/380] Collecting: Wolverhampton vs Everton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_972822887
[105/380] Collecting: Brentford vs Aston Villa
Saved: mt_013233281
[106/380] Collecting: Liverpool vs Southampton
Saved: mt_584144188
[107/380] Collecting: Crystal Palace vs Ipswich Town
Saved: mt_196566531
[108/380] Collecting: Brighton & Hove Albion vs Fulham
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_629499413
[109/380] Collecting: Nottingham Forest vs Manchester City
Saved: mt_361711762
[110/380] Collecting: West Ham United vs Leicester City
Saved: mt_251903078
[111/380] Collecting: Liverpool vs Newcastle United
Saved: mt_830900920
[112/380] Collecting: Manchester United vs Ipswich Town
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_257077032
[113/380] Collecting: Tottenham Hotspur vs Manchester City
Saved: mt_408688045
[114/380] Collecting: Nottingham Forest vs Arsenal
Saved: mt_013233107
[115/380] Collecting: Brentford vs Everton
Saved: mt_830900379
[116/380] Collecting: Chelsea vs Southampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_629499484
[117/380] Collecting: Crystal Palace vs Aston Villa
Saved: mt_584144166
[118/380] Collecting: Wolverhampton vs Fulham
Saved: mt_257077521
[119/380] Collecting: Brighton & Hove Albion vs Bournemouth
Saved: mt_196566986
[120/380] Collecting: Manchester City vs Liverpool
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_361718418
[121/380] Collecting: Newcastle United vs Nottingham Forest
Saved: mt_584144839
[122/380] Collecting: Aston Villa vs Chelsea
Saved: mt_257076161
[123/380] Collecting: Southampton vs Brighton & Hove Albion
Saved: mt_408688029
[124/380] Collecting: Arsenal vs West Ham United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_196566970
[125/380] Collecting: Bournemouth vs Wolverhampton
Saved: mt_830900363
[126/380] Collecting: Ipswich Town vs Tottenham Hotspur
Saved: mt_745359650
[127/380] Collecting: Fulham vs Crystal Palace
Saved: mt_013234538
[128/380] Collecting: Everton vs Manchester United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_408687280
[129/380] Collecting: Leicester City vs Brentford
Saved: mt_584142946
[130/380] Collecting: Aston Villa vs Liverpool
Saved: mt_745355391
[131/380] Collecting: Tottenham Hotspur vs Manchester United
Saved: mt_972822722
[132/380] Collecting: Liverpool vs Wolverhampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_408688072
[133/380] Collecting: Crystal Palace vs Everton
Saved: mt_745355492
[134/380] Collecting: West Ham United vs Brentford
Saved: mt_629499258
[135/380] Collecting: Southampton vs Bournemouth
Saved: mt_196566965
[136/380] Collecting: Manchester City vs Newcastle United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_830900304
[137/380] Collecting: Fulham vs Nottingham Forest
Saved: mt_196566909
[138/380] Collecting: Aston Villa vs Ipswich Town
Saved: mt_013233123
[139/380] Collecting: Leicester City vs Arsenal
Saved: mt_584144824
[140/380] Collecting: Brighton & Hove Albion vs Chelsea
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_361711673
[141/380] Collecting: Everton vs Liverpool
Saved: mt_837288284
[142/380] Collecting: Chelsea vs West Ham United
Saved: mt_745355427
[143/380] Collecting: Arsenal vs Manchester City
Saved: mt_584144878
[144/380] Collecting: Manchester United vs Crystal Palace
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_408688008
[145/380] Collecting: Brentford vs Tottenham Hotspur
Saved: mt_629499219
[146/380] Collecting: Wolverhampton vs Aston Villa
Saved: mt_972822788
[147/380] Collecting: Newcastle United vs Fulham
Saved: mt_830900338
[148/380] Collecting: Ipswich Town vs Southampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_013233114
[149/380] Collecting: Everton vs Leicester City
Saved: mt_257077559
[150/380] Collecting: Bournemouth vs Liverpool
Saved: mt_257077593
[151/380] Collecting: Nottingham Forest vs Brighton & Hove Albion
Saved: mt_196566953
[152/380] Collecting: Fulham vs Manchester United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_745355270
[153/380] Collecting: Aston Villa vs West Ham United
Saved: mt_584144756
[154/380] Collecting: Tottenham Hotspur vs Leicester City
Saved: mt_361711651
[155/380] Collecting: Crystal Palace vs Brentford
Saved: mt_361711038
[156/380] Collecting: Manchester City vs Chelsea
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_584144867
[157/380] Collecting: Wolverhampton vs Arsenal
Saved: mt_745355416
[158/380] Collecting: Southampton vs Newcastle United
Saved: mt_408688096
[159/380] Collecting: Liverpool vs Ipswich Town
Saved: mt_257077922
[160/380] Collecting: Brighton & Hove Albion vs Everton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_408688540
[161/380] Collecting: Bournemouth vs Nottingham Forest
Saved: mt_257077911
[162/380] Collecting: Chelsea vs Wolverhampton
Saved: mt_408687876
[163/380] Collecting: Ipswich Town vs Manchester City
Saved: mt_745359545
[164/380] Collecting: Nottingham Forest vs Southampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_361711047
[165/380] Collecting: Manchester United vs Brighton & Hove Albion
Saved: mt_584144735
[166/380] Collecting: Everton vs Tottenham Hotspur
Saved: mt_830905090
[167/380] Collecting: Arsenal vs Aston Villa
Saved: mt_584142416
[168/380] Collecting: West Ham United vs Crystal Palace
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_745355265
[169/380] Collecting: Leicester City vs Fulham
Saved: mt_972821279
[170/380] Collecting: Brentford vs Liverpool
Saved: mt_196560697
[171/380] Collecting: Newcastle United vs Bournemouth
Saved: mt_408688525
[172/380] Collecting: Manchester United vs Southampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_629493521
[173/380] Collecting: Ipswich Town vs Brighton & Hove Albion
Saved: mt_013234927
[174/380] Collecting: Arsenal vs Tottenham Hotspur
Saved: mt_257076897
[175/380] Collecting: Newcastle United vs Wolverhampton
Saved: mt_745359035
[176/380] Collecting: Leicester City vs Crystal Palace
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_361718277
[177/380] Collecting: Everton vs Aston Villa
Saved: mt_013234317
[178/380] Collecting: Nottingham Forest vs Liverpool
Saved: mt_629493542
[179/380] Collecting: Chelsea vs Bournemouth
Saved: mt_257076801
[180/380] Collecting: West Ham United vs Fulham
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_745359023
[181/380] Collecting: Brentford vs Manchester City
Saved: mt_629493922
[182/380] Collecting: Wolverhampton vs Nottingham Forest
Saved: mt_361718167
[183/380] Collecting: Liverpool vs Manchester United
Saved: mt_013234980
[184/380] Collecting: Fulham vs Ipswich Town
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_408687165
[185/380] Collecting: Brighton & Hove Albion vs Arsenal
Saved: mt_830905695
[186/380] Collecting: Aston Villa vs Leicester City
Saved: mt_584142385
[187/380] Collecting: Southampton vs Brentford
Saved: mt_196560796
[188/380] Collecting: Bournemouth vs Everton
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_830905639
[189/380] Collecting: Manchester City vs West Ham United
Saved: mt_830905643
[190/380] Collecting: Crystal Palace vs Chelsea
Saved: mt_745359513
[191/380] Collecting: Tottenham Hotspur vs Newcastle United
Saved: mt_745359049
[192/380] Collecting: Brentford vs Arsenal
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_196560015
[193/380] Collecting: Manchester United vs Newcastle United
Saved: mt_972821473
[194/380] Collecting: Aston Villa vs Brighton & Hove Albion
Saved: mt_196560757
[195/380] Collecting: Ipswich Town vs Chelsea
Saved: mt_196560730
[196/380] Collecting: West Ham United vs Liverpool
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_584142379
[197/380] Collecting: Crystal Palace vs Southampton
Saved: mt_972821489
[198/380] Collecting: Tottenham Hotspur vs Wolverhampton
Saved: mt_257076858
[199/380] Collecting: Everton vs Nottingham Forest
Saved: mt_361718266
[200/380] Collecting: Fulham vs Bournemouth
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_408687109
[201/380] Collecting: Leicester City vs Manchester City
Saved: mt_972821464
[202/380] Collecting: Arsenal vs Ipswich Town
Saved: mt_972821247
[203/380] Collecting: Brighton & Hove Albion vs Brentford
Saved: mt_408687818
[204/380] Collecting: Liverpool vs Leicester City
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_013234394
[205/380] Collecting: Wolverhampton vs Manchester United
Saved: mt_972821238
[206/380] Collecting: Southampton vs West Ham United
Saved: mt_196560683
[207/380] Collecting: Nottingham Forest vs Tottenham Hotspur

In [112]:
# Verify that all matches in season 2024/25 saved properly.

season_2024_dir = SEASON_DIRS["2024_25"]

saved_files = list(season_2024_dir.glob("*.json"))

print("Saved matches:", len(saved_files))

Saved matches: 380

In [113]:
# Check for incomplete files
incomplete_files = []

for file_path in SEASON_DIRS["2024_25"].glob("*.json"):
    with open(file_path, "r", encoding = "utf-8") as f:
        data = json.load(f)

    missing = [
        section
        for section in ["details", "statistics", "odds"]
        if data.get(section) is None
    ]

    if missing:
        incomplete_files.append((file_path.name, missing))

print("Total files:", len(saved_files))
print("Incomplete files:", len(incomplete_files))

if incomplete_files:
    for file_name, missing in incomplete_files:
        print(file_name, "- MISSING:", missing)
else:
    print("All 2024/25 files are complete.")

Total files: 380
Incomplete files: 0
All 2024/25 files are complete.

In [114]:
# Start collecting historical data from season 2023/24
# First conduct an initial check on that season.
matches_2023_24 = get_all_season_matches(
    PREMIER_LEAGUE_ID,
    SEASONS["2023_24"]
)

print("Matches found:", len(matches_2023_24))

Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Matches found: 380

In [115]:
status_counts_2023_24 = Counter(
    match["status"] for match in matches_2023_24
)

print(status_counts_2023_24)

Counter({'finished': 380})

In [116]:
# This season doesn't need any filtering
# Go ahead and collect all the data from that season.

collect_season_baseline_data(
    "2023_24",
    matches_2023_24
)

[1/380] Collecting: Sheffield United vs Tottenham Hotspur
Saved: mt_012211518
[2/380] Collecting: Manchester City vs West Ham United
Saved: mt_250055191
[3/380] Collecting: Luton Town vs Fulham
Saved: mt_839933745
[4/380] Collecting: Liverpool vs Wolverhampton
Saved: mt_406600255
[5/380] Collecting: Crystal Palace vs Aston Villa
Saved: mt_978877303
[6/380] Collecting: Chelsea vs Bournemouth
Saved: mt_839933729
[7/380] Collecting: Burnley vs Nottingham Forest
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_406600299
[8/380] Collecting: Brighton & Hove Albion vs Manchester United
Saved: mt_978877494
[9/380] Collecting: Brentford vs Newcastle United
Saved: mt_743344073
[10/380] Collecting: Arsenal vs Everton
Saved: mt_624422568
[11/380] Collecting: Manchester United vs Newcastle United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_257357296
[12/380] Collecting: Brighton & Hove Albion vs Chelsea
Saved: mt_196496135
[13/380] Collecting: Tottenham Hotspur vs Manchester City
Saved: mt_013713004
[14/380] Collecting: Aston Villa vs Liverpool
Saved: mt_581188342
[15/380] Collecting: Manchester United vs Arsenal
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_978877441
[16/380] Collecting: Nottingham Forest vs Chelsea
Saved: mt_743344064
[17/380] Collecting: Tottenham Hotspur vs Burnley
Saved: mt_978877432
[18/380] Collecting: Newcastle United vs Brighton & Hove Albion
Saved: mt_624422556
[19/380] Collecting: Everton vs Sheffield United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_367766213
[20/380] Collecting: Bournemouth vs Brentford
Saved: mt_743344051
[21/380] Collecting: Wolverhampton vs Crystal Palace
Saved: mt_624422535
[22/380] Collecting: West Ham United vs Luton Town
Saved: mt_581188321
[23/380] Collecting: Fulham vs Manchester City
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_743344002
[24/380] Collecting: Crystal Palace vs Manchester United
Saved: mt_408997867
[25/380] Collecting: Liverpool vs Tottenham Hotspur
Saved: mt_195599791
[26/380] Collecting: Chelsea vs West Ham United
Saved: mt_012211911
[27/380] Collecting: Brighton & Hove Albion vs Aston Villa
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_839933640
[28/380] Collecting: Manchester City vs Wolverhampton
Saved: mt_367766272
[29/380] Collecting: Sheffield United vs Nottingham Forest
Saved: mt_195599704
[30/380] Collecting: Burnley vs Newcastle United
Saved: mt_250055892
[31/380] Collecting: Brentford vs Fulham
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_406600150
[32/380] Collecting: Arsenal vs Bournemouth
Saved: mt_978877409
[33/380] Collecting: Luton Town vs Everton
Saved: mt_581188318
[34/380] Collecting: Chelsea vs Tottenham Hotspur
Saved: mt_013774054
[35/380] Collecting: Nottingham Forest vs Manchester City
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_195599616
[36/380] Collecting: Tottenham Hotspur vs Arsenal
Saved: mt_978877293
[37/380] Collecting: Bournemouth vs Brighton & Hove Albion
Saved: mt_250055786
[38/380] Collecting: Aston Villa vs Chelsea
Saved: mt_012211395
[39/380] Collecting: Everton vs Brentford
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_367766140
[40/380] Collecting: Wolverhampton vs Luton Town
Saved: mt_743344015
[41/380] Collecting: Newcastle United vs Sheffield United
Saved: mt_367766136
[42/380] Collecting: Manchester United vs Burnley
Saved: mt_581188499
[43/380] Collecting: Fulham vs Crystal Palace
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_195599680
[44/380] Collecting: West Ham United vs Liverpool
Saved: mt_624422582
[45/380] Collecting: Brighton & Hove Albion vs Manchester City
Saved: mt_256263330
[46/380] Collecting: Crystal Palace vs Newcastle United
Saved: mt_190104449
[47/380] Collecting: Everton vs Liverpool
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_749791112
[48/380] Collecting: Manchester United vs Sheffield United
Saved: mt_623646660
[49/380] Collecting: Wolverhampton vs Bournemouth
Saved: mt_971989998
[50/380] Collecting: Arsenal vs Chelsea
Saved: mt_971989937
[51/380] Collecting: Fulham vs Liverpool
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_978877218
[52/380] Collecting: Crystal Palace vs West Ham United
Saved: mt_406600868
[53/380] Collecting: Aston Villa vs Bournemouth
Saved: mt_195599654
[54/380] Collecting: Everton vs Nottingham Forest
Saved: mt_743344591
[55/380] Collecting: Wolverhampton vs Arsenal
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_839933064
[56/380] Collecting: Sheffield United vs Burnley
Saved: mt_250055770
[57/380] Collecting: Luton Town vs Brentford
Saved: mt_012211343
[58/380] Collecting: Chelsea vs Everton
Saved: mt_250055732
[59/380] Collecting: Arsenal vs Aston Villa
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_195599017
[60/380] Collecting: West Ham United vs Fulham
Saved: mt_624422929
[61/380] Collecting: Liverpool vs Crystal Palace
Saved: mt_581188477
[62/380] Collecting: Bournemouth vs Manchester United
Saved: mt_367766837
[63/380] Collecting: Nottingham Forest vs Wolverhampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_581188488
[64/380] Collecting: Manchester City vs Luton Town
Saved: mt_624422913
[65/380] Collecting: Burnley vs Brighton & Hove Albion
Saved: mt_367766158
[66/380] Collecting: Brentford vs Sheffield United
Saved: mt_012211378
[67/380] Collecting: Newcastle United vs Tottenham Hotspur
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_195599631
[68/380] Collecting: Tottenham Hotspur vs Nottingham Forest
Saved: mt_250055618
[69/380] Collecting: Sheffield United vs Chelsea
Saved: mt_839933579
[70/380] Collecting: Manchester United vs Liverpool
Saved: mt_012211490
[71/380] Collecting: Brighton & Hove Albion vs Arsenal
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_743344954
[72/380] Collecting: Wolverhampton vs West Ham United
Saved: mt_012211407
[73/380] Collecting: Luton Town vs Bournemouth
Saved: mt_250055687
[74/380] Collecting: Fulham vs Newcastle United
Saved: mt_839933563
[75/380] Collecting: Everton vs Burnley
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_012211435
[76/380] Collecting: Aston Villa vs Brentford
Saved: mt_406600772
[77/380] Collecting: Crystal Palace vs Manchester City
Saved: mt_978877122
[78/380] Collecting: Chelsea vs Manchester United
Saved: mt_195599053
[79/380] Collecting: Liverpool vs Sheffield United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_367766873
[80/380] Collecting: Manchester City vs Aston Villa
Saved: mt_978877111
[81/380] Collecting: Brentford vs Brighton & Hove Albion
Saved: mt_406600757
[82/380] Collecting: Arsenal vs Luton Town
Saved: mt_978877166
[83/380] Collecting: West Ham United vs Tottenham Hotspur
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_624422325
[84/380] Collecting: Burnley vs Wolverhampton
Saved: mt_195599094
[85/380] Collecting: Bournemouth vs Crystal Palace
Saved: mt_743344916
[86/380] Collecting: Newcastle United vs Everton
Saved: mt_581188212
[87/380] Collecting: Nottingham Forest vs Fulham
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_581188281
[88/380] Collecting: Manchester City vs Arsenal
Saved: mt_743344662
[89/380] Collecting: Liverpool vs Brighton & Hove Albion
Saved: mt_367766423
[90/380] Collecting: Brentford vs Manchester United
Saved: mt_012211593
[91/380] Collecting: Aston Villa vs Wolverhampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_581188932
[92/380] Collecting: Tottenham Hotspur vs Luton Town
Saved: mt_012211559
[93/380] Collecting: Sheffield United vs Fulham
Saved: mt_581188994
[94/380] Collecting: Nottingham Forest vs Crystal Palace
Saved: mt_978877331
[95/380] Collecting: Chelsea vs Burnley
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_624422050
[96/380] Collecting: Bournemouth vs Everton
Saved: mt_978877348
[97/380] Collecting: Newcastle United vs West Ham United
Saved: mt_195599889
[98/380] Collecting: West Ham United vs Aston Villa
Saved: mt_743344601
[99/380] Collecting: Fulham vs Tottenham Hotspur
Saved: mt_012211534
[100/380] Collecting: Luton Town vs Nottingham Forest
Saved: mt_624422095
[101/380] Collecting: Burnley vs Brentford
Saved: mt_743344697
[102/380] Collecting: Bournemouth vs Luton Town
Saved: mt_835575639
[103/380] Collecting: Chelsea vs Newcastle United
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_250055152
[104/380] Collecting: Liverpool vs Manchester City
Saved: mt_839933796
[105/380] Collecting: West Ham United vs Burnley
Saved: mt_581188928
[106/380] Collecting: Brighton & Hove Albion vs Nottingham Forest
Saved: mt_743344640
[107/380] Collecting: Aston Villa vs Tottenham Hotspur
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_406600200
[108/380] Collecting: Arsenal vs Brentford
Saved: mt_978877369
[109/380] Collecting: Wolverhampton vs Fulham
Saved: mt_406600277
[110/380] Collecting: Crystal Palace vs Luton Town
Saved: mt_406600266
[111/380] Collecting: Bournemouth vs Sheffield United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_367766407
[112/380] Collecting: Manchester United vs Everton
Saved: mt_250055163
[113/380] Collecting: Sheffield United vs Arsenal
Saved: mt_195599846
[114/380] Collecting: Manchester City vs Manchester United
Saved: mt_839933683
[115/380] Collecting: Burnley vs Bournemouth
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_581188334
[116/380] Collecting: Luton Town vs Aston Villa
Saved: mt_406600124
[117/380] Collecting: Tottenham Hotspur vs Crystal Palace
Saved: mt_012211587
[118/380] Collecting: Nottingham Forest vs Liverpool
Saved: mt_624422081
[119/380] Collecting: Newcastle United vs Wolverhampton
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_581188359
[120/380] Collecting: Fulham vs Brighton & Hove Albion
Saved: mt_195599785
[121/380] Collecting: Everton vs West Ham United
Saved: mt_367766245
[122/380] Collecting: Brentford vs Chelsea
Saved: mt_195599779
[123/380] Collecting: West Ham United vs Brentford
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_250055875
[124/380] Collecting: Wolverhampton vs Sheffield United
Saved: mt_406600181
[125/380] Collecting: Arsenal vs Newcastle United
Saved: mt_581188387
[126/380] Collecting: Bournemouth vs Manchester City
Saved: mt_195599738
[127/380] Collecting: Manchester United vs Fulham
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_839933658
[128/380] Collecting: Crystal Palace vs Burnley
Saved: mt_743344037
[129/380] Collecting: Brighton & Hove Albion vs Everton
Saved: mt_978877486
[130/380] Collecting: Aston Villa vs Nottingham Forest
Saved: mt_743344046
[131/380] Collecting: Liverpool vs Luton Town
Saved: mt_978877417
[132/380] Collecting: Manchester City vs Brentford
Saved: mt_368821282
[133/380] Collecting: Everton vs Crystal Palace
Saved: mt_839933073
[134/380] Collecting: Luton Town vs Manchester United
Saved: mt_406600849
[135/380] Collecting: Sheffield United vs Brighton & Hove Albion
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_250055831
[136/380] Collecting: Manchester City vs Chelsea
Saved: mt_743344579
[137/380] Collecting: Tottenham Hotspur vs Wolverhampton
Saved: mt_624422514
[138/380] Collecting: Nottingham Forest vs West Ham United
Saved: mt_839933625
[139/380] Collecting: Newcastle United vs Bournemouth
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_012211977
[140/380] Collecting: Fulham vs Aston Villa
Saved: mt_978877234
[141/380] Collecting: Burnley vs Arsenal
Saved: mt_581188433
[142/380] Collecting: Brentford vs Liverpool
Saved: mt_195599675
[143/380] Collecting: Crystal Palace vs Chelsea
Saved: mt_406600807
[144/380] Collecting: Aston Villa vs Manchester United
Saved: mt_978877276
[145/380] Collecting: West Ham United vs Arsenal
Saved: mt_581188444
[146/380] Collecting: Nottingham Forest vs Newcastle United
Saved: mt_406600871
[147/380] Collecting: Wolverhampton vs Brentford
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_624422996
[148/380] Collecting: Tottenham Hotspur vs Brighton & Hove Albion
Saved: mt_743344552
[149/380] Collecting: Luton Town vs Sheffield United
Saved: mt_367766174
[150/380] Collecting: Liverpool vs Burnley
Saved: mt_581188411
[151/380] Collecting: Fulham vs Bournemouth
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_743344547
[152/380] Collecting: Manchester City vs Everton
Saved: mt_250055765
[153/380] Collecting: Brentford vs Manchester City
Saved: mt_195599086
[154/380] Collecting: Arsenal vs Liverpool
Saved: mt_624422301
[155/380] Collecting: Manchester United vs West Ham United
Saved: mt_839933020
[156/380] Collecting: Chelsea vs Wolverhampton
Saved: mt_978877199
[157/380] Collecting: Bournemouth vs Nottingham Forest
Saved: mt_978877144
[158/380] Collecting: Sheffield United vs Aston Villa
Saved: mt_743344526
[159/380] Collecting: Newcastle United vs Luton Town
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Saved: mt_978877260
[160/380] Collecting: Burnley vs Fulham
Saved: mt_624422362
[161/380] Collecting: Brighton & Hove Albion vs Crystal Palace
Saved: mt_581188295
[162/380] Collecting: Everton vs Tottenham Hotspur
Saved: mt_406600890
[163/380] Collecting: Wolverhampton vs Manchester United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_971816298
[164/380] Collecting: West Ham United vs Bournemouth
Saved: mt_012211449
[165/380] Collecting: Liverpool vs Chelsea
Saved: mt_406600784
[166/380] Collecting: Manchester City vs Burnley
Saved: mt_743344903
[167/380] Collecting: Tottenham Hotspur vs Brentford
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_250055660
[168/380] Collecting: Aston Villa vs Newcastle United
Saved: mt_839933538
[169/380] Collecting: Crystal Palace vs Sheffield United
Saved: mt_250055676
[170/380] Collecting: Luton Town vs Brighton & Hove Albion
Saved: mt_012211423
[171/380] Collecting: Fulham vs Everton
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_978877188
[172/380] Collecting: Nottingham Forest vs Arsenal
Saved: mt_839933552
[173/380] Collecting: Brighton & Hove Albion vs Wolverhampton
Saved: mt_406600796
[174/380] Collecting: Bournemouth vs Liverpool
Saved: mt_839933980
[175/380] Collecting: Sheffield United vs West Ham United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_012211414
[176/380] Collecting: Brentford vs Nottingham Forest
Saved: mt_581188267
[177/380] Collecting: Arsenal vs Crystal Palace
Saved: mt_250055022
[178/380] Collecting: Manchester United vs Tottenham Hotspur
Saved: mt_839933547
[179/380] Collecting: Everton vs Aston Villa
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_012211482
[180/380] Collecting: Newcastle United vs Manchester City
Saved: mt_250055659
[181/380] Collecting: Chelsea vs Fulham
Saved: mt_250055693
[182/380] Collecting: Burnley vs Luton Town
Saved: mt_839933526
[183/380] Collecting: West Ham United vs Brighton & Hove Albion
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_743344636
[184/380] Collecting: Liverpool vs Newcastle United
Saved: mt_195599898
[185/380] Collecting: Tottenham Hotspur vs Bournemouth
Saved: mt_367766471
[186/380] Collecting: Fulham vs Arsenal
Saved: mt_367766468
[187/380] Collecting: Nottingham Forest vs Manchester United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_624422043
[188/380] Collecting: Wolverhampton vs Everton
Saved: mt_978877316
[189/380] Collecting: Manchester City vs Sheffield United
Saved: mt_581188917
[190/380] Collecting: Crystal Palace vs Brentford
Saved: mt_624422024
[191/380] Collecting: Aston Villa vs Burnley
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_581188986
[192/380] Collecting: Luton Town vs Chelsea
Saved: mt_978877380
[193/380] Collecting: Arsenal vs West Ham United
Saved: mt_256963061
[194/380] Collecting: Brighton & Hove Albion vs Tottenham Hotspur
Saved: mt_190304507
[195/380] Collecting: Everton vs Manchester City
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_743344619
[196/380] Collecting: Chelsea vs Crystal Palace
Saved: mt_367766456
[197/380] Collecting: Brentford vs Wolverhampton
Saved: mt_367766230
[198/380] Collecting: Manchester United vs Aston Villa
Saved: mt_581188965
[199/380] Collecting: Burnley vs Liverpool
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_012211900
[200/380] Collecting: Sheffield United vs Luton Town
Saved: mt_743344625
[201/380] Collecting: Bournemouth vs Fulham
Saved: mt_250055816
[202/380] Collecting: Newcastle United vs Nottingham Forest
Saved: mt_624422012
[203/380] Collecting: Wolverhampton vs Chelsea
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_839933674
[204/380] Collecting: Liverpool vs Arsenal
Saved: mt_195599763
[205/380] Collecting: Tottenham Hotspur vs Everton
Saved: mt_250055880
[206/380] Collecting: Nottingham Forest vs Bournemouth
Saved: mt_839933662
[207/380] Collecting: Luton Town vs Newcastle United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_978877428
[208/380] Collecting: Fulham vs Burnley
Saved: mt_367766284
[209/380] Collecting: West Ham United vs Manchester United
Saved: mt_406600112
[210/380] Collecting: Aston Villa vs Sheffield United
Saved: mt_250055869
[211/380] Collecting: Crystal Palace vs Brighton & Hove Albion
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_012211944
[212/380] Collecting: Liverpool vs Manchester United
Saved: mt_624422523
[213/380] Collecting: West Ham United vs Wolverhampton
Saved: mt_839933697
[214/380] Collecting: Brentford vs Aston Villa
Saved: mt_367766208
[215/380] Collecting: Arsenal vs Brighton & Hove Albion
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_581188376
[216/380] Collecting: Burnley vs Everton
Saved: mt_743344020
[217/380] Collecting: Newcastle United vs Fulham
Saved: mt_250055803
[218/380] Collecting: Manchester City vs Crystal Palace
Saved: mt_839933636
[219/380] Collecting: Chelsea vs Sheffield United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_978877470
[220/380] Collecting: Nottingham Forest vs Tottenham Hotspur
Saved: mt_406600167
[221/380] Collecting: Tottenham Hotspur vs Newcastle United
Saved: mt_581188455
[222/380] Collecting: Luton Town vs Manchester City
Saved: mt_012211350
[223/380] Collecting: Fulham vs West Ham United
Rate limit reached. Waiting 5 seconds before retry 1/5
Saved: mt_250055717
[224/380] Collecting: Everton vs Chelsea
Saved: mt_743344563
[225/380] Collecting: Aston Villa vs Arsenal
Saved: mt_743344504
[226/380] Collecting: Wolverhampton vs Nottingham Forest
Saved: mt_367766257
[227/380] Collecting: Sheffield United vs Brentford
Rate limit reached. Waiting 5 seconds before retry 1/5

In [313]:
# ---------------------------------------------------------
# GET 2026/27 PREMIER LEAGUE MATCH LIST
# ---------------------------------------------------------

matches_2026_27 = get_all_season_matches(
    "comp_3039",
    "sn_8406098"
)

print(
    "2026/27 Premier League matches found:",
    len(matches_2026_27)
)

2026/27 Premier League matches found: 60

In [314]:
print("Total returned:", len(matches_2026_27))
print()

for match in matches_2026_27[:10]:
    print(
        match.get("id"),
        match.get("date"),
        match.get("status"),
        match.get("home_team", {}).get("name"),
        "vs",
        match.get("away_team", {}).get("name")
    )

Total returned: 60

mt_022588781 None scheduled Coventry City vs Newcastle United
mt_899744246 None scheduled Liverpool vs Manchester City
mt_644011813 None scheduled Hull City vs Everton
mt_466255956 None scheduled Crystal Palace vs Nottingham Forest
mt_733622126 None scheduled Manchester United vs Tottenham Hotspur
mt_155833431 None scheduled Sunderland vs Brighton & Hove Albion
mt_377400501 None scheduled Ipswich Town vs Fulham
mt_511977677 None scheduled Chelsea vs Bournemouth
mt_988366060 None scheduled Aston Villa vs Brentford
mt_200199332 None scheduled Arsenal vs Leeds United

In [315]:
from collections import Counter

status_counts = Counter(
    match.get("status")
    for match in matches_2026_27
)

print("STATUS COUNTS")
print()

for status, count in status_counts.items():
    print(status, count)

STATUS COUNTS

scheduled 40
finished 20

In [316]:
# ---------------------------------------------------------
# KEEP ONLY FINISHED 2026/27 PREMIER LEAGUE MATCHES
# ---------------------------------------------------------

finished_matches_2026_27 = [
    match
    for match in matches_2026_27
    if match.get("status") == "finished"
]


print(
    "Finished 2026/27 Premier League matches:",
    len(finished_matches_2026_27)
)

Finished 2026/27 Premier League matches: 20

In [317]:
# ---------------------------------------------------------
# COLLECT / RESUME FINISHED 2026/27 MATCHES
# ---------------------------------------------------------

collect_season_baseline_data(
    "2026_27",
    finished_matches_2026_27
)

[1/20] Collecting: Aston Villa vs Arsenal
Saved: mt_466259566
[2/20] Collecting: Manchester United vs Ipswich Town
Saved: mt_511976728
[3/20] Collecting: Leeds United vs Brentford
Saved: mt_644018195
[4/20] Collecting: Sunderland vs Fulham
Saved: mt_466259577
[5/20] Collecting: Chelsea vs Brighton & Hove Albion
Saved: mt_733621236
[6/20] Skipping mt_644018139 - already saved
[7/20] Skipping mt_155834351 - already saved
[8/20] Skipping mt_377405071 - already saved
[9/20] Skipping mt_022587842 - already saved
[10/20] Skipping mt_988360616 - already saved
[11/20] Skipping mt_022587821 - already saved
[12/20] Skipping mt_644018143 - already saved
[13/20] Skipping mt_511976717 - already saved
[14/20] Skipping mt_644018124 - already saved
[15/20] Skipping mt_988360680 - already saved
[16/20] Skipping mt_644018510 - already saved
[17/20] Skipping mt_466259151 - already saved
[18/20] Skipping mt_899742430 - already saved
[19/20] Skipping mt_022587983 - already saved
[20/20] Skipping mt_511976372 - already saved

In [321]:
import json
import pandas as pd
from pathlib import Path


# ---------------------------------------------------------
# PATHS
# ---------------------------------------------------------

RAW_MATCH_DIR = Path("../data/raw/matches")

PROCESSED_DIR = Path("../data/processed")

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ---------------------------------------------------------
# SAFE STAT EXTRACTOR
# ---------------------------------------------------------

def get_stat(statistics, team_side, stat_name):

    if statistics is None:
        return None

    if isinstance(statistics, dict):
        statistics = statistics.get(
            "data",
            statistics
        )

    if not isinstance(statistics, dict):
        return None

    team_stats = statistics.get(
        team_side,
        {}
    )

    if not isinstance(team_stats, dict):
        return None

    value = team_stats.get(
        stat_name
    )

    return value


# ---------------------------------------------------------
# PROCESS ONE RAW MATCH FILE
# ---------------------------------------------------------

def process_match_file(file_path):

    try:

        with open(
            file_path,
            "r",
            encoding="utf-8"
        ) as f:

            match_data = json.load(f)

    except Exception as e:

        print(
            f"Could not read {file_path}: {e}"
        )

        return None


    # -----------------------------------------------------
    # DETAILS
    # -----------------------------------------------------

    details = match_data.get(
        "details"
    )

    if details is None:
        return None

    if isinstance(details, dict):

        details = details.get(
            "data",
            details
        )

    if not isinstance(details, dict):
        return None


    # Only completed matches
    if details.get("status") != "finished":
        return None


    # -----------------------------------------------------
    # STATISTICS
    # -----------------------------------------------------

    statistics = match_data.get(
        "statistics"
    )


    # -----------------------------------------------------
    # TEAM INFORMATION
    # -----------------------------------------------------

    home_team_data = details.get(
        "home_team",
        {}
    )

    away_team_data = details.get(
        "away_team",
        {}
    )


    home_team = (
        home_team_data.get("name")
        if isinstance(
            home_team_data,
            dict
        )
        else None
    )

    away_team = (
        away_team_data.get("name")
        if isinstance(
            away_team_data,
            dict
        )
        else None
    )


    # -----------------------------------------------------
    # SCORE
    # -----------------------------------------------------

    home_goals = details.get(
        "home_score"
    )

    away_goals = details.get(
        "away_score"
    )


    # Some API responses may store score differently
    if isinstance(home_goals, dict):

        home_goals = (
            home_goals.get("current")
            or home_goals.get("display")
        )


    if isinstance(away_goals, dict):

        away_goals = (
            away_goals.get("current")
            or away_goals.get("display")
        )


    # -----------------------------------------------------
    # WINNER
    # -----------------------------------------------------

    winner = None

    if (
        home_goals is not None
        and away_goals is not None
    ):

        try:

            if home_goals > away_goals:
                winner = "H"

            elif away_goals > home_goals:
                winner = "A"

            else:
                winner = "D"

        except TypeError:
            winner = None


    # -----------------------------------------------------
    # FOLDER INFORMATION
    #
    # .../matches/competition/season/file.json
    # -----------------------------------------------------

    season = file_path.parent.name

    competition = (
        file_path
        .parent
        .parent
        .name
    )


    # -----------------------------------------------------
    # BUILD ROW
    # -----------------------------------------------------

    row = {

        "match_id":
            details.get("id"),

        "date":
            details.get("date"),

        "season":
            season,

        "competition":
            competition,

        "matchday":
            details.get("matchday"),

        "home_team":
            home_team,

        "away_team":
            away_team,

        "home_goals":
            home_goals,

        "away_goals":
            away_goals,

        "home_xg":
            get_stat(
                statistics,
                "home",
                "expected_goals"
            ),

        "away_xg":
            get_stat(
                statistics,
                "away",
                "expected_goals"
            ),

        "home_shots":
            get_stat(
                statistics,
                "home",
                "shots"
            ),

        "away_shots":
            get_stat(
                statistics,
                "away",
                "shots"
            ),

        "home_shots_on_target":
            get_stat(
                statistics,
                "home",
                "shots_on_target"
            ),

        "away_shots_on_target":
            get_stat(
                statistics,
                "away",
                "shots_on_target"
            ),

        "home_possession":
            get_stat(
                statistics,
                "home",
                "ball_possession"
            ),

        "away_possession":
            get_stat(
                statistics,
                "away",
                "ball_possession"
            ),

        "home_passes":
            get_stat(
                statistics,
                "home",
                "passes"
            ),

        "away_passes":
            get_stat(
                statistics,
                "away",
                "passes"
            ),

        "home_corners":
            get_stat(
                statistics,
                "home",
                "corners"
            ),

        "away_corners":
            get_stat(
                statistics,
                "away",
                "corners"
            ),

        "winner":
            winner
    }


    return row


# ---------------------------------------------------------
# PROCESS ALL RAW JSON FILES
# ---------------------------------------------------------

rows = []


for file_path in RAW_MATCH_DIR.rglob("*.json"):

    row = process_match_file(
        file_path
    )

    if row is not None:
        rows.append(row)


historical_df = pd.DataFrame(
    rows
)


# ---------------------------------------------------------
# REMOVE DUPLICATE MATCH IDS
# ---------------------------------------------------------

historical_df = (
    historical_df
    .drop_duplicates(
        subset="match_id",
        keep="last"
    )
    .copy()
)


# ---------------------------------------------------------
# SORT
# ---------------------------------------------------------

historical_df["date"] = pd.to_datetime(
    historical_df["date"],
    utc=True,
    errors="coerce"
)


historical_df = (
    historical_df
    .sort_values(
        [
            "date",
            "match_id"
        ]
    )
    .reset_index(
        drop=True
    )
)


# ---------------------------------------------------------
# SAVE
# ---------------------------------------------------------

output_path = (
    PROCESSED_DIR
    / "historical_matches.csv"
)


historical_df.to_csv(
    output_path,
    index=False
)


# ---------------------------------------------------------
# CHECK RESULTS
# ---------------------------------------------------------

print(
    "Historical shape:",
    historical_df.shape
)

print()

print(
    "COMPETITION COUNTS"
)

print()

print(
    historical_df[
        "competition"
    ]
    .value_counts()
)

print()

print(
    "Premier League by season"
)

print()

print(
    historical_df[
        historical_df[
            "competition"
        ]
        == "premier_league"
    ][
        "season"
    ]
    .value_counts()
    .sort_index()
)

print()

print(
    "Saved:",
    output_path
)

Historical shape: (10673, 22)

COMPETITION COUNTS

competition
championship         3342
premier_league       2300
europa_league        1426
champions_league     1383
conference_league     869
fa_cup                798
efl_cup               555
Name: count, dtype: int64

Premier League by season

season
2020_21    380
2021_22    380
2022_23    380
2023_24    380
2024_25    380
2025_26    380
2026_27     20
Name: count, dtype: int64

Saved: ..\data\processed\historical_matches.csv

In [117]:
# Verify all matches were saved.

season_2023_dir = SEASON_DIRS["2023_24"]

saved_files = list(season_2023_dir.glob("*.json"))

print("Saved matches:", len(saved_files))

Saved matches: 380

In [118]:
incomplete_files = []

for file_path in SEASON_DIRS["2023_24"].glob("*.json"):
    with open(file_path, "r", encoding = "utf-8") as f:
        data = json.load(f)

    missing = [
        section
        for section in ["details", "statistics", "odds"]
        if data.get(section) is None
    ]

    if missing:
        incomplete_files.append((file_path.name, missing))

print("Total files:", len(saved_files))
print("incomplete files:", len(incomplete_files))

if incomplete_files:
    for file_name, missing in incomplete_files:
        print(file_name, "- MISSING:", missing)
else:
    print("All 2023/24 files are complete.")

Total files: 380
incomplete files: 0
All 2023/24 files are complete.

In [119]:
import shutil

current_season_dir = SEASON_DIRS["2026_27"]

for file_path in RAW_MATCH_DIR.glob("*.json"):
    destination = current_season_dir / file_path.name

    shutil.move(str(file_path), str(destination))

    print("Moved:", file_path.name)

Moved: mt_022587821.json
Moved: mt_022587983.json
Moved: mt_466259151.json
Moved: mt_511976372.json
Moved: mt_511976717.json
Moved: mt_644018124.json
Moved: mt_644018143.json
Moved: mt_644018510.json
Moved: mt_899742430.json
Moved: mt_988360680.json

In [189]:
def get_stat(overview, stat_name, side):
    stat = overview.get(stat_name)

    if stat is None:
        return None

    full_match = stat.get("all")

    if full_match is None:
        return None

    return full_match.get(side)

In [190]:
missing_xg_matches = []

for season_name in ["2023_24", "2024_25", "2025_26"]:
    season_dir = SEASON_DIRS[season_name]

    for file_path in season_dir.glob("*.json"):
        with open(file_path, "r", encoding="utf-8") as f:
            match_data = json.load(f)

        details = match_data["details"]["data"]
        overview = match_data["statistics"]["data"]["overview"]

        expected_goals = overview.get("expected_goals")

        if expected_goals is None or expected_goals.get("all") is None:
            missing_xg_matches.append({
                "season": season_name,
                "match_id": details["id"],
                "home_team": details["home_team"]["name"],
                "away_team": details["away_team"]["name"]
            })

print("Matches missing xG:", len(missing_xg_matches))

for match in missing_xg_matches:
    print(match)

Matches missing xG: 2
{'season': '2023_24', 'match_id': 'mt_581188321', 'home_team': 'West Ham United', 'away_team': 'Luton Town'}
{'season': '2023_24', 'match_id': 'mt_978877432', 'home_team': 'Tottenham Hotspur', 'away_team': 'Burnley'}

In [197]:
# Helper function for matches with no xG.
def get_stat(stats, stat_name, side):
    stat = stats["overview"].get(stat_name)

    if stat is None or stat.get("all") is None:
        return None

    return stat["all"][side]

In [198]:
def extract_historical_match_row(match_data):
    details = match_data["details"]["data"]
    stats = match_data["statistics"]["data"]

    return {
        "match_id": details["id"],
        "date": details["utc_date"],
        "matchday": details["matchday"],

        "home_team": details["home_team"]["name"],
        "away_team": details["away_team"]["name"],

        "home_goals": details["score"]["home"],
        "away_goals": details["score"]["away"],

        "home_xg": get_stat(stats, "expected_goals", "home"),
        "away_xg": get_stat(stats, "expected_goals", "away"),

        "home_shots": get_stat(stats, "total_shots", "home"),
        "away_shots": get_stat(stats, "total_shots", "away"),

        "home_shots_on_target": get_stat(stats, "shots_on_target", "home"),
        "away_shots_on_target": get_stat(stats, "shots_on_target", "away"),

        "home_possession": get_stat(stats, "ball_possession", "home"),
        "away_possession": get_stat(stats, "ball_possession", "away"),

        "home_passes": get_stat(stats, "passes", "home"),
        "away_passes": get_stat(stats, "passes", "away"),

        "home_corners": get_stat(stats, "corner_kicks", "home"),
        "away_corners": get_stat(stats, "corner_kicks", "away"),

        "winner": details["score"]["winner"]
    }

In [199]:
historical_rows = []

for season_name in ["2023_24", "2024_25", "2025_26"]:
    season_dir = SEASON_DIRS[season_name]

    for file_path in season_dir.glob("*.json"):
        with open(file_path, "r", encoding="utf-8") as f:
            match_data = json.load(f)

        row = extract_historical_match_row(match_data)
        row["season"] = season_name

        historical_rows.append(row)

print("Historical rows collected:", len(historical_rows))

Historical rows collected: 1140

In [200]:
# Turning our historical seasons rows into a DataFrame

historical_df = pd.DataFrame(historical_rows)

historical_df.shape

(1140, 21)

In [201]:
historical_df.head()

,match_id,date,matchday,home_team,away_team,home_goals,away_goals,home_xg,away_xg,home_shots,...,home_shots_on_target,away_shots_on_target,home_possession,away_possession,home_passes,away_passes,home_corners,away_corners,winner,season
0,mt_012211017,2023-10-07T14:00:00.000Z,8,Manchester United,Brentford,2,1,1.43,0.95,21.0,...,8.0,3.0,64.0,36.0,557.0,326.0,7.0,5.0,home,2023_24
1,mt_012211028,2023-10-21T14:00:00.000Z,9,Newcastle United,Crystal Palace,4,0,2.39,1.21,10.0,...,7.0,3.0,60.0,40.0,573.0,389.0,6.0,8.0,home,2023_24
2,mt_012211041,2023-10-29T14:00:00.000Z,10,Liverpool,Nottingham Forest,3,0,3.19,0.45,21.0,...,8.0,1.0,73.0,27.0,728.0,266.0,8.0,3.0,home,2023_24
3,mt_012211070,2023-09-30T16:30:00.000Z,7,Tottenham Hotspur,Liverpool,2,1,2.23,1.31,24.0,...,8.0,4.0,65.0,35.0,662.0,364.0,11.0,5.0,home,2023_24
4,mt_012211208,2023-11-04T15:00:00.000Z,11,Brentford,West Ham United,3,2,1.63,1.82,16.0,...,4.0,2.0,59.0,41.0,560.0,373.0,4.0,3.0,home,2023_24

In [ ]:
# Checking to see if there are any null values to clean up.
historical_df.isnull().sum()

match_id                0
date                    0
matchday                0
home_team               0
away_team               0
home_goals              0
away_goals              0
home_xg                 2
away_xg                 2
home_shots              2
away_shots              2
home_shots_on_target    3
away_shots_on_target    3
home_possession         2
away_possession         2
home_passes             3
away_passes             3
home_corners            2
away_corners            2
winner                  0
season                  0
dtype: int64

In [203]:
historical_df["date"] = pd.to_datetime(
    historical_df["date"],
    utc = True
)

historical_df.dtypes

match_id                                str
date                    datetime64[us, UTC]
matchday                              int64
home_team                               str
away_team                               str
home_goals                            int64
away_goals                            int64
home_xg                             float64
away_xg                             float64
home_shots                          float64
away_shots                          float64
home_shots_on_target                float64
away_shots_on_target                float64
home_possession                     float64
away_possession                     float64
home_passes                         float64
away_passes                         float64
home_corners                        float64
away_corners                        float64
winner                                  str
season                                  str
dtype: object

In [204]:
# Conduct a final quality check.

print("Total matches:", len(historical_df))
print("Duplicate match IDs:", historical_df["match_id"].duplicated().sum())

print("\nMatches per season:")
print(historical_df["season"].value_counts())

print("\nDate range:")
print(historical_df["date"].min())
print(historical_df["date"].max())

Total matches: 1140
Duplicate match IDs: 0

Matches per season:
season
2023_24    380
2024_25    380
2025_26    380
Name: count, dtype: int64

Date range:
2023-08-11 19:00:00+00:00
2026-05-24 15:00:00+00:00

In [318]:
# Saving the processed historical dataset.

historical_file = PROCESSED_DIR / "historical_matches.csv"

historical_df.to_csv(
    historical_file,
    index = False
)

print("Saved to:", historical_file)

Saved to: ..\data\processed\historical_matches.csv

In [206]:
# Inspect a historical match's odds structure
# Will help us decide what fields to extract
# Shows us how the API organizes bookmakers, markets, and prices.
sample_file = next(SEASON_DIRS["2023_24"].glob("*.json"))

with open(sample_file, "r", encoding = "utf-8") as f:
    sample_match = json.load(f)

print(json.dumps(sample_match["odds"], indent = 2)[:5000])

{
  "data": {
    "match_id": "mt_012211017",
    "bookmakers": [
      {
        "bookmaker": "Bet365",
        "markets": {
          "match_odds": {
            "home": {
              "opening": null,
              "last_seen": "1.600"
            },
            "draw": {
              "opening": null,
              "last_seen": "4.330"
            },
            "away": {
              "opening": null,
              "last_seen": "5.000"
            }
          },
          "btts": {
            "yes": {
              "opening": null,
              "last_seen": "1.700"
            },
            "no": {
              "opening": null,
              "last_seen": "2.050"
            }
          },
          "total_goals": {
            "0.5": {
              "over": {
                "opening": null,
                "last_seen": "1.040"
              },
              "under": {
                "opening": null,
                "last_seen": "13.000"
              }
            },
            "1.5": {
              "over": {
                "opening": null,
                "last_seen": "1.220"
              },
              "under": {
                "opening": null,
                "last_seen": "4.330"
              }
            },
            "2.5": {
              "over": {
                "opening": null,
                "last_seen": "1.670"
              },
              "under": {
                "opening": null,
                "last_seen": "2.150"
              }
            },
            "3.5": {
              "over": {
                "opening": null,
                "last_seen": "2.750"
              },
              "under": {
                "opening": null,
                "last_seen": "1.440"
              }
            },
            "4.5": {
              "over": {
                "opening": null,
                "last_seen": "5.000"
              },
              "under": {
                "opening": null,
                "last_seen": "1.170"
              }
            },
            "5.5": {
              "over": {
                "opening": null,
                "last_seen": "10.000"
              },
              "under": {
                "opening": null,
                "last_seen": "1.060"
              }
            },
            "6.5": {
              "over": {
                "opening": null,
                "last_seen": "19.000"
              },
              "under": {
                "opening": null,
                "last_seen": "1.020"
              }
            },
            "7.5": {
              "over": {
                "opening": null,
                "last_seen": "41.000"
              },
              "under": {
                "opening": null,
                "last_seen": "1.000"
              }
            }
          },
          "match_corners": {
            "10.5": {
              "over": {
                "opening": null,
                "last_seen": "1.800"
              },
              "under": {
                "opening": null,
                "last_seen": "1.910"
              }
            }
          },
          "total_cards": {
            "4.5": {
              "over": {
                "opening": null,
                "last_seen": "2.100"
              },
              "under": {
                "opening": null,
                "last_seen": "1.670"
              }
            }
          },
          "draw_no_bet": {
            "home": {
              "opening": null,
              "last_seen": "1.290"
            },
            "away": {
              "opening": null,
              "last_seen": "3.500"
            }
          },
          "double_chance": {
            "home_draw": {
              "opening": null,
              "last_seen": "1.180"
            },
            "home_away": {
              "opening": null,
              "last_seen": "1.220"
            },
            "draw_away": {
              "opening": null,
              "last_seen": "2.200"
            }
          },
          "first_half_result": {
            "home": {
              "opening": null,
              "last_seen": "2.200"
            },
            "draw": {
              "opening": null,
              "last_seen": "2.380"
            },
            "away": {
              "opening": null,
              "last_seen": "5.000"
            }
          },
          "first_team_to_score": {
            "home": {
              "opening": null,
              "last_seen": "1.440"
            },
            "away": {
              "opening": null,
              "last_seen": "2.880"
            },
            "none": {
              "opening": null,
              "last_seen": "13.000"
            }
          }
        }
      }
    ]
  }
}

In [207]:
# Check if all 1,140 matches have Bet365 odds
# Showing which bookmakers are available across the dataset and how often they appear.
bookmaker_counts = {}

for season_name in ["2023_24", "2024_25", "2025_26"]:
    season_dir = SEASON_DIRS[season_name]

    for file_path in season_dir.glob("*.json"):
        with open(file_path, "r", encoding = "utf-8") as f:
            match_data = json.load(f)

        bookmakers = match_data["odds"]["data"]["bookmakers"]

        for bookmaker in bookmakers:
            name = bookmaker["bookmaker"]

            bookmaker_counts[name] = bookmaker_counts.get(name, 0) + 1

print(bookmaker_counts)

{'Bet365': 1140}

In [208]:
# Make sure match odds are present for all 1,140 matches.

missing_match_odds = []

for season_name in ["2023_24", "2024_25", "2025_26"]:
    season_dir = SEASON_DIRS[season_name]

    for file_path in season_dir.glob("*.json"):
        with open(file_path, "r", encoding = "utf-8") as f:
            match_data = json.load(f)

        details = match_data["details"]["data"]
        bookmakers = match_data["odds"]["data"]["bookmakers"]

        bet365 = bookmakers[0]
        match_odds = bet365["markets"].get("match_odds")

        if match_odds is None:
            missing_match_odds.append({
                "season": season_name,
                "match_id": details["id"],
                "home_team": details["home_team"]["name"],
                "away_team": details["away_team"]["name"]
            })

print("Matches missing match odds:", len(missing_match_odds))

Matches missing match odds: 0

In [209]:
# Adding home/draw/away odds to our historical dataset.

odds_rows = []

for season_name in ["2023_24", "2024_25", "2025_26"]:
    season_dir = SEASON_DIRS[season_name]

    for file_path in season_dir.glob("*.json"):
        with open(file_path, "r", encoding="utf-8") as f:
            match_data = json.load(f)

        match_id = match_data["details"]["data"]["id"]

        bookmakers = match_data["odds"]["data"]["bookmakers"]
        match_odds = bookmakers[0]["markets"]["match_odds"]

        odds_rows.append({
            "match_id": match_id,
            "home_odds": float(match_odds["home"]["last_seen"]),
            "draw_odds": float(match_odds["draw"]["last_seen"]),
            "away_odds": float(match_odds["away"]["last_seen"])
        })

odds_df = pd.DataFrame(odds_rows)

odds_df.shape

(1140, 4)

In [210]:
# Merging into our DataFrame

historical_df = historical_df.merge(
    odds_df,
    on = "match_id",
    how = "left"
)

historical_df.shape

(1140, 24)

In [211]:
historical_df[
    [
        "home_team",
        "away_team",
        "home_odds",
        "draw_odds",
        "away_odds"
    ]
].head()

           home_team          away_team  home_odds  draw_odds  away_odds
0  Manchester United          Brentford       1.60       4.33        5.0
1   Newcastle United     Crystal Palace       1.50       4.33        6.5
2          Liverpool  Nottingham Forest       1.22       7.00       11.0
3  Tottenham Hotspur          Liverpool       3.00       3.80        2.2
4          Brentford    West Ham United       2.05       3.60        3.5

In [212]:
# Make sure none of the odds became missing after the merge.

historical_df[
    ["home_odds", "draw_odds", "away_odds"]
].isnull().sum()

home_odds    0
draw_odds    0
away_odds    0
dtype: int64

In [320]:
# Overwrite our historical matches CSV with updated DataFrame

historical_df.to_csv(
    historical_file,
    index = False 
)

print("Saved to:", historical_file)
print("Shape:", historical_df.shape)

Saved to: ..\data\processed\historical_matches.csv
Shape: (10653, 22)

# DATA PIPELINE PART 2
ADDING MORE COMPETITIONS

In [98]:
# Set up Championship seasons and create a directory to store these matches

CHAMPIONSHIP_ID = "comp_8321"

CHAMPIONSHIP_SEASONS = {
    "2026_27": "sn_3014533",
    "2025_26": "sn_3064530",
    "2024_25": "sn_2930227",
    "2023_24": "sn_343481",
    "2022_23": "sn_286965",
    "2021_22": "sn_033091",
    "2020_21": "sn_855998"
}

CHAMPIONSHIP_DIR = RAW_MATCH_DIR / "championship"

CHAMPIONSHIP_SEASON_DIRS = {}

for season_name in CHAMPIONSHIP_SEASONS:
    season_dir = CHAMPIONSHIP_DIR / season_name
    season_dir.mkdir(parents = True, exist_ok = True)

    CHAMPIONSHIP_SEASON_DIRS[season_name] = season_dir

print(CHAMPIONSHIP_SEASON_DIRS)

{'2026_27': WindowsPath('../data/raw/matches/championship/2026_27'), '2025_26': WindowsPath('../data/raw/matches/championship/2025_26'), '2024_25': WindowsPath('../data/raw/matches/championship/2024_25'), '2023_24': WindowsPath('../data/raw/matches/championship/2023_24'), '2022_23': WindowsPath('../data/raw/matches/championship/2022_23'), '2021_22': WindowsPath('../data/raw/matches/championship/2021_22'), '2020_21': WindowsPath('../data/raw/matches/championship/2020_21')}

In [99]:
# Test on one Championship season
championship_2022_23_matches = get_all_season_matches(
    CHAMPIONSHIP_ID,
    CHAMPIONSHIP_SEASONS["2022_23"]
)

print("Total matches returned:", len(championship_2022_23_matches))

Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
Total matches returned: 557

In [100]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in championship_2022_23_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in championship_2022_23_matches))

Statuses:
Counter({'finished': 557})

Stages:
Counter({None: 552, 'semi_final': 4, 'final': 1})

In [101]:
# Check if the data is compatible

test_championship_match = championship_2022_23_matches[0]

print(
    test_championship_match["home_team"]["name"],
    "vs",
    test_championship_match["away_team"]["name"]
)

test_championship_data = get_baseline_match_data(
    test_championship_match["id"]
)

print(test_championship_data.keys())

Coventry City vs Luton Town
dict_keys(['details', 'statistics', 'odds'])

In [102]:
# Make a Championship save path
# Don't want to mix up the JSONs 

def collect_championship_baseline_data(season_name, matches):
    season_dir = CHAMPIONSHIP_SEASON_DIRS[season_name]

    total_matches = len(matches)

    for i, match in enumerate(matches, start=1):
        match_id = match["id"]
        file_path = season_dir / f"{match_id}.json"

        if file_path.exists():
            print(f"{i}/{total_matches} - Skipping existing: {match_id}")
            continue

        print(f"{i}/{total_matches} - Collecting: {match_id}")

        match_data = get_baseline_match_data(match_id)

        if match_data is None:
            print("Skipped:", match_id)
            continue

        save_match_data(
            match_id,
            match_data,
            season_dir
        )

        time.sleep(1)

In [103]:
# Collect 2022/23 Championship matches

collect_championship_baseline_data(
    "2022_23",
    championship_2022_23_matches
)

1/557 - Collecting: mt_581874371
2/557 - Collecting: mt_406526716
3/557 - Collecting: mt_367048338
4/557 - Collecting: mt_978638174
5/557 - Collecting: mt_624104353
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
6/557 - Collecting: mt_360165605
7/557 - Collecting: mt_259753983
8/557 - Collecting: mt_193694308
9/557 - Collecting: mt_976270602
Rate limit reached. Waiting 5 seconds before retry 1/5
10/557 - Collecting: mt_193694345
11/557 - Collecting: mt_405809942
12/557 - Collecting: mt_621928855
13/557 - Collecting: mt_360165581
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
14/557 - Collecting: mt_621928833
15/557 - Collecting: mt_587486627
16/557 - Collecting: mt_834032235
17/557 - Collecting: mt_742541129
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
18/557 - Collecting: mt_018317794
19/557 - Collecting: mt_405809960
20/557 - Collecting: mt_587475594
21/557 - Collecting: mt_621928811
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
22/557 - Collecting: mt_405809921
23/557 - Collecting: mt_976270698
24/557 - Collecting: mt_018317880
25/557 - Collecting: mt_193694419
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
26/557 - Collecting: mt_976270004
27/557 - Collecting: mt_193694440
28/557 - Collecting: mt_018380005
29/557 - Collecting: mt_621916606
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
30/557 - Collecting: mt_976270026
31/557 - Collecting: mt_581641865
32/557 - Collecting: mt_833788765
33/557 - Collecting: mt_199148301
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
34/557 - Collecting: mt_834048808
35/557 - Collecting: mt_018317077
36/557 - Collecting: mt_976270994
37/557 - Collecting: mt_834048884
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
38/557 - Collecting: mt_742527762
39/557 - Collecting: mt_621916650
40/557 - Collecting: mt_259792279
41/557 - Collecting: mt_193631164
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
42/557 - Collecting: mt_587475528
43/557 - Collecting: mt_834048896
44/557 - Collecting: mt_360103307
45/557 - Collecting: mt_621928562
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
46/557 - Collecting: mt_405854400
47/557 - Collecting: mt_621928008
48/557 - Collecting: mt_834048830
49/557 - Collecting: mt_360103368
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
50/557 - Collecting: mt_587475586
51/557 - Collecting: mt_405809897
52/557 - Collecting: mt_621928045
53/557 - Collecting: mt_259753821
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
54/557 - Collecting: mt_193694786
55/557 - Collecting: mt_405809196
56/557 - Collecting: mt_587486468
57/557 - Collecting: mt_834033978
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
58/557 - Collecting: mt_193699818
59/557 - Collecting: mt_360166426
60/557 - Collecting: mt_259755100
61/557 - Collecting: mt_587488329
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
62/557 - Collecting: mt_742544323
63/557 - Collecting: mt_834032746
64/557 - Collecting: mt_193694753
65/557 - Collecting: mt_259753859
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
66/557 - Collecting: mt_742541960
67/557 - Collecting: mt_834033628
68/557 - Collecting: mt_405800297
69/557 - Collecting: mt_587488372
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
70/557 - Collecting: mt_018311530
71/557 - Collecting: mt_742544716
72/557 - Collecting: mt_834033780
73/557 - Collecting: mt_018311545
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
74/557 - Collecting: mt_018311529
75/557 - Collecting: mt_834033792
76/557 - Collecting: mt_587488396
77/557 - Collecting: mt_834033665
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
78/557 - Collecting: mt_193699561
79/557 - Collecting: mt_834033939
80/557 - Collecting: mt_193699766
81/557 - Collecting: mt_621922563
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
82/557 - Collecting: mt_193699194
83/557 - Collecting: mt_259755293
84/557 - Collecting: mt_976277900
85/557 - Collecting: mt_405800146
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
86/557 - Collecting: mt_976277490
87/557 - Collecting: mt_259755881
88/557 - Collecting: mt_360166216
89/557 - Collecting: mt_259755895
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
90/557 - Collecting: mt_405800641
91/557 - Collecting: mt_834033609
92/557 - Collecting: mt_193699788
93/557 - Collecting: mt_976277911
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
94/557 - Collecting: mt_742544670
95/557 - Collecting: mt_360166463
96/557 - Collecting: mt_976277306
97/557 - Collecting: mt_834033670
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
98/557 - Collecting: mt_405800151
99/557 - Collecting: mt_976277468
100/557 - Collecting: mt_193699744
101/557 - Collecting: mt_259755083
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
102/557 - Collecting: mt_259755878
103/557 - Collecting: mt_360166722
104/557 - Collecting: mt_360166351
105/557 - Collecting: mt_621922421
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
106/557 - Collecting: mt_976277966
107/557 - Collecting: mt_018311513
108/557 - Collecting: mt_360166452
109/557 - Collecting: mt_621922504
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
110/557 - Collecting: mt_587488345
111/557 - Collecting: mt_976277414
112/557 - Collecting: mt_834033906
113/557 - Collecting: mt_259755036
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
114/557 - Collecting: mt_742544390
115/557 - Collecting: mt_621922098
116/557 - Collecting: mt_587488923
117/557 - Collecting: mt_976277423
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
118/557 - Collecting: mt_360166744
119/557 - Collecting: mt_018311231
120/557 - Collecting: mt_621928902
121/557 - Collecting: mt_587488357
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
122/557 - Collecting: mt_018311958
123/557 - Collecting: mt_193694185
124/557 - Collecting: mt_621928501
125/557 - Collecting: mt_976270206
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
126/557 - Collecting: mt_259753170
127/557 - Collecting: mt_976277846
128/557 - Collecting: mt_259753117
129/557 - Collecting: mt_018317907
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
130/557 - Collecting: mt_834032652
131/557 - Collecting: mt_360165264
132/557 - Collecting: mt_259753893
133/557 - Collecting: mt_742541016
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
134/557 - Collecting: mt_587486367
135/557 - Collecting: mt_259753799
136/557 - Collecting: mt_834032874
137/557 - Collecting: mt_621922591
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
138/557 - Collecting: mt_199703059
139/557 - Collecting: mt_977469089
140/557 - Collecting: mt_255851852
141/557 - Collecting: mt_587486999
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
142/557 - Collecting: mt_193694765
143/557 - Collecting: mt_834032626
144/557 - Collecting: mt_193694687
145/557 - Collecting: mt_405809825
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
146/557 - Collecting: mt_018317329
147/557 - Collecting: mt_360165104
148/557 - Collecting: mt_405809858
149/557 - Collecting: mt_193694011
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
150/557 - Collecting: mt_742541905
151/557 - Collecting: mt_259753667
152/557 - Collecting: mt_976270387
153/557 - Collecting: mt_255720966
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
154/557 - Collecting: mt_366230244
155/557 - Collecting: mt_976270376
156/557 - Collecting: mt_834032663
157/557 - Collecting: mt_405809184
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
158/557 - Collecting: mt_621928304
159/557 - Collecting: mt_587486213
160/557 - Collecting: mt_742541921
161/557 - Collecting: mt_587486119
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
162/557 - Collecting: mt_976270872
163/557 - Collecting: mt_834032388
164/557 - Collecting: mt_405809027
165/557 - Collecting: mt_742541450
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
Connection error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)).Waiting 40 seconds before retry 4/5...
Rate limit reached. Waiting 40 seconds before retry 4/5
166/557 - Collecting: mt_360165273
167/557 - Collecting: mt_588326884
168/557 - Collecting: mt_977410771
169/557 - Collecting: mt_744091442
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
170/557 - Collecting: mt_833694638
171/557 - Collecting: mt_833642009
172/557 - Collecting: mt_018317474
173/557 - Collecting: mt_360165875
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
174/557 - Collecting: mt_259753082
175/557 - Collecting: mt_259753071
176/557 - Collecting: mt_405809604
177/557 - Collecting: mt_587486162
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
178/557 - Collecting: mt_018317104
179/557 - Collecting: mt_742541406
180/557 - Collecting: mt_587486815
181/557 - Collecting: mt_834032399
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
182/557 - Collecting: mt_193694044
183/557 - Collecting: mt_742541424
184/557 - Collecting: mt_405809789
185/557 - Collecting: mt_621928121
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
186/557 - Collecting: mt_193694605
187/557 - Collecting: mt_621928403
188/557 - Collecting: mt_018317827
189/557 - Collecting: mt_259753936
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
190/557 - Collecting: mt_621928159
191/557 - Collecting: mt_405809509
192/557 - Collecting: mt_976270701
193/557 - Collecting: mt_259753962
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
194/557 - Collecting: mt_976270689
195/557 - Collecting: mt_193694458
196/557 - Collecting: mt_193694949
197/557 - Collecting: mt_834032322
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
198/557 - Collecting: mt_621928160
199/557 - Collecting: mt_742541256
200/557 - Collecting: mt_405809594
201/557 - Collecting: mt_360165055
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
202/557 - Collecting: mt_193694474
203/557 - Collecting: mt_018380042
204/557 - Collecting: mt_360103371
205/557 - Collecting: mt_976269980
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
206/557 - Collecting: mt_621916624
207/557 - Collecting: mt_360103314
208/557 - Collecting: mt_400115926
209/557 - Collecting: mt_744537105
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
210/557 - Collecting: mt_405854477
211/557 - Collecting: mt_018380500
212/557 - Collecting: mt_742527673
213/557 - Collecting: mt_018380599
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
214/557 - Collecting: mt_742527602
215/557 - Collecting: mt_193631863
216/557 - Collecting: mt_018380544
217/557 - Collecting: mt_259792169
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
218/557 - Collecting: mt_405854488
219/557 - Collecting: mt_018380522
220/557 - Collecting: mt_834032249
221/557 - Collecting: mt_366288231
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
222/557 - Collecting: mt_400104980
223/557 - Collecting: mt_018380939
224/557 - Collecting: mt_259792705
225/557 - Collecting: mt_621916561
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
226/557 - Collecting: mt_587487371
227/557 - Collecting: mt_018318397
228/557 - Collecting: mt_834034094
229/557 - Collecting: mt_742542542
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
230/557 - Collecting: mt_621921910
231/557 - Collecting: mt_834048689
232/557 - Collecting: mt_259792817
233/557 - Collecting: mt_360160817
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
234/557 - Collecting: mt_193631087
235/557 - Collecting: mt_587487472
236/557 - Collecting: mt_621921926
237/557 - Collecting: mt_587487225
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
238/557 - Collecting: mt_834034559
239/557 - Collecting: mt_360160870
240/557 - Collecting: mt_405805627
241/557 - Collecting: mt_742542395
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
242/557 - Collecting: mt_360160787
243/557 - Collecting: mt_193693590
244/557 - Collecting: mt_834034922
245/557 - Collecting: mt_018318103
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
246/557 - Collecting: mt_405805086
247/557 - Collecting: mt_834034560
248/557 - Collecting: mt_621921428
249/557 - Collecting: mt_360160688
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
250/557 - Collecting: mt_621921465
251/557 - Collecting: mt_018318252
252/557 - Collecting: mt_742542490
253/557 - Collecting: mt_976276773
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
254/557 - Collecting: mt_405805988
255/557 - Collecting: mt_405805675
256/557 - Collecting: mt_834034343
257/557 - Collecting: mt_621921100
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
258/557 - Collecting: mt_621921155
259/557 - Collecting: mt_193693984
260/557 - Collecting: mt_018318894
261/557 - Collecting: mt_976276610
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
262/557 - Collecting: mt_360160523
263/557 - Collecting: mt_193694803
264/557 - Collecting: mt_360165138
265/557 - Collecting: mt_018318180
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
266/557 - Collecting: mt_018318175
267/557 - Collecting: mt_405805560
268/557 - Collecting: mt_587487628
269/557 - Collecting: mt_976270909
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
270/557 - Collecting: mt_587486933
271/557 - Collecting: mt_405805977
272/557 - Collecting: mt_742541764
273/557 - Collecting: mt_259753700
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
274/557 - Collecting: mt_193694179
275/557 - Collecting: mt_976270928
276/557 - Collecting: mt_360165425
277/557 - Collecting: mt_405809129
Rate limit reached. Waiting 5 seconds before retry 1/5
Rate limit reached. Waiting 10 seconds before retry 2/5
Rate limit reached. Waiting 20 seconds before retry 3/5
278/557 - Collecting: mt_834032638
279/557 - Collecting: mt_621928964
280/557 - Collecting: mt_360165110
281/557 - Collecting: mt_018317313

In [107]:
saved_championship_2021_22 = list(
    CHAMPIONSHIP_SEASON_DIRS["2021_22"].glob("*.json")
)

print("Saved Championship 2021/22 files:", len(saved_championship_2021_22))

Saved Championship 2021/22 files: 536

In [111]:
championship_2020_21_matches = get_all_season_matches(
    CHAMPIONSHIP_ID,
    CHAMPIONSHIP_SEASONS["2020_21"]
)

print("Total matches returned:", len(championship_2020_21_matches))

Total matches returned: 557

In [113]:
# Collect 2020_21 Championship season

collect_championship_baseline_data(
    "2020_21",
    championship_2020_21_matches
)

1/557 - Skipping existing: mt_575521629
2/557 - Skipping existing: mt_131138187
3/557 - Skipping existing: mt_848848362
4/557 - Skipping existing: mt_727724757
5/557 - Skipping existing: mt_080081324
6/557 - Skipping existing: mt_452112657
7/557 - Skipping existing: mt_085995157
8/557 - Skipping existing: mt_452112074
9/557 - Skipping existing: mt_085995184
10/557 - Skipping existing: mt_138778311
11/557 - Skipping existing: mt_610550163
12/557 - Skipping existing: mt_304224080
13/557 - Skipping existing: mt_085995702
14/557 - Skipping existing: mt_963443072
15/557 - Skipping existing: mt_579333537
16/557 - Skipping existing: mt_085999554
17/557 - Skipping existing: mt_579333985
18/557 - Skipping existing: mt_575332523
19/557 - Skipping existing: mt_304224751
20/557 - Skipping existing: mt_452112040
21/557 - Skipping existing: mt_085995145
22/557 - Skipping existing: mt_847667409
23/557 - Skipping existing: mt_847667287
24/557 - Skipping existing: mt_304224570
25/557 - Skipping existing: mt_963444936
26/557 - Skipping existing: mt_085999091
27/557 - Skipping existing: mt_610555632
28/557 - Skipping existing: mt_847666767
29/557 - Skipping existing: mt_726000656
30/557 - Skipping existing: mt_291881780
31/557 - Skipping existing: mt_292729981
32/557 - Skipping existing: mt_138776730
33/557 - Skipping existing: mt_452118842
34/557 - Skipping existing: mt_579339195
35/557 - Skipping existing: mt_291881906
36/557 - Skipping existing: mt_847667293
37/557 - Skipping existing: mt_452118109
38/557 - Skipping existing: mt_963442464
39/557 - Skipping existing: mt_291887897
40/557 - Skipping existing: mt_847660643
41/557 - Skipping existing: mt_085993975
42/557 - Skipping existing: mt_610559966
43/557 - Skipping existing: mt_726005049
44/557 - Skipping existing: mt_847667303
45/557 - Skipping existing: mt_291881967
46/557 - Skipping existing: mt_847667432
47/557 - Skipping existing: mt_085995897
48/557 - Skipping existing: mt_291887836
49/557 - Skipping existing: mt_304224027
50/557 - Skipping existing: mt_304221255
51/557 - Skipping existing: mt_452112714
52/557 - Skipping existing: mt_085995443
53/557 - Skipping existing: mt_610550329
54/557 - Skipping existing: mt_726000795
55/557 - Skipping existing: mt_847666706
56/557 - Skipping existing: mt_726005014
57/557 - Skipping existing: mt_610550483
58/557 - Skipping existing: mt_304221200
59/557 - Skipping existing: mt_847667598
60/557 - Skipping existing: mt_452112756
61/557 - Skipping existing: mt_085999079
62/557 - Skipping existing: mt_304221266
63/557 - Skipping existing: mt_610559521
64/557 - Skipping existing: mt_579334363
65/557 - Skipping existing: mt_847660624
66/557 - Skipping existing: mt_610559518
67/557 - Skipping existing: mt_452118194
68/557 - Skipping existing: mt_969494368
69/557 - Skipping existing: mt_303164146
70/557 - Skipping existing: mt_292828195
71/557 - Skipping existing: mt_138777845
72/557 - Skipping existing: mt_963443294
73/557 - Skipping existing: mt_085995478
74/557 - Skipping existing: mt_138778987
75/557 - Skipping existing: mt_304224652
76/557 - Skipping existing: mt_291881533
77/557 - Skipping existing: mt_138778388
78/557 - Skipping existing: mt_291881995
79/557 - Skipping existing: mt_963444997
80/557 - Skipping existing: mt_726005023
81/557 - Skipping existing: mt_085993309
82/557 - Skipping existing: mt_138776745
83/557 - Skipping existing: mt_579333589
84/557 - Skipping existing: mt_963442473
85/557 - Skipping existing: mt_138777171
86/557 - Skipping existing: mt_452112564
87/557 - Skipping existing: mt_085995290
88/557 - Skipping existing: mt_291881522
89/557 - Skipping existing: mt_579339868
90/557 - Skipping existing: mt_726006276
91/557 - Skipping existing: mt_847666800
92/557 - Skipping existing: mt_085993980
93/557 - Skipping existing: mt_579334379
94/557 - Skipping existing: mt_963442402
95/557 - Skipping existing: mt_847660639
96/557 - Skipping existing: mt_963443286
97/557 - Skipping existing: mt_085995214
98/557 - Skipping existing: mt_138778300
99/557 - Skipping existing: mt_847667025
100/557 - Skipping existing: mt_963443193
101/557 - Skipping existing: mt_138778016
102/557 - Skipping existing: mt_452112749
103/557 - Skipping existing: mt_610550458
104/557 - Skipping existing: mt_085995883
105/557 - Skipping existing: mt_304222318
106/557 - Skipping existing: mt_726000724
107/557 - Skipping existing: mt_963444346
108/557 - Skipping existing: mt_726000030
109/557 - Skipping existing: mt_579333979
110/557 - Skipping existing: mt_291888710
111/557 - Skipping existing: mt_610555943
112/557 - Skipping existing: mt_579333417
113/557 - Skipping existing: mt_847666574
114/557 - Skipping existing: mt_847666597
115/557 - Skipping existing: mt_726000391
116/557 - Skipping existing: mt_847666294
117/557 - Skipping existing: mt_304221341
118/557 - Skipping existing: mt_847666668
119/557 - Skipping existing: mt_138777079
120/557 - Skipping existing: mt_085999872
121/557 - Skipping existing: mt_138777400
122/557 - Skipping existing: mt_963444404
123/557 - Skipping existing: mt_963444269
124/557 - Skipping existing: mt_138777063
125/557 - Skipping existing: mt_610555429
126/557 - Skipping existing: mt_610555566
127/557 - Skipping existing: mt_452111187
128/557 - Skipping existing: mt_138777689
129/557 - Skipping existing: mt_304222156
130/557 - Skipping existing: mt_138777444
131/557 - Skipping existing: mt_726000519
132/557 - Skipping existing: mt_452111822
133/557 - Skipping existing: mt_138777698
134/557 - Skipping existing: mt_085999239
135/557 - Skipping existing: mt_291888070
136/557 - Skipping existing: mt_726000105
137/557 - Skipping existing: mt_726000159
138/557 - Skipping existing: mt_963444071
139/557 - Skipping existing: mt_452118426
140/557 - Skipping existing: mt_452111607
141/557 - Skipping existing: mt_610555838
142/557 - Skipping existing: mt_616920901
143/557 - Skipping existing: mt_454779004
144/557 - Skipping existing: mt_454802829
145/557 - Skipping existing: mt_291888158
146/557 - Skipping existing: mt_610555500
147/557 - Skipping existing: mt_304222224
148/557 - Skipping existing: mt_452111855
149/557 - Skipping existing: mt_085999400
150/557 - Skipping existing: mt_452111712
151/557 - Skipping existing: mt_304222783
152/557 - Skipping existing: mt_847666253
153/557 - Skipping existing: mt_304221332
154/557 - Skipping existing: mt_085999783
155/557 - Skipping existing: mt_291888851
156/557 - Skipping existing: mt_085999725
157/557 - Skipping existing: mt_138777719
158/557 - Skipping existing: mt_726000937
159/557 - Skipping existing: mt_963444203
160/557 - Skipping existing: mt_579333188
161/557 - Skipping existing: mt_138777896
162/557 - Skipping existing: mt_452111781
163/557 - Skipping existing: mt_610555533
164/557 - Skipping existing: mt_138777736
165/557 - Skipping existing: mt_610555995
166/557 - Skipping existing: mt_726000597
167/557 - Skipping existing: mt_291888350
168/557 - Skipping existing: mt_579333392
169/557 - Skipping existing: mt_847666743
170/557 - Skipping existing: mt_085999932
171/557 - Skipping existing: mt_610555906
172/557 - Skipping existing: mt_138777673
173/557 - Skipping existing: mt_304222168
174/557 - Skipping existing: mt_610555356
175/557 - Skipping existing: mt_963444128
176/557 - Skipping existing: mt_291888669
177/557 - Skipping existing: mt_847666998
178/557 - Skipping existing: mt_847666635
179/557 - Skipping existing: mt_579333672
180/557 - Skipping existing: mt_452111724
181/557 - Skipping existing: mt_963444117
182/557 - Skipping existing: mt_452111671
183/557 - Skipping existing: mt_452111265
184/557 - Skipping existing: mt_085999909
185/557 - Skipping existing: mt_452111176
186/557 - Skipping existing: mt_963444438
187/557 - Skipping existing: mt_963444463
188/557 - Skipping existing: mt_579333428
189/557 - Skipping existing: mt_452111294
190/557 - Skipping existing: mt_726000562
191/557 - Skipping existing: mt_963444082
192/557 - Skipping existing: mt_085999305
193/557 - Skipping existing: mt_847666008
194/557 - Skipping existing: mt_085999433
195/557 - Skipping existing: mt_579333144
196/557 - Skipping existing: mt_304222762
197/557 - Skipping existing: mt_579333696
198/557 - Skipping existing: mt_085999797
199/557 - Skipping existing: mt_579333684
200/557 - Skipping existing: mt_452111951
201/557 - Skipping existing: mt_452111998
202/557 - Skipping existing: mt_579333657
203/557 - Skipping existing: mt_452111899
204/557 - Skipping existing: mt_726000160
205/557 - Skipping existing: mt_610559603
206/557 - Skipping existing: mt_847666057
207/557 - Skipping existing: mt_610555912
208/557 - Skipping existing: mt_579333613
209/557 - Skipping existing: mt_138776178
210/557 - Skipping existing: mt_304222250
211/557 - Skipping existing: mt_304222278
212/557 - Skipping existing: mt_726000304
213/557 - Skipping existing: mt_726000176
214/557 - Skipping existing: mt_726000649
215/557 - Skipping existing: mt_847666228
216/557 - Skipping existing: mt_291887819
217/557 - Skipping existing: mt_291887720
218/557 - Skipping existing: mt_138776619
219/557 - Skipping existing: mt_726005572
220/557 - Skipping existing: mt_291887715
221/557 - Skipping existing: mt_138776683
222/557 - Skipping existing: mt_304221124
223/557 - Skipping existing: mt_963442247
224/557 - Skipping existing: mt_085993394
225/557 - Skipping existing: mt_963442291
226/557 - Skipping existing: mt_616338248
227/557 - Skipping existing: mt_080458934
228/557 - Skipping existing: mt_727991433
229/557 - Skipping existing: mt_291887130
230/557 - Skipping existing: mt_138776713
231/557 - Skipping existing: mt_726005007
232/557 - Skipping existing: mt_452118821
233/557 - Skipping existing: mt_085993353
234/557 - Skipping existing: mt_579334492
235/557 - Skipping existing: mt_963442238
236/557 - Skipping existing: mt_847660068
237/557 - Skipping existing: mt_610559955
238/557 - Skipping existing: mt_726005561
239/557 - Skipping existing: mt_610559900
240/557 - Skipping existing: mt_575226883
241/557 - Skipping existing: mt_292673660
242/557 - Skipping existing: mt_969110729
243/557 - Skipping existing: mt_292663507
244/557 - Skipping existing: mt_304221222
245/557 - Skipping existing: mt_579335698
246/557 - Skipping existing: mt_963444860
247/557 - Skipping existing: mt_610556180
248/557 - Skipping existing: mt_085999281
249/557 - Skipping existing: mt_452111690
250/557 - Skipping existing: mt_963442498
251/557 - Skipping existing: mt_963442437
252/557 - Skipping existing: mt_963442446
253/557 - Skipping existing: mt_138776761
254/557 - Skipping existing: mt_579334454
255/557 - Skipping existing: mt_847660082
256/557 - Skipping existing: mt_304221233
257/557 - Skipping existing: mt_579334391
258/557 - Skipping existing: mt_969110772
259/557 - Skipping existing: mt_575216119
260/557 - Skipping existing: mt_138777531
261/557 - Skipping existing: mt_963444799
262/557 - Skipping existing: mt_727374562
263/557 - Skipping existing: mt_610556285
264/557 - Skipping existing: mt_726005612
265/557 - Skipping existing: mt_610559505
266/557 - Skipping existing: mt_085999107
267/557 - Skipping existing: mt_138776784
268/557 - Skipping existing: mt_085990873
269/557 - Skipping existing: mt_138777548
270/557 - Skipping existing: mt_847666385
271/557 - Skipping existing: mt_847660678
272/557 - Skipping existing: mt_085993992
273/557 - Skipping existing: mt_847666920
274/557 - Skipping existing: mt_610555484
275/557 - Skipping existing: mt_304221244
276/557 - Skipping existing: mt_847660722
277/557 - Skipping existing: mt_610559560
278/557 - Skipping existing: mt_291882308
279/557 - Collecting: mt_726007150
280/557 - Collecting: mt_138771490
281/557 - Collecting: mt_138771449
282/557 - Collecting: mt_291881225
283/557 - Collecting: mt_963443937
284/557 - Collecting: mt_726005557
285/557 - Collecting: mt_963442226
286/557 - Collecting: mt_847666363
287/557 - Collecting: mt_454621944
288/557 - Collecting: mt_080205832
289/557 - Collecting: mt_138778184
290/557 - Collecting: mt_610550659
291/557 - Collecting: mt_610550066
292/557 - Collecting: mt_452112221
293/557 - Collecting: mt_610555201
294/557 - Collecting: mt_304222620
295/557 - Collecting: mt_963444711
296/557 - Collecting: mt_610559999
297/557 - Collecting: mt_138778819
298/557 - Collecting: mt_304223518
299/557 - Collecting: mt_610550000
300/557 - Collecting: mt_138777965
301/557 - Collecting: mt_291882357
302/557 - Collecting: mt_610550605
303/557 - Collecting: mt_579339916
304/557 - Collecting: mt_138778751
305/557 - Collecting: mt_579334347
306/557 - Collecting: mt_304221112
307/557 - Collecting: mt_452112242
308/557 - Collecting: mt_138771435
309/557 - Collecting: mt_963449074
310/557 - Collecting: mt_452112417
311/557 - Collecting: mt_726006723
312/557 - Collecting: mt_304224300
313/557 - Collecting: mt_963443310
314/557 - Collecting: mt_847667790
315/557 - Collecting: mt_085995993
316/557 - Collecting: mt_304224130
317/557 - Collecting: mt_610555258
318/557 - Collecting: mt_138776674
319/557 - Collecting: mt_291882372
320/557 - Collecting: mt_291882396
321/557 - Collecting: mt_726006790
322/557 - Collecting: mt_304224377
323/557 - Collecting: mt_304224214
324/557 - Collecting: mt_963443416
325/557 - Collecting: mt_579339365
326/557 - Collecting: mt_085999190
327/557 - Collecting: mt_610559534
328/557 - Collecting: mt_291888576
329/557 - Collecting: mt_138778610
330/557 - Collecting: mt_085993332
331/557 - Collecting: mt_579334448
332/557 - Collecting: mt_291887773
333/557 - Collecting: mt_452118887
334/557 - Collecting: mt_138776601
335/557 - Collecting: mt_304224223
336/557 - Collecting: mt_304221181
337/557 - Collecting: mt_726006062
338/557 - Collecting: mt_304224268
339/557 - Collecting: mt_847660056
340/557 - Collecting: mt_610559933
341/557 - Collecting: mt_726005596
342/557 - Collecting: mt_579335637
343/557 - Collecting: mt_726006756
344/557 - Collecting: mt_085995048
345/557 - Collecting: mt_304224366
346/557 - Collecting: mt_085995075
347/557 - Collecting: mt_963443326
348/557 - Collecting: mt_291881137
349/557 - Collecting: mt_610550524
350/557 - Collecting: mt_963444744
351/557 - Collecting: mt_304221288
352/557 - Collecting: mt_452118170
353/557 - Collecting: mt_963443304
354/557 - Collecting: mt_963449083
355/557 - Collecting: mt_847667824
356/557 - Collecting: mt_847667083
357/557 - Collecting: mt_138776708
358/557 - Collecting: mt_726005090
359/557 - Collecting: mt_847660650
360/557 - Collecting: mt_304224322
361/557 - Collecting: mt_610550634
362/557 - Collecting: mt_579339526
363/557 - Collecting: mt_085995553
364/557 - Collecting: mt_085995528
365/557 - Collecting: mt_304224207
366/557 - Collecting: mt_452114954
367/557 - Collecting: mt_085995003
368/557 - Collecting: mt_963443998
369/557 - Collecting: mt_304224311
370/557 - Collecting: mt_304224355
371/557 - Collecting: mt_847667782
372/557 - Collecting: mt_610550033
373/557 - Collecting: mt_085995934
374/557 - Collecting: mt_579339328
375/557 - Collecting: mt_291887801
376/557 - Collecting: mt_610550618
377/557 - Collecting: mt_291881258
378/557 - Collecting: mt_963442489
379/557 - Collecting: mt_138776757
380/557 - Collecting: mt_726005035
381/557 - Collecting: mt_452118876
382/557 - Collecting: mt_291887702
383/557 - Collecting: mt_579334427
384/557 - Collecting: mt_085993341
385/557 - Collecting: mt_963442210
386/557 - Collecting: mt_138776658
387/557 - Collecting: mt_304221178
388/557 - Collecting: mt_610559944
389/557 - Collecting: mt_726005530
390/557 - Collecting: mt_452112259
391/557 - Collecting: mt_085995054
392/557 - Collecting: mt_579339931
393/557 - Collecting: mt_726006630
394/557 - Collecting: mt_452112824
395/557 - Collecting: mt_138778685
396/557 - Collecting: mt_726000403
397/557 - Collecting: mt_847660695
398/557 - Collecting: mt_304221277
399/557 - Collecting: mt_847660090
400/557 - Collecting: mt_579339442
401/557 - Collecting: mt_291881189
402/557 - Collecting: mt_452112470
403/557 - Collecting: mt_138778874
404/557 - Collecting: mt_963443431
405/557 - Collecting: mt_610550642
406/557 - Collecting: mt_304224235
407/557 - Collecting: mt_610550361
408/557 - Collecting: mt_726007124
409/557 - Collecting: mt_579339538
410/557 - Collecting: mt_726006613
411/557 - Collecting: mt_291881826
412/557 - Collecting: mt_085993948
413/557 - Collecting: mt_579334326
414/557 - Collecting: mt_579339493
415/557 - Collecting: mt_304224161
416/557 - Collecting: mt_085995235
417/557 - Collecting: mt_304224048
418/557 - Collecting: mt_138778439
419/557 - Collecting: mt_085999503
420/557 - Collecting: mt_726000607
421/557 - Collecting: mt_452118165
422/557 - Collecting: mt_963442279
423/557 - Collecting: mt_291887751
424/557 - Collecting: mt_085993927
425/557 - Collecting: mt_963443844
426/557 - Collecting: mt_291881731
427/557 - Collecting: mt_847667564
428/557 - Collecting: mt_847667520
429/557 - Collecting: mt_726006453
430/557 - Collecting: mt_452112062
431/557 - Collecting: mt_085995720
432/557 - Collecting: mt_610555059
433/557 - Collecting: mt_138776697
434/557 - Collecting: mt_847660035
435/557 - Collecting: mt_452118805
436/557 - Collecting: mt_963444962
437/557 - Collecting: mt_610550104
438/557 - Collecting: mt_610555694
439/557 - Collecting: mt_138777156
440/557 - Collecting: mt_304221167
441/557 - Collecting: mt_304221106
442/557 - Collecting: mt_085995840
443/557 - Collecting: mt_291881390
444/557 - Collecting: mt_085993459
445/557 - Collecting: mt_579334294
446/557 - Collecting: mt_963442263
447/557 - Collecting: mt_304221835
448/557 - Collecting: mt_610559306
449/557 - Collecting: mt_452118722
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
450/557 - Collecting: mt_291881021
451/557 - Collecting: mt_726006166
452/557 - Collecting: mt_726005529
453/557 - Collecting: mt_847660049
454/557 - Collecting: mt_610559911
455/557 - Collecting: mt_963442131
456/557 - Collecting: mt_291887610
457/557 - Collecting: mt_138776089
458/557 - Collecting: mt_726005962
459/557 - Collecting: mt_847660572
460/557 - Collecting: mt_726006494
461/557 - Collecting: mt_085999085
462/557 - Collecting: mt_579339871
463/557 - Collecting: mt_085993317
464/557 - Collecting: mt_579334475
465/557 - Collecting: mt_138776636
466/557 - Collecting: mt_452118859
467/557 - Collecting: mt_291881555
468/557 - Collecting: mt_452112878
469/557 - Collecting: mt_579339167
470/557 - Collecting: mt_452112097
471/557 - Collecting: mt_452112952
472/557 - Collecting: mt_291887798
473/557 - Collecting: mt_726006375
474/557 - Collecting: mt_452112881
475/557 - Collecting: mt_452112771
476/557 - Collecting: mt_726006354
477/557 - Collecting: mt_963443800
478/557 - Collecting: mt_452112520
479/557 - Collecting: mt_726006293
480/557 - Collecting: mt_138778481
481/557 - Collecting: mt_726006155
482/557 - Collecting: mt_291887858
483/557 - Collecting: mt_138776796
484/557 - Collecting: mt_579339619
485/557 - Collecting: mt_291881703
486/557 - Collecting: mt_304224737
487/557 - Collecting: mt_847667369
488/557 - Collecting: mt_726005545
489/557 - Collecting: mt_610559922
490/557 - Collecting: mt_963442192
491/557 - Collecting: mt_726006369
492/557 - Collecting: mt_304224720
493/557 - Collecting: mt_610550152
494/557 - Collecting: mt_610555686
495/557 - Collecting: mt_610559542
496/557 - Collecting: mt_579334416
497/557 - Collecting: mt_726005974
498/557 - Collecting: mt_963444940
499/557 - Collecting: mt_963443241
500/557 - Collecting: mt_847667040
501/557 - Collecting: mt_610550462
502/557 - Collecting: mt_610550220
503/557 - Collecting: mt_847666855
504/557 - Collecting: mt_452111475
505/557 - Collecting: mt_085993328
506/557 - Collecting: mt_291887626
507/557 - Collecting: mt_138776015
508/557 - Collecting: mt_847660584
509/557 - Collecting: mt_291881087
510/557 - Collecting: mt_726000767
511/557 - Collecting: mt_452112661
512/557 - Collecting: mt_291881792
513/557 - Collecting: mt_726006910
514/557 - Collecting: mt_847667938

In [114]:
saved_championship_2020_21 = list(
    CHAMPIONSHIP_SEASON_DIRS["2020_21"].glob("*.json")
)

print("Saved Championship 2020/21 files:", len(saved_championship_2020_21))

Saved Championship 2020/21 files: 557

In [115]:
# Collect 2023/24 season

championship_2023_24_matches = get_all_season_matches(
    CHAMPIONSHIP_ID,
    CHAMPIONSHIP_SEASONS["2023_24"]
)

print("Total matches returned:", len(championship_2023_24_matches))

Total matches returned: 557

In [116]:
collect_championship_baseline_data(
    "2023_24",
    championship_2023_24_matches
)

1/557 - Collecting: mt_584868233
2/557 - Collecting: mt_196356808
3/557 - Collecting: mt_257907162
4/557 - Collecting: mt_972682302
5/557 - Collecting: mt_584714963
6/557 - Collecting: mt_978814673
7/557 - Collecting: mt_743390249
8/557 - Collecting: mt_367782066
9/557 - Collecting: mt_581123779
10/557 - Collecting: mt_978814664
11/557 - Collecting: mt_250068997
12/557 - Collecting: mt_195507330
13/557 - Collecting: mt_012249875
14/557 - Collecting: mt_195507345
15/557 - Collecting: mt_743390214
16/557 - Collecting: mt_839956424
17/557 - Collecting: mt_367782055
18/557 - Collecting: mt_407408711
19/557 - Collecting: mt_408998442
20/557 - Collecting: mt_012249848
21/557 - Collecting: mt_367782011
22/557 - Collecting: mt_581123747
23/557 - Collecting: mt_978814620
24/557 - Collecting: mt_195507308
25/557 - Collecting: mt_839956450
26/557 - Collecting: mt_624435134
27/557 - Collecting: mt_581123726
28/557 - Collecting: mt_195507357
29/557 - Collecting: mt_839956495
30/557 - Collecting: mt_406671570
31/557 - Collecting: mt_971317064
32/557 - Collecting: mt_749650173
33/557 - Collecting: mt_368370803
34/557 - Collecting: mt_406671528
35/557 - Collecting: mt_406671541
36/557 - Collecting: mt_839956322
37/557 - Collecting: mt_367782033
38/557 - Collecting: mt_624435160
39/557 - Collecting: mt_012249803
40/557 - Collecting: mt_581123752
41/557 - Collecting: mt_195507313
42/557 - Collecting: mt_624435105
43/557 - Collecting: mt_250068925
44/557 - Collecting: mt_014551085
45/557 - Collecting: mt_195507907
46/557 - Collecting: mt_839956355
47/557 - Collecting: mt_367782687
48/557 - Collecting: mt_624435232
49/557 - Collecting: mt_406671075
50/557 - Collecting: mt_581123815
51/557 - Collecting: mt_978814783
52/557 - Collecting: mt_250068508
53/557 - Collecting: mt_581123873
54/557 - Collecting: mt_250068596
55/557 - Collecting: mt_012249147
56/557 - Collecting: mt_743390495
57/557 - Collecting: mt_195507956
58/557 - Collecting: mt_743390439
59/557 - Collecting: mt_012249110
60/557 - Collecting: mt_743390450
61/557 - Collecting: mt_367782618
62/557 - Collecting: mt_406671069
63/557 - Collecting: mt_250068561
64/557 - Collecting: mt_624435294
65/557 - Collecting: mt_406671080
66/557 - Collecting: mt_012249138
67/557 - Collecting: mt_581123846
68/557 - Collecting: mt_978814719
69/557 - Collecting: mt_406671691
70/557 - Collecting: mt_581123162
71/557 - Collecting: mt_978814808
72/557 - Collecting: mt_250068035
73/557 - Collecting: mt_406671048
74/557 - Collecting: mt_012249104
75/557 - Collecting: mt_581123851
76/557 - Collecting: mt_978814797
77/557 - Collecting: mt_195507914
78/557 - Collecting: mt_839956377
79/557 - Collecting: mt_743390467
80/557 - Collecting: mt_250068529
81/557 - Collecting: mt_250070065
82/557 - Collecting: mt_743353391
83/557 - Collecting: mt_406686671
84/557 - Collecting: mt_581141122
85/557 - Collecting: mt_978828818
86/557 - Collecting: mt_839956993
87/557 - Collecting: mt_367782770
88/557 - Collecting: mt_624435448
89/557 - Collecting: mt_406671604
90/557 - Collecting: mt_012249215
91/557 - Collecting: mt_978814872
92/557 - Collecting: mt_195565503
93/557 - Collecting: mt_195565569
94/557 - Collecting: mt_624494496
95/557 - Collecting: mt_367717725
96/557 - Collecting: mt_012232239
97/557 - Collecting: mt_581141144
98/557 - Collecting: mt_250070070
99/557 - Collecting: mt_839909902
100/557 - Collecting: mt_367717783
101/557 - Collecting: mt_624494430
102/557 - Collecting: mt_012232243
103/557 - Collecting: mt_406686682
104/557 - Collecting: mt_839909964
105/557 - Collecting: mt_624494408
106/557 - Collecting: mt_195565580
107/557 - Collecting: mt_012232295
108/557 - Collecting: mt_581141133
109/557 - Collecting: mt_250070086
110/557 - Collecting: mt_743353304
111/557 - Collecting: mt_743395664
112/557 - Collecting: mt_624439090
113/557 - Collecting: mt_195506863
114/557 - Collecting: mt_250067175
115/557 - Collecting: mt_582457313
116/557 - Collecting: mt_195506198
117/557 - Collecting: mt_624439624
118/557 - Collecting: mt_406678466
119/557 - Collecting: mt_581124586
120/557 - Collecting: mt_978812969
121/557 - Collecting: mt_743395725
122/557 - Collecting: mt_839950845
123/557 - Collecting: mt_367781307
124/557 - Collecting: mt_624439612
125/557 - Collecting: mt_581124565
126/557 - Collecting: mt_195506137
127/557 - Collecting: mt_406678400
128/557 - Collecting: mt_624439643
129/557 - Collecting: mt_012243021
130/557 - Collecting: mt_250067252
131/557 - Collecting: mt_743395740
132/557 - Collecting: mt_978812980
133/557 - Collecting: mt_743395736
134/557 - Collecting: mt_839950896
135/557 - Collecting: mt_581124517
136/557 - Collecting: mt_839950830
137/557 - Collecting: mt_367781368
138/557 - Collecting: mt_012243018
139/557 - Collecting: mt_406678422
140/557 - Collecting: mt_012243059
141/557 - Collecting: mt_581124594
142/557 - Collecting: mt_839950872
143/557 - Collecting: mt_012243093
144/557 - Collecting: mt_839950808
145/557 - Collecting: mt_012243034
146/557 - Collecting: mt_978812927
147/557 - Collecting: mt_195506164
148/557 - Collecting: mt_978812931
149/557 - Collecting: mt_250067210
150/557 - Collecting: mt_581124532
151/557 - Collecting: mt_250068351
152/557 - Collecting: mt_743390145
153/557 - Collecting: mt_367782567
154/557 - Collecting: mt_406671905
155/557 - Collecting: mt_012249717
156/557 - Collecting: mt_250068398
157/557 - Collecting: mt_195507436
158/557 - Collecting: mt_743390129
159/557 - Collecting: mt_839956249
160/557 - Collecting: mt_839956235
161/557 - Collecting: mt_195507497
162/557 - Collecting: mt_624435822
163/557 - Collecting: mt_407726590
164/557 - Collecting: mt_014490357
165/557 - Collecting: mt_835502567
166/557 - Collecting: mt_368815822
167/557 - Collecting: mt_624435800
168/557 - Collecting: mt_012249753
169/557 - Collecting: mt_978814038
170/557 - Collecting: mt_195507483
171/557 - Collecting: mt_743390161
172/557 - Collecting: mt_839956268
173/557 - Collecting: mt_367782524
174/557 - Collecting: mt_624435855
175/557 - Collecting: mt_406671918
176/557 - Collecting: mt_406671976
177/557 - Collecting: mt_250068315
178/557 - Collecting: mt_012249732
179/557 - Collecting: mt_406671921
180/557 - Collecting: mt_743390172
181/557 - Collecting: mt_839956282
182/557 - Collecting: mt_367782543
183/557 - Collecting: mt_581123692
184/557 - Collecting: mt_406686795
185/557 - Collecting: mt_012249794
186/557 - Collecting: mt_406686649
187/557 - Collecting: mt_581141199
188/557 - Collecting: mt_250070017
189/557 - Collecting: mt_367717740
190/557 - Collecting: mt_406686614
191/557 - Collecting: mt_250070028
192/557 - Collecting: mt_012232477
193/557 - Collecting: mt_978828893
194/557 - Collecting: mt_195565516
195/557 - Collecting: mt_743353379
196/557 - Collecting: mt_367717736
197/557 - Collecting: mt_624494461
198/557 - Collecting: mt_012232250
199/557 - Collecting: mt_978828834
200/557 - Collecting: mt_839909973
201/557 - Collecting: mt_839909989
202/557 - Collecting: mt_743353363
203/557 - Collecting: mt_195565047
204/557 - Collecting: mt_624494314
205/557 - Collecting: mt_012232488
206/557 - Collecting: mt_581141276
207/557 - Collecting: mt_978828109
208/557 - Collecting: mt_250070631
209/557 - Collecting: mt_743353915
210/557 - Collecting: mt_839909525
211/557 - Collecting: mt_367717857
212/557 - Collecting: mt_624494382
213/557 - Collecting: mt_581141155
214/557 - Collecting: mt_406686750
215/557 - Collecting: mt_749907509
216/557 - Collecting: mt_835568069
217/557 - Collecting: mt_368823126
218/557 - Collecting: mt_978828170
219/557 - Collecting: mt_743353920
220/557 - Collecting: mt_367717808
221/557 - Collecting: mt_624494323
222/557 - Collecting: mt_582116491
223/557 - Collecting: mt_406686767
224/557 - Collecting: mt_195565004
225/557 - Collecting: mt_743353937
226/557 - Collecting: mt_839909597
227/557 - Collecting: mt_367717872
228/557 - Collecting: mt_012232422
229/557 - Collecting: mt_581141218
230/557 - Collecting: mt_978828186
231/557 - Collecting: mt_250070603
232/557 - Collecting: mt_012232411
233/557 - Collecting: mt_195565091
234/557 - Collecting: mt_250015317
235/557 - Collecting: mt_839909558
236/557 - Collecting: mt_978828128
237/557 - Collecting: mt_250070675
238/557 - Collecting: mt_743353951
239/557 - Collecting: mt_624494335
240/557 - Collecting: mt_406686778
241/557 - Collecting: mt_012232444
242/557 - Collecting: mt_581141221
243/557 - Collecting: mt_250070669
244/557 - Collecting: mt_195565063
245/557 - Collecting: mt_367717884
246/557 - Collecting: mt_406686781
247/557 - Collecting: mt_012232499
248/557 - Collecting: mt_581141234
249/557 - Collecting: mt_978828141
250/557 - Collecting: mt_250070680
251/557 - Collecting: mt_195565079
252/557 - Collecting: mt_743353902
253/557 - Collecting: mt_839909562
254/557 - Collecting: mt_367717813
255/557 - Collecting: mt_624494390
256/557 - Collecting: mt_581141242
257/557 - Collecting: mt_012232433
258/557 - Collecting: mt_406686712
259/557 - Collecting: mt_624494368
260/557 - Collecting: mt_406686724
261/557 - Collecting: mt_012232455
262/557 - Collecting: mt_581141293
263/557 - Collecting: mt_978828132
264/557 - Collecting: mt_250070616
265/557 - Collecting: mt_195565085
266/557 - Collecting: mt_743353964
267/557 - Collecting: mt_839909574
268/557 - Collecting: mt_367717845
269/557 - Collecting: mt_624494356
270/557 - Collecting: mt_012232400
271/557 - Collecting: mt_367717156
272/557 - Collecting: mt_839909029
273/557 - Collecting: mt_624494981
274/557 - Collecting: mt_406686899
275/557 - Collecting: mt_581141259
276/557 - Collecting: mt_195565010
277/557 - Collecting: mt_743353973
278/557 - Collecting: mt_839909583
279/557 - Collecting: mt_367717830
280/557 - Collecting: mt_250070627
281/557 - Collecting: mt_978828194
282/557 - Collecting: mt_195565637
283/557 - Collecting: mt_839909045
284/557 - Collecting: mt_624494912
285/557 - Collecting: mt_406686855
286/557 - Collecting: mt_012232387
287/557 - Collecting: mt_581141465
288/557 - Collecting: mt_978828203
289/557 - Collecting: mt_250070738
290/557 - Collecting: mt_195565646
291/557 - Collecting: mt_367717107
292/557 - Collecting: mt_978828269
293/557 - Collecting: mt_743353519
294/557 - Collecting: mt_978828280
295/557 - Collecting: mt_743353525
296/557 - Collecting: mt_250070752
297/557 - Collecting: mt_743353540
298/557 - Collecting: mt_839909030
299/557 - Collecting: mt_367717168
300/557 - Collecting: mt_624494924
301/557 - Collecting: mt_406686800
302/557 - Collecting: mt_012232318
303/557 - Collecting: mt_581141486
304/557 - Collecting: mt_250070791
305/557 - Collecting: mt_195565698
306/557 - Collecting: mt_406686866
307/557 - Collecting: mt_195565651
308/557 - Collecting: mt_743353536
309/557 - Collecting: mt_839909096
310/557 - Collecting: mt_012232321
311/557 - Collecting: mt_581141417
312/557 - Collecting: mt_250070763
313/557 - Collecting: mt_624494939
314/557 - Collecting: mt_406686877
315/557 - Collecting: mt_012232342
316/557 - Collecting: mt_581141428
317/557 - Collecting: mt_978828216
318/557 - Collecting: mt_367717114
319/557 - Collecting: mt_624494995
320/557 - Collecting: mt_012232334
321/557 - Collecting: mt_581141441
322/557 - Collecting: mt_978828227
323/557 - Collecting: mt_250070779
324/557 - Collecting: mt_195565664
325/557 - Collecting: mt_743353597
326/557 - Collecting: mt_367717182
327/557 - Collecting: mt_743353501
328/557 - Collecting: mt_839909057
329/557 - Collecting: mt_406686888
330/557 - Collecting: mt_195563100
331/557 - Collecting: mt_581141432
332/557 - Collecting: mt_839904809
333/557 - Collecting: mt_367710316
334/557 - Collecting: mt_406685489
335/557 - Collecting: mt_012238040
336/557 - Collecting: mt_581147529
337/557 - Collecting: mt_978826914
338/557 - Collecting: mt_250079267
339/557 - Collecting: mt_743352793
340/557 - Collecting: mt_839909008
341/557 - Collecting: mt_624491691
342/557 - Collecting: mt_012238025
343/557 - Collecting: mt_839904853
344/557 - Collecting: mt_367710380
345/557 - Collecting: mt_624491638
346/557 - Collecting: mt_406685464
347/557 - Collecting: mt_581147513
348/557 - Collecting: mt_978826982
349/557 - Collecting: mt_250079206
350/557 - Collecting: mt_195563155
351/557 - Collecting: mt_743352734
352/557 - Collecting: mt_839904894
353/557 - Collecting: mt_367710375
354/557 - Collecting: mt_581147584
355/557 - Collecting: mt_624491626
356/557 - Collecting: mt_406685402
357/557 - Collecting: mt_012238019
358/557 - Collecting: mt_978826971
359/557 - Collecting: mt_250079250
360/557 - Collecting: mt_743352742
361/557 - Collecting: mt_839904832
362/557 - Collecting: mt_367710303
363/557 - Collecting: mt_624491610
364/557 - Collecting: mt_406685451
365/557 - Collecting: mt_195563199
366/557 - Collecting: mt_012238083
367/557 - Collecting: mt_978826968
368/557 - Collecting: mt_250079295
369/557 - Collecting: mt_195563133
370/557 - Collecting: mt_743352721
371/557 - Collecting: mt_839904828
372/557 - Collecting: mt_367710354
373/557 - Collecting: mt_624491685
374/557 - Collecting: mt_406685498
375/557 - Collecting: mt_012238074
376/557 - Collecting: mt_581147572
377/557 - Collecting: mt_581147561
378/557 - Collecting: mt_014824725
379/557 - Collecting: mt_624491069
380/557 - Collecting: mt_978826907
381/557 - Collecting: mt_250079239
382/557 - Collecting: mt_195563144
383/557 - Collecting: mt_743352677
384/557 - Collecting: mt_839904787
385/557 - Collecting: mt_367710432
386/557 - Collecting: mt_406685247
387/557 - Collecting: mt_581147958
388/557 - Collecting: mt_978826396
389/557 - Collecting: mt_250079123
390/557 - Collecting: mt_012238502
391/557 - Collecting: mt_250079182
392/557 - Collecting: mt_367710441
393/557 - Collecting: mt_195563881
394/557 - Collecting: mt_743352666
395/557 - Collecting: mt_624491003
396/557 - Collecting: mt_406685226
397/557 - Collecting: mt_581147997
398/557 - Collecting: mt_978826330
399/557 - Collecting: mt_195563878
400/557 - Collecting: mt_743352600
401/557 - Collecting: mt_839904776
402/557 - Collecting: mt_012238551
403/557 - Collecting: mt_839904760
404/557 - Collecting: mt_367710428
405/557 - Collecting: mt_624491054
406/557 - Collecting: mt_406685210
407/557 - Collecting: mt_012238598
408/557 - Collecting: mt_581147936
409/557 - Collecting: mt_978826329
410/557 - Collecting: mt_839904705
411/557 - Collecting: mt_250079171
412/557 - Collecting: mt_195563867
413/557 - Collecting: mt_743352655
414/557 - Collecting: mt_367710417
415/557 - Collecting: mt_624491092
416/557 - Collecting: mt_406685285
417/557 - Collecting: mt_012238537
418/557 - Collecting: mt_581147925
419/557 - Collecting: mt_195563806
420/557 - Collecting: mt_743352699
421/557 - Collecting: mt_839904759
422/557 - Collecting: mt_367710486
423/557 - Collecting: mt_624491031
424/557 - Collecting: mt_406685279
425/557 - Collecting: mt_250079168
426/557 - Collecting: mt_581147919
427/557 - Collecting: mt_978826384
428/557 - Collecting: mt_250079107
429/557 - Collecting: mt_195563850
430/557 - Collecting: mt_743352633
431/557 - Collecting: mt_839904793
432/557 - Collecting: mt_367710470
433/557 - Collecting: mt_624491048
434/557 - Collecting: mt_406685204
435/557 - Collecting: mt_012238515
436/557 - Collecting: mt_012238520
437/557 - Collecting: mt_581147983
438/557 - Collecting: mt_195563895
439/557 - Collecting: mt_978826372
440/557 - Collecting: mt_250079156
441/557 - Collecting: mt_743352644
442/557 - Collecting: mt_839904734
443/557 - Collecting: mt_367710465
444/557 - Collecting: mt_624491016
445/557 - Collecting: mt_406685252
446/557 - Collecting: mt_012238589
447/557 - Collecting: mt_581147974
448/557 - Collecting: mt_978826361
449/557 - Collecting: mt_250079190
450/557 - Collecting: mt_743352611
451/557 - Collecting: mt_195563839
452/557 - Collecting: mt_367710453
453/557 - Collecting: mt_624491080
454/557 - Collecting: mt_406685291
455/557 - Collecting: mt_012238573
456/557 - Collecting: mt_581147962
457/557 - Collecting: mt_978826308
458/557 - Collecting: mt_250079135
459/557 - Collecting: mt_195563843
460/557 - Collecting: mt_743352622
461/557 - Collecting: mt_839904742
462/557 - Collecting: mt_406120724
463/557 - Collecting: mt_624491565
464/557 - Collecting: mt_406685148
465/557 - Collecting: mt_839904688
466/557 - Collecting: mt_367710234
467/557 - Collecting: mt_012238904
468/557 - Collecting: mt_581147351
469/557 - Collecting: mt_978826497
470/557 - Collecting: mt_250079829
471/557 - Collecting: mt_195563714
472/557 - Collecting: mt_743352067
473/557 - Collecting: mt_367710242
474/557 - Collecting: mt_406685127
475/557 - Collecting: mt_624491509
476/557 - Collecting: mt_012238952
477/557 - Collecting: mt_581147398
478/557 - Collecting: mt_978826436
479/557 - Collecting: mt_250079813
480/557 - Collecting: mt_743352006
481/557 - Collecting: mt_195563771
482/557 - Collecting: mt_839904666
483/557 - Collecting: mt_367710221
484/557 - Collecting: mt_624491553
485/557 - Collecting: mt_406685116
486/557 - Collecting: mt_581147337
487/557 - Collecting: mt_195563768
488/557 - Collecting: mt_012238991
489/557 - Collecting: mt_250079872
490/557 - Collecting: mt_743352050
491/557 - Collecting: mt_839904600
492/557 - Collecting: mt_367710218
493/557 - Collecting: mt_406685180
494/557 - Collecting: mt_012238938
495/557 - Collecting: mt_581147346
496/557 - Collecting: mt_624491594
497/557 - Collecting: mt_978826440
498/557 - Collecting: mt_978826419
499/557 - Collecting: mt_743352095
500/557 - Collecting: mt_839904655
501/557 - Collecting: mt_367710287
502/557 - Collecting: mt_624491532
503/557 - Collecting: mt_406685175
504/557 - Collecting: mt_012238947
505/557 - Collecting: mt_581147315
506/557 - Collecting: mt_978826483
507/557 - Collecting: mt_250079861
508/557 - Collecting: mt_195563707
509/557 - Collecting: mt_250079808
510/557 - Collecting: mt_743352039
511/557 - Collecting: mt_195563756
512/557 - Collecting: mt_839904699
513/557 - Collecting: mt_367710276
514/557 - Collecting: mt_624491541
515/557 - Collecting: mt_406685169
516/557 - Collecting: mt_012238910
517/557 - Collecting: mt_978826474
518/557 - Collecting: mt_250079857
519/557 - Collecting: mt_195563790
520/557 - Collecting: mt_743352043
521/557 - Collecting: mt_581147389
522/557 - Collecting: mt_978826462
523/557 - Collecting: mt_839904633
524/557 - Collecting: mt_367710260
525/557 - Collecting: mt_624491528
526/557 - Collecting: mt_406685154
527/557 - Collecting: mt_012238985
528/557 - Collecting: mt_250079896
529/557 - Collecting: mt_195563735
530/557 - Collecting: mt_839904644
531/557 - Collecting: mt_367710205
532/557 - Collecting: mt_581147373
533/557 - Collecting: mt_743352024
534/557 - Collecting: mt_624491586
535/557 - Collecting: mt_406685192
536/557 - Collecting: mt_012238979
537/557 - Collecting: mt_581147364
538/557 - Collecting: mt_978826401
539/557 - Collecting: mt_250079830
540/557 - Collecting: mt_195563749
541/557 - Collecting: mt_743352012
542/557 - Collecting: mt_839904622
543/557 - Collecting: mt_624491960
544/557 - Collecting: mt_406685841
545/557 - Collecting: mt_367710133
546/557 - Collecting: mt_012238303
547/557 - Collecting: mt_581147452
548/557 - Collecting: mt_978826298
549/557 - Collecting: mt_978828117
550/557 - Collecting: mt_250079725
551/557 - Collecting: mt_195563613
552/557 - Collecting: mt_839904078
553/557 - Collecting: mt_367710144
554/557 - Collecting: mt_624491905
555/557 - Collecting: mt_406685828
556/557 - Collecting: mt_012238354
557/557 - Collecting: mt_581147491

In [117]:
saved_championship_2023_24 = list(
    CHAMPIONSHIP_SEASON_DIRS["2023_24"].glob("*.json")
)

print("Saved Championship 2023/24 files:", len(saved_championship_2023_24))

Saved Championship 2023/24 files: 557

In [118]:
# Collect 2024/25 Championship season
championship_2024_25_matches = get_all_season_matches(
    CHAMPIONSHIP_ID,
    CHAMPIONSHIP_SEASONS["2024_25"]
)

print("Total matches returned:", len(championship_2024_25_matches))

Total matches returned: 559

In [119]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in championship_2024_25_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in championship_2024_25_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in championship_2024_25_matches
)))

Statuses:
Counter({'finished': 557, 'postponed': 2})

Stages:
Counter({None: 554, 'semi_final': 4, 'final': 1})

Unique IDs: 559

In [120]:
finished_championship_2024_25 = [
    match for match in championship_2024_25_matches
    if match["status"] == "finished"
]

print("Finished matches:", len(finished_championship_2024_25))

Finished matches: 557

In [121]:
collect_championship_baseline_data(
    "2024_25",
    finished_championship_2024_25
)

1/557 - Collecting: mt_838435709
2/557 - Collecting: mt_363510466
3/557 - Collecting: mt_838204739
4/557 - Collecting: mt_404985209
5/557 - Collecting: mt_626891021
6/557 - Collecting: mt_830528275
7/557 - Collecting: mt_361853547
8/557 - Collecting: mt_629386802
9/557 - Collecting: mt_745917109
10/557 - Collecting: mt_629386898
11/557 - Collecting: mt_584265623
12/557 - Collecting: mt_972109012
13/557 - Collecting: mt_745917194
14/557 - Collecting: mt_629386846
15/557 - Collecting: mt_013470729
16/557 - Collecting: mt_584265614
17/557 - Collecting: mt_972109081
18/557 - Collecting: mt_364473134
19/557 - Collecting: mt_257632311
20/557 - Collecting: mt_196041487
21/557 - Collecting: mt_408794925
22/557 - Collecting: mt_584265635
23/557 - Collecting: mt_257632388
24/557 - Collecting: mt_196041476
25/557 - Collecting: mt_361853526
26/557 - Collecting: mt_629386851
27/557 - Collecting: mt_830528269
28/557 - Collecting: mt_408794919
29/557 - Collecting: mt_013470730
30/557 - Collecting: mt_584265649
31/557 - Collecting: mt_972109677
32/557 - Collecting: mt_257632959
33/557 - Collecting: mt_745917227
34/557 - Collecting: mt_830528447
35/557 - Collecting: mt_361853002
36/557 - Collecting: mt_629386119
37/557 - Collecting: mt_408794557
38/557 - Collecting: mt_257632377
39/557 - Collecting: mt_745917153
40/557 - Collecting: mt_013470745
41/557 - Collecting: mt_257632366
42/557 - Collecting: mt_196041394
43/557 - Collecting: mt_408792489
44/557 - Collecting: mt_361853073
45/557 - Collecting: mt_584265778
46/557 - Collecting: mt_629380691
47/557 - Collecting: mt_013475040
48/557 - Collecting: mt_629380092
49/557 - Collecting: mt_972103313
50/557 - Collecting: mt_629380031
51/557 - Collecting: mt_408792279
52/557 - Collecting: mt_584269919
53/557 - Collecting: mt_013475598
54/557 - Collecting: mt_015342434
55/557 - Collecting: mt_408792226
56/557 - Collecting: mt_013475551
57/557 - Collecting: mt_584269997
58/557 - Collecting: mt_972103330
59/557 - Collecting: mt_745916600
60/557 - Collecting: mt_830527760
61/557 - Collecting: mt_361854428
62/557 - Collecting: mt_196048867
63/557 - Collecting: mt_257631182
64/557 - Collecting: mt_257631171
65/557 - Collecting: mt_408792210
66/557 - Collecting: mt_745916699
67/557 - Collecting: mt_972103329
68/557 - Collecting: mt_745916655
69/557 - Collecting: mt_013475520
70/557 - Collecting: mt_584269529
71/557 - Collecting: mt_196048100
72/557 - Collecting: mt_629380054
73/557 - Collecting: mt_830527705
74/557 - Collecting: mt_408792285
75/557 - Collecting: mt_013475537
76/557 - Collecting: mt_830527759
77/557 - Collecting: mt_972103384
78/557 - Collecting: mt_830527828
79/557 - Collecting: mt_408792498
80/557 - Collecting: mt_013475074
81/557 - Collecting: mt_972103907
82/557 - Collecting: mt_257631239
83/557 - Collecting: mt_196048144
84/557 - Collecting: mt_745916677
85/557 - Collecting: mt_830527787
86/557 - Collecting: mt_196048133
87/557 - Collecting: mt_745916721
88/557 - Collecting: mt_584269561
89/557 - Collecting: mt_629380685
90/557 - Collecting: mt_746592907
91/557 - Collecting: mt_408756664
92/557 - Collecting: mt_745916793
93/557 - Collecting: mt_830527853
94/557 - Collecting: mt_361854380
95/557 - Collecting: mt_408792464
96/557 - Collecting: mt_013475025
97/557 - Collecting: mt_584269513
98/557 - Collecting: mt_972103982
99/557 - Collecting: mt_629314438
100/557 - Collecting: mt_257631267
101/557 - Collecting: mt_972103914
102/557 - Collecting: mt_972168814
103/557 - Collecting: mt_257690078
104/557 - Collecting: mt_196035566
105/557 - Collecting: mt_745923359
106/557 - Collecting: mt_629314491
107/557 - Collecting: mt_408756689
108/557 - Collecting: mt_013482240
109/557 - Collecting: mt_196035500
110/557 - Collecting: mt_361807780
111/557 - Collecting: mt_361807716
112/557 - Collecting: mt_257690067
113/557 - Collecting: mt_830549909
114/557 - Collecting: mt_830549965
115/557 - Collecting: mt_361807727
116/557 - Collecting: mt_629314452
117/557 - Collecting: mt_408756615
118/557 - Collecting: mt_972168823
119/557 - Collecting: mt_584271145
120/557 - Collecting: mt_257690012
121/557 - Collecting: mt_629314404
122/557 - Collecting: mt_257690081
123/557 - Collecting: mt_196035577
124/557 - Collecting: mt_745923305
125/557 - Collecting: mt_013482297
126/557 - Collecting: mt_830549970
127/557 - Collecting: mt_013482201
128/557 - Collecting: mt_584271157
129/557 - Collecting: mt_972168890
130/557 - Collecting: mt_196035588
131/557 - Collecting: mt_361807748
132/557 - Collecting: mt_408756620
133/557 - Collecting: mt_584271196
134/557 - Collecting: mt_972168849
135/557 - Collecting: mt_408756646
136/557 - Collecting: mt_013482258
137/557 - Collecting: mt_745923360
138/557 - Collecting: mt_402684520
139/557 - Collecting: mt_015230858
140/557 - Collecting: mt_589145796
141/557 - Collecting: mt_973829649
142/557 - Collecting: mt_629314389
143/557 - Collecting: mt_972168106
144/557 - Collecting: mt_196035511
145/557 - Collecting: mt_361807731
146/557 - Collecting: mt_257690699
147/557 - Collecting: mt_361807852
148/557 - Collecting: mt_745923376
149/557 - Collecting: mt_629314463
150/557 - Collecting: mt_620215154
151/557 - Collecting: mt_251913016
152/557 - Collecting: mt_401159122
153/557 - Collecting: mt_408756797
154/557 - Collecting: mt_745923941
155/557 - Collecting: mt_629314315
156/557 - Collecting: mt_013482484
157/557 - Collecting: mt_196035034
158/557 - Collecting: mt_830549527
159/557 - Collecting: mt_408756758
160/557 - Collecting: mt_584271271
161/557 - Collecting: mt_972168167
162/557 - Collecting: mt_830549548
163/557 - Collecting: mt_361807804
164/557 - Collecting: mt_746261364
165/557 - Collecting: mt_364063534
166/557 - Collecting: mt_401159259
167/557 - Collecting: mt_972168181
168/557 - Collecting: mt_830549592
169/557 - Collecting: mt_361807863
170/557 - Collecting: mt_629314320
171/557 - Collecting: mt_013482413
172/557 - Collecting: mt_584271282
173/557 - Collecting: mt_257690655
174/557 - Collecting: mt_257690600
175/557 - Collecting: mt_408756701
176/557 - Collecting: mt_972168178
177/557 - Collecting: mt_196035093
178/557 - Collecting: mt_013482429
179/557 - Collecting: mt_196035059
180/557 - Collecting: mt_584271223
181/557 - Collecting: mt_196035005
182/557 - Collecting: mt_361807885
183/557 - Collecting: mt_408756762
184/557 - Collecting: mt_584271214
185/557 - Collecting: mt_745923994
186/557 - Collecting: mt_972168112
187/557 - Collecting: mt_257690666
188/557 - Collecting: mt_830549554
189/557 - Collecting: mt_629314346
190/557 - Collecting: mt_629314351
191/557 - Collecting: mt_972168124
192/557 - Collecting: mt_830549503
193/557 - Collecting: mt_408756774
194/557 - Collecting: mt_013482445
195/557 - Collecting: mt_196035060
196/557 - Collecting: mt_584271249
197/557 - Collecting: mt_257690677
198/557 - Collecting: mt_836642672
199/557 - Collecting: mt_629314302
200/557 - Collecting: mt_013482457
201/557 - Collecting: mt_584271235
202/557 - Collecting: mt_257690688
203/557 - Collecting: mt_745923909
204/557 - Collecting: mt_361807826
205/557 - Collecting: mt_013482430
206/557 - Collecting: mt_972168143
207/557 - Collecting: mt_196035076
208/557 - Collecting: mt_408756719
209/557 - Collecting: mt_361807847
210/557 - Collecting: mt_401261754
211/557 - Collecting: mt_740029779
212/557 - Collecting: mt_629038018
213/557 - Collecting: mt_830549580
214/557 - Collecting: mt_629314364
215/557 - Collecting: mt_408756740
216/557 - Collecting: mt_972168139
217/557 - Collecting: mt_745923965
218/557 - Collecting: mt_830549575
219/557 - Collecting: mt_013482408
220/557 - Collecting: mt_584271256
221/557 - Collecting: mt_257690611
222/557 - Collecting: mt_196035087
223/557 - Collecting: mt_745923970
224/557 - Collecting: mt_408756896
225/557 - Collecting: mt_257690622
226/557 - Collecting: mt_196035018
227/557 - Collecting: mt_361807151
228/557 - Collecting: mt_257690793
229/557 - Collecting: mt_745923516
230/557 - Collecting: mt_830549026
231/557 - Collecting: mt_629314983
232/557 - Collecting: mt_013482371
233/557 - Collecting: mt_584271467
234/557 - Collecting: mt_972168200
235/557 - Collecting: mt_013482314
236/557 - Collecting: mt_745923531
237/557 - Collecting: mt_830549038
238/557 - Collecting: mt_972168277
239/557 - Collecting: mt_196035694
240/557 - Collecting: mt_408756857
241/557 - Collecting: mt_972168266
242/557 - Collecting: mt_196035641
243/557 - Collecting: mt_013482323
244/557 - Collecting: mt_257690759
245/557 - Collecting: mt_830549047
246/557 - Collecting: mt_257690705
247/557 - Collecting: mt_740630314
248/557 - Collecting: mt_974972382
249/557 - Collecting: mt_258253179
250/557 - Collecting: mt_830792629
251/557 - Collecting: mt_257690760
252/557 - Collecting: mt_830549063
253/557 - Collecting: mt_408756884
254/557 - Collecting: mt_013482335
255/557 - Collecting: mt_584271443
256/557 - Collecting: mt_196035665
257/557 - Collecting: mt_408756872
258/557 - Collecting: mt_830549052
259/557 - Collecting: mt_745923503
260/557 - Collecting: mt_361807115
261/557 - Collecting: mt_745923592
262/557 - Collecting: mt_013482390
263/557 - Collecting: mt_257690721
264/557 - Collecting: mt_745923010
265/557 - Collecting: mt_013482978
266/557 - Collecting: mt_196035617
267/557 - Collecting: mt_361807137
268/557 - Collecting: mt_013482307
269/557 - Collecting: mt_361807146
270/557 - Collecting: mt_584271439
271/557 - Collecting: mt_972168233
272/557 - Collecting: mt_196035686
273/557 - Collecting: mt_745923569
274/557 - Collecting: mt_745923026
275/557 - Collecting: mt_629314529
276/557 - Collecting: mt_972168487
277/557 - Collecting: mt_257690809
278/557 - Collecting: mt_361807262
279/557 - Collecting: mt_830549646
280/557 - Collecting: mt_257690832
281/557 - Collecting: mt_830549620
282/557 - Collecting: mt_361807258
283/557 - Collecting: mt_257690853
284/557 - Collecting: mt_013482981
285/557 - Collecting: mt_584271377
286/557 - Collecting: mt_629314545
287/557 - Collecting: mt_745923052
288/557 - Collecting: mt_745923004
289/557 - Collecting: mt_013482939
290/557 - Collecting: mt_972168421
291/557 - Collecting: mt_257690870
292/557 - Collecting: mt_830549602
293/557 - Collecting: mt_408756171
294/557 - Collecting: mt_013482943
295/557 - Collecting: mt_196035703
296/557 - Collecting: mt_830549698
297/557 - Collecting: mt_408756168
298/557 - Collecting: mt_257690886
299/557 - Collecting: mt_013482577
300/557 - Collecting: mt_257690828
301/557 - Collecting: mt_196035716
302/557 - Collecting: mt_013482950
303/557 - Collecting: mt_972168434
304/557 - Collecting: mt_361807240
305/557 - Collecting: mt_830549664
306/557 - Collecting: mt_830549689
307/557 - Collecting: mt_584271399
308/557 - Collecting: mt_408756114
309/557 - Collecting: mt_629314561
310/557 - Collecting: mt_257690192
311/557 - Collecting: mt_830549725
312/557 - Collecting: mt_196035891
313/557 - Collecting: mt_972168370
314/557 - Collecting: mt_830549740
315/557 - Collecting: mt_408756250
316/557 - Collecting: mt_584271976
317/557 - Collecting: mt_745923615
318/557 - Collecting: mt_361807461
319/557 - Collecting: mt_629314023
320/557 - Collecting: mt_257690131
321/557 - Collecting: mt_584271987
322/557 - Collecting: mt_257690103
323/557 - Collecting: mt_361807484
324/557 - Collecting: mt_257690169
325/557 - Collecting: mt_361807472
326/557 - Collecting: mt_408756267
327/557 - Collecting: mt_408756281
328/557 - Collecting: mt_629314090
329/557 - Collecting: mt_196035863
330/557 - Collecting: mt_745923651
331/557 - Collecting: mt_408756278
332/557 - Collecting: mt_972168317
333/557 - Collecting: mt_196035804
334/557 - Collecting: mt_257690180
335/557 - Collecting: mt_361807430
336/557 - Collecting: mt_584271993
337/557 - Collecting: mt_196035885
338/557 - Collecting: mt_361807445
339/557 - Collecting: mt_629314056
340/557 - Collecting: mt_408756224
341/557 - Collecting: mt_196035879
342/557 - Collecting: mt_830549762
343/557 - Collecting: mt_257690127
344/557 - Collecting: mt_257690291
345/557 - Collecting: mt_013482018
346/557 - Collecting: mt_584271586
347/557 - Collecting: mt_629314612
348/557 - Collecting: mt_257690238
349/557 - Collecting: mt_830549829
350/557 - Collecting: mt_361807356
351/557 - Collecting: mt_408756400
352/557 - Collecting: mt_745923725
353/557 - Collecting: mt_013482087
354/557 - Collecting: mt_013482500
355/557 - Collecting: mt_196035146
356/557 - Collecting: mt_013482021
357/557 - Collecting: mt_361807382
358/557 - Collecting: mt_629314643
359/557 - Collecting: mt_972168980
360/557 - Collecting: mt_196035151
361/557 - Collecting: mt_013482034
362/557 - Collecting: mt_257690279
363/557 - Collecting: mt_013482042
364/557 - Collecting: mt_972168916
365/557 - Collecting: mt_257690263
366/557 - Collecting: mt_745923736
367/557 - Collecting: mt_830549808
368/557 - Collecting: mt_257690210
369/557 - Collecting: mt_196035189
370/557 - Collecting: mt_745923762
371/557 - Collecting: mt_013482093
372/557 - Collecting: mt_972168948
373/557 - Collecting: mt_629314695
374/557 - Collecting: mt_408756422
375/557 - Collecting: mt_584271594
376/557 - Collecting: mt_745923701
377/557 - Collecting: mt_361807323
378/557 - Collecting: mt_361808567
379/557 - Collecting: mt_361808506
380/557 - Collecting: mt_361808550
381/557 - Collecting: mt_257696398
382/557 - Collecting: mt_408757959
383/557 - Collecting: mt_257696337
384/557 - Collecting: mt_830545223
385/557 - Collecting: mt_013482005
386/557 - Collecting: mt_584272675
387/557 - Collecting: mt_196030440
388/557 - Collecting: mt_972168992
389/557 - Collecting: mt_257690226
390/557 - Collecting: mt_629048581
391/557 - Collecting: mt_830545235
392/557 - Collecting: mt_629313822
393/557 - Collecting: mt_830545256
394/557 - Collecting: mt_972161079
395/557 - Collecting: mt_196030497
396/557 - Collecting: mt_584272627
397/557 - Collecting: mt_629313844
398/557 - Collecting: mt_196030401
399/557 - Collecting: mt_629313833
400/557 - Collecting: mt_972161010
401/557 - Collecting: mt_257696302
402/557 - Collecting: mt_408757918
403/557 - Collecting: mt_013484753
404/557 - Collecting: mt_257696315
405/557 - Collecting: mt_196030483
406/557 - Collecting: mt_257696389
407/557 - Collecting: mt_830545207
408/557 - Collecting: mt_629313899
409/557 - Collecting: mt_408757987
410/557 - Collecting: mt_584272692
411/557 - Collecting: mt_972161047
412/557 - Collecting: mt_584272648
413/557 - Collecting: mt_361808524
414/557 - Collecting: mt_408757594
415/557 - Collecting: mt_745929223
416/557 - Collecting: mt_013484875
417/557 - Collecting: mt_972161602
418/557 - Collecting: mt_830545424
419/557 - Collecting: mt_408757942
420/557 - Collecting: mt_584272654
421/557 - Collecting: mt_972161091
422/557 - Collecting: mt_257696997
423/557 - Collecting: mt_629313118
424/557 - Collecting: mt_257696320
425/557 - Collecting: mt_361808055
426/557 - Collecting: mt_013484880
427/557 - Collecting: mt_584272726
428/557 - Collecting: mt_196030396
429/557 - Collecting: mt_629313121
430/557 - Collecting: mt_584272779
431/557 - Collecting: mt_408757565
432/557 - Collecting: mt_629313134
433/557 - Collecting: mt_408757570
434/557 - Collecting: mt_972161689
435/557 - Collecting: mt_361808077
436/557 - Collecting: mt_013484827
437/557 - Collecting: mt_584272785
438/557 - Collecting: mt_972161646
439/557 - Collecting: mt_745929207
440/557 - Collecting: mt_257696983
441/557 - Collecting: mt_830545406
442/557 - Collecting: mt_013484831
443/557 - Collecting: mt_257696962
444/557 - Collecting: mt_745929290
445/557 - Collecting: mt_629313159
446/557 - Collecting: mt_013484892
447/557 - Collecting: mt_361808011
448/557 - Collecting: mt_972161620
449/557 - Collecting: mt_830545467
450/557 - Collecting: mt_745929271
451/557 - Collecting: mt_830545478
452/557 - Collecting: mt_629313105
453/557 - Collecting: mt_972161637
454/557 - Collecting: mt_257696919
455/557 - Collecting: mt_196030384
456/557 - Collecting: mt_361808022
457/557 - Collecting: mt_408757517
458/557 - Collecting: mt_361808044
459/557 - Collecting: mt_408757528
460/557 - Collecting: mt_584272791
461/557 - Collecting: mt_013484854
462/557 - Collecting: mt_257696925
463/557 - Collecting: mt_196030949
464/557 - Collecting: mt_972161698
465/557 - Collecting: mt_196030313
466/557 - Collecting: mt_013484803
467/557 - Collecting: mt_257696530
468/557 - Collecting: mt_745929412
469/557 - Collecting: mt_830545322
470/557 - Collecting: mt_361808033
471/557 - Collecting: mt_629313160
472/557 - Collecting: mt_408757541
473/557 - Collecting: mt_584272752
474/557 - Collecting: mt_972161701
475/557 - Collecting: mt_584272873
476/557 - Collecting: mt_257696596
477/557 - Collecting: mt_196030935
478/557 - Collecting: mt_830545344
479/557 - Collecting: mt_361808605
480/557 - Collecting: mt_629313286
481/557 - Collecting: mt_584272864
482/557 - Collecting: mt_972161762
483/557 - Collecting: mt_745929424
484/557 - Collecting: mt_013484179
485/557 - Collecting: mt_408757092
486/557 - Collecting: mt_745929443
487/557 - Collecting: mt_408757069
488/557 - Collecting: mt_013484110
489/557 - Collecting: mt_584272889
490/557 - Collecting: mt_972161774
491/557 - Collecting: mt_257696557
492/557 - Collecting: mt_196030990
493/557 - Collecting: mt_361808660
494/557 - Collecting: mt_830545333
495/557 - Collecting: mt_629313228
496/557 - Collecting: mt_408757054
497/557 - Collecting: mt_013484185
498/557 - Collecting: mt_745929439
499/557 - Collecting: mt_830545355
500/557 - Collecting: mt_361808687
501/557 - Collecting: mt_408757075
502/557 - Collecting: mt_257696508
503/557 - Collecting: mt_830545399
504/557 - Collecting: mt_361808676
505/557 - Collecting: mt_629313241
506/557 - Collecting: mt_584272815
507/557 - Collecting: mt_972161783
508/557 - Collecting: mt_196030956
509/557 - Collecting: mt_013484147
510/557 - Collecting: mt_361808618
511/557 - Collecting: mt_629313294
512/557 - Collecting: mt_013484138
513/557 - Collecting: mt_584272846
514/557 - Collecting: mt_972161719
515/557 - Collecting: mt_196030907
516/557 - Collecting: mt_745929495
517/557 - Collecting: mt_629313232
518/557 - Collecting: mt_745929450
519/557 - Collecting: mt_830545300
520/557 - Collecting: mt_408757080
521/557 - Collecting: mt_257696561
522/557 - Collecting: mt_257696572
523/557 - Collecting: mt_196030971
524/557 - Collecting: mt_361808621
525/557 - Collecting: mt_629313253
526/557 - Collecting: mt_408757016
527/557 - Collecting: mt_013484191
528/557 - Collecting: mt_972161740
529/557 - Collecting: mt_196030968
530/557 - Collecting: mt_257696513
531/557 - Collecting: mt_745929406
532/557 - Collecting: mt_830545366
533/557 - Collecting: mt_584272837
534/557 - Collecting: mt_830545377
535/557 - Collecting: mt_972161797
536/557 - Collecting: mt_257696529
537/557 - Collecting: mt_745929467
538/557 - Collecting: mt_629313209
539/557 - Collecting: mt_408757027
540/557 - Collecting: mt_013484152
541/557 - Collecting: mt_584272898
542/557 - Collecting: mt_196030914
543/557 - Collecting: mt_361808642
544/557 - Collecting: mt_972161736
545/557 - Collecting: mt_584272851
546/557 - Collecting: mt_629319100
547/557 - Collecting: mt_745925272
548/557 - Collecting: mt_830540482
549/557 - Collecting: mt_361801043
550/557 - Collecting: mt_408758521
551/557 - Collecting: mt_013483853
552/557 - Collecting: mt_584274792
553/557 - Collecting: mt_972162638
554/557 - Collecting: mt_257697915
555/557 - Collecting: mt_361801024
556/557 - Collecting: mt_257697920
557/557 - Collecting: mt_196036319

In [122]:
saved_championship_2024_25 = list(
    CHAMPIONSHIP_SEASON_DIRS["2024_25"].glob("*.json")
)

print("Saved Championship 2024/25 files:", len(saved_championship_2024_25))

Saved Championship 2024/25 files: 557

In [124]:
# Collect 2025/26 Championship season

championship_2025_26_matches = get_all_season_matches(
    CHAMPIONSHIP_ID,
    CHAMPIONSHIP_SEASONS["2025_26"]
)

print("Total matches returned:", len(championship_2025_26_matches))

Total matches returned: 558

In [125]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in championship_2025_26_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in championship_2025_26_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in championship_2025_26_matches
)))

Statuses:
Counter({'finished': 557, 'postponed': 1})

Stages:
Counter({None: 552, 'semi_final': 4, 'final': 2})

Unique IDs: 558

In [126]:
finished_championship_2025_26 = [
    match for match in championship_2025_26_matches
    if match["status"] == "finished"
]

print("Finished matches:", len(finished_championship_2025_26))

Finished matches: 557

In [129]:
collect_championship_baseline_data(
    "2025_26",
    finished_championship_2025_26
)

1/557 - Skipping existing: mt_899557794
2/557 - Skipping existing: mt_466047116
3/557 - Skipping existing: mt_377638221
4/557 - Skipping existing: mt_155910486
5/557 - Skipping existing: mt_733479169
6/557 - Skipping existing: mt_747917034
7/557 - Skipping existing: mt_838528694
8/557 - Skipping existing: mt_363853275
9/557 - Skipping existing: mt_626386526
10/557 - Skipping existing: mt_404794102
11/557 - Skipping existing: mt_010470919
12/557 - Skipping existing: mt_585265384
13/557 - Skipping existing: mt_979109471
14/557 - Skipping existing: mt_252632850
15/557 - Skipping existing: mt_191041799
16/557 - Skipping existing: mt_747917042
17/557 - Skipping existing: mt_363853203
18/557 - Skipping existing: mt_734524246
19/557 - Skipping existing: mt_010470983
20/557 - Skipping existing: mt_838528632
21/557 - Skipping existing: mt_626386510
22/557 - Skipping existing: mt_979109468
23/557 - Skipping existing: mt_252632895
24/557 - Skipping existing: mt_363853254
25/557 - Skipping existing: mt_404794198
26/557 - Skipping existing: mt_585265372
27/557 - Skipping existing: mt_191041733
28/557 - Skipping existing: mt_838528628
29/557 - Skipping existing: mt_404794151
30/557 - Skipping existing: mt_747917021
31/557 - Skipping existing: mt_626386585
32/557 - Skipping existing: mt_585265361
33/557 - Skipping existing: mt_585265458
34/557 - Skipping existing: mt_979109407
35/557 - Skipping existing: mt_252632839
36/557 - Skipping existing: mt_191041744
37/557 - Skipping existing: mt_747917577
38/557 - Skipping existing: mt_838528087
39/557 - Skipping existing: mt_363853132
40/557 - Skipping existing: mt_626386969
41/557 - Skipping existing: mt_010470302
42/557 - Skipping existing: mt_252632723
43/557 - Skipping existing: mt_404794847
44/557 - Skipping existing: mt_191041681
45/557 - Skipping existing: mt_747917566
46/557 - Skipping existing: mt_626386903
47/557 - Skipping existing: mt_404794826
48/557 - Skipping existing: mt_010470351
49/557 - Skipping existing: mt_585265497
50/557 - Skipping existing: mt_979109296
51/557 - Skipping existing: mt_838528076
52/557 - Skipping existing: mt_363853141
53/557 - Skipping existing: mt_979109230
54/557 - Skipping existing: mt_893043436
55/557 - Skipping existing: mt_010470974
56/557 - Skipping existing: mt_404794885
57/557 - Skipping existing: mt_252632782
58/557 - Skipping existing: mt_747917500
59/557 - Skipping existing: mt_838528060
60/557 - Skipping existing: mt_363853128
61/557 - Skipping existing: mt_010470398
62/557 - Skipping existing: mt_585265436
63/557 - Skipping existing: mt_979109229
64/557 - Skipping existing: mt_626386954
65/557 - Skipping existing: mt_404794810
66/557 - Skipping existing: mt_747917555
67/557 - Skipping existing: mt_191041678
68/557 - Skipping existing: mt_363853117
69/557 - Skipping existing: mt_747917599
70/557 - Skipping existing: mt_252632771
71/557 - Skipping existing: mt_191041667
72/557 - Skipping existing: mt_838528005
73/557 - Skipping existing: mt_626386992
74/557 - Skipping existing: mt_010470337
75/557 - Skipping existing: mt_252632768
76/557 - Skipping existing: mt_191041606
77/557 - Skipping existing: mt_626386931
78/557 - Skipping existing: mt_585265425
79/557 - Skipping existing: mt_979109213
80/557 - Skipping existing: mt_747917533
81/557 - Skipping existing: mt_838528059
82/557 - Skipping existing: mt_363853186
83/557 - Skipping existing: mt_010470320
84/557 - Skipping existing: mt_585265419
85/557 - Skipping existing: mt_252632707
86/557 - Skipping existing: mt_191041650
87/557 - Skipping existing: mt_838528093
88/557 - Skipping existing: mt_363853170
89/557 - Skipping existing: mt_626386948
90/557 - Skipping existing: mt_979109284
91/557 - Skipping existing: mt_010470315
92/557 - Skipping existing: mt_404794804
93/557 - Skipping existing: mt_585265483
94/557 - Skipping existing: mt_979109272
95/557 - Skipping existing: mt_252632756
96/557 - Skipping existing: mt_363853165
97/557 - Skipping existing: mt_404794852
98/557 - Skipping existing: mt_010470389
99/557 - Skipping existing: mt_747917544
100/557 - Skipping existing: mt_838528034
101/557 - Skipping existing: mt_252632790
102/557 - Skipping existing: mt_191041695
103/557 - Skipping existing: mt_893929803
104/557 - Skipping existing: mt_460618091
105/557 - Skipping existing: mt_205500279
106/557 - Skipping existing: mt_585265474
107/557 - Skipping existing: mt_979109261
108/557 - Skipping existing: mt_191041639
109/557 - Skipping existing: mt_626386980
110/557 - Skipping existing: mt_404794891
111/557 - Skipping existing: mt_010470373
112/557 - Skipping existing: mt_979109208
113/557 - Skipping existing: mt_838528042
114/557 - Skipping existing: mt_363853153
115/557 - Skipping existing: mt_585265462
116/557 - Skipping existing: mt_626386916
117/557 - Skipping existing: mt_838528588
118/557 - Skipping existing: mt_252632735
119/557 - Skipping existing: mt_191041643
120/557 - Skipping existing: mt_747917511
121/557 - Skipping existing: mt_585265251
122/557 - Skipping existing: mt_191041014
123/557 - Skipping existing: mt_626386365
124/557 - Skipping existing: mt_363853834
125/557 - Skipping existing: mt_404794748
126/557 - Skipping existing: mt_010470404
127/557 - Skipping existing: mt_979109197
128/557 - Skipping existing: mt_252632629
129/557 - Skipping existing: mt_010470452
130/557 - Skipping existing: mt_838528577
131/557 - Skipping existing: mt_404794727
132/557 - Skipping existing: mt_585265298
133/557 - Skipping existing: mt_252632613
134/557 - Skipping existing: mt_191041071
135/557 - Skipping existing: mt_747917906
136/557 - Skipping existing: mt_626386309
137/557 - Skipping existing: mt_838528566
138/557 - Skipping existing: mt_979109136
139/557 - Skipping existing: mt_987011920
140/557 - Skipping existing: mt_465856919
141/557 - Skipping existing: mt_363853821
142/557 - Skipping existing: mt_626386353
143/557 - Skipping existing: mt_404794716
144/557 - Skipping existing: mt_585265237
145/557 - Skipping existing: mt_191041068
146/557 - Skipping existing: mt_747917950
147/557 - Skipping existing: mt_363853818
148/557 - Skipping existing: mt_010470491
149/557 - Skipping existing: mt_979109140
150/557 - Skipping existing: mt_252632672
151/557 - Skipping existing: mt_838528500
152/557 - Skipping existing: mt_404794775
153/557 - Skipping existing: mt_010470438
154/557 - Skipping existing: mt_585265246
155/557 - Skipping existing: mt_252632661
156/557 - Skipping existing: mt_363853887
157/557 - Skipping existing: mt_626386394
158/557 - Skipping existing: mt_979109119
159/557 - Skipping existing: mt_191041007
160/557 - Skipping existing: mt_747917995
161/557 - Skipping existing: mt_838528555
162/557 - Skipping existing: mt_626386332
163/557 - Skipping existing: mt_010470447
164/557 - Skipping existing: mt_585265215
165/557 - Skipping existing: mt_979109183
166/557 - Skipping existing: mt_191041056
167/557 - Skipping existing: mt_626386341
168/557 - Skipping existing: mt_404794769
169/557 - Skipping existing: mt_585265289
170/557 - Skipping existing: mt_979109174
171/557 - Skipping existing: mt_252632608
172/557 - Skipping existing: mt_747917939
173/557 - Skipping existing: mt_838528599
174/557 - Skipping existing: mt_191041090
175/557 - Skipping existing: mt_747917943
176/557 - Skipping existing: mt_376588715
177/557 - Skipping existing: mt_734125542
178/557 - Skipping existing: mt_191041035
179/557 - Skipping existing: mt_252632657
180/557 - Skipping existing: mt_838528533
181/557 - Skipping existing: mt_363853860
182/557 - Skipping existing: mt_626386328
183/557 - Skipping existing: mt_010470485
184/557 - Skipping existing: mt_747917924
185/557 - Skipping existing: mt_363853805
186/557 - Skipping existing: mt_404794754
187/557 - Skipping existing: mt_585265273
188/557 - Skipping existing: mt_363853876
189/557 - Skipping existing: mt_010470479
190/557 - Skipping existing: mt_010470410
191/557 - Skipping existing: mt_838528544
192/557 - Skipping existing: mt_404794792
193/557 - Skipping existing: mt_979109101
194/557 - Skipping existing: mt_747917912
195/557 - Skipping existing: mt_626386460
196/557 - Skipping existing: mt_252632696
197/557 - Skipping existing: mt_585265264
198/557 - Skipping existing: mt_252632630
199/557 - Skipping existing: mt_191041049
200/557 - Skipping existing: mt_641649210
201/557 - Skipping existing: mt_465468547
202/557 - Skipping existing: mt_209722969
203/557 - Skipping existing: mt_838528522
204/557 - Skipping existing: mt_363853733
205/557 - Skipping existing: mt_010470203
206/557 - Skipping existing: mt_979109898
207/557 - Skipping existing: mt_252632025
208/557 - Skipping existing: mt_747917371
209/557 - Skipping existing: mt_838528978
210/557 - Skipping existing: mt_010470254
211/557 - Skipping existing: mt_404794641
212/557 - Skipping existing: mt_585265152
213/557 - Skipping existing: mt_191041513
214/557 - Skipping existing: mt_363853744
215/557 - Skipping existing: mt_252632019
216/557 - Skipping existing: mt_585265191
217/557 - Skipping existing: mt_404794628
218/557 - Skipping existing: mt_979109837
219/557 - Skipping existing: mt_747917307
220/557 - Skipping existing: mt_363853722
221/557 - Skipping existing: mt_626386459
222/557 - Skipping existing: mt_404794617
223/557 - Skipping existing: mt_979109846
224/557 - Skipping existing: mt_191041584
225/557 - Skipping existing: mt_838528967
226/557 - Skipping existing: mt_010470292
227/557 - Skipping existing: mt_252632083
228/557 - Skipping existing: mt_585265138
229/557 - Skipping existing: mt_747917356
230/557 - Skipping existing: mt_838528906
231/557 - Skipping existing: mt_191041561
232/557 - Skipping existing: mt_363853711
233/557 - Skipping existing: mt_626386493
234/557 - Skipping existing: mt_404794686
235/557 - Skipping existing: mt_010470231
236/557 - Skipping existing: mt_585265147
237/557 - Skipping existing: mt_252632062
238/557 - Skipping existing: mt_191041508
239/557 - Skipping existing: mt_747917390
240/557 - Skipping existing: mt_979109820
241/557 - Skipping existing: mt_626386434
242/557 - Skipping existing: mt_404794670
243/557 - Skipping existing: mt_010470248
244/557 - Skipping existing: mt_585265126
245/557 - Skipping existing: mt_979109889
246/557 - Skipping existing: mt_252632001
247/557 - Skipping existing: mt_363853788
248/557 - Skipping existing: mt_191041557
249/557 - Skipping existing: mt_838528995
250/557 - Skipping existing: mt_838528950
251/557 - Skipping existing: mt_838528939
252/557 - Skipping existing: mt_010470227
253/557 - Skipping existing: mt_585265185
254/557 - Skipping existing: mt_979109873
255/557 - Skipping existing: mt_191041596
256/557 - Skipping existing: mt_747917349
257/557 - Skipping existing: mt_404794609
258/557 - Skipping existing: mt_404794665
259/557 - Skipping existing: mt_626386421
260/557 - Skipping existing: mt_585265179
261/557 - Skipping existing: mt_363853766
262/557 - Skipping existing: mt_010470280
263/557 - Skipping existing: mt_979109864
264/557 - Skipping existing: mt_252632097
265/557 - Skipping existing: mt_191041530
266/557 - Skipping existing: mt_747917323
267/557 - Skipping existing: mt_838528943
268/557 - Skipping existing: mt_363853700
269/557 - Skipping existing: mt_626386418
270/557 - Skipping existing: mt_404794694
271/557 - Skipping existing: mt_585265163
272/557 - Skipping existing: mt_585265854
273/557 - Skipping existing: mt_747917335
274/557 - Skipping existing: mt_010470275
275/557 - Skipping existing: mt_979109802
276/557 - Skipping existing: mt_252632036
277/557 - Skipping existing: mt_191041545
278/557 - Skipping existing: mt_747917314
279/557 - Skipping existing: mt_838528924
280/557 - Skipping existing: mt_363853755
281/557 - Skipping existing: mt_626386266
282/557 - Skipping existing: mt_404794042
283/557 - Skipping existing: mt_010470109
284/557 - Skipping existing: mt_252632520
285/557 - Skipping existing: mt_979109791
286/557 - Skipping existing: mt_191041919
287/557 - Skipping existing: mt_747917472
288/557 - Skipping existing: mt_838528382
289/557 - Skipping existing: mt_363853643
290/557 - Skipping existing: mt_404794021
291/557 - Skipping existing: mt_010470153
292/557 - Skipping existing: mt_979109738
293/557 - Skipping existing: mt_252632515
294/557 - Skipping existing: mt_626386200
295/557 - Skipping existing: mt_191041983
296/557 - Skipping existing: mt_585265892
297/557 - Skipping existing: mt_747917461
298/557 - Skipping existing: mt_363853624
299/557 - Skipping existing: mt_626386255
300/557 - Skipping existing: mt_585265831
301/557 - Skipping existing: mt_979109747
302/557 - Skipping existing: mt_252632589
303/557 - Skipping existing: mt_747917457
304/557 - Skipping existing: mt_404794018
305/557 - Skipping existing: mt_010470194
306/557 - Skipping existing: mt_191041974
307/557 - Skipping existing: mt_838528368
308/557 - Skipping existing: mt_027705559
309/557 - Skipping existing: mt_363853612
310/557 - Skipping existing: mt_010470132
311/557 - Skipping existing: mt_252632573
312/557 - Skipping existing: mt_191041901
313/557 - Skipping existing: mt_838528356
314/557 - Skipping existing: mt_363853681
315/557 - Skipping existing: mt_626386233
316/557 - Skipping existing: mt_404794087
317/557 - Skipping existing: mt_585265848
318/557 - Skipping existing: mt_979109726
319/557 - Skipping existing: mt_838528307
320/557 - Skipping existing: mt_747917496
321/557 - Skipping existing: mt_404794076
322/557 - Skipping existing: mt_010470141
323/557 - Skipping existing: mt_585265827
324/557 - Skipping existing: mt_747917430
325/557 - Skipping existing: mt_979109710
326/557 - Skipping existing: mt_252632502
327/557 - Skipping existing: mt_191041958
328/557 - Skipping existing: mt_838528390
329/557 - Skipping existing: mt_363853678
330/557 - Skipping existing: mt_626386244
331/557 - Skipping existing: mt_404794060
332/557 - Skipping existing: mt_010470128
333/557 - Skipping existing: mt_979109779
334/557 - Skipping existing: mt_252632551
335/557 - Skipping existing: mt_747917445
336/557 - Skipping existing: mt_838528335
337/557 - Skipping existing: mt_363853667
338/557 - Skipping existing: mt_585265875
339/557 - Skipping existing: mt_585265816
340/557 - Skipping existing: mt_191041997
341/557 - Skipping existing: mt_404794005
342/557 - Skipping existing: mt_375325204
343/557 - Skipping existing: mt_980093331
344/557 - Skipping existing: mt_010470117
345/557 - Skipping existing: mt_252632598
346/557 - Skipping existing: mt_363853606
347/557 - Skipping existing: mt_626386211
348/557 - Skipping existing: mt_404794059
349/557 - Skipping existing: mt_010470170
350/557 - Skipping existing: mt_191041940
351/557 - Skipping existing: mt_191041936
352/557 - Skipping existing: mt_747917429
353/557 - Skipping existing: mt_585265869
354/557 - Skipping existing: mt_838528349
355/557 - Skipping existing: mt_404794544
356/557 - Skipping existing: mt_747917413
357/557 - Skipping existing: mt_838528323
358/557 - Skipping existing: mt_979109692
359/557 - Skipping existing: mt_747917274
360/557 - Skipping existing: mt_585265753
361/557 - Skipping existing: mt_252632537
362/557 - Skipping existing: mt_363853650
363/557 - Skipping existing: mt_626386288
364/557 - Skipping existing: mt_010470805
365/557 - Skipping existing: mt_252632926
366/557 - Skipping existing: mt_838528484
367/557 - Skipping existing: mt_191041315
368/557 - Skipping existing: mt_626386106
369/557 - Skipping existing: mt_404794522
370/557 - Skipping existing: mt_010470859
371/557 - Skipping existing: mt_585265794
372/557 - Skipping existing: mt_979109631
373/557 - Skipping existing: mt_191041389
374/557 - Skipping existing: mt_626386150
375/557 - Skipping existing: mt_252632910
376/557 - Skipping existing: mt_838528472
377/557 - Skipping existing: mt_363853023
378/557 - Skipping existing: mt_363853035
379/557 - Skipping existing: mt_747917262
380/557 - Skipping existing: mt_404794511
381/557 - Skipping existing: mt_010470893
382/557 - Skipping existing: mt_585265732
383/557 - Skipping existing: mt_979109648
384/557 - Skipping existing: mt_191041373
385/557 - Skipping existing: mt_747917201
386/557 - Skipping existing: mt_838528408
387/557 - Skipping existing: mt_363853014
388/557 - Skipping existing: mt_626386195
389/557 - Skipping existing: mt_010470834
390/557 - Skipping existing: mt_252632985
391/557 - Skipping existing: mt_191041364
392/557 - Skipping existing: mt_404794588
393/557 - Skipping existing: mt_585265741
394/557 - Skipping existing: mt_979109627
395/557 - Skipping existing: mt_404794577
396/557 - Skipping existing: mt_252632979
397/557 - Skipping existing: mt_747917297
398/557 - Skipping existing: mt_838528457
399/557 - Skipping existing: mt_363853082
400/557 - Skipping existing: mt_626386139
401/557 - Skipping existing: mt_010470842
402/557 - Skipping existing: mt_585265728
403/557 - Skipping existing: mt_191041351
404/557 - Skipping existing: mt_747917236
405/557 - Skipping existing: mt_838528496
406/557 - Skipping existing: mt_363853071
407/557 - Skipping existing: mt_626386143
408/557 - Skipping existing: mt_010470821
409/557 - Skipping existing: mt_979109680
410/557 - Skipping existing: mt_838528430
411/557 - Skipping existing: mt_979109616
412/557 - Skipping existing: mt_404794566
413/557 - Skipping existing: mt_585265717
414/557 - Skipping existing: mt_252632963
415/557 - Skipping existing: mt_252632952
416/557 - Skipping existing: mt_363853068
417/557 - Skipping existing: mt_626386124
418/557 - Skipping existing: mt_404794500
419/557 - Skipping existing: mt_585265786
420/557 - Skipping existing: mt_979109669
421/557 - Skipping existing: mt_191041337
422/557 - Skipping existing: mt_838528445
423/557 - Skipping existing: mt_747917240
424/557 - Skipping existing: mt_010470818
425/557 - Skipping existing: mt_747917225
426/557 - Skipping existing: mt_191041398
427/557 - Skipping existing: mt_626386112
428/557 - Skipping existing: mt_252632991
429/557 - Skipping existing: mt_363853007
430/557 - Skipping existing: mt_404794555
431/557 - Skipping existing: mt_747917219
432/557 - Skipping existing: mt_010470887
433/557 - Skipping existing: mt_585265765
434/557 - Skipping existing: mt_979109603
435/557 - Skipping existing: mt_252632938
436/557 - Skipping existing: mt_191041346
437/557 - Skipping existing: mt_838528429
438/557 - Skipping existing: mt_404794599
439/557 - Skipping existing: mt_838528283
440/557 - Skipping existing: mt_363853056
441/557 - Skipping existing: mt_626386181
442/557 - Skipping existing: mt_979109094
443/557 - Skipping existing: mt_191041410
444/557 - Skipping existing: mt_363853530
445/557 - Skipping existing: mt_626386868
446/557 - Skipping existing: mt_010470755
447/557 - Skipping existing: mt_010470700
448/557 - Skipping existing: mt_585265659
449/557 - Skipping existing: mt_252632327
450/557 - Skipping existing: mt_747917173
451/557 - Skipping existing: mt_626386856
452/557 - Skipping existing: mt_585265693
453/557 - Skipping existing: mt_979109032
454/557 - Skipping existing: mt_191041485
455/557 - Skipping existing: mt_747917164
456/557 - Skipping existing: mt_838528274
457/557 - Skipping existing: mt_404794912
458/557 - Skipping existing: mt_010470799
459/557 - Skipping existing: mt_252632316
460/557 - Skipping existing: mt_363853545
461/557 - Skipping existing: mt_747917102
462/557 - Skipping existing: mt_404794924
463/557 - Skipping existing: mt_191041479
464/557 - Skipping existing: mt_979109041
465/557 - Skipping existing: mt_252632380
466/557 - Skipping existing: mt_838528262
467/557 - Skipping existing: mt_404794981
468/557 - Skipping existing: mt_585265634
469/557 - Skipping existing: mt_363853513
470/557 - Skipping existing: mt_626386890
471/557 - Skipping existing: mt_010470733
472/557 - Skipping existing: mt_585265642
473/557 - Skipping existing: mt_979109028
474/557 - Skipping existing: mt_252632375
475/557 - Skipping existing: mt_838528258
476/557 - Skipping existing: mt_363853584
477/557 - Skipping existing: mt_404794978
478/557 - Skipping existing: mt_010470744

In [130]:
for season in [
    "2020_21",
    "2021_22",
    "2022_23",
    "2023_24",
    "2024_25",
    "2025_26"
]:
    files = list(CHAMPIONSHIP_SEASON_DIRS[season].glob("*.json"))
    print(season, len(files))

2020_21 557
2021_22 557
2022_23 557
2023_24 557
2024_25 557
2025_26 557

In [131]:
# Adding Champions League Seasons

CHAMPIONS_LEAGUE_ID = "comp_3498"

CHAMPIONS_LEAGUE_SEASONS = {
    "2026_27": "sn_8406903",
    "2025_26": "sn_5783461",
    "2024_25": "sn_0872372",
    "2023_24": "sn_939193",
    "2022_23": "sn_327866",
    "2021_22": "sn_699943",
    "2020_21": "sn_388063"
}

In [132]:
# Create a folder for Champions League matches

CHAMPIONS_LEAGUE_DIR = RAW_MATCH_DIR / "champions_league"

CHAMPIONS_LEAGUE_SEASON_DIRS = {}

for season_name in CHAMPIONS_LEAGUE_SEASONS:
    season_dir = CHAMPIONS_LEAGUE_DIR / season_name
    season_dir.mkdir(parents=True, exist_ok=True)

    CHAMPIONS_LEAGUE_SEASON_DIRS[season_name] = season_dir

print(CHAMPIONS_LEAGUE_SEASON_DIRS)

{'2026_27': WindowsPath('../data/raw/matches/champions_league/2026_27'), '2025_26': WindowsPath('../data/raw/matches/champions_league/2025_26'), '2024_25': WindowsPath('../data/raw/matches/champions_league/2024_25'), '2023_24': WindowsPath('../data/raw/matches/champions_league/2023_24'), '2022_23': WindowsPath('../data/raw/matches/champions_league/2022_23'), '2021_22': WindowsPath('../data/raw/matches/champions_league/2021_22'), '2020_21': WindowsPath('../data/raw/matches/champions_league/2020_21')}

In [ ]:
# Inspect 2023/24 season (Before format change)

ucl_2023_24_matches = get_all_season_matches(
    CHAMPIONS_LEAGUE_ID,
    CHAMPIONS_LEAGUE_SEASONS["2023_24"]
)

print("Total matches returned:", len(ucl_2023_24_matches))

Total matches returned: 214

In [134]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in ucl_2023_24_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in ucl_2023_24_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in ucl_2023_24_matches
)))

Statuses:
Counter({'finished': 214})

Stages:
Counter({None: 96, 'qualifying': 74, 'round_of_16': 28, 'quarter_final': 8, 'semi_final': 6, 'final': 2})

Unique IDs: 214

In [135]:
stage_examples = {}

for match in ucl_2023_24_matches:
    stage = match.get("stage_name")

    if stage not in stage_examples:
        stage_examples[stage] = match

for stage, match in stage_examples.items():
    print(
        stage,
        "-",
        match["home_team"]["name"],
        "vs",
        match["away_team"]["name"]
    )

final - Borussia Dortmund vs Real Madrid
semi_final - Real Madrid vs FC Bayern München
quarter_final - FC Bayern München vs Arsenal
round_of_16 - Atlético Madrid vs Inter
None - Borussia Dortmund vs Paris Saint-Germain
qualifying - AEK Athens vs GNK Dinamo Zagreb

In [136]:
# Check for Unique IDs

for stage in ["round_of_16", "semi_final", "final"]:
    print(f"\n--- {stage.upper()} ---")

    stage_matches = [
        match for match in ucl_2023_24_matches
        if match.get("stage_name") == stage
    ]

    for match in sorted(stage_matches, key=lambda x: x["utc_date"]):
        print(
            match["utc_date"][:10],
            match["id"],
            match["home_team"]["name"],
            "vs",
            match["away_team"]["name"]
        )

--- ROUND_OF_16 ---
2023-08-22 mt_195770686 Royal Antwerp FC vs AEK Athens
2023-08-22 mt_581327334 Raków Częstochowa vs FC København
2023-08-22 mt_978416441 Rangers vs PSV Eindhoven
2023-08-23 mt_012948955 Sporting Braga vs Panathinaikos
2023-08-23 mt_978416432 Molde FK vs Galatasaray
2023-08-23 mt_743092064 Maccabi Haifa vs Young Boys
2023-08-29 mt_406170250 Young Boys vs Maccabi Haifa
2023-08-29 mt_978417309 Galatasaray vs Molde FK
2023-08-29 mt_250865131 Panathinaikos vs Sporting Braga
2023-08-30 mt_250886718 AEK Athens vs Royal Antwerp FC
2023-08-30 mt_250869816 PSV Eindhoven vs Rangers
2023-08-30 mt_195703785 FC København vs Raków Częstochowa
2024-02-13 mt_749359750 RB Leipzig vs Real Madrid
2024-02-13 mt_407687480 FC København vs Manchester City
2024-02-14 mt_971821919 Lazio vs FC Bayern München
2024-02-14 mt_835905855 Paris Saint-Germain vs Real Sociedad
2024-02-20 mt_190560107 PSV Eindhoven vs Borussia Dortmund
2024-02-20 mt_749359795 Inter vs Atlético Madrid
2024-02-21 mt_368718387 Napoli vs Barcelona
2024-02-21 mt_623493632 FC Porto vs Arsenal
2024-03-05 mt_256076229 Real Sociedad vs Paris Saint-Germain
2024-03-05 mt_623493609 FC Bayern München vs Lazio
2024-03-06 mt_407687427 Manchester City vs FC København
2024-03-06 mt_014234052 Real Madrid vs RB Leipzig
2024-03-12 mt_407687448 Arsenal vs FC Porto
2024-03-12 mt_971821997 Barcelona vs Napoli
2024-03-13 mt_749359767 Atlético Madrid vs Inter
2024-03-13 mt_368718342 Borussia Dortmund vs PSV Eindhoven

--- SEMI_FINAL ---
2023-06-27 mt_406651497 Atlètic Club Escaldes vs FK Budućnost Podgorica
2023-06-27 mt_624415689 SP Tre Penne vs Breidablik Kópavogur
2024-04-30 mt_623614610 FC Bayern München vs Real Madrid
2024-05-01 mt_407456451 Borussia Dortmund vs Paris Saint-Germain
2024-05-07 mt_368307303 Paris Saint-Germain vs Borussia Dortmund
2024-05-08 mt_835849832 Real Madrid vs FC Bayern München

--- FINAL ---
2023-06-30 mt_012258082 FK Budućnost Podgorica vs Breidablik Kópavogur
2024-06-01 mt_749723742 Borussia Dortmund vs Real Madrid

In [138]:
# Create a collector for Champions League seasons

def collect_champions_league_baseline_data(season_name, matches):
    season_dir = CHAMPIONS_LEAGUE_SEASON_DIRS[season_name]

    total_matches = len(matches)

    for i, match in enumerate(matches, start=1):
        match_id = match["id"]
        file_path = season_dir / f"{match_id}.json"

        if file_path.exists():
            print(f"{i}/{total_matches} - Skipping existing: {match_id}")
            continue

        print(f"{i}/{total_matches} - Collecting: {match_id}")

        match_data = get_baseline_match_data(match_id)

        if match_data is None:
            print("Skipped:", match_id)
            continue

        save_match_data(
            match_id,
            match_data,
            season_dir
        )

        time.sleep(1)

In [139]:
# Collect 2023_24 CL season

collect_champions_league_baseline_data(
    "2023_24",
    ucl_2023_24_matches
)

1/214 - Collecting: mt_749723742
2/214 - Collecting: mt_835849832
3/214 - Collecting: mt_368307303
4/214 - Collecting: mt_407456451
5/214 - Collecting: mt_623614610
6/214 - Collecting: mt_014082083
7/214 - Collecting: mt_971968968
8/214 - Collecting: mt_256290295
9/214 - Collecting: mt_749676092
10/214 - Collecting: mt_190135133
11/214 - Collecting: mt_256121860
12/214 - Collecting: mt_190818709
13/214 - Collecting: mt_835787652
14/214 - Collecting: mt_749359767
15/214 - Collecting: mt_368718342
16/214 - Collecting: mt_407687448
17/214 - Collecting: mt_971821997
18/214 - Collecting: mt_407687427
19/214 - Collecting: mt_014234052
20/214 - Collecting: mt_256076229
21/214 - Collecting: mt_623493609
22/214 - Collecting: mt_368718387
23/214 - Collecting: mt_623493632
24/214 - Collecting: mt_190560107
25/214 - Collecting: mt_749359795
26/214 - Collecting: mt_971821919
27/214 - Collecting: mt_835905855
28/214 - Collecting: mt_749359750
29/214 - Collecting: mt_407687480
30/214 - Collecting: mt_839758964
31/214 - Collecting: mt_195801503
32/214 - Collecting: mt_406274668
33/214 - Collecting: mt_978319887
34/214 - Collecting: mt_250162009
35/214 - Collecting: mt_195801554
36/214 - Collecting: mt_839758998
37/214 - Collecting: mt_581925111
38/214 - Collecting: mt_367483725
39/214 - Collecting: mt_624036430
40/214 - Collecting: mt_406274671
41/214 - Collecting: mt_581925122
42/214 - Collecting: mt_978319818
43/214 - Collecting: mt_367483774
44/214 - Collecting: mt_250162065
45/214 - Collecting: mt_624036445
46/214 - Collecting: mt_250162086
47/214 - Collecting: mt_743697304
48/214 - Collecting: mt_195801569
49/214 - Collecting: mt_012540243
50/214 - Collecting: mt_743697391
51/214 - Collecting: mt_012540224
52/214 - Collecting: mt_195801575
53/214 - Collecting: mt_978319821
54/214 - Collecting: mt_624036496
55/214 - Collecting: mt_406274682
56/214 - Collecting: mt_012540239
57/214 - Collecting: mt_250162070
58/214 - Collecting: mt_743697352
59/214 - Collecting: mt_839758902
60/214 - Collecting: mt_581925144
61/214 - Collecting: mt_367483783
62/214 - Collecting: mt_581925881
63/214 - Collecting: mt_978319777
64/214 - Collecting: mt_839758326
65/214 - Collecting: mt_406274096
66/214 - Collecting: mt_012540171
67/214 - Collecting: mt_978319639
68/214 - Collecting: mt_250162593
69/214 - Collecting: mt_367483047
70/214 - Collecting: mt_978319744
71/214 - Collecting: mt_978319722
72/214 - Collecting: mt_743697454
73/214 - Collecting: mt_624036236
74/214 - Collecting: mt_250162560
75/214 - Collecting: mt_250162505
76/214 - Collecting: mt_012540135
77/214 - Collecting: mt_581925812
78/214 - Collecting: mt_250162587
79/214 - Collecting: mt_406274084
80/214 - Collecting: mt_367483615
81/214 - Collecting: mt_406274072
82/214 - Collecting: mt_978319788
83/214 - Collecting: mt_195801953
84/214 - Collecting: mt_581925839
85/214 - Collecting: mt_624036258
86/214 - Collecting: mt_195801994
87/214 - Collecting: mt_406274057
88/214 - Collecting: mt_978319766
89/214 - Collecting: mt_743697416
90/214 - Collecting: mt_581925867
91/214 - Collecting: mt_250162911
92/214 - Collecting: mt_250162559
93/214 - Collecting: mt_195801387
94/214 - Collecting: mt_743697403
95/214 - Collecting: mt_367483620
96/214 - Collecting: mt_581925824
97/214 - Collecting: mt_978319711
98/214 - Collecting: mt_839758338
99/214 - Collecting: mt_624036225
100/214 - Collecting: mt_195801970
101/214 - Collecting: mt_195801965
102/214 - Collecting: mt_743697427
103/214 - Collecting: mt_624036219
104/214 - Collecting: mt_367483651
105/214 - Collecting: mt_978319700
106/214 - Collecting: mt_250162922
107/214 - Collecting: mt_839758475
108/214 - Collecting: mt_581925878
109/214 - Collecting: mt_581925756
110/214 - Collecting: mt_839758347
111/214 - Collecting: mt_012540182
112/214 - Collecting: mt_624036283
113/214 - Collecting: mt_195801318
114/214 - Collecting: mt_743697265
115/214 - Collecting: mt_624036102
116/214 - Collecting: mt_367483602
117/214 - Collecting: mt_195801941
118/214 - Collecting: mt_581925843
119/214 - Collecting: mt_250162576
120/214 - Collecting: mt_012540149
121/214 - Collecting: mt_367483673
122/214 - Collecting: mt_624036240
123/214 - Collecting: mt_743697431
124/214 - Collecting: mt_839758304
125/214 - Collecting: mt_367483664
126/214 - Collecting: mt_250886718
127/214 - Collecting: mt_250869816
128/214 - Collecting: mt_195703785
129/214 - Collecting: mt_406170250
130/214 - Collecting: mt_978417309
131/214 - Collecting: mt_250865131
132/214 - Collecting: mt_012948955
133/214 - Collecting: mt_978416432
134/214 - Collecting: mt_743092064
135/214 - Collecting: mt_195770686
136/214 - Collecting: mt_581327334
137/214 - Collecting: mt_978416441
138/214 - Collecting: mt_743016244
139/214 - Collecting: mt_406816546
140/214 - Collecting: mt_624950486
141/214 - Collecting: mt_624949890
142/214 - Collecting: mt_195678535
143/214 - Collecting: mt_195678996
144/214 - Collecting: mt_250798235
145/214 - Collecting: mt_367124705
146/214 - Collecting: mt_012395279
147/214 - Collecting: mt_978243801
148/214 - Collecting: mt_367124666
149/214 - Collecting: mt_406812692
150/214 - Collecting: mt_581439164
151/214 - Collecting: mt_012392801
152/214 - Collecting: mt_839067944
153/214 - Collecting: mt_743520711
154/214 - Collecting: mt_250781030
155/214 - Collecting: mt_367162723
156/214 - Collecting: mt_195678549
157/214 - Collecting: mt_624950221
158/214 - Collecting: mt_839587969
159/214 - Collecting: mt_624360451
160/214 - Collecting: mt_367834747
161/214 - Collecting: mt_406742625
162/214 - Collecting: mt_367834726
163/214 - Collecting: mt_978812266
164/214 - Collecting: mt_978193843
165/214 - Collecting: mt_581259149
166/214 - Collecting: mt_581259135
167/214 - Collecting: mt_624360402
168/214 - Collecting: mt_012405257
169/214 - Collecting: mt_581124478
170/214 - Collecting: mt_250621088
171/214 - Collecting: mt_195018576
172/214 - Collecting: mt_978193824
173/214 - Collecting: mt_012405230
174/214 - Collecting: mt_581259797
175/214 - Collecting: mt_406742526
176/214 - Collecting: mt_406742619
177/214 - Collecting: mt_195509360
178/214 - Collecting: mt_012405851
179/214 - Collecting: mt_743394253
180/214 - Collecting: mt_743976309
181/214 - Collecting: mt_839585733
182/214 - Collecting: mt_367774351
183/214 - Collecting: mt_406662457
184/214 - Collecting: mt_743336716
185/214 - Collecting: mt_624440640
186/214 - Collecting: mt_012225082
187/214 - Collecting: mt_581119578
188/214 - Collecting: mt_250001293
189/214 - Collecting: mt_367800408
190/214 - Collecting: mt_839997852
191/214 - Collecting: mt_012225014
192/214 - Collecting: mt_624440619
193/214 - Collecting: mt_012225023
194/214 - Collecting: mt_978883977
195/214 - Collecting: mt_978883966
196/214 - Collecting: mt_195558141
197/214 - Collecting: mt_743336670
198/214 - Collecting: mt_250001259
199/214 - Collecting: mt_839997826
200/214 - Collecting: mt_195558818
201/214 - Collecting: mt_406662461
202/214 - Collecting: mt_406755250
203/214 - Collecting: mt_367774373
204/214 - Collecting: mt_406662496
205/214 - Collecting: mt_250001122
206/214 - Collecting: mt_406662408
207/214 - Collecting: mt_012225071
208/214 - Collecting: mt_581119567
209/214 - Collecting: mt_624440683
210/214 - Collecting: mt_978883900
211/214 - Collecting: mt_581119581
212/214 - Collecting: mt_012258082
213/214 - Collecting: mt_624415689
214/214 - Collecting: mt_406651497

In [140]:
saved_ucl_2023_24 = list(
    CHAMPIONS_LEAGUE_SEASON_DIRS["2023_24"].glob("*.json")
)

print("Saved UCL 2023/24 files:", len(saved_ucl_2023_24))

Saved UCL 2023/24 files: 214

In [141]:
# Collect 2022/23 CL season

ucl_2022_23_matches = get_all_season_matches(
    CHAMPIONS_LEAGUE_ID,
    CHAMPIONS_LEAGUE_SEASONS["2022_23"]
)

print("Total matches returned:", len(ucl_2022_23_matches))

Total matches returned: 214

In [142]:
collect_champions_league_baseline_data(
    "2022_23",
    ucl_2022_23_matches
)

1/214 - Collecting: mt_012183397
2/214 - Collecting: mt_367054855
3/214 - Collecting: mt_624180554
4/214 - Collecting: mt_195347766
5/214 - Collecting: mt_195347788
6/214 - Collecting: mt_011034475
7/214 - Collecting: mt_977921102
8/214 - Collecting: mt_588542263
9/214 - Collecting: mt_255276636
10/214 - Collecting: mt_744759914
11/214 - Collecting: mt_366318855
12/214 - Collecting: mt_199160045
13/214 - Collecting: mt_833805524
14/214 - Collecting: mt_833524407
15/214 - Collecting: mt_622381199
16/214 - Collecting: mt_199043374
17/214 - Collecting: mt_011478832
18/214 - Collecting: mt_366850012
19/214 - Collecting: mt_255639989
20/214 - Collecting: mt_744912257
21/214 - Collecting: mt_400795587
22/214 - Collecting: mt_977106626
23/214 - Collecting: mt_622381133
24/214 - Collecting: mt_199043301
25/214 - Collecting: mt_833524456
26/214 - Collecting: mt_255639973
27/214 - Collecting: mt_366850081
28/214 - Collecting: mt_588267748
29/214 - Collecting: mt_744912296
30/214 - Collecting: mt_366504007
31/214 - Collecting: mt_622810112
32/214 - Collecting: mt_011785887
33/214 - Collecting: mt_977063603
34/214 - Collecting: mt_199438346
35/214 - Collecting: mt_833247429
36/214 - Collecting: mt_400952555
37/214 - Collecting: mt_255391938
38/214 - Collecting: mt_588679765
39/214 - Collecting: mt_744126219
40/214 - Collecting: mt_366504056
41/214 - Collecting: mt_622810181
42/214 - Collecting: mt_400952599
43/214 - Collecting: mt_011785700
44/214 - Collecting: mt_833247445
45/214 - Collecting: mt_588679659
46/214 - Collecting: mt_199438485
47/214 - Collecting: mt_833247274
48/214 - Collecting: mt_400952912
49/214 - Collecting: mt_744126102
50/214 - Collecting: mt_366504513
51/214 - Collecting: mt_400952981
52/214 - Collecting: mt_255391316
53/214 - Collecting: mt_622810890
54/214 - Collecting: mt_744126164
55/214 - Collecting: mt_366504545
56/214 - Collecting: mt_011785799
57/214 - Collecting: mt_977063041
58/214 - Collecting: mt_255391380
59/214 - Collecting: mt_833247262
60/214 - Collecting: mt_588679634
61/214 - Collecting: mt_199438479
62/214 - Collecting: mt_588679642
63/214 - Collecting: mt_977063028
64/214 - Collecting: mt_833247258
65/214 - Collecting: mt_977063017
66/214 - Collecting: mt_199438404
67/214 - Collecting: mt_366504572
68/214 - Collecting: mt_744126137
69/214 - Collecting: mt_400952967
70/214 - Collecting: mt_622810856
71/214 - Collecting: mt_199438463
72/214 - Collecting: mt_744126151
73/214 - Collecting: mt_400952978
74/214 - Collecting: mt_011785744
75/214 - Collecting: mt_255391369
76/214 - Collecting: mt_011785733
77/214 - Collecting: mt_255391375
78/214 - Collecting: mt_366504584
79/214 - Collecting: mt_622810835
80/214 - Collecting: mt_011785722
81/214 - Collecting: mt_977063086
82/214 - Collecting: mt_255391303
83/214 - Collecting: mt_833247236
84/214 - Collecting: mt_833247297
85/214 - Collecting: mt_622810849
86/214 - Collecting: mt_588679618
87/214 - Collecting: mt_199438491
88/214 - Collecting: mt_744126146
89/214 - Collecting: mt_622810823
90/214 - Collecting: mt_400952906
91/214 - Collecting: mt_011785711
92/214 - Collecting: mt_588679621
93/214 - Collecting: mt_366504561
94/214 - Collecting: mt_011785788
95/214 - Collecting: mt_255391331
96/214 - Collecting: mt_199438447
97/214 - Collecting: mt_011785777
98/214 - Collecting: mt_977064993
99/214 - Collecting: mt_255398228
100/214 - Collecting: mt_366502336
101/214 - Collecting: mt_400952995
102/214 - Collecting: mt_199437116
103/214 - Collecting: mt_400952950
104/214 - Collecting: mt_588679676
105/214 - Collecting: mt_744126115
106/214 - Collecting: mt_366504557
107/214 - Collecting: mt_622810882
108/214 - Collecting: mt_977063009
109/214 - Collecting: mt_833247225
110/214 - Collecting: mt_977064934
111/214 - Collecting: mt_833246873
112/214 - Collecting: mt_366502340
113/214 - Collecting: mt_622815608
114/214 - Collecting: mt_400951414
115/214 - Collecting: mt_011789095
116/214 - Collecting: mt_588673555
117/214 - Collecting: mt_011789050
118/214 - Collecting: mt_744120779
119/214 - Collecting: mt_833246889
120/214 - Collecting: mt_622815661
121/214 - Collecting: mt_400951449
122/214 - Collecting: mt_255398217
123/214 - Collecting: mt_744120763
124/214 - Collecting: mt_588673599
125/214 - Collecting: mt_199437180
126/214 - Collecting: mt_587998921
127/214 - Collecting: mt_193889838
128/214 - Collecting: mt_742697745
129/214 - Collecting: mt_587998976
130/214 - Collecting: mt_405225178
131/214 - Collecting: mt_621001961
132/214 - Collecting: mt_587997321
133/214 - Collecting: mt_405225849
134/214 - Collecting: mt_018558944
135/214 - Collecting: mt_621001535
136/214 - Collecting: mt_742662037
137/214 - Collecting: mt_834758757
138/214 - Collecting: mt_259880788
139/214 - Collecting: mt_621021953
140/214 - Collecting: mt_193775676
141/214 - Collecting: mt_742642011
142/214 - Collecting: mt_018583851
143/214 - Collecting: mt_621013634
144/214 - Collecting: mt_193893743
145/214 - Collecting: mt_587974736
146/214 - Collecting: mt_587972526
147/214 - Collecting: mt_018518391
148/214 - Collecting: mt_976362629
149/214 - Collecting: mt_405205816
150/214 - Collecting: mt_259159729
151/214 - Collecting: mt_193893614
152/214 - Collecting: mt_976376240
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
153/214 - Collecting: mt_405257470
154/214 - Collecting: mt_976448224
155/214 - Collecting: mt_193775660
156/214 - Collecting: mt_587974797
157/214 - Collecting: mt_976361989
158/214 - Collecting: mt_193080603
159/214 - Collecting: mt_193731687
160/214 - Collecting: mt_976461624
161/214 - Collecting: mt_834645403
162/214 - Collecting: mt_834575098
163/214 - Collecting: mt_259892711
164/214 - Collecting: mt_259896977
165/214 - Collecting: mt_193730360
166/214 - Collecting: mt_976469239
167/214 - Collecting: mt_018985042
168/214 - Collecting: mt_742029253
169/214 - Collecting: mt_742969591
170/214 - Collecting: mt_587379528
171/214 - Collecting: mt_360203147
172/214 - Collecting: mt_360848174
173/214 - Collecting: mt_018454324
174/214 - Collecting: mt_587372723
175/214 - Collecting: mt_360208085
176/214 - Collecting: mt_834648075
177/214 - Collecting: mt_405157574
178/214 - Collecting: mt_405727868
179/214 - Collecting: mt_742027565
180/214 - Collecting: mt_621513198
181/214 - Collecting: mt_018984845
182/214 - Collecting: mt_405729568
183/214 - Collecting: mt_742961252
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
184/214 - Collecting: mt_742961291
185/214 - Collecting: mt_976130642
186/214 - Collecting: mt_405729582
187/214 - Collecting: mt_405729571
188/214 - Collecting: mt_193653357
189/214 - Collecting: mt_360845025
190/214 - Collecting: mt_976130618
191/214 - Collecting: mt_259613965
192/214 - Collecting: mt_193084303
193/214 - Collecting: mt_834572402
194/214 - Collecting: mt_018457843
195/214 - Collecting: mt_587296722
196/214 - Collecting: mt_834572464
197/214 - Collecting: mt_193084369
198/214 - Collecting: mt_587296744
199/214 - Collecting: mt_834572498
200/214 - Collecting: mt_742961204
201/214 - Collecting: mt_259613986
202/214 - Collecting: mt_018457839
203/214 - Collecting: mt_621308145
204/214 - Collecting: mt_360845083
205/214 - Collecting: mt_360845074
206/214 - Collecting: mt_621308196
207/214 - Collecting: mt_976130621
208/214 - Collecting: mt_621308130
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
209/214 - Collecting: mt_259613970
210/214 - Collecting: mt_834094495
211/214 - Collecting: mt_193084375
212/214 - Collecting: mt_587478776
213/214 - Collecting: mt_621392336
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
214/214 - Collecting: mt_405780772
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']

In [143]:
saved_ucl_2022_23 = list(
    CHAMPIONS_LEAGUE_SEASON_DIRS["2022_23"].glob("*.json")
)

print("Saved UCL 2022/23 files:", len(saved_ucl_2022_23))

Saved UCL 2022/23 files: 214

In [144]:
# Collect 2021/22 CL season

ucl_2021_22_matches = get_all_season_matches(
    CHAMPIONS_LEAGUE_ID,
    CHAMPIONS_LEAGUE_SEASONS["2021_22"]
)

print("Total matches returned:", len(ucl_2021_22_matches))

Total matches returned: 218

In [145]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in ucl_2021_22_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in ucl_2021_22_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in ucl_2021_22_matches
)))

Statuses:
Counter({'finished': 218})

Stages:
Counter({None: 96, 'qualifying': 90, 'round_of_16': 16, 'quarter_final': 8, 'semi_final': 6, 'final': 2})

Unique IDs: 218

In [146]:
collect_champions_league_baseline_data(
    "2021_22",
    ucl_2021_22_matches
)

1/218 - Collecting: mt_193598476
2/218 - Collecting: mt_587849297
3/218 - Collecting: mt_742456900
4/218 - Collecting: mt_834307560
5/218 - Collecting: mt_018135451
6/218 - Collecting: mt_018899922
7/218 - Collecting: mt_834466636
8/218 - Collecting: mt_405511106
9/218 - Collecting: mt_018899911
10/218 - Collecting: mt_360022261
11/218 - Collecting: mt_587733387
12/218 - Collecting: mt_193377791
13/218 - Collecting: mt_742200046
14/218 - Collecting: mt_586946873
15/218 - Collecting: mt_253173596
16/218 - Collecting: mt_017537185
17/218 - Collecting: mt_832702344
18/218 - Collecting: mt_832702333
19/218 - Collecting: mt_628098228
20/218 - Collecting: mt_365415660
21/218 - Collecting: mt_628098286
22/218 - Collecting: mt_365415605
23/218 - Collecting: mt_017537179
24/218 - Collecting: mt_194864935
25/218 - Collecting: mt_409289092
26/218 - Collecting: mt_741651443
27/218 - Collecting: mt_741651424
28/218 - Collecting: mt_409289054
29/218 - Collecting: mt_970320762
30/218 - Collecting: mt_970877691
31/218 - Collecting: mt_741344272
32/218 - Collecting: mt_832933468
33/218 - Collecting: mt_365766024
34/218 - Collecting: mt_017211894
35/218 - Collecting: mt_741344257
36/218 - Collecting: mt_628422199
37/218 - Collecting: mt_253055973
38/218 - Collecting: mt_586188754
39/218 - Collecting: mt_194599319
40/218 - Collecting: mt_628422100
41/218 - Collecting: mt_409600521
42/218 - Collecting: mt_409600518
43/218 - Collecting: mt_194599374
44/218 - Collecting: mt_017211853
45/218 - Collecting: mt_741344261
46/218 - Collecting: mt_017211809
47/218 - Collecting: mt_586188792
48/218 - Collecting: mt_253055915
49/218 - Collecting: mt_194599383
50/218 - Collecting: mt_832933407
51/218 - Collecting: mt_970877626
52/218 - Collecting: mt_832933482
53/218 - Collecting: mt_970877638
54/218 - Collecting: mt_253055920
55/218 - Collecting: mt_628422155
56/218 - Collecting: mt_253055989
57/218 - Collecting: mt_365766012
58/218 - Collecting: mt_409600587
59/218 - Collecting: mt_586188748
60/218 - Collecting: mt_365766043
61/218 - Collecting: mt_017211832
62/218 - Collecting: mt_741344296
63/218 - Collecting: mt_017211817
64/218 - Collecting: mt_970877663
65/218 - Collecting: mt_253055937
66/218 - Collecting: mt_628422806
67/218 - Collecting: mt_586188694
68/218 - Collecting: mt_832933449
69/218 - Collecting: mt_970877604
70/218 - Collecting: mt_970877647
71/218 - Collecting: mt_832933490
72/218 - Collecting: mt_741344213
73/218 - Collecting: mt_832933423
74/218 - Collecting: mt_970877031
75/218 - Collecting: mt_194599489
76/218 - Collecting: mt_586188731
77/218 - Collecting: mt_017211828
78/218 - Collecting: mt_832933456
79/218 - Collecting: mt_628422133
80/218 - Collecting: mt_253055902
81/218 - Collecting: mt_586188716
82/218 - Collecting: mt_253055310
83/218 - Collecting: mt_741344162
84/218 - Collecting: mt_970877610
85/218 - Collecting: mt_970877092
86/218 - Collecting: mt_586188775
87/218 - Collecting: mt_194599336
88/218 - Collecting: mt_365766006
89/218 - Collecting: mt_628422188
90/218 - Collecting: mt_253055326
91/218 - Collecting: mt_409600922
92/218 - Collecting: mt_253055998
93/218 - Collecting: mt_017211759
94/218 - Collecting: mt_365766081
95/218 - Collecting: mt_409600576
96/218 - Collecting: mt_586188727
97/218 - Collecting: mt_409600560
98/218 - Collecting: mt_628422111
99/218 - Collecting: mt_409600944
100/218 - Collecting: mt_741344230
101/218 - Collecting: mt_194599415
102/218 - Collecting: mt_194599397
103/218 - Collecting: mt_832933435
104/218 - Collecting: mt_409600505
105/218 - Collecting: mt_741344229
106/218 - Collecting: mt_586188769
107/218 - Collecting: mt_586188653
108/218 - Collecting: mt_365766067
109/218 - Collecting: mt_832933284
110/218 - Collecting: mt_970877679
111/218 - Collecting: mt_253055951
112/218 - Collecting: mt_741344245
113/218 - Collecting: mt_409600559
114/218 - Collecting: mt_017211870
115/218 - Collecting: mt_017211705
116/218 - Collecting: mt_628422122
117/218 - Collecting: mt_365766535
118/218 - Collecting: mt_194599301
119/218 - Collecting: mt_194599358
120/218 - Collecting: mt_628422144
121/218 - Collecting: mt_194599340
122/218 - Collecting: mt_365766050
123/218 - Collecting: mt_741344174
124/218 - Collecting: mt_017211841
125/218 - Collecting: mt_365766078
126/218 - Collecting: mt_970717684
127/218 - Collecting: mt_409070992
128/218 - Collecting: mt_017181285
129/218 - Collecting: mt_253565396
130/218 - Collecting: mt_741494124
131/218 - Collecting: mt_017141779
132/218 - Collecting: mt_194909435
133/218 - Collecting: mt_832353244
134/218 - Collecting: mt_628232886
135/218 - Collecting: mt_253565907
136/218 - Collecting: mt_586828664
137/218 - Collecting: mt_586878173
138/218 - Collecting: mt_253925150
139/218 - Collecting: mt_741274642
140/218 - Collecting: mt_741292525
141/218 - Collecting: mt_586867368
142/218 - Collecting: mt_628281629
143/218 - Collecting: mt_832324627
144/218 - Collecting: mt_409095197
145/218 - Collecting: mt_628131906
146/218 - Collecting: mt_409095407
147/218 - Collecting: mt_365036310
148/218 - Collecting: mt_832483803
149/218 - Collecting: mt_194319899
150/218 - Collecting: mt_970616269
151/218 - Collecting: mt_365650362
152/218 - Collecting: mt_017178972
153/218 - Collecting: mt_365650252
154/218 - Collecting: mt_628281589
155/218 - Collecting: mt_194303637
156/218 - Collecting: mt_832324837
157/218 - Collecting: mt_832483732
158/218 - Collecting: mt_970680606
159/218 - Collecting: mt_017729043
160/218 - Collecting: mt_194398354
161/218 - Collecting: mt_017815824
162/218 - Collecting: mt_628845630
163/218 - Collecting: mt_409961471
164/218 - Collecting: mt_017815812
165/218 - Collecting: mt_586717211
166/218 - Collecting: mt_409569176
167/218 - Collecting: mt_365064062
168/218 - Collecting: mt_194353691
169/218 - Collecting: mt_586789711
170/218 - Collecting: mt_409502507
171/218 - Collecting: mt_253909703
172/218 - Collecting: mt_017828424
173/218 - Collecting: mt_586613522
174/218 - Collecting: mt_741246247
175/218 - Collecting: mt_253951909
176/218 - Collecting: mt_970673687
177/218 - Collecting: mt_253903933
178/218 - Collecting: mt_970084918
179/218 - Collecting: mt_253308265
180/218 - Collecting: mt_628120145
181/218 - Collecting: mt_628120129
182/218 - Collecting: mt_409502568
183/218 - Collecting: mt_628148533
184/218 - Collecting: mt_253390997
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
185/218 - Collecting: mt_017782753
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
186/218 - Collecting: mt_194435330
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
187/218 - Collecting: mt_365507543
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
188/218 - Collecting: mt_628814866
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
189/218 - Collecting: mt_409956921
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
190/218 - Collecting: mt_409956942
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
191/218 - Collecting: mt_741123223
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
192/218 - Collecting: mt_017782875
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
193/218 - Collecting: mt_628835241
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
194/218 - Collecting: mt_628814121
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
195/218 - Collecting: mt_586671779
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
196/218 - Collecting: mt_409956509
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
197/218 - Collecting: mt_628814118
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
198/218 - Collecting: mt_586671763
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
199/218 - Collecting: mt_253390320
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
200/218 - Collecting: mt_970068091
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
201/218 - Collecting: mt_017782880
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
202/218 - Collecting: mt_832249424
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
203/218 - Collecting: mt_017782709
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
204/218 - Collecting: mt_832249282
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
205/218 - Collecting: mt_628814800
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
206/218 - Collecting: mt_365507000
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
207/218 - Collecting: mt_586671654
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
208/218 - Collecting: mt_741123172
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
209/218 - Collecting: mt_409956594
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
210/218 - Collecting: mt_194435419
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
211/218 - Collecting: mt_970068602
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
212/218 - Collecting: mt_365507055
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
213/218 - Collecting: mt_409971069
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
214/218 - Collecting: mt_832249443
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
215/218 - Collecting: mt_586671692
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
216/218 - Collecting: mt_970088111
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
217/218 - Collecting: mt_194430489
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
218/218 - Collecting: mt_586663398
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']

In [147]:
saved_ucl_2021_22 = list(
    CHAMPIONS_LEAGUE_SEASON_DIRS["2021_22"].glob("*.json")
)

print("Saved UCL 2021/22 files:", len(saved_ucl_2021_22))

Saved UCL 2021/22 files: 218

In [148]:
# Collect 2020/21 CL season

ucl_2020_21_matches = get_all_season_matches(
    CHAMPIONS_LEAGUE_ID,
    CHAMPIONS_LEAGUE_SEASONS["2020_21"]
)

print("Total matches returned:", len(ucl_2020_21_matches))

Total matches returned: 177

In [149]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in ucl_2020_21_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in ucl_2020_21_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in ucl_2020_21_matches
)))

Statuses:
Counter({'finished': 177})

Stages:
Counter({None: 96, 'qualifying': 49, 'round_of_16': 16, 'quarter_final': 8, 'semi_final': 6, 'final': 2})

Unique IDs: 177

In [150]:
collect_champions_league_baseline_data(
    "2020_21",
    ucl_2020_21_matches
)

1/177 - Collecting: mt_080078873
2/177 - Collecting: mt_454266877
3/177 - Collecting: mt_616044939
4/177 - Collecting: mt_575911428
5/177 - Collecting: mt_080522342
6/177 - Collecting: mt_454168465
7/177 - Collecting: mt_969482973
8/177 - Collecting: mt_080923027
9/177 - Collecting: mt_575314585
10/177 - Collecting: mt_848690895
11/177 - Collecting: mt_303271377
12/177 - Collecting: mt_727035735
13/177 - Collecting: mt_616549642
14/177 - Collecting: mt_131554189
15/177 - Collecting: mt_727331762
16/177 - Collecting: mt_080227059
17/177 - Collecting: mt_848992872
18/177 - Collecting: mt_454669422
19/177 - Collecting: mt_292003210
20/177 - Collecting: mt_575116594
21/177 - Collecting: mt_969880931
22/177 - Collecting: mt_080227093
23/177 - Collecting: mt_131554173
24/177 - Collecting: mt_969880948
25/177 - Collecting: mt_727331701
26/177 - Collecting: mt_303775323
27/177 - Collecting: mt_616448650
28/177 - Collecting: mt_454669411
29/177 - Collecting: mt_575116532
30/177 - Collecting: mt_292328198
31/177 - Collecting: mt_727170629
32/177 - Collecting: mt_616865011
33/177 - Collecting: mt_575653969
34/177 - Collecting: mt_848286684
35/177 - Collecting: mt_727170062
36/177 - Collecting: mt_454941276
37/177 - Collecting: mt_616865044
38/177 - Collecting: mt_080709541
39/177 - Collecting: mt_292328102
40/177 - Collecting: mt_131417858
41/177 - Collecting: mt_303532467
42/177 - Collecting: mt_080709905
43/177 - Collecting: mt_292328826
44/177 - Collecting: mt_969094304
45/177 - Collecting: mt_848286723
46/177 - Collecting: mt_616865033
47/177 - Collecting: mt_727170630
48/177 - Collecting: mt_616865088
49/177 - Collecting: mt_575653353
50/177 - Collecting: mt_303532235
51/177 - Collecting: mt_616865550
52/177 - Collecting: mt_848286756
53/177 - Collecting: mt_080709528
54/177 - Collecting: mt_969094379
55/177 - Collecting: mt_292328151
56/177 - Collecting: mt_616865022
57/177 - Collecting: mt_080709570
58/177 - Collecting: mt_727170001
59/177 - Collecting: mt_303532214
60/177 - Collecting: mt_848286790
61/177 - Collecting: mt_303532406
62/177 - Collecting: mt_575653927
63/177 - Collecting: mt_303532478
64/177 - Collecting: mt_454941205
65/177 - Collecting: mt_131417789
66/177 - Collecting: mt_303532223
67/177 - Collecting: mt_848286608
68/177 - Collecting: mt_080709517
69/177 - Collecting: mt_454941259
70/177 - Collecting: mt_575653916
71/177 - Collecting: mt_727170613
72/177 - Collecting: mt_454941144
73/177 - Collecting: mt_080709959
74/177 - Collecting: mt_080709993
75/177 - Collecting: mt_575653332
76/177 - Collecting: mt_303532481
77/177 - Collecting: mt_969094310
78/177 - Collecting: mt_131417897
79/177 - Collecting: mt_848286735
80/177 - Collecting: mt_131417836
81/177 - Collecting: mt_575653394
82/177 - Collecting: mt_454941111
83/177 - Collecting: mt_969094448
84/177 - Collecting: mt_848286749
85/177 - Collecting: mt_969094431
86/177 - Collecting: mt_616860535
87/177 - Collecting: mt_292328137
88/177 - Collecting: mt_969094492
89/177 - Collecting: mt_727170074
90/177 - Collecting: mt_616865506
91/177 - Collecting: mt_848286672
92/177 - Collecting: mt_131417840
93/177 - Collecting: mt_292328810
94/177 - Collecting: mt_727170645
95/177 - Collecting: mt_575653975
96/177 - Collecting: mt_969094363
97/177 - Collecting: mt_454941122
98/177 - Collecting: mt_292328885
99/177 - Collecting: mt_131417773
100/177 - Collecting: mt_454941260
101/177 - Collecting: mt_131417715
102/177 - Collecting: mt_616865595
103/177 - Collecting: mt_454941188
104/177 - Collecting: mt_080709934
105/177 - Collecting: mt_969094427
106/177 - Collecting: mt_292328879
107/177 - Collecting: mt_727170097
108/177 - Collecting: mt_575653341
109/177 - Collecting: mt_131417764
110/177 - Collecting: mt_303531433
111/177 - Collecting: mt_616869060
112/177 - Collecting: mt_080703503
113/177 - Collecting: mt_292327125
114/177 - Collecting: mt_131416813
115/177 - Collecting: mt_303531444
116/177 - Collecting: mt_454948241
117/177 - Collecting: mt_969092398
118/177 - Collecting: mt_131416149
119/177 - Collecting: mt_727175712
120/177 - Collecting: mt_848280822
121/177 - Collecting: mt_575654952
122/177 - Collecting: mt_727175671
123/177 - Collecting: mt_575654938
124/177 - Collecting: mt_969092901
125/177 - Collecting: mt_292327230
126/177 - Collecting: mt_847802642
127/177 - Collecting: mt_452489088
128/177 - Collecting: mt_138107709
129/177 - Collecting: mt_610698250
130/177 - Collecting: mt_963920727
131/177 - Collecting: mt_579529686
132/177 - Collecting: mt_452489011
133/177 - Collecting: mt_291273579
134/177 - Collecting: mt_085045718
135/177 - Collecting: mt_726751022
136/177 - Collecting: mt_085037134
137/177 - Collecting: mt_291268860
138/177 - Collecting: mt_304420410
139/177 - Collecting: mt_291185931
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
140/177 - Collecting: mt_085591739
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
141/177 - Collecting: mt_610051098
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
142/177 - Collecting: mt_452215274
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
143/177 - Collecting: mt_610051051
144/177 - Collecting: mt_138873876
145/177 - Collecting: mt_726604104
146/177 - Collecting: mt_304225578
147/177 - Collecting: mt_579399316
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
148/177 - Collecting: mt_726001130
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
149/177 - Collecting: mt_085997728
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
150/177 - Collecting: mt_579336616
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
151/177 - Collecting: mt_610558844
152/177 - Collecting: mt_610954969
153/177 - Collecting: mt_291883302
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
154/177 - Collecting: mt_847662290
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
155/177 - Collecting: mt_452119960
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
156/177 - Collecting: mt_452816847
157/177 - Collecting: mt_138774458
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
158/177 - Collecting: mt_726503566
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
159/177 - Collecting: mt_579431458
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
160/177 - Collecting: mt_847069087
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
161/177 - Collecting: mt_085392302
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
162/177 - Collecting: mt_138675681
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
163/177 - Collecting: mt_291780205
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
164/177 - Collecting: mt_726503731
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
165/177 - Collecting: mt_085392014
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
166/177 - Collecting: mt_291780723
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
167/177 - Collecting: mt_610954625
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
168/177 - Collecting: mt_452816408
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['statistics', 'odds']
169/177 - Collecting: mt_847069076
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
170/177 - Collecting: mt_304127132
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
171/177 - Collecting: mt_963248296
172/177 - Collecting: mt_847069838
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
173/177 - Collecting: mt_304142684
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
174/177 - Collecting: mt_304127364
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
175/177 - Collecting: mt_138668638
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
176/177 - Collecting: mt_847096460
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
177/177 - Collecting: mt_304172028
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']

In [151]:
saved_ucl_2020_21 = list(
    CHAMPIONS_LEAGUE_SEASON_DIRS["2020_21"].glob("*.json")
)

print("Saved UCL 2020/21 files:", len(saved_ucl_2020_21))

Saved UCL 2020/21 files: 177

In [152]:
# Collect 2024/25 CL season (new format)

ucl_2024_25_matches = get_all_season_matches(
    CHAMPIONS_LEAGUE_ID,
    CHAMPIONS_LEAGUE_SEASONS["2024_25"]
)

print("Total matches returned:", len(ucl_2024_25_matches))

Total matches returned: 279

In [153]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in ucl_2024_25_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in ucl_2024_25_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in ucl_2024_25_matches
)))

Statuses:
Counter({'finished': 279})

Stages:
Counter({None: 144, 'qualifying': 76, 'round_of_16': 46, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 279

In [156]:
collect_champions_league_baseline_data(
    "2024_25",
    ucl_2024_25_matches
)

1/279 - Skipping existing: mt_015208290
2/279 - Skipping existing: mt_364741364
3/279 - Skipping existing: mt_620409625
4/279 - Skipping existing: mt_015253014
5/279 - Skipping existing: mt_402628408
6/279 - Skipping existing: mt_973832988
7/279 - Skipping existing: mt_198586153
8/279 - Skipping existing: mt_251017205
9/279 - Skipping existing: mt_402628457
10/279 - Skipping existing: mt_620409619
11/279 - Skipping existing: mt_015253082
12/279 - Skipping existing: mt_589194578
13/279 - Skipping existing: mt_973832966
14/279 - Skipping existing: mt_837979789
15/279 - Skipping existing: mt_015252550
16/279 - Skipping existing: mt_198585880
17/279 - Skipping existing: mt_973838334
18/279 - Skipping existing: mt_973838393
19/279 - Skipping existing: mt_198585816
20/279 - Skipping existing: mt_620404061
21/279 - Skipping existing: mt_015252077
22/279 - Skipping existing: mt_589191955
23/279 - Skipping existing: mt_251010128
24/279 - Skipping existing: mt_402626249
25/279 - Skipping existing: mt_746363679
26/279 - Skipping existing: mt_364747436
27/279 - Skipping existing: mt_589191999
28/279 - Skipping existing: mt_251010117
29/279 - Skipping existing: mt_746363663
30/279 - Skipping existing: mt_402050972
31/279 - Skipping existing: mt_251595360
32/279 - Skipping existing: mt_015181723
33/279 - Skipping existing: mt_015181735
34/279 - Skipping existing: mt_251595376
35/279 - Skipping existing: mt_364606515
36/279 - Skipping existing: mt_620212840
37/279 - Skipping existing: mt_973767011
38/279 - Skipping existing: mt_620212836
39/279 - Skipping existing: mt_198939409
40/279 - Skipping existing: mt_402050961
41/279 - Skipping existing: mt_198939465
42/279 - Skipping existing: mt_973767022
43/279 - Skipping existing: mt_015181749
44/279 - Skipping existing: mt_746424192
45/279 - Skipping existing: mt_589878612
46/279 - Skipping existing: mt_197430683
47/279 - Skipping existing: mt_362508112
48/279 - Skipping existing: mt_019784341
49/279 - Skipping existing: mt_019784328
50/279 - Skipping existing: mt_836245572
51/279 - Skipping existing: mt_740129925
52/279 - Skipping existing: mt_974061886
53/279 - Skipping existing: mt_625813261
54/279 - Skipping existing: mt_362508625
55/279 - Skipping existing: mt_258396570
56/279 - Skipping existing: mt_258396553
57/279 - Skipping existing: mt_974061699
58/279 - Skipping existing: mt_401957508
59/279 - Skipping existing: mt_974061666
60/279 - Skipping existing: mt_019784713
61/279 - Skipping existing: mt_740123776
62/279 - Skipping existing: mt_625814626
63/279 - Skipping existing: mt_836249760
64/279 - Skipping existing: mt_401957805
65/279 - Skipping existing: mt_740129901
66/279 - Skipping existing: mt_836245529
67/279 - Skipping existing: mt_583672877
68/279 - Skipping existing: mt_836245452
69/279 - Skipping existing: mt_974068313
70/279 - Skipping existing: mt_836249759
71/279 - Skipping existing: mt_625813988
72/279 - Skipping existing: mt_836245557
73/279 - Skipping existing: mt_197430636
74/279 - Skipping existing: mt_019784211
75/279 - Skipping existing: mt_362508037
76/279 - Skipping existing: mt_836245463
77/279 - Skipping existing: mt_258396377
78/279 - Skipping existing: mt_197430405
79/279 - Skipping existing: mt_583671561
80/279 - Skipping existing: mt_401957681
81/279 - Skipping existing: mt_625814069
82/279 - Skipping existing: mt_401957818
83/279 - Skipping existing: mt_258396586
84/279 - Skipping existing: mt_740129426
85/279 - Skipping existing: mt_625813183
86/279 - Skipping existing: mt_583672623
87/279 - Skipping existing: mt_740123655
88/279 - Skipping existing: mt_019782520
89/279 - Skipping existing: mt_258396031
90/279 - Skipping existing: mt_258390250
91/279 - Skipping existing: mt_019784405
92/279 - Skipping existing: mt_836245584
93/279 - Skipping existing: mt_019784421
94/279 - Skipping existing: mt_019784890
95/279 - Skipping existing: mt_019784814
96/279 - Skipping existing: mt_583671596
97/279 - Skipping existing: mt_019782502
98/279 - Skipping existing: mt_740129447
99/279 - Skipping existing: mt_625813284
100/279 - Skipping existing: mt_019784418
101/279 - Skipping existing: mt_019784299
102/279 - Skipping existing: mt_836245936
103/279 - Skipping existing: mt_019784178
104/279 - Skipping existing: mt_836245438
105/279 - Skipping existing: mt_836245269
106/279 - Skipping existing: mt_740123600
107/279 - Skipping existing: mt_258396702
108/279 - Skipping existing: mt_836245485
109/279 - Skipping existing: mt_362508124
110/279 - Skipping existing: mt_258396751
111/279 - Skipping existing: mt_258396069
112/279 - Skipping existing: mt_019784139
113/279 - Skipping existing: mt_197430493
114/279 - Skipping existing: mt_974068990
115/279 - Skipping existing: mt_197435100
116/279 - Skipping existing: mt_258396798
117/279 - Skipping existing: mt_258396737
118/279 - Skipping existing: mt_583672448
119/279 - Skipping existing: mt_974061263
120/279 - Skipping existing: mt_401957624
121/279 - Skipping existing: mt_583672822
122/279 - Skipping existing: mt_625813213
123/279 - Skipping existing: mt_740129269
124/279 - Skipping existing: mt_019784772
125/279 - Skipping existing: mt_836245023
126/279 - Skipping existing: mt_258396976
127/279 - Skipping existing: mt_836245090
128/279 - Skipping existing: mt_974061127
129/279 - Skipping existing: mt_625813414
130/279 - Skipping existing: mt_258396528
131/279 - Skipping existing: mt_974061688
132/279 - Skipping existing: mt_401957557
133/279 - Skipping existing: mt_740129170
134/279 - Skipping existing: mt_019784370
135/279 - Skipping existing: mt_625813312
136/279 - Skipping existing: mt_974061238
137/279 - Skipping existing: mt_625813306
138/279 - Skipping existing: mt_401957777
139/279 - Skipping existing: mt_362508784
140/279 - Skipping existing: mt_401957974
141/279 - Skipping existing: mt_019782025
142/279 - Skipping existing: mt_836249828
143/279 - Skipping existing: mt_974061677
144/279 - Skipping existing: mt_974068396
145/279 - Skipping existing: mt_258396773
146/279 - Skipping existing: mt_401957788
147/279 - Skipping existing: mt_974061103
148/279 - Skipping existing: mt_740129463
149/279 - Skipping existing: mt_401957068
150/279 - Skipping existing: mt_362507428
151/279 - Skipping existing: mt_401956210
152/279 - Skipping existing: mt_197430585
153/279 - Skipping existing: mt_019782515
154/279 - Skipping existing: mt_740129530
155/279 - Skipping existing: mt_740129936
156/279 - Skipping existing: mt_197430538
157/279 - Skipping existing: mt_019784277
158/279 - Skipping existing: mt_836245320
159/279 - Skipping existing: mt_836245292
160/279 - Skipping existing: mt_625814054
161/279 - Skipping existing: mt_974061192
162/279 - Skipping existing: mt_019784112
163/279 - Skipping existing: mt_625813911
164/279 - Skipping existing: mt_197430098
165/279 - Skipping existing: mt_362508683
166/279 - Skipping existing: mt_740129216
167/279 - Skipping existing: mt_625814652
168/279 - Skipping existing: mt_740123759
169/279 - Skipping existing: mt_019782598
170/279 - Skipping existing: mt_583672431
171/279 - Skipping existing: mt_583672294
172/279 - Skipping existing: mt_974061841
173/279 - Skipping existing: mt_362508064
174/279 - Skipping existing: mt_401956451
175/279 - Skipping existing: mt_197435881
176/279 - Skipping existing: mt_740129410
177/279 - Skipping existing: mt_583672795
178/279 - Skipping existing: mt_583672159
179/279 - Skipping existing: mt_583672121
180/279 - Skipping existing: mt_019784835
181/279 - Skipping existing: mt_401957561
182/279 - Skipping existing: mt_740129545
183/279 - Skipping existing: mt_583672767
184/279 - Skipping existing: mt_625813944
185/279 - Skipping existing: mt_974061148
186/279 - Skipping existing: mt_974061067
187/279 - Skipping existing: mt_197435806
188/279 - Skipping existing: mt_625813955
189/279 - Skipping existing: mt_401957014
190/279 - Skipping existing: mt_013554184
191/279 - Skipping existing: mt_361446370
192/279 - Skipping existing: mt_361446365
193/279 - Skipping existing: mt_629002648
194/279 - Skipping existing: mt_257116653
195/279 - Skipping existing: mt_196889195
196/279 - Skipping existing: mt_361460810
197/279 - Skipping existing: mt_830773876
198/279 - Skipping existing: mt_629002616
199/279 - Skipping existing: mt_408220452
200/279 - Skipping existing: mt_629021398
201/279 - Skipping existing: mt_745664766
202/279 - Skipping existing: mt_745664744
203/279 - Skipping existing: mt_830773834
204/279 - Skipping existing: mt_361235464
205/279 - Skipping existing: mt_196714718
206/279 - Skipping existing: mt_830642200
207/279 - Skipping existing: mt_830683462
208/279 - Skipping existing: mt_196714734
209/279 - Skipping existing: mt_745071631
210/279 - Skipping existing: mt_745074202
211/279 - Skipping existing: mt_972434392
212/279 - Skipping existing: mt_257818126
213/279 - Skipping existing: mt_257896199
214/279 - Skipping existing: mt_830682738
215/279 - Skipping existing: mt_830670428
216/279 - Skipping existing: mt_629518894
217/279 - Skipping existing: mt_361205518
218/279 - Skipping existing: mt_361241054
219/279 - Skipping existing: mt_629568025
220/279 - Skipping existing: mt_745071070
221/279 - Skipping existing: mt_745071017
222/279 - Skipping existing: mt_013907514
223/279 - Skipping existing: mt_408149208
224/279 - Skipping existing: mt_196689187
225/279 - Skipping existing: mt_584493167
226/279 - Skipping existing: mt_584424268
227/279 - Skipping existing: mt_257789729
228/279 - Skipping existing: mt_196578399
229/279 - Skipping existing: mt_408815827
230/279 - Skipping existing: mt_408821696
231/279 - Skipping existing: mt_745560470
232/279 - Skipping existing: mt_972234800
233/279 - Skipping existing: mt_361181852
234/279 - Skipping existing: mt_013359271
235/279 - Skipping existing: mt_257767699
236/279 - Skipping existing: mt_257081950
237/279 - Skipping existing: mt_830050527
238/279 - Skipping existing: mt_972237307
239/279 - Skipping existing: mt_584498961
240/279 - Skipping existing: mt_745564765
241/279 - Skipping existing: mt_629939389
242/279 - Skipping existing: mt_584131325
243/279 - Skipping existing: mt_745595917
244/279 - Skipping existing: mt_257767633
245/279 - Skipping existing: mt_972848413
246/279 - Skipping existing: mt_196606034
247/279 - Skipping existing: mt_408820401
248/279 - Skipping existing: mt_257715139
249/279 - Skipping existing: mt_196606511
250/279 - Skipping existing: mt_408878646
251/279 - Skipping existing: mt_361146363
252/279 - Skipping existing: mt_629495642
253/279 - Skipping existing: mt_361712366
254/279 - Skipping existing: mt_257078201
255/279 - Skipping existing: mt_257078258
256/279 - Skipping existing: mt_745350723
257/279 - Skipping existing: mt_745350735
258/279 - Skipping existing: mt_830906895
259/279 - Skipping existing: mt_584143585
260/279 - Skipping existing: mt_584143526
261/279 - Skipping existing: mt_408681465
262/279 - Skipping existing: mt_408681470
263/279 - Skipping existing: mt_013239080
264/279 - Skipping existing: mt_972824964
265/279 - Skipping existing: mt_830906839
266/279 - Skipping existing: mt_629495618
267/279 - Skipping existing: mt_013239048
268/279 - Skipping existing: mt_196567157
269/279 - Skipping existing: mt_830906843
270/279 - Skipping existing: mt_629495621
271/279 - Skipping existing: mt_013239075
272/279 - Skipping existing: mt_013239027
273/279 - Skipping existing: mt_196567196
274/279 - Skipping existing: mt_972824989
275/279 - Skipping existing: mt_972824973
276/279 - Skipping existing: mt_745350749
277/279 - Skipping existing: mt_408681494
278/279 - Skipping existing: mt_584143579
279/279 - Skipping existing: mt_257078297

In [157]:
saved_ucl_2024_25 = list(
    CHAMPIONS_LEAGUE_SEASON_DIRS["2024_25"].glob("*.json")
)

print("Saved UCL 2024/25 files:", len(saved_ucl_2024_25))

Saved UCL 2024/25 files: 279

In [158]:
# Collecting 2025/26 CL season

ucl_2025_26_matches = get_all_season_matches(
    CHAMPIONS_LEAGUE_ID,
    CHAMPIONS_LEAGUE_SEASONS["2025_26"]
)

print("Total matches returned:", len(ucl_2025_26_matches))

Total matches returned: 281

In [159]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in ucl_2025_26_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in ucl_2025_26_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in ucl_2025_26_matches
)))

Statuses:
Counter({'finished': 281})

Stages:
Counter({None: 144, 'qualifying': 78, 'round_of_16': 46, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 281

In [160]:
collect_champions_league_baseline_data(
    "2025_26",
    ucl_2025_26_matches
)

1/281 - Collecting: mt_642459639
2/281 - Collecting: mt_021293042
3/281 - Collecting: mt_460618477
4/281 - Collecting: mt_518134528
5/281 - Collecting: mt_987842916
6/281 - Collecting: mt_205087263
7/281 - Collecting: mt_893960466
8/281 - Collecting: mt_734305206
9/281 - Collecting: mt_376721021
10/281 - Collecting: mt_460618516
11/281 - Collecting: mt_518134737
12/281 - Collecting: mt_642459153
13/281 - Collecting: mt_021293891
14/281 - Collecting: mt_205086923
15/281 - Collecting: mt_159570381
16/281 - Collecting: mt_734309266
17/281 - Collecting: mt_893965476
18/281 - Collecting: mt_987841696
19/281 - Collecting: mt_376728041
20/281 - Collecting: mt_460617526
21/281 - Collecting: mt_642453103
22/281 - Collecting: mt_205086968
23/281 - Collecting: mt_460617579
24/281 - Collecting: mt_734309233
25/281 - Collecting: mt_518132797
26/281 - Collecting: mt_205086982
27/281 - Collecting: mt_642453154
28/281 - Collecting: mt_376728017
29/281 - Collecting: mt_205086971
30/281 - Collecting: mt_159479310
31/281 - Collecting: mt_987047641
32/281 - Collecting: mt_734104202
33/281 - Collecting: mt_021791800
34/281 - Collecting: mt_642852212
35/281 - Collecting: mt_021791855
36/281 - Collecting: mt_893263474
37/281 - Collecting: mt_734104419
38/281 - Collecting: mt_021791833
39/281 - Collecting: mt_893263458
40/281 - Collecting: mt_460910578
41/281 - Collecting: mt_159479363
42/281 - Collecting: mt_205385969
43/281 - Collecting: mt_987047628
44/281 - Collecting: mt_734104251
45/281 - Collecting: mt_642852135
46/281 - Collecting: mt_375726053
47/281 - Collecting: mt_154579414
48/281 - Collecting: mt_648452894
49/281 - Collecting: mt_154579456
50/281 - Collecting: mt_731304143
51/281 - Collecting: mt_203085396
52/281 - Collecting: mt_469615441
53/281 - Collecting: mt_648451055
54/281 - Collecting: mt_648451033
55/281 - Collecting: mt_375720478
56/281 - Collecting: mt_469615205
57/281 - Collecting: mt_154573840
58/281 - Collecting: mt_469615122
59/281 - Collecting: mt_469615166
60/281 - Collecting: mt_731302040
61/281 - Collecting: mt_516137386
62/281 - Collecting: mt_731302019
63/281 - Collecting: mt_731302564
64/281 - Collecting: mt_375726534
65/281 - Collecting: mt_980847001
66/281 - Collecting: mt_203089258
67/281 - Collecting: mt_469615287
68/281 - Collecting: mt_731302629
69/281 - Collecting: mt_516137418
70/281 - Collecting: mt_516137487
71/281 - Collecting: mt_469610916
72/281 - Collecting: mt_154579407
73/281 - Collecting: mt_516138774
74/281 - Collecting: mt_648451605
75/281 - Collecting: mt_027298092
76/281 - Collecting: mt_648451642
77/281 - Collecting: mt_516137992
78/281 - Collecting: mt_980846241
79/281 - Collecting: mt_892964058
80/281 - Collecting: mt_203089262
81/281 - Collecting: mt_027291815
82/281 - Collecting: mt_892963299
83/281 - Collecting: mt_375720412
84/281 - Collecting: mt_648451044
85/281 - Collecting: mt_375720467
86/281 - Collecting: mt_375720235
87/281 - Collecting: mt_203089716
88/281 - Collecting: mt_469615878
89/281 - Collecting: mt_203085361
90/281 - Collecting: mt_027298553
91/281 - Collecting: mt_203085329
92/281 - Collecting: mt_892963200
93/281 - Collecting: mt_980847062
94/281 - Collecting: mt_892964895
95/281 - Collecting: mt_648451011
96/281 - Collecting: mt_203089891
97/281 - Collecting: mt_203089780
98/281 - Collecting: mt_980846270
99/281 - Collecting: mt_469610504
100/281 - Collecting: mt_469615428
101/281 - Collecting: mt_469615417
102/281 - Collecting: mt_027298594
103/281 - Collecting: mt_469615276
104/281 - Collecting: mt_375720450
105/281 - Collecting: mt_892964630
106/281 - Collecting: mt_892964629
107/281 - Collecting: mt_027291889
108/281 - Collecting: mt_892963442
109/281 - Collecting: mt_980847074
110/281 - Collecting: mt_469610992
111/281 - Collecting: mt_980846920
112/281 - Collecting: mt_469615470
113/281 - Collecting: mt_516137317
114/281 - Collecting: mt_154573685
115/281 - Collecting: mt_154573691
116/281 - Collecting: mt_375726521
117/281 - Collecting: mt_027298003
118/281 - Collecting: mt_892963288
119/281 - Collecting: mt_648451660
120/281 - Collecting: mt_980846973
121/281 - Collecting: mt_469615260
122/281 - Collecting: mt_648451022
123/281 - Collecting: mt_980846480
124/281 - Collecting: mt_027298399
125/281 - Collecting: mt_648452180
126/281 - Collecting: mt_731304195
127/281 - Collecting: mt_375720344
128/281 - Collecting: mt_027298031
129/281 - Collecting: mt_731302735
130/281 - Collecting: mt_375720424
131/281 - Collecting: mt_648451099
132/281 - Collecting: mt_648451524
133/281 - Collecting: mt_648451581
134/281 - Collecting: mt_154579490
135/281 - Collecting: mt_516138664
136/281 - Collecting: mt_375726518
137/281 - Collecting: mt_648451659
138/281 - Collecting: mt_027298541
139/281 - Collecting: mt_892964749
140/281 - Collecting: mt_648451935
141/281 - Collecting: mt_980846286
142/281 - Collecting: mt_203089792
143/281 - Collecting: mt_648452853
144/281 - Collecting: mt_203085308
145/281 - Collecting: mt_203085990
146/281 - Collecting: mt_648452865
147/281 - Collecting: mt_731304167
148/281 - Collecting: mt_516138673
149/281 - Collecting: mt_203089115
150/281 - Collecting: mt_892964723
151/281 - Collecting: mt_027298959
152/281 - Collecting: mt_648452148
153/281 - Collecting: mt_980846469
154/281 - Collecting: mt_469610980
155/281 - Collecting: mt_203085357
156/281 - Collecting: mt_980846338
157/281 - Collecting: mt_731302613
158/281 - Collecting: mt_648451506
159/281 - Collecting: mt_154573737
160/281 - Collecting: mt_980846232
161/281 - Collecting: mt_980847097
162/281 - Collecting: mt_980847019
163/281 - Collecting: mt_469610591
164/281 - Collecting: mt_027291791
165/281 - Collecting: mt_516137547
166/281 - Collecting: mt_516137585
167/281 - Collecting: mt_469615218
168/281 - Collecting: mt_516137434
169/281 - Collecting: mt_203089703
170/281 - Collecting: mt_516138783
171/281 - Collecting: mt_375720406
172/281 - Collecting: mt_469610948
173/281 - Collecting: mt_375720322
174/281 - Collecting: mt_375720481
175/281 - Collecting: mt_027298921
176/281 - Collecting: mt_980847661
177/281 - Collecting: mt_892964790
178/281 - Collecting: mt_516137552
179/281 - Collecting: mt_375720268
180/281 - Collecting: mt_375720256
181/281 - Collecting: mt_154573638
182/281 - Collecting: mt_027291779
183/281 - Collecting: mt_892964878
184/281 - Collecting: mt_375720377
185/281 - Collecting: mt_027298532
186/281 - Collecting: mt_892964735
187/281 - Collecting: mt_375720184
188/281 - Collecting: mt_731304139
189/281 - Collecting: mt_027291785
190/281 - Collecting: mt_469991584
191/281 - Collecting: mt_404444150
192/281 - Collecting: mt_585555376
193/281 - Collecting: mt_979999409
194/281 - Collecting: mt_626666514
195/281 - Collecting: mt_252222831
196/281 - Collecting: mt_010000988
197/281 - Collecting: mt_838888625
198/281 - Collecting: mt_363333257
199/281 - Collecting: mt_404444195
200/281 - Collecting: mt_010000977
201/281 - Collecting: mt_731110254
202/281 - Collecting: mt_747777015
203/281 - Collecting: mt_626666582
204/281 - Collecting: mt_252197750
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
205/281 - Collecting: mt_585974852
206/281 - Collecting: mt_191836699
207/281 - Collecting: mt_747625542
208/281 - Collecting: mt_010583908
209/281 - Collecting: mt_363460575
210/281 - Collecting: mt_979362271
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
211/281 - Collecting: mt_838740032
212/281 - Collecting: mt_010583103
213/281 - Collecting: mt_585974484
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
214/281 - Collecting: mt_979362798
215/281 - Collecting: mt_191836961
216/281 - Collecting: mt_747625521
217/281 - Collecting: mt_404258898
218/281 - Collecting: mt_838740028
219/281 - Collecting: mt_010583374
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
220/281 - Collecting: mt_626021826
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
221/281 - Collecting: mt_191836633
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
222/281 - Collecting: mt_363401154
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
223/281 - Collecting: mt_626019985
224/281 - Collecting: mt_747352239
225/281 - Collecting: mt_838950067
226/281 - Collecting: mt_404685569
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
227/281 - Collecting: mt_404198560
228/281 - Collecting: mt_626491132
229/281 - Collecting: mt_191563390
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
230/281 - Collecting: mt_626589144
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
231/281 - Collecting: mt_363710076
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
232/281 - Collecting: mt_010973828
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
233/281 - Collecting: mt_404685575
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
234/281 - Collecting: mt_252079908
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
235/281 - Collecting: mt_626491141
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
236/281 - Collecting: mt_010238847
237/281 - Collecting: mt_585147789
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
238/281 - Collecting: mt_363251078
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
239/281 - Collecting: mt_979826683
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
240/281 - Collecting: mt_191506661
241/281 - Collecting: mt_363781122
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
242/281 - Collecting: mt_010243392
243/281 - Collecting: mt_404678817
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
244/281 - Collecting: mt_626439959
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
245/281 - Collecting: mt_585147715
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
246/281 - Collecting: mt_010238810
247/281 - Collecting: mt_252079957
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
248/281 - Collecting: mt_979812246
249/281 - Collecting: mt_252067783
250/281 - Collecting: mt_747395556
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
251/281 - Collecting: mt_404685516
252/281 - Collecting: mt_979826674
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
253/281 - Collecting: mt_191563356
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
254/281 - Collecting: mt_252063319
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
255/281 - Collecting: mt_252063383
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
256/281 - Collecting: mt_626434683
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
257/281 - Collecting: mt_191505818
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
258/281 - Collecting: mt_979810037
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
259/281 - Collecting: mt_191504461
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
260/281 - Collecting: mt_585121567
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
261/281 - Collecting: mt_747393670
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
262/281 - Collecting: mt_838959780
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
263/281 - Collecting: mt_363787438
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
264/281 - Collecting: mt_252060111
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
265/281 - Collecting: mt_010247792
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
266/281 - Collecting: mt_626438893
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
267/281 - Collecting: mt_404676496
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
268/281 - Collecting: mt_979810020
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
269/281 - Collecting: mt_363785511
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
270/281 - Collecting: mt_404679986
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
271/281 - Collecting: mt_010247731
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
272/281 - Collecting: mt_838952267
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
273/281 - Collecting: mt_979810046
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
274/281 - Collecting: mt_404679917
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
275/281 - Collecting: mt_585126638
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
276/281 - Collecting: mt_585126647
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']

In [161]:
saved_ucl_2025_26 = list(
    CHAMPIONS_LEAGUE_SEASON_DIRS["2025_26"].glob("*.json")
)

print("Saved UCL 2025/26 files:", len(saved_ucl_2025_26))

Saved UCL 2025/26 files: 281

In [162]:
# Collecting FA cup seasons

FA_CUP_ID = "comp_7428"

FA_CUP_SEASONS = {
    "2026_27": "sn_7205142",
    "2025_26": "sn_3071665",
    "2024_25": "sn_8449488",
    "2023_24": "sn_885727",
    "2022_23": "sn_531226",
    "2021_22": "sn_097717",
    "2020_21": "sn_169084"
}

In [163]:
# Create separate folder to store FA cup matches

FA_CUP_DIR = RAW_MATCH_DIR / "fa_cup"

FA_CUP_SEASON_DIRS = {}

for season_name in FA_CUP_SEASONS:
    season_dir = FA_CUP_DIR / season_name
    season_dir.mkdir(parents=True, exist_ok=True)
    FA_CUP_SEASON_DIRS[season_name] = season_dir

In [164]:
# Collector for matches

def collect_fa_cup_baseline_data(season_name, matches):
    season_dir = FA_CUP_SEASON_DIRS[season_name]
    total_matches = len(matches)

    for i, match in enumerate(matches, start=1):
        match_id = match["id"]
        file_path = season_dir / f"{match_id}.json"

        if file_path.exists():
            print(f"{i}/{total_matches} - Skipping existing: {match_id}")
            continue

        print(f"{i}/{total_matches} - Collecting: {match_id}")

        match_data = get_baseline_match_data(match_id)

        if match_data is None:
            print("Skipped:", match_id)
            continue

        save_match_data(match_id, match_data, season_dir)
        time.sleep(1)

In [ ]:
# Collect 2023/24 FA Cup matches

fa_cup_2023_24_matches = get_all_season_matches(
    FA_CUP_ID,
    FA_CUP_SEASONS["2023_24"]
)

print("Total matches returned:", len(fa_cup_2023_24_matches))

Total matches returned: 149

In [166]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in fa_cup_2023_24_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in fa_cup_2023_24_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in fa_cup_2023_24_matches
)))

Statuses:
Counter({'finished': 149})

Stages:
Counter({None: 142, 'quarter_final': 4, 'semi_final': 2, 'final': 1})

Unique IDs: 149

In [167]:
collect_fa_cup_baseline_data(
    "2023_24",
    fa_cup_2023_24_matches
)

1/149 - Collecting: mt_972030842
2/149 - Collecting: mt_368351478
3/149 - Collecting: mt_835820790
4/149 - Collecting: mt_256193788
5/149 - Collecting: mt_971360243
6/149 - Collecting: mt_582976435
7/149 - Collecting: mt_190834676
8/149 - Collecting: mt_256837517
9/149 - Collecting: mt_835642455
10/149 - Collecting: mt_582364176
11/149 - Collecting: mt_190734356
12/149 - Collecting: mt_582364899
13/149 - Collecting: mt_014973288
14/149 - Collecting: mt_971402734
15/149 - Collecting: mt_971402809
16/149 - Collecting: mt_014341798
17/149 - Collecting: mt_623932854
18/149 - Collecting: mt_014342208
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
19/149 - Collecting: mt_407870910
20/149 - Collecting: mt_582428636
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
21/149 - Collecting: mt_407771921
22/149 - Collecting: mt_014459388
23/149 - Collecting: mt_407745966
24/149 - Collecting: mt_835556268
25/149 - Collecting: mt_749960537
26/149 - Collecting: mt_749990161
27/149 - Collecting: mt_014408721
28/149 - Collecting: mt_190087638
29/149 - Collecting: mt_368882524
30/149 - Collecting: mt_623335855
31/149 - Collecting: mt_256668315
32/149 - Collecting: mt_582223692
33/149 - Collecting: mt_749972229
34/149 - Collecting: mt_971114038
35/149 - Collecting: mt_190007483
36/149 - Collecting: mt_623335800
37/149 - Collecting: mt_407777288
38/149 - Collecting: mt_835553352
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
39/149 - Collecting: mt_971171114
40/149 - Collecting: mt_014444534
41/149 - Collecting: mt_971111327
42/149 - Collecting: mt_256665560
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
43/149 - Collecting: mt_190009909
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
44/149 - Collecting: mt_749994492
45/149 - Collecting: mt_582178845
46/149 - Collecting: mt_623412291
47/149 - Collecting: mt_835962456
48/149 - Collecting: mt_835959690
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
49/149 - Collecting: mt_407650015
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
50/149 - Collecting: mt_368706616
51/149 - Collecting: mt_582178829
52/149 - Collecting: mt_368706680
53/149 - Collecting: mt_971867782
54/149 - Collecting: mt_835943365
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
55/149 - Collecting: mt_407650089
56/149 - Collecting: mt_256095567
57/149 - Collecting: mt_835943353
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
58/149 - Collecting: mt_256060802
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
59/149 - Collecting: mt_190505758
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
60/149 - Collecting: mt_749393030
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
61/149 - Collecting: mt_014281197
62/149 - Collecting: mt_256095578
63/149 - Collecting: mt_190539966
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
64/149 - Collecting: mt_014281140
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
65/149 - Collecting: mt_190539900
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
66/149 - Collecting: mt_623412238
67/149 - Collecting: mt_582178813
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
68/149 - Collecting: mt_407650064
69/149 - Collecting: mt_368787278
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
70/149 - Collecting: mt_582117998
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
71/149 - Collecting: mt_749324405
72/149 - Collecting: mt_971867723
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
73/149 - Collecting: mt_835943309
74/149 - Collecting: mt_623412252
75/149 - Collecting: mt_749324493
76/149 - Collecting: mt_014281125
77/149 - Collecting: mt_582128294
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
78/149 - Collecting: mt_749324459
79/149 - Collecting: mt_623420823
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
80/149 - Collecting: mt_407605811
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
81/149 - Collecting: mt_368706627
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
82/149 - Collecting: mt_971867714
83/149 - Collecting: mt_835925407
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
84/149 - Collecting: mt_407692776
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['odds']
85/149 - Collecting: mt_749430701
86/149 - Collecting: mt_256508285
87/149 - Collecting: mt_014129059
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
88/149 - Collecting: mt_623245650
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
89/149 - Collecting: mt_407061411
90/149 - Collecting: mt_190975781
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
91/149 - Collecting: mt_749491912
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
92/149 - Collecting: mt_835352522
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
93/149 - Collecting: mt_623238460
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
94/149 - Collecting: mt_407079641
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
95/149 - Collecting: mt_256508210
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
96/149 - Collecting: mt_749430762
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
97/149 - Collecting: mt_582813532
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
98/149 - Collecting: mt_971784948
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
99/149 - Collecting: mt_190957173
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
100/149 - Collecting: mt_256563630
101/149 - Collecting: mt_014129093
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
102/149 - Collecting: mt_190317057
103/149 - Collecting: mt_582753279
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
104/149 - Collecting: mt_971694164
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
105/149 - Collecting: mt_835489553
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
106/149 - Collecting: mt_368037880
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
107/149 - Collecting: mt_623164338
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
108/149 - Collecting: mt_014802425
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
109/149 - Collecting: mt_582751213
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
110/149 - Collecting: mt_407546764
111/149 - Collecting: mt_749240212
112/149 - Collecting: mt_835436422
113/149 - Collecting: mt_368062544
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
114/149 - Collecting: mt_407501928
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
115/149 - Collecting: mt_368062533
116/149 - Collecting: mt_256958325
117/149 - Collecting: mt_256998936
118/149 - Collecting: mt_623125860
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
119/149 - Collecting: mt_407501941
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
120/149 - Collecting: mt_014819703
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
121/149 - Collecting: mt_971674098
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
122/149 - Collecting: mt_190397413
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
123/149 - Collecting: mt_749240171
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
124/149 - Collecting: mt_835436278
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
125/149 - Collecting: mt_623125805
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
126/149 - Collecting: mt_014819754
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
127/149 - Collecting: mt_582783691
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
128/149 - Collecting: mt_971674037
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
129/149 - Collecting: mt_256958319
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
130/149 - Collecting: mt_190397484
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
131/149 - Collecting: mt_749240107
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
132/149 - Collecting: mt_407551594
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
133/149 - Collecting: mt_014889875
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
134/149 - Collecting: mt_582773763
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
135/149 - Collecting: mt_971664602
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
136/149 - Collecting: mt_190337345
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
137/149 - Collecting: mt_749220214
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
138/149 - Collecting: mt_835446424
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
139/149 - Collecting: mt_623115866
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
140/149 - Collecting: mt_407551942
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
141/149 - Collecting: mt_014889709
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
142/149 - Collecting: mt_582773654
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
143/149 - Collecting: mt_971664091
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
144/149 - Collecting: mt_256998320
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
145/149 - Collecting: mt_190337419
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
146/149 - Collecting: mt_835446282
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
147/149 - Collecting: mt_368062522
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
148/149 - Collecting: mt_582783652
149/149 - Collecting: mt_749220172

In [168]:
saved_fa_cup_2023_24 = list(
    FA_CUP_SEASON_DIRS["2023_24"].glob("*.json")
)

print("Saved FA Cup 2023/24 files:", len(saved_fa_cup_2023_24))

Saved FA Cup 2023/24 files: 149

In [169]:
# Collect 2022/23 FA cup season

fa_cup_2022_23_matches = get_all_season_matches(
    FA_CUP_ID,
    FA_CUP_SEASONS["2022_23"]
)

print("Total matches returned:", len(fa_cup_2022_23_matches))

Total matches returned: 144

In [170]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in fa_cup_2022_23_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in fa_cup_2022_23_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in fa_cup_2022_23_matches
)))

Statuses:
Counter({'finished': 144})

Stages:
Counter({None: 137, 'quarter_final': 4, 'semi_final': 2, 'final': 1})

Unique IDs: 144

In [171]:
collect_fa_cup_baseline_data(
    "2022_23",
    fa_cup_2022_23_matches
)

1/144 - Collecting: mt_012818277
2/144 - Collecting: mt_255280160
3/144 - Collecting: mt_588531566
4/144 - Collecting: mt_255125703
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['odds']
5/144 - Collecting: mt_744674546
6/144 - Collecting: mt_199819691
7/144 - Collecting: mt_833783036
8/144 - Collecting: mt_977303986
9/144 - Collecting: mt_833668633
10/144 - Collecting: mt_977303994
11/144 - Collecting: mt_588969518
12/144 - Collecting: mt_744007043
13/144 - Collecting: mt_833744357
14/144 - Collecting: mt_199789108
15/144 - Collecting: mt_366223260
16/144 - Collecting: mt_977442663
17/144 - Collecting: mt_255888520
18/144 - Collecting: mt_011993817
19/144 - Collecting: mt_588334775
20/144 - Collecting: mt_255887998
21/144 - Collecting: mt_255886280
22/144 - Collecting: mt_744575504
23/144 - Collecting: mt_833080064
24/144 - Collecting: mt_366131125
25/144 - Collecting: mt_977479097
26/144 - Collecting: mt_199616675
27/144 - Collecting: mt_011303339
28/144 - Collecting: mt_011910704
29/144 - Collecting: mt_255852329
30/144 - Collecting: mt_199791414
31/144 - Collecting: mt_622969996
32/144 - Collecting: mt_588454444
33/144 - Collecting: mt_977292221
34/144 - Collecting: mt_199616669
35/144 - Collecting: mt_255866895
36/144 - Collecting: mt_255727770
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['odds']
37/144 - Collecting: mt_400848882
38/144 - Collecting: mt_366267671
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['odds']
39/144 - Collecting: mt_977298612
40/144 - Collecting: mt_744574410
41/144 - Collecting: mt_588452563
42/144 - Collecting: mt_588451723
43/144 - Collecting: mt_255725532
44/144 - Collecting: mt_199619948
45/144 - Collecting: mt_744906534
46/144 - Collecting: mt_744906593
47/144 - Collecting: mt_977143282
48/144 - Collecting: mt_400892814
49/144 - Collecting: mt_011495340
50/144 - Collecting: mt_366824175
51/144 - Collecting: mt_366824103
52/144 - Collecting: mt_011495325
53/144 - Collecting: mt_977143271
54/144 - Collecting: mt_622350938
55/144 - Collecting: mt_588239484
56/144 - Collecting: mt_400712889
57/144 - Collecting: mt_366824180
58/144 - Collecting: mt_199078655
59/144 - Collecting: mt_744906542
60/144 - Collecting: mt_588239429
61/144 - Collecting: mt_977143214
62/144 - Collecting: mt_199078600
63/144 - Collecting: mt_400712864
64/144 - Collecting: mt_255681706
65/144 - Collecting: mt_833567094
66/144 - Collecting: mt_622350926
67/144 - Collecting: mt_400712802
68/144 - Collecting: mt_199078699
69/144 - Collecting: mt_622350910
70/144 - Collecting: mt_255731786
71/144 - Collecting: mt_255681767
72/144 - Collecting: mt_011495319
73/144 - Collecting: mt_255681750
74/144 - Collecting: mt_833567032
75/144 - Collecting: mt_588239413
76/144 - Collecting: mt_199077401
77/144 - Collecting: mt_255688373
78/144 - Collecting: mt_977187980
79/144 - Collecting: mt_366878067
80/144 - Collecting: mt_744934736
81/144 - Collecting: mt_011421021
82/144 - Collecting: mt_833593896
83/144 - Collecting: mt_400767505
84/144 - Collecting: mt_744934797
85/144 - Collecting: mt_400761765
86/144 - Collecting: mt_011429427
87/144 - Collecting: mt_622343122
88/144 - Collecting: mt_011424817
89/144 - Collecting: mt_588212775
90/144 - Collecting: mt_588218528
91/144 - Collecting: mt_366876371
92/144 - Collecting: mt_622342643
93/144 - Collecting: mt_400760466
94/144 - Collecting: mt_255605252
95/144 - Collecting: mt_744934740
96/144 - Collecting: mt_833593830
97/144 - Collecting: mt_199059198
98/144 - Collecting: mt_011488709
99/144 - Collecting: mt_255028335
100/144 - Collecting: mt_833524490
101/144 - Collecting: mt_833522003
102/144 - Collecting: mt_588153662
103/144 - Collecting: mt_199517443
104/144 - Collecting: mt_744370111
105/144 - Collecting: mt_977894008
106/144 - Collecting: mt_622431219
107/144 - Collecting: mt_400669855
108/144 - Collecting: mt_199591757
109/144 - Collecting: mt_011227387
110/144 - Collecting: mt_366775107
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
111/144 - Collecting: mt_622448912
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
112/144 - Collecting: mt_588116465
113/144 - Collecting: mt_977880203
114/144 - Collecting: mt_255052819
115/144 - Collecting: mt_199591784
116/144 - Collecting: mt_744347007
117/144 - Collecting: mt_833938667
118/144 - Collecting: mt_366763222
119/144 - Collecting: mt_622426559
120/144 - Collecting: mt_011210992
121/144 - Collecting: mt_588185338
122/144 - Collecting: mt_977879446
123/144 - Collecting: mt_255052883
124/144 - Collecting: mt_199591761
125/144 - Collecting: mt_744347056
126/144 - Collecting: mt_833938606
127/144 - Collecting: mt_622426593
128/144 - Collecting: mt_400604186
129/144 - Collecting: mt_011210931
130/144 - Collecting: mt_588185347
131/144 - Collecting: mt_977879420
132/144 - Collecting: mt_255052862
133/144 - Collecting: mt_199591708
134/144 - Collecting: mt_833938650
135/144 - Collecting: mt_622426534
136/144 - Collecting: mt_977879489
137/144 - Collecting: mt_255052801
138/144 - Collecting: mt_744347035
139/144 - Collecting: mt_833938695
140/144 - Collecting: mt_366763211
141/144 - Collecting: mt_366763288
142/144 - Collecting: mt_011210948
143/144 - Collecting: mt_400604170
144/144 - Collecting: mt_744347090

In [172]:
saved_fa_cup_2022_23 = list(
    FA_CUP_SEASON_DIRS["2022_23"].glob("*.json")
)

print("Saved FA Cup 2022/23 files:", len(saved_fa_cup_2022_23))

Saved FA Cup 2022/23 files: 144

In [173]:
# Collect 2021/22 FA cup season

fa_cup_2021_22_matches = get_all_season_matches(
    FA_CUP_ID,
    FA_CUP_SEASONS["2021_22"]
)

print("Total matches returned:", len(fa_cup_2021_22_matches))

Total matches returned: 136

In [174]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in fa_cup_2021_22_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in fa_cup_2021_22_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in fa_cup_2021_22_matches
)))

Statuses:
Counter({'finished': 136})

Stages:
Counter({None: 129, 'quarter_final': 4, 'semi_final': 2, 'final': 1})

Unique IDs: 136

In [175]:
collect_fa_cup_baseline_data(
    "2021_22",
    fa_cup_2021_22_matches
)

1/136 - Collecting: mt_834948985
2/136 - Collecting: mt_193385684
3/136 - Collecting: mt_018854178
4/136 - Collecting: mt_405562665
5/136 - Collecting: mt_193396437
6/136 - Collecting: mt_834430407
7/136 - Collecting: mt_259957391
8/136 - Collecting: mt_259305261
9/136 - Collecting: mt_360577715
10/136 - Collecting: mt_587617536
11/136 - Collecting: mt_976086204
12/136 - Collecting: mt_259309737
13/136 - Collecting: mt_587617469
14/136 - Collecting: mt_405965859
15/136 - Collecting: mt_018728370
16/136 - Collecting: mt_365370166
17/136 - Collecting: mt_970986308
18/136 - Collecting: mt_970986191
19/136 - Collecting: mt_409465809
20/136 - Collecting: mt_194153696
21/136 - Collecting: mt_586517485
22/136 - Collecting: mt_832894039
23/136 - Collecting: mt_628641921
24/136 - Collecting: mt_017028380
25/136 - Collecting: mt_586517479
26/136 - Collecting: mt_970986264
27/136 - Collecting: mt_253209797
28/136 - Collecting: mt_586517254
29/136 - Collecting: mt_253209758
30/136 - Collecting: mt_741732549
31/136 - Collecting: mt_628643605
32/136 - Collecting: mt_586917853
33/136 - Collecting: mt_365470706
34/136 - Collecting: mt_628041411
35/136 - Collecting: mt_017528270
36/136 - Collecting: mt_586917169
37/136 - Collecting: mt_832794923
38/136 - Collecting: mt_628041488
39/136 - Collecting: mt_017528105
40/136 - Collecting: mt_194853915
41/136 - Collecting: mt_586917894
42/136 - Collecting: mt_970386731
43/136 - Collecting: mt_409265044
44/136 - Collecting: mt_970386792
45/136 - Collecting: mt_253109526
46/136 - Collecting: mt_017528159
47/136 - Collecting: mt_194875389
48/136 - Collecting: mt_628041433
49/136 - Collecting: mt_409265659
50/136 - Collecting: mt_194853540
51/136 - Collecting: mt_832794384
52/136 - Collecting: mt_365470635
53/136 - Collecting: mt_628041206
54/136 - Collecting: mt_409265022
55/136 - Collecting: mt_194853989
56/136 - Collecting: mt_741632462
57/136 - Collecting: mt_365470750
58/136 - Collecting: mt_253109037
59/136 - Collecting: mt_741632313
60/136 - Collecting: mt_741632474
61/136 - Collecting: mt_832794372
62/136 - Collecting: mt_970386804
63/136 - Collecting: mt_253109510
64/136 - Collecting: mt_253103375
65/136 - Collecting: mt_194757874
66/136 - Collecting: mt_365272412
67/136 - Collecting: mt_586313931
68/136 - Collecting: mt_017992945
69/136 - Collecting: mt_970448412
70/136 - Collecting: mt_409116174
71/136 - Collecting: mt_586331323
72/136 - Collecting: mt_253880866
73/136 - Collecting: mt_194775705
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
74/136 - Collecting: mt_741003094
75/136 - Collecting: mt_832669654
76/136 - Collecting: mt_970484347
77/136 - Collecting: mt_253808189
78/136 - Collecting: mt_741030657
79/136 - Collecting: mt_832696707
80/136 - Collecting: mt_628545099
81/136 - Collecting: mt_409161287
82/136 - Collecting: mt_017929532
83/136 - Collecting: mt_253888965
84/136 - Collecting: mt_365227285
85/136 - Collecting: mt_970449940
86/136 - Collecting: mt_017922348
87/136 - Collecting: mt_365277111
88/136 - Collecting: mt_194755657
89/136 - Collecting: mt_741047764
90/136 - Collecting: mt_832638874
91/136 - Collecting: mt_628526656
92/136 - Collecting: mt_409104412
93/136 - Collecting: mt_017910099
94/136 - Collecting: mt_586385534
95/136 - Collecting: mt_970479941
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
96/136 - Collecting: mt_586311426
97/136 - Collecting: mt_409849755
98/136 - Collecting: mt_628968312
99/136 - Collecting: mt_409845822
100/136 - Collecting: mt_017308393
101/136 - Collecting: mt_741571925
102/136 - Collecting: mt_628961906
103/136 - Collecting: mt_832082545
104/136 - Collecting: mt_365135807
105/136 - Collecting: mt_253728668
106/136 - Collecting: mt_586457453
107/136 - Collecting: mt_970296292
108/136 - Collecting: mt_253729726
109/136 - Collecting: mt_194613615
110/136 - Collecting: mt_741572574
111/136 - Collecting: mt_832084084
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
112/136 - Collecting: mt_365130135
113/136 - Collecting: mt_017308359
114/136 - Collecting: mt_586457494
115/136 - Collecting: mt_970296231
116/136 - Collecting: mt_253729710
117/136 - Collecting: mt_194613689
118/136 - Collecting: mt_741572562
119/136 - Collecting: mt_832084072
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
120/136 - Collecting: mt_365130123
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
121/136 - Collecting: mt_628961950
122/136 - Collecting: mt_409845811
123/136 - Collecting: mt_586457432
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
124/136 - Collecting: mt_970296248
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
125/136 - Collecting: mt_253729785
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
126/136 - Collecting: mt_194613673
127/136 - Collecting: mt_741572501
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
128/136 - Collecting: mt_365130114
129/136 - Collecting: mt_628961995
130/136 - Collecting: mt_017308334
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
131/136 - Collecting: mt_586457441
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
132/136 - Collecting: mt_970296227
133/136 - Collecting: mt_253729779
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
134/136 - Collecting: mt_832084008
135/136 - Collecting: mt_409845888
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
136/136 - Collecting: mt_194745184

In [176]:
saved_fa_cup_2021_22 = list(
    FA_CUP_SEASON_DIRS["2021_22"].glob("*.json")
)

print("Saved FA Cup 2021/22 files:", len(saved_fa_cup_2021_22))

Saved FA Cup 2021/22 files: 136

In [177]:
# Collect 2020/21 FA cup season

fa_cup_2020_21_matches = get_all_season_matches(
    FA_CUP_ID,
    FA_CUP_SEASONS["2020_21"]
)

print("Total matches returned:", len(fa_cup_2020_21_matches))

Total matches returned: 123

In [178]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in fa_cup_2020_21_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in fa_cup_2020_21_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in fa_cup_2020_21_matches
)))

Statuses:
Counter({'finished': 123})

Stages:
Counter({None: 116, 'quarter_final': 4, 'semi_final': 2, 'final': 1})

Unique IDs: 123

In [179]:
collect_fa_cup_baseline_data(
    "2020_21",
    fa_cup_2020_21_matches
)

1/123 - Collecting: mt_454289680
2/123 - Collecting: mt_080941822
3/123 - Collecting: mt_575328718
4/123 - Collecting: mt_080384858
5/123 - Collecting: mt_727529276
6/123 - Collecting: mt_575472796
7/123 - Collecting: mt_454857520
8/123 - Collecting: mt_080431273
9/123 - Collecting: mt_969114116
10/123 - Collecting: mt_616392964
11/123 - Collecting: mt_292675035
12/123 - Collecting: mt_080449442
13/123 - Collecting: mt_575223228
14/123 - Collecting: mt_969127808
15/123 - Collecting: mt_292676293
16/123 - Collecting: mt_303873654
17/123 - Collecting: mt_080488454
18/123 - Collecting: mt_131033013
19/123 - Collecting: mt_080488403
20/123 - Collecting: mt_848544578
21/123 - Collecting: mt_616311305
22/123 - Collecting: mt_303800844
23/123 - Collecting: mt_575277252
24/123 - Collecting: mt_454755440
25/123 - Collecting: mt_303800833
26/123 - Collecting: mt_616311360
27/123 - Collecting: mt_454755741
28/123 - Collecting: mt_969166198
29/123 - Collecting: mt_454755728
30/123 - Collecting: mt_575213723
31/123 - Collecting: mt_848544022
32/123 - Collecting: mt_616315263
33/123 - Collecting: mt_575856568
34/123 - Collecting: mt_969790906
35/123 - Collecting: mt_303635352
36/123 - Collecting: mt_292523200
37/123 - Collecting: mt_727471741
38/123 - Collecting: mt_303635304
39/123 - Collecting: mt_575856571
40/123 - Collecting: mt_969790967
41/123 - Collecting: mt_292523299
42/123 - Collecting: mt_080107072
43/123 - Collecting: mt_080107084
44/123 - Collecting: mt_616268689
45/123 - Collecting: mt_616268620
46/123 - Collecting: mt_848382892
47/123 - Collecting: mt_303635363
48/123 - Collecting: mt_575856582
49/123 - Collecting: mt_131914193
50/123 - Collecting: mt_848382848
51/123 - Collecting: mt_616268615
52/123 - Collecting: mt_454049458
53/123 - Collecting: mt_131914134
54/123 - Collecting: mt_727471717
55/123 - Collecting: mt_848382827
56/123 - Collecting: mt_727471732
57/123 - Collecting: mt_131913564
58/123 - Collecting: mt_080107013
59/123 - Collecting: mt_292523255
60/123 - Collecting: mt_454049497
61/123 - Collecting: mt_292523233
62/123 - Collecting: mt_454049401
63/123 - Collecting: mt_969790978
64/123 - Collecting: mt_292596689
65/123 - Collecting: mt_616213399
66/123 - Collecting: mt_969736012
67/123 - Collecting: mt_727496116
68/123 - Collecting: mt_292596615
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
69/123 - Collecting: mt_848345568
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
70/123 - Collecting: mt_575872231
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
71/123 - Collecting: mt_969761147
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
72/123 - Collecting: mt_848345507
73/123 - Collecting: mt_454057787
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
74/123 - Collecting: mt_131930083
75/123 - Collecting: mt_727429961
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
76/123 - Collecting: mt_616213355
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
77/123 - Collecting: mt_454057718
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
78/123 - Collecting: mt_080184494
79/123 - Collecting: mt_727429957
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
80/123 - Collecting: mt_131930074
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
81/123 - Collecting: mt_303608812
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
82/123 - Collecting: mt_303608824
83/123 - Collecting: mt_575872292
84/123 - Collecting: mt_303684756
85/123 - Collecting: mt_575739577
86/123 - Collecting: mt_303042641
87/123 - Collecting: mt_616105203
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
88/123 - Collecting: mt_969634730
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
89/123 - Collecting: mt_292918582
90/123 - Collecting: mt_131387978
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
91/123 - Collecting: mt_969643976
92/123 - Collecting: mt_727206726
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
93/123 - Collecting: mt_454512456
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
94/123 - Collecting: mt_969643960
95/123 - Collecting: mt_131378148
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
96/123 - Collecting: mt_292918571
97/123 - Collecting: mt_292535868
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
98/123 - Collecting: mt_848476376
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
99/123 - Collecting: mt_454521026
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
100/123 - Collecting: mt_080859151
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
101/123 - Collecting: mt_575793897
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
102/123 - Collecting: mt_727260400
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
103/123 - Collecting: mt_848476360
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
104/123 - Collecting: mt_303042628
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
105/123 - Collecting: mt_454521010
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
106/123 - Collecting: mt_080859198
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
107/123 - Collecting: mt_131387967
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
108/123 - Collecting: mt_727260455
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
109/123 - Collecting: mt_848476305
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
110/123 - Collecting: mt_727207939
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
111/123 - Collecting: mt_292981253
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
112/123 - Collecting: mt_131378131
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
113/123 - Collecting: mt_848467846
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
114/123 - Collecting: mt_303024301
115/123 - Collecting: mt_292981232
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
116/123 - Collecting: mt_727206710
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
117/123 - Collecting: mt_848467820
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
118/123 - Collecting: mt_303024358
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
119/123 - Collecting: mt_616150684
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
120/123 - Collecting: mt_969643399
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
121/123 - Collecting: mt_969634729
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
122/123 - Collecting: mt_575793836
123/123 - Collecting: mt_616150613

In [180]:
saved_fa_cup_2020_21 = list(
    FA_CUP_SEASON_DIRS["2020_21"].glob("*.json")
)

print("Saved FA Cup 2020/21 files:", len(saved_fa_cup_2020_21))

Saved FA Cup 2020/21 files: 123

In [181]:
# Collect 2024/25 FA cup season

fa_cup_2024_25_matches = get_all_season_matches(
    FA_CUP_ID,
    FA_CUP_SEASONS["2024_25"]
)

print("Total matches returned:", len(fa_cup_2024_25_matches))

Total matches returned: 123

In [182]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in fa_cup_2024_25_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in fa_cup_2024_25_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in fa_cup_2024_25_matches
)))

Statuses:
Counter({'finished': 123})

Stages:
Counter({None: 116, 'quarter_final': 4, 'semi_final': 2, 'final': 1})

Unique IDs: 123

In [183]:
collect_fa_cup_baseline_data(
    "2024_25",
    fa_cup_2024_25_matches
)

1/123 - Collecting: mt_585663327
2/123 - Collecting: mt_364231276
3/123 - Collecting: mt_837680699
4/123 - Collecting: mt_198066538
5/123 - Collecting: mt_251677092
6/123 - Collecting: mt_251683870
7/123 - Collecting: mt_620399414
8/123 - Collecting: mt_015210289
9/123 - Collecting: mt_837377827
10/123 - Collecting: mt_198988134
11/123 - Collecting: mt_746466717
12/123 - Collecting: mt_620200689
13/123 - Collecting: mt_251522823
14/123 - Collecting: mt_364644352
15/123 - Collecting: mt_402022497
16/123 - Collecting: mt_973661498
17/123 - Collecting: mt_251996825
18/123 - Collecting: mt_589634324
19/123 - Collecting: mt_620859536
20/123 - Collecting: mt_015793949
21/123 - Collecting: mt_837260652
22/123 - Collecting: mt_402918172
23/123 - Collecting: mt_973042411
24/123 - Collecting: mt_402945817
25/123 - Collecting: mt_015708392
26/123 - Collecting: mt_251387860
27/123 - Collecting: mt_364521273
28/123 - Collecting: mt_620859540
29/123 - Collecting: mt_973096401
30/123 - Collecting: mt_620861959
31/123 - Collecting: mt_198476709
32/123 - Collecting: mt_198474538
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
33/123 - Collecting: mt_251378723
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['statistics', 'odds']
34/123 - Collecting: mt_973028931
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
35/123 - Collecting: mt_362476802
36/123 - Collecting: mt_583918267
37/123 - Collecting: mt_258105659
38/123 - Collecting: mt_583918278
39/123 - Collecting: mt_362476851
40/123 - Collecting: mt_019521471
41/123 - Collecting: mt_019521414
42/123 - Collecting: mt_362476864
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
43/123 - Collecting: mt_625042464
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
44/123 - Collecting: mt_625042319
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
45/123 - Collecting: mt_836793980
46/123 - Collecting: mt_625042325
47/123 - Collecting: mt_974387177
48/123 - Collecting: mt_197859094
49/123 - Collecting: mt_401260757
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
50/123 - Collecting: mt_258105693
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
51/123 - Collecting: mt_740634916
52/123 - Collecting: mt_401260796
53/123 - Collecting: mt_258105022
54/123 - Collecting: mt_362476738
55/123 - Collecting: mt_836793547
56/123 - Collecting: mt_583918281
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
57/123 - Collecting: mt_019521482
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
58/123 - Collecting: mt_974387100
59/123 - Collecting: mt_836793526
60/123 - Collecting: mt_197859518
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
61/123 - Collecting: mt_974387166
62/123 - Collecting: mt_197859041
63/123 - Collecting: mt_625042383
64/123 - Collecting: mt_401871808
65/123 - Collecting: mt_019349314
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
66/123 - Collecting: mt_197607018
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
67/123 - Collecting: mt_625935919
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
68/123 - Collecting: mt_362182164
69/123 - Collecting: mt_019349371
70/123 - Collecting: mt_258770737
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
71/123 - Collecting: mt_625935925
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
72/123 - Collecting: mt_197607694
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
73/123 - Collecting: mt_362182102
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
74/123 - Collecting: mt_019349382
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
75/123 - Collecting: mt_974214266
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
76/123 - Collecting: mt_258768793
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
77/123 - Collecting: mt_197607641
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
78/123 - Collecting: mt_740590516
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
79/123 - Collecting: mt_362182151
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
80/123 - Collecting: mt_583423467
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
81/123 - Collecting: mt_974214200
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
82/123 - Collecting: mt_583423478
83/123 - Collecting: mt_583423481
84/123 - Collecting: mt_258690621
85/123 - Collecting: mt_362732574
86/123 - Collecting: mt_019209739
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
87/123 - Collecting: mt_197517469
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
88/123 - Collecting: mt_583153622
89/123 - Collecting: mt_258028365
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
90/123 - Collecting: mt_974894076
91/123 - Collecting: mt_625466820
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
92/123 - Collecting: mt_401644901
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
93/123 - Collecting: mt_019200713
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
94/123 - Collecting: mt_583155682
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
95/123 - Collecting: mt_974899078
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
96/123 - Collecting: mt_197517475
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
97/123 - Collecting: mt_836986264
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
98/123 - Collecting: mt_362732525
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
99/123 - Collecting: mt_625465896
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
100/123 - Collecting: mt_401641982
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
101/123 - Collecting: mt_974894021
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
102/123 - Collecting: mt_258028370
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
103/123 - Collecting: mt_836986202
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
104/123 - Collecting: mt_362732583
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
105/123 - Collecting: mt_401641971
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
106/123 - Collecting: mt_019209743
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
107/123 - Collecting: mt_974894018
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
108/123 - Collecting: mt_197517403
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
109/123 - Collecting: mt_740370191
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
110/123 - Collecting: mt_625465845
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
111/123 - Collecting: mt_019209724
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
112/123 - Collecting: mt_974894087
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
113/123 - Collecting: mt_258028309
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
114/123 - Collecting: mt_197517454
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
115/123 - Collecting: mt_625465829
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
116/123 - Collecting: mt_401641907
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
117/123 - Collecting: mt_019209712
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
118/123 - Collecting: mt_583153688
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
119/123 - Collecting: mt_258028353
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
120/123 - Collecting: mt_197517431
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
121/123 - Collecting: mt_740370126
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
122/123 - Collecting: mt_583153644
123/123 - Collecting: mt_401641968
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']

In [184]:
saved_fa_cup_2024_25 = list(
    FA_CUP_SEASON_DIRS["2024_25"].glob("*.json")
)

print("Saved FA Cup 2024/25 files:", len(saved_fa_cup_2024_25))

Saved FA Cup 2024/25 files: 123

In [185]:
# Collect 2025/26 FA cup season

fa_cup_2025_26_matches = get_all_season_matches(
    FA_CUP_ID,
    FA_CUP_SEASONS["2025_26"]
)

print("Total matches returned:", len(fa_cup_2025_26_matches))

Total matches returned: 123

In [186]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in fa_cup_2025_26_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in fa_cup_2025_26_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in fa_cup_2025_26_matches
)))

Statuses:
Counter({'finished': 123})

Stages:
Counter({None: 116, 'quarter_final': 4, 'semi_final': 2, 'final': 1})

Unique IDs: 123

In [187]:
collect_fa_cup_baseline_data(
    "2025_26",
    fa_cup_2025_26_matches
)

1/123 - Collecting: mt_155994774
2/123 - Collecting: mt_377560288
3/123 - Collecting: mt_644821534
4/123 - Collecting: mt_205617336
5/123 - Collecting: mt_159080065
6/123 - Collecting: mt_734969954
7/123 - Collecting: mt_893575504
8/123 - Collecting: mt_376648321
9/123 - Collecting: mt_734491561
10/123 - Collecting: mt_460794620
11/123 - Collecting: mt_893352068
12/123 - Collecting: mt_376685124
13/123 - Collecting: mt_205563715
14/123 - Collecting: mt_159904683
15/123 - Collecting: mt_518826492
16/123 - Collecting: mt_987768874
17/123 - Collecting: mt_986960210
18/123 - Collecting: mt_732721530
19/123 - Collecting: mt_894842090
20/123 - Collecting: mt_986960279
21/123 - Collecting: mt_641618944
22/123 - Collecting: mt_517576427
23/123 - Collecting: mt_986967877
24/123 - Collecting: mt_465459860
25/123 - Collecting: mt_986934793
26/123 - Collecting: mt_028087341
27/123 - Collecting: mt_028087328
28/123 - Collecting: mt_517576416
29/123 - Collecting: mt_153134658
30/123 - Collecting: mt_465459876
31/123 - Collecting: mt_370305178
32/123 - Collecting: mt_153880678
33/123 - Collecting: mt_732557045
34/123 - Collecting: mt_986287490
35/123 - Collecting: mt_209705812
36/123 - Collecting: mt_028321958
37/123 - Collecting: mt_153659777
38/123 - Collecting: mt_370176227
39/123 - Collecting: mt_894093609
40/123 - Collecting: mt_894093665
41/123 - Collecting: mt_732534005
42/123 - Collecting: mt_641942591
43/123 - Collecting: mt_894093670
44/123 - Collecting: mt_465860120
45/123 - Collecting: mt_209705878
46/123 - Collecting: mt_370176216
47/123 - Collecting: mt_153655607
48/123 - Collecting: mt_732534060
49/123 - Collecting: mt_641942504
50/123 - Collecting: mt_465860115
51/123 - Collecting: mt_028321997
52/123 - Collecting: mt_517418345
53/123 - Collecting: mt_153659766
54/123 - Collecting: mt_028321940
55/123 - Collecting: mt_986287414
56/123 - Collecting: mt_153659788
57/123 - Collecting: mt_517418396
58/123 - Collecting: mt_986287423
59/123 - Collecting: mt_732534059
60/123 - Collecting: mt_370176248
61/123 - Collecting: mt_641942552
62/123 - Collecting: mt_465860189
63/123 - Collecting: mt_517418329
64/123 - Collecting: mt_209551196
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['odds']
65/123 - Collecting: mt_641289183
66/123 - Collecting: mt_641289864
67/123 - Collecting: mt_153946487
68/123 - Collecting: mt_209537322
69/123 - Collecting: mt_894320280
70/123 - Collecting: mt_028173871
71/123 - Collecting: mt_894320426
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
72/123 - Collecting: mt_370651051
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
73/123 - Collecting: mt_465098596
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
74/123 - Collecting: mt_517864767
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
75/123 - Collecting: mt_986702600
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
76/123 - Collecting: mt_153946418
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
77/123 - Collecting: mt_732415170
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
78/123 - Collecting: mt_465098940
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
79/123 - Collecting: mt_028173708
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
80/123 - Collecting: mt_209537311
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
81/123 - Collecting: mt_732415165
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
82/123 - Collecting: mt_894320275
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
83/123 - Collecting: mt_370651538
84/123 - Collecting: mt_209367523
85/123 - Collecting: mt_153433101
86/123 - Collecting: mt_894244849
87/123 - Collecting: mt_641811633
88/123 - Collecting: mt_986066963
89/123 - Collecting: mt_153433197
90/123 - Collecting: mt_986066926
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
91/123 - Collecting: mt_209399273
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
92/123 - Collecting: mt_732122796
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
93/123 - Collecting: mt_370500381
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
94/123 - Collecting: mt_465955476
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
95/123 - Collecting: mt_028788041
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
96/123 - Collecting: mt_517677527
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
97/123 - Collecting: mt_209399202
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
98/123 - Collecting: mt_153433158
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
99/123 - Collecting: mt_732122730
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
100/123 - Collecting: mt_894244890
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
101/123 - Collecting: mt_370500378
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
102/123 - Collecting: mt_465955460
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
103/123 - Collecting: mt_028788028
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
104/123 - Collecting: mt_517677516
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
105/123 - Collecting: mt_986066979
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
106/123 - Collecting: mt_209399251
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
107/123 - Collecting: mt_732122745
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
108/123 - Collecting: mt_894244835
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
109/123 - Collecting: mt_370500367
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
110/123 - Collecting: mt_641811622
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
111/123 - Collecting: mt_465955405
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
112/123 - Collecting: mt_028788017
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
113/123 - Collecting: mt_517677575
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
114/123 - Collecting: mt_209399298
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
115/123 - Collecting: mt_732122729
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
116/123 - Collecting: mt_641811611
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
117/123 - Collecting: mt_465955459
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
118/123 - Collecting: mt_028788070
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
119/123 - Collecting: mt_517677569
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
120/123 - Collecting: mt_986066904
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
121/123 - Collecting: mt_209399237
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
122/123 - Collecting: mt_641811644
123/123 - Collecting: mt_153433136

In [188]:
saved_fa_cup_2025_26 = list(
    FA_CUP_SEASON_DIRS["2025_26"].glob("*.json")
)

print("Saved FA Cup 2025/26 files:", len(saved_fa_cup_2025_26))

Saved FA Cup 2025/26 files: 123

In [189]:
# Creating code to collect EFL Cup matches

EFL_CUP_ID = "comp_2504"

EFL_CUP_SEASONS = {
    "2026_27": "sn_4588470",
    "2025_26": "sn_1398983",
    "2024_25": "sn_5762314",
    "2023_24": "sn_595992",
    "2022_23": "sn_532755",
    "2021_22": "sn_311334",
    "2020_21": "sn_044278"
}

In [190]:
# Create separate folder for EFL Cup matches

EFL_CUP_DIR = RAW_MATCH_DIR / "efl_cup"

EFL_CUP_SEASON_DIRS = {}

for season_name in EFL_CUP_SEASONS:
    season_dir = EFL_CUP_DIR / season_name
    season_dir.mkdir(parents=True, exist_ok=True)
    EFL_CUP_SEASON_DIRS[season_name] = season_dir

In [191]:
# Collector for matches in EFL Cup

def collect_efl_cup_baseline_data(season_name, matches):
    season_dir = EFL_CUP_SEASON_DIRS[season_name]
    total_matches = len(matches)

    for i, match in enumerate(matches, start=1):
        match_id = match["id"]
        file_path = season_dir / f"{match_id}.json"

        if file_path.exists():
            print(f"{i}/{total_matches} - Skipping existing: {match_id}")
            continue

        print(f"{i}/{total_matches} - Collecting: {match_id}")

        match_data = get_baseline_match_data(match_id)

        if match_data is None:
            print("Skipped:", match_id)
            continue

        save_match_data(match_id, match_data, season_dir)
        time.sleep(1)

In [192]:
# Collect 2023/24 EFL Cup matches

efl_cup_2023_24_matches = get_all_season_matches(
    EFL_CUP_ID,
    EFL_CUP_SEASONS["2023_24"]
)

print("Total matches returned:", len(efl_cup_2023_24_matches))

Total matches returned: 93

In [193]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in efl_cup_2023_24_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in efl_cup_2023_24_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in efl_cup_2023_24_matches
)))

Statuses:
Counter({'finished': 93})

Stages:
Counter({None: 84, 'semi_final': 4, 'quarter_final': 4, 'final': 1})

Unique IDs: 93

In [194]:
collect_efl_cup_baseline_data(
    "2023_24",
    efl_cup_2023_24_matches
)

1/93 - Collecting: mt_014314841
2/93 - Collecting: mt_368727166
3/93 - Collecting: mt_623454921
4/93 - Collecting: mt_971847978
5/93 - Collecting: mt_014291013
6/93 - Collecting: mt_582797565
7/93 - Collecting: mt_256919238
8/93 - Collecting: mt_014858087
9/93 - Collecting: mt_971636903
10/93 - Collecting: mt_971007023
11/93 - Collecting: mt_582668645
12/93 - Collecting: mt_256335378
13/93 - Collecting: mt_749114159
14/93 - Collecting: mt_835223209
15/93 - Collecting: mt_407990915
16/93 - Collecting: mt_014771797
17/93 - Collecting: mt_190449466
18/93 - Collecting: mt_250101395
19/93 - Collecting: mt_624040810
20/93 - Collecting: mt_406262951
21/93 - Collecting: mt_581919672
22/93 - Collecting: mt_195858433
23/93 - Collecting: mt_743636121
24/93 - Collecting: mt_839797228
25/93 - Collecting: mt_367474554
26/93 - Collecting: mt_624045603
27/93 - Collecting: mt_839797232
28/93 - Collecting: mt_743636142
29/93 - Collecting: mt_367474503
30/93 - Collecting: mt_012525783
31/93 - Collecting: mt_978383068
32/93 - Collecting: mt_839796876
33/93 - Collecting: mt_367472341
34/93 - Collecting: mt_367207118
35/93 - Collecting: mt_012918308
36/93 - Collecting: mt_743023550
37/93 - Collecting: mt_839649000
38/93 - Collecting: mt_195735607
39/93 - Collecting: mt_012982391
40/93 - Collecting: mt_012982338
41/93 - Collecting: mt_624533062
42/93 - Collecting: mt_367207121
43/93 - Collecting: mt_624514953
44/93 - Collecting: mt_406156816
45/93 - Collecting: mt_581371437
46/93 - Collecting: mt_978468240
47/93 - Collecting: mt_250890772
48/93 - Collecting: mt_195735668
49/93 - Collecting: mt_624514994
50/93 - Collecting: mt_406156880
51/93 - Collecting: mt_581371446
52/93 - Collecting: mt_978468219
53/93 - Collecting: mt_250890761
54/93 - Collecting: mt_743023595
55/93 - Collecting: mt_839649055
56/93 - Collecting: mt_624514932
57/93 - Collecting: mt_367207187
58/93 - Collecting: mt_195560586
59/93 - Collecting: mt_367718715
60/93 - Collecting: mt_250076021
61/93 - Collecting: mt_581142195
62/93 - Collecting: mt_978821833
63/93 - Collecting: mt_367718720
64/93 - Collecting: mt_406687684
65/93 - Collecting: mt_839905904
66/93 - Collecting: mt_195560517
67/93 - Collecting: mt_743359375
68/93 - Collecting: mt_839905985
69/93 - Collecting: mt_367718737
70/93 - Collecting: mt_624493462
71/93 - Collecting: mt_406687645
72/93 - Collecting: mt_012234207
73/93 - Collecting: mt_250076018
74/93 - Collecting: mt_743359369
75/93 - Collecting: mt_839905979
76/93 - Collecting: mt_367718746
77/93 - Collecting: mt_624493401
78/93 - Collecting: mt_406687629
79/93 - Collecting: mt_012234290
80/93 - Collecting: mt_581142139
81/93 - Collecting: mt_978821844
82/93 - Collecting: mt_195560570
83/93 - Collecting: mt_743359303
84/93 - Collecting: mt_839905963
85/93 - Collecting: mt_624493458
86/93 - Collecting: mt_581142143
87/93 - Collecting: mt_250076076
88/93 - Collecting: mt_743359354
89/93 - Collecting: mt_978821899
90/93 - Collecting: mt_012234235
91/93 - Collecting: mt_978821822
92/93 - Collecting: mt_195560565
93/93 - Collecting: mt_250076087

In [195]:
saved_efl_cup_2023_24 = list(
    EFL_CUP_SEASON_DIRS["2023_24"].glob("*.json")
)

print("Saved EFL Cup 2023/24 files:", len(saved_efl_cup_2023_24))

Saved EFL Cup 2023/24 files: 93

In [196]:
# Collect 2022/23 EFL Cup season

efl_cup_2022_23_matches = get_all_season_matches(
    EFL_CUP_ID,
    EFL_CUP_SEASONS["2022_23"]
)

print("Total matches returned:", len(efl_cup_2022_23_matches))

Total matches returned: 93

In [197]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in efl_cup_2022_23_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in efl_cup_2022_23_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in efl_cup_2022_23_matches
)))

Statuses:
Counter({'finished': 93})

Stages:
Counter({None: 84, 'semi_final': 4, 'quarter_final': 4, 'final': 1})

Unique IDs: 93

In [198]:
collect_efl_cup_baseline_data(
    "2022_23",
    efl_cup_2022_23_matches
)

1/93 - Collecting: mt_833677780
2/93 - Collecting: mt_833629068
3/93 - Collecting: mt_977408402
4/93 - Collecting: mt_622584922
5/93 - Collecting: mt_255830751
6/93 - Collecting: mt_833055324
7/93 - Collecting: mt_400877542
8/93 - Collecting: mt_366188655
9/93 - Collecting: mt_622933166
10/93 - Collecting: mt_588286114
11/93 - Collecting: mt_400709662
12/93 - Collecting: mt_366865631
13/93 - Collecting: mt_622328263
14/93 - Collecting: mt_622328446
15/93 - Collecting: mt_011417229
16/93 - Collecting: mt_977170881
17/93 - Collecting: mt_833532386
18/93 - Collecting: mt_833222649
19/93 - Collecting: mt_833222623
20/93 - Collecting: mt_622888588
21/93 - Collecting: mt_199444736
22/93 - Collecting: mt_744111029
23/93 - Collecting: mt_400999159
24/93 - Collecting: mt_011777970
25/93 - Collecting: mt_255333837
26/93 - Collecting: mt_199444740
27/93 - Collecting: mt_255333898
28/93 - Collecting: mt_366555206
29/93 - Collecting: mt_588666369
30/93 - Collecting: mt_744111013
31/93 - Collecting: mt_400999844
32/93 - Collecting: mt_011777305
33/93 - Collecting: mt_588666453
34/93 - Collecting: mt_193144591
35/93 - Collecting: mt_834822936
36/93 - Collecting: mt_405499606
37/93 - Collecting: mt_259233092
38/93 - Collecting: mt_976969119
39/93 - Collecting: mt_976900886
40/93 - Collecting: mt_259233003
41/93 - Collecting: mt_742711346
42/93 - Collecting: mt_360355761
43/93 - Collecting: mt_621688423
44/93 - Collecting: mt_018077211
45/93 - Collecting: mt_976900870
46/93 - Collecting: mt_193144538
47/93 - Collecting: mt_742711320
48/93 - Collecting: mt_834822940
49/93 - Collecting: mt_360355708
50/93 - Collecting: mt_621688414
51/93 - Collecting: mt_405499650
52/93 - Collecting: mt_018077288
53/93 - Collecting: mt_587566176
54/93 - Collecting: mt_976900809
55/93 - Collecting: mt_193144547
56/93 - Collecting: mt_834828345
57/93 - Collecting: mt_259233031
58/93 - Collecting: mt_587566187
59/93 - Collecting: mt_834065702
60/93 - Collecting: mt_742506202
61/93 - Collecting: mt_259780362
62/93 - Collecting: mt_193675408
63/93 - Collecting: mt_621954834
64/93 - Collecting: mt_259780301
65/93 - Collecting: mt_193675457
66/93 - Collecting: mt_405816970
67/93 - Collecting: mt_834067462
68/93 - Collecting: mt_360124013
69/93 - Collecting: mt_621950190
70/93 - Collecting: mt_405812581
71/93 - Collecting: mt_018395833
72/93 - Collecting: mt_587439742
73/93 - Collecting: mt_976243628
74/93 - Collecting: mt_259781975
75/93 - Collecting: mt_193678363
76/93 - Collecting: mt_742506251
77/93 - Collecting: mt_834067458
78/93 - Collecting: mt_360124084
79/93 - Collecting: mt_621950135
80/93 - Collecting: mt_405812578
81/93 - Collecting: mt_018395844
82/93 - Collecting: mt_587439721
83/93 - Collecting: mt_976243617
84/93 - Collecting: mt_259781969
85/93 - Collecting: mt_193678304
86/93 - Collecting: mt_742506237
87/93 - Collecting: mt_834067497
88/93 - Collecting: mt_360124072
89/93 - Collecting: mt_621950149
90/93 - Collecting: mt_405812567
91/93 - Collecting: mt_018395822
92/93 - Collecting: mt_976248089
93/93 - Collecting: mt_018911501

In [199]:
saved_efl_cup_2022_23 = list(
    EFL_CUP_SEASON_DIRS["2022_23"].glob("*.json")
)

print("Saved EFL Cup 2022/23 files:", len(saved_efl_cup_2022_23))

Saved EFL Cup 2022/23 files: 93

In [200]:
# Collect 2021/22 FA Cup season

efl_cup_2021_22_matches = get_all_season_matches(
    EFL_CUP_ID,
    EFL_CUP_SEASONS["2021_22"]
)

print("Total matches returned:", len(efl_cup_2021_22_matches))

Total matches returned: 93

In [201]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in efl_cup_2021_22_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in efl_cup_2021_22_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in efl_cup_2021_22_matches
)))

Statuses:
Counter({'finished': 93})

Stages:
Counter({None: 84, 'semi_final': 4, 'quarter_final': 4, 'final': 1})

Unique IDs: 93

In [202]:
collect_efl_cup_baseline_data(
    "2021_22",
    efl_cup_2021_22_matches
)

1/93 - Collecting: mt_253281021
2/93 - Collecting: mt_741742974
3/93 - Collecting: mt_365438832
4/93 - Collecting: mt_741679977
5/93 - Collecting: mt_628063369
6/93 - Collecting: mt_628585844
7/93 - Collecting: mt_409191960
8/93 - Collecting: mt_017979728
9/93 - Collecting: mt_586363616
10/93 - Collecting: mt_832598327
11/93 - Collecting: mt_365873652
12/93 - Collecting: mt_017420172
13/93 - Collecting: mt_586215868
14/93 - Collecting: mt_970189706
15/93 - Collecting: mt_741937417
16/93 - Collecting: mt_628346289
17/93 - Collecting: mt_253602533
18/93 - Collecting: mt_586174265
19/93 - Collecting: mt_970862103
20/93 - Collecting: mt_970862894
21/93 - Collecting: mt_253097027
22/93 - Collecting: mt_832940983
23/93 - Collecting: mt_017283200
24/93 - Collecting: mt_253097638
25/93 - Collecting: mt_194536046
26/93 - Collecting: mt_741325919
27/93 - Collecting: mt_832940529
28/93 - Collecting: mt_365701856
29/93 - Collecting: mt_628419381
30/93 - Collecting: mt_409658799
31/93 - Collecting: mt_586174159
32/93 - Collecting: mt_194536510
33/93 - Collecting: mt_741325373
34/93 - Collecting: mt_409071641
35/93 - Collecting: mt_586823273
36/93 - Collecting: mt_017149479
37/93 - Collecting: mt_365682744
38/93 - Collecting: mt_628235328
39/93 - Collecting: mt_409071754
40/93 - Collecting: mt_017149485
41/93 - Collecting: mt_970714162
42/93 - Collecting: mt_253568696
43/93 - Collecting: mt_194907035
44/93 - Collecting: mt_832356544
45/93 - Collecting: mt_365682805
46/93 - Collecting: mt_628235386
47/93 - Collecting: mt_409071792
48/93 - Collecting: mt_017149203
49/93 - Collecting: mt_586823152
50/93 - Collecting: mt_253568025
51/93 - Collecting: mt_194907513
52/93 - Collecting: mt_741490371
53/93 - Collecting: mt_832356978
54/93 - Collecting: mt_628235405
55/93 - Collecting: mt_409071628
56/93 - Collecting: mt_365682860
57/93 - Collecting: mt_741490924
58/93 - Collecting: mt_970714898
59/93 - Collecting: mt_586642442
60/93 - Collecting: mt_194460663
61/93 - Collecting: mt_253376769
62/93 - Collecting: mt_365518172
63/93 - Collecting: mt_586642418
64/93 - Collecting: mt_365518113
65/93 - Collecting: mt_017734322
66/93 - Collecting: mt_017734399
67/93 - Collecting: mt_586642434
68/93 - Collecting: mt_970021241
69/93 - Collecting: mt_253376780
70/93 - Collecting: mt_741159502
71/93 - Collecting: mt_832205062
72/93 - Collecting: mt_628893990
73/93 - Collecting: mt_409987881
74/93 - Collecting: mt_017734333
75/93 - Collecting: mt_970021228
76/93 - Collecting: mt_253376775
77/93 - Collecting: mt_741159551
78/93 - Collecting: mt_832205058
79/93 - Collecting: mt_628893935
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
80/93 - Collecting: mt_409987878
81/93 - Collecting: mt_017734344
82/93 - Collecting: mt_586642421
83/93 - Collecting: mt_194460604
84/93 - Collecting: mt_832205097
85/93 - Collecting: mt_628893949
86/93 - Collecting: mt_970021286
87/93 - Collecting: mt_253376703
88/93 - Collecting: mt_194460691
89/93 - Collecting: mt_970021217
90/93 - Collecting: mt_365518184
91/93 - Collecting: mt_741159537
92/93 - Collecting: mt_194460679
93/93 - Collecting: mt_409987867

In [203]:
saved_efl_cup_2021_22 = list(
    EFL_CUP_SEASON_DIRS["2021_22"].glob("*.json")
)

print("Saved EFL Cup 2021/22 files:", len(saved_efl_cup_2021_22))

Saved EFL Cup 2021/22 files: 93

In [204]:
# Collect 2020/21 FA Cup season

efl_cup_2020_21_matches = get_all_season_matches(
    EFL_CUP_ID,
    EFL_CUP_SEASONS["2020_21"]
)

print("Total matches returned:", len(efl_cup_2020_21_matches))

Total matches returned: 90

In [205]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in efl_cup_2020_21_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in efl_cup_2020_21_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in efl_cup_2020_21_matches
)))

Statuses:
Counter({'finished': 90})

Stages:
Counter({None: 83, 'quarter_final': 4, 'semi_final': 2, 'final': 1})

Unique IDs: 90

In [206]:
collect_efl_cup_baseline_data(
    "2020_21",
    efl_cup_2020_21_matches
)

1/90 - Collecting: mt_080205127
2/90 - Collecting: mt_454682996
3/90 - Collecting: mt_616490883
4/90 - Collecting: mt_575758248
5/90 - Collecting: mt_454540787
6/90 - Collecting: mt_080801432
7/90 - Collecting: mt_969697126
8/90 - Collecting: mt_726777244
9/90 - Collecting: mt_291222956
10/90 - Collecting: mt_138111395
11/90 - Collecting: mt_847888434
12/90 - Collecting: mt_610666116
13/90 - Collecting: mt_452444552
14/90 - Collecting: mt_304333065
15/90 - Collecting: mt_969000020
16/90 - Collecting: mt_963940710
17/90 - Collecting: mt_304325678
18/90 - Collecting: mt_085097141
19/90 - Collecting: mt_847862356
20/90 - Collecting: mt_579536827
21/90 - Collecting: mt_452419060
22/90 - Collecting: mt_085097128
23/90 - Collecting: mt_726701496
24/90 - Collecting: mt_610658233
25/90 - Collecting: mt_847862390
26/90 - Collecting: mt_610658244
27/90 - Collecting: mt_138174958
28/90 - Collecting: mt_304325681
29/90 - Collecting: mt_452419076
30/90 - Collecting: mt_726701430
31/90 - Collecting: mt_847828228
32/90 - Collecting: mt_452494998
33/90 - Collecting: mt_579565661
34/90 - Collecting: mt_963903996
35/90 - Collecting: mt_138141433
36/90 - Collecting: mt_963909007
37/90 - Collecting: mt_085075002
38/90 - Collecting: mt_579569558
39/90 - Collecting: mt_726716766
40/90 - Collecting: mt_963909068
41/90 - Collecting: mt_291232395
42/90 - Collecting: mt_726717121
43/90 - Collecting: mt_085070774
44/90 - Collecting: mt_452492447
45/90 - Collecting: mt_291232339
46/90 - Collecting: mt_304354332
47/90 - Collecting: mt_610686885
48/90 - Collecting: mt_726716777
49/90 - Collecting: mt_847827887
50/90 - Collecting: mt_138148181
51/90 - Collecting: mt_291231223
52/90 - Collecting: mt_304353554
53/90 - Collecting: mt_138141444
54/90 - Collecting: mt_610680669
55/90 - Collecting: mt_847827876
56/90 - Collecting: mt_963430460
57/90 - Collecting: mt_304433715
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['odds']
58/90 - Collecting: mt_579396377
59/90 - Collecting: mt_291813832
60/90 - Collecting: mt_138784748
61/90 - Collecting: mt_726061010
62/90 - Collecting: mt_847672620
63/90 - Collecting: mt_304245258
64/90 - Collecting: mt_610508584
65/90 - Collecting: mt_452129190
66/90 - Collecting: mt_291813721
67/90 - Collecting: mt_138784617
68/90 - Collecting: mt_726061575
69/90 - Collecting: mt_304245137
70/90 - Collecting: mt_610508962
71/90 - Collecting: mt_452129845
72/90 - Collecting: mt_085957307
73/90 - Collecting: mt_610508958
74/90 - Collecting: mt_452129884
75/90 - Collecting: mt_085957335
76/90 - Collecting: mt_579396443
77/90 - Collecting: mt_963430222
78/90 - Collecting: mt_726061554
79/90 - Collecting: mt_291813776
80/90 - Collecting: mt_138784665
81/90 - Collecting: mt_452145845
82/90 - Collecting: mt_847672004
83/90 - Collecting: mt_452129569
84/90 - Collecting: mt_610508141
85/90 - Collecting: mt_610561962
86/90 - Collecting: mt_085957810
87/90 - Collecting: mt_847672499
88/90 - Collecting: mt_304245076
89/90 - Collecting: mt_291813957
90/90 - Collecting: mt_138784390

In [207]:
saved_efl_cup_2020_21 = list(
    EFL_CUP_SEASON_DIRS["2020_21"].glob("*.json")
)

print("Saved EFL Cup 2020/21 files:", len(saved_efl_cup_2020_21))

Saved EFL Cup 2020/21 files: 90

In [208]:
# Collect 2024/25 FA Cup season

efl_cup_2024_25_matches = get_all_season_matches(
    EFL_CUP_ID,
    EFL_CUP_SEASONS["2024_25"]
)

print("Total matches returned:", len(efl_cup_2024_25_matches))

Total matches returned: 93

In [209]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in efl_cup_2024_25_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in efl_cup_2024_25_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in efl_cup_2024_25_matches
)))

Statuses:
Counter({'finished': 93})

Stages:
Counter({None: 91, 'final': 1, 'semi_final': 1})

Unique IDs: 93

In [210]:
collect_efl_cup_baseline_data(
    "2024_25",
    efl_cup_2024_25_matches
)

1/93 - Collecting: mt_746402015
2/93 - Collecting: mt_401468670
3/93 - Collecting: mt_625649434
4/93 - Collecting: mt_197156557
5/93 - Collecting: mt_258207001
6/93 - Collecting: mt_197648316
7/93 - Collecting: mt_258731531
8/93 - Collecting: mt_197648947
9/93 - Collecting: mt_740516415
10/93 - Collecting: mt_740496537
11/93 - Collecting: mt_740479467
12/93 - Collecting: mt_362684172
13/93 - Collecting: mt_625230949
14/93 - Collecting: mt_974713286
15/93 - Collecting: mt_019145322
16/93 - Collecting: mt_583829418
17/93 - Collecting: mt_836357097
18/93 - Collecting: mt_974779168
19/93 - Collecting: mt_362582672
20/93 - Collecting: mt_974014728
21/93 - Collecting: mt_583623842
22/93 - Collecting: mt_401924512
23/93 - Collecting: mt_974014770
24/93 - Collecting: mt_836256340
25/93 - Collecting: mt_197440830
26/93 - Collecting: mt_019774580
27/93 - Collecting: mt_019774527
28/93 - Collecting: mt_740119635
29/93 - Collecting: mt_625883042
30/93 - Collecting: mt_401997265
31/93 - Collecting: mt_625883021
32/93 - Collecting: mt_401997294
33/93 - Collecting: mt_258336158
34/93 - Collecting: mt_196193483
35/93 - Collecting: mt_830834268
36/93 - Collecting: mt_361360524
37/93 - Collecting: mt_013505780
38/93 - Collecting: mt_196818430
39/93 - Collecting: mt_257121336
40/93 - Collecting: mt_972976047
41/93 - Collecting: mt_972393064
42/93 - Collecting: mt_361434500
43/93 - Collecting: mt_013018753
44/93 - Collecting: mt_584587692
45/93 - Collecting: mt_257259315
46/93 - Collecting: mt_745742161
47/93 - Collecting: mt_629621855
48/93 - Collecting: mt_408405918
49/93 - Collecting: mt_013018794
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['odds']
50/93 - Collecting: mt_584587631
51/93 - Collecting: mt_408242909
52/93 - Collecting: mt_584959679
53/93 - Collecting: mt_257121397
54/93 - Collecting: mt_745676123
55/93 - Collecting: mt_830787243
56/93 - Collecting: mt_629060818
57/93 - Collecting: mt_408242994
58/93 - Collecting: mt_972976038
59/93 - Collecting: mt_361861854
60/93 - Collecting: mt_830530987
61/93 - Collecting: mt_584284197
62/93 - Collecting: mt_257657639
63/93 - Collecting: mt_584284414
64/93 - Collecting: mt_629329920
65/93 - Collecting: mt_408708801
66/93 - Collecting: mt_972172278
67/93 - Collecting: mt_830530048
68/93 - Collecting: mt_972172168
69/93 - Collecting: mt_257657695
70/93 - Collecting: mt_196096033
71/93 - Collecting: mt_830530528
72/93 - Collecting: mt_629329385
73/93 - Collecting: mt_408708798
74/93 - Collecting: mt_013413474
75/93 - Collecting: mt_584284261
76/93 - Collecting: mt_972172107
77/93 - Collecting: mt_196096044
78/93 - Collecting: mt_745945377
79/93 - Collecting: mt_361861732
80/93 - Collecting: mt_629329469
81/93 - Collecting: mt_013413202
82/93 - Collecting: mt_584284158
83/93 - Collecting: mt_972172896
84/93 - Collecting: mt_257657023
85/93 - Collecting: mt_196096581
86/93 - Collecting: mt_745945366
87/93 - Collecting: mt_361861741
88/93 - Collecting: mt_408708626
89/93 - Collecting: mt_972172830
90/93 - Collecting: mt_196096578
91/93 - Collecting: mt_361861104
92/93 - Collecting: mt_745945921
93/93 - Collecting: mt_408708647

In [211]:
saved_efl_cup_2024_25 = list(
    EFL_CUP_SEASON_DIRS["2024_25"].glob("*.json")
)

print("Saved EFL Cup 2024/25 files:", len(saved_efl_cup_2024_25))

Saved EFL Cup 2024/25 files: 93

In [212]:
# Collect 2025/26 FA Cup season

efl_cup_2025_26_matches = get_all_season_matches(
    EFL_CUP_ID,
    EFL_CUP_SEASONS["2025_26"]
)

print("Total matches returned:", len(efl_cup_2025_26_matches))

Total matches returned: 93

In [213]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in efl_cup_2025_26_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in efl_cup_2025_26_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in efl_cup_2025_26_matches
)))

Statuses:
Counter({'finished': 93})

Stages:
Counter({None: 84, 'semi_final': 4, 'quarter_final': 4, 'final': 1})

Unique IDs: 93

In [214]:
collect_efl_cup_baseline_data(
    "2025_26",
    efl_cup_2025_26_matches
)

1/93 - Collecting: mt_734246357
2/93 - Collecting: mt_209892338
3/93 - Collecting: mt_209879302
4/93 - Collecting: mt_153763458
5/93 - Collecting: mt_153738138
6/93 - Collecting: mt_894457408
7/93 - Collecting: mt_153308373
8/93 - Collecting: mt_209961985
9/93 - Collecting: mt_732296201
10/93 - Collecting: mt_027578092
11/93 - Collecting: mt_648081659
12/93 - Collecting: mt_980306946
13/93 - Collecting: mt_203139283
14/93 - Collecting: mt_154843161
15/93 - Collecting: mt_731612756
16/93 - Collecting: mt_469295417
17/93 - Collecting: mt_516967538
18/93 - Collecting: mt_980170934
19/93 - Collecting: mt_375865336
20/93 - Collecting: mt_648328661
21/93 - Collecting: mt_516286599
22/93 - Collecting: mt_203653217
23/93 - Collecting: mt_469705995
24/93 - Collecting: mt_203653228
25/93 - Collecting: mt_154094116
26/93 - Collecting: mt_731941779
27/93 - Collecting: mt_892532889
28/93 - Collecting: mt_469709449
29/93 - Collecting: mt_027417050
30/93 - Collecting: mt_980170993
31/93 - Collecting: mt_516286555
32/93 - Collecting: mt_154094180
33/93 - Collecting: mt_027418777
34/93 - Collecting: mt_892436582
35/93 - Collecting: mt_154397019
36/93 - Collecting: mt_516783292
37/93 - Collecting: mt_980674138
38/93 - Collecting: mt_648126810
39/93 - Collecting: mt_892338537
40/93 - Collecting: mt_375063575
41/93 - Collecting: mt_516785684
42/93 - Collecting: mt_980673972
43/93 - Collecting: mt_203951256
44/93 - Collecting: mt_154398195
45/93 - Collecting: mt_516783254
46/93 - Collecting: mt_731240972
47/93 - Collecting: mt_375062843
48/93 - Collecting: mt_648125300
49/93 - Collecting: mt_469501721
50/93 - Collecting: mt_203958615
51/93 - Collecting: mt_154397083
52/93 - Collecting: mt_731240961
53/93 - Collecting: mt_892436568
54/93 - Collecting: mt_980674191
55/93 - Collecting: mt_203958620
56/93 - Collecting: mt_027819453
57/93 - Collecting: mt_154390755
58/93 - Collecting: mt_363875081
59/93 - Collecting: mt_191054301
60/93 - Collecting: mt_979180610
61/93 - Collecting: mt_626348144
62/93 - Collecting: mt_979180679
63/93 - Collecting: mt_363875067
64/93 - Collecting: mt_469977808
65/93 - Collecting: mt_626348199
66/93 - Collecting: mt_404769587
67/93 - Collecting: mt_010427832
68/93 - Collecting: mt_585216748
69/93 - Collecting: mt_838592456
70/93 - Collecting: mt_626348133
71/93 - Collecting: mt_404769576
72/93 - Collecting: mt_585216727
73/93 - Collecting: mt_252603902
74/93 - Collecting: mt_747931230
75/93 - Collecting: mt_363875078
76/93 - Collecting: mt_404769560
77/93 - Collecting: mt_010427828
78/93 - Collecting: mt_585216716
79/93 - Collecting: mt_252603951
80/93 - Collecting: mt_191054397
81/93 - Collecting: mt_747931245
82/93 - Collecting: mt_838592435
83/93 - Collecting: mt_404769505
84/93 - Collecting: mt_010427817
85/93 - Collecting: mt_585216775
86/93 - Collecting: mt_979180663
87/93 - Collecting: mt_203337830
88/93 - Collecting: mt_252603973
89/93 - Collecting: mt_010427841
90/93 - Collecting: mt_191054358
91/93 - Collecting: mt_838592490
92/93 - Collecting: mt_010339701
93/93 - Collecting: mt_585443657

In [215]:
saved_efl_cup_2025_26 = list(
    EFL_CUP_SEASON_DIRS["2025_26"].glob("*.json")
)

print("Saved EFL Cup 2025/26 files:", len(saved_efl_cup_2025_26))

Saved EFL Cup 2025/26 files: 93

In [216]:
# Create code to collect UEFA Europa League seasons

EUROPA_LEAGUE_ID = "comp_7739"

EUROPA_LEAGUE_SEASONS = {
    "2026_27": "sn_9624824",
    "2025_26": "sn_0819325",
    "2024_25": "sn_4596897",
    "2023_24": "sn_008323",
    "2022_23": "sn_706199",
    "2021_22": "sn_481111",
    "2020_21": "sn_522881"
}

In [217]:
# Create a folder for UEFA Europa League matches

EUROPA_LEAGUE_DIR = RAW_MATCH_DIR / "europa_league"

EUROPA_LEAGUE_SEASON_DIRS = {}

for season_name in EUROPA_LEAGUE_SEASONS:
    season_dir = EUROPA_LEAGUE_DIR / season_name
    season_dir.mkdir(parents=True, exist_ok=True)
    EUROPA_LEAGUE_SEASON_DIRS[season_name] = season_dir

In [218]:
# Create the collector for Europa League seasons

def collect_europa_league_baseline_data(season_name, matches):
    season_dir = EUROPA_LEAGUE_SEASON_DIRS[season_name]
    total_matches = len(matches)

    for i, match in enumerate(matches, start=1):
        match_id = match["id"]
        file_path = season_dir / f"{match_id}.json"

        if file_path.exists():
            print(f"{i}/{total_matches} - Skipping existing: {match_id}")
            continue

        print(f"{i}/{total_matches} - Collecting: {match_id}")

        match_data = get_baseline_match_data(match_id)

        if match_data is None:
            print("Skipped:", match_id)
            continue

        save_match_data(match_id, match_data, season_dir)
        time.sleep(1)

In [ ]:
# Collect 2023/24 Europa League season

europa_2023_24_matches = get_all_season_matches(
    EUROPA_LEAGUE_ID,
    EUROPA_LEAGUE_SEASONS["2023_24"]
)

print("Total matches returned:", len(europa_2023_24_matches))

Total matches returned: 175

In [220]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in europa_2023_24_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in europa_2023_24_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in europa_2023_24_matches
)))

Statuses:
Counter({'finished': 175})

Stages:
Counter({None: 96, 'round_of_16': 52, 'qualifying': 14, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 175

In [221]:
collect_europa_league_baseline_data(
    "2023_24",
    europa_2023_24_matches
)

1/175 - Collecting: mt_582571997
2/175 - Collecting: mt_971968330
3/175 - Collecting: mt_256290182
4/175 - Collecting: mt_190135878
5/175 - Collecting: mt_835849760
6/175 - Collecting: mt_623614054
7/175 - Collecting: mt_014082598
8/175 - Collecting: mt_749676647
9/175 - Collecting: mt_835787737
10/175 - Collecting: mt_582571936
11/175 - Collecting: mt_971968329
12/175 - Collecting: mt_368434462
13/175 - Collecting: mt_623060029
14/175 - Collecting: mt_749069630
15/175 - Collecting: mt_835675790
16/175 - Collecting: mt_014954528
17/175 - Collecting: mt_971431379
18/175 - Collecting: mt_368248478
19/175 - Collecting: mt_623503044
20/175 - Collecting: mt_407127260
21/175 - Collecting: mt_582392916
22/175 - Collecting: mt_190780836
23/175 - Collecting: mt_835675749
24/175 - Collecting: mt_368248406
25/175 - Collecting: mt_407127259
26/175 - Collecting: mt_256816198
27/175 - Collecting: mt_623503011
28/175 - Collecting: mt_014954570
29/175 - Collecting: mt_749069629
30/175 - Collecting: mt_368711031
31/175 - Collecting: mt_256077912
32/175 - Collecting: mt_256077981
33/175 - Collecting: mt_835900465
34/175 - Collecting: mt_623499163
35/175 - Collecting: mt_014233801
36/175 - Collecting: mt_190566388
37/175 - Collecting: mt_368711048
38/175 - Collecting: mt_190566300
39/175 - Collecting: mt_749355293
40/175 - Collecting: mt_582144772
41/175 - Collecting: mt_835900428
42/175 - Collecting: mt_971822614
43/175 - Collecting: mt_256077967
44/175 - Collecting: mt_256077906
45/175 - Collecting: mt_014233874
46/175 - Collecting: mt_250170936
47/175 - Collecting: mt_367417055
48/175 - Collecting: mt_624094866
49/175 - Collecting: mt_581941654
50/175 - Collecting: mt_978328091
51/175 - Collecting: mt_743653172
52/175 - Collecting: mt_012532753
53/175 - Collecting: mt_250170315
54/175 - Collecting: mt_624094118
55/175 - Collecting: mt_012532875
56/175 - Collecting: mt_406286942
57/175 - Collecting: mt_250170320
58/175 - Collecting: mt_195865419
59/175 - Collecting: mt_367417543
60/175 - Collecting: mt_624094800
61/175 - Collecting: mt_978328038
62/175 - Collecting: mt_014882333
63/175 - Collecting: mt_250170997
64/175 - Collecting: mt_195865330
65/175 - Collecting: mt_839709443
66/175 - Collecting: mt_195865345
67/175 - Collecting: mt_839709424
68/175 - Collecting: mt_012532709
69/175 - Collecting: mt_839709282
70/175 - Collecting: mt_406286921
71/175 - Collecting: mt_581941692
72/175 - Collecting: mt_978328664
73/175 - Collecting: mt_743653223
74/175 - Collecting: mt_367417000
75/175 - Collecting: mt_406286594
76/175 - Collecting: mt_581941763
77/175 - Collecting: mt_978328602
78/175 - Collecting: mt_743653214
79/175 - Collecting: mt_367417524
80/175 - Collecting: mt_406286905
81/175 - Collecting: mt_978328063
82/175 - Collecting: mt_839709249
83/175 - Collecting: mt_624094811
84/175 - Collecting: mt_581941669
85/175 - Collecting: mt_978327992
86/175 - Collecting: mt_624092606
87/175 - Collecting: mt_978328047
88/175 - Collecting: mt_406286987
89/175 - Collecting: mt_250170373
90/175 - Collecting: mt_195865401
91/175 - Collecting: mt_367417581
92/175 - Collecting: mt_012532728
93/175 - Collecting: mt_195865497
94/175 - Collecting: mt_624094888
95/175 - Collecting: mt_012532794
96/175 - Collecting: mt_581941648
97/175 - Collecting: mt_743653196
98/175 - Collecting: mt_406286976
99/175 - Collecting: mt_978328079
100/175 - Collecting: mt_250170351
101/175 - Collecting: mt_839709223
102/175 - Collecting: mt_250170389
103/175 - Collecting: mt_367417567
104/175 - Collecting: mt_624094822
105/175 - Collecting: mt_012532717
106/175 - Collecting: mt_367417506
107/175 - Collecting: mt_743653113
108/175 - Collecting: mt_250175226
109/175 - Collecting: mt_839703884
110/175 - Collecting: mt_624094855
111/175 - Collecting: mt_195865474
112/175 - Collecting: mt_743653157
113/175 - Collecting: mt_624094899
114/175 - Collecting: mt_978328026
115/175 - Collecting: mt_839709256
116/175 - Collecting: mt_581941616
117/175 - Collecting: mt_743653145
118/175 - Collecting: mt_839709290
119/175 - Collecting: mt_367417578
120/175 - Collecting: mt_250170398
121/175 - Collecting: mt_743653129
122/175 - Collecting: mt_406286959
123/175 - Collecting: mt_012532770
124/175 - Collecting: mt_743654774
125/175 - Collecting: mt_367416335
126/175 - Collecting: mt_581941675
127/175 - Collecting: mt_195865436
128/175 - Collecting: mt_978328004
129/175 - Collecting: mt_250170337
130/175 - Collecting: mt_195865440
131/175 - Collecting: mt_367417550
132/175 - Collecting: mt_195869115
133/175 - Collecting: mt_406280422
134/175 - Collecting: mt_839709268
135/175 - Collecting: mt_581941631
136/175 - Collecting: mt_839709207
137/175 - Collecting: mt_367417512
138/175 - Collecting: mt_012532732
139/175 - Collecting: mt_624094833
140/175 - Collecting: mt_406286960
141/175 - Collecting: mt_839709235
142/175 - Collecting: mt_581348281
143/175 - Collecting: mt_195769094
144/175 - Collecting: mt_743011070
145/175 - Collecting: mt_978427177
146/175 - Collecting: mt_743054927
147/175 - Collecting: mt_250886721
148/175 - Collecting: mt_250875605
149/175 - Collecting: mt_250875659
150/175 - Collecting: mt_839655245
151/175 - Collecting: mt_195769053
152/175 - Collecting: mt_624592319
153/175 - Collecting: mt_012931482
154/175 - Collecting: mt_406180708
155/175 - Collecting: mt_195705163
156/175 - Collecting: mt_743570640
157/175 - Collecting: mt_978441233
158/175 - Collecting: mt_012931414
159/175 - Collecting: mt_406180757
160/175 - Collecting: mt_367216802
161/175 - Collecting: mt_581348278
162/175 - Collecting: mt_195671071
163/175 - Collecting: mt_367123821
164/175 - Collecting: mt_406814716
165/175 - Collecting: mt_978241327
166/175 - Collecting: mt_406814727
167/175 - Collecting: mt_978249136
168/175 - Collecting: mt_367123834
169/175 - Collecting: mt_581439146
170/175 - Collecting: mt_978243819
171/175 - Collecting: mt_250781061
172/175 - Collecting: mt_743509504
173/175 - Collecting: mt_195678507
174/175 - Collecting: mt_406812654
175/175 - Collecting: mt_012395285

In [222]:
saved_europa_2023_24 = list(
    EUROPA_LEAGUE_SEASON_DIRS["2023_24"].glob("*.json")
)

print("Saved Europa League 2023/24 files:", len(saved_europa_2023_24))

Saved Europa League 2023/24 files: 175

In [223]:
# Collect 2022/23 Europa League season

europa_2022_23_matches = get_all_season_matches(
    EUROPA_LEAGUE_ID,
    EUROPA_LEAGUE_SEASONS["2022_23"]
)

print("Total matches returned:", len(europa_2022_23_matches))

Total matches returned: 175

In [224]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in europa_2022_23_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in europa_2022_23_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in europa_2022_23_matches
)))

Statuses:
Counter({'finished': 175})

Stages:
Counter({None: 96, 'qualifying': 34, 'round_of_16': 32, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 175

In [225]:
collect_europa_league_baseline_data(
    "2022_23",
    europa_2022_23_matches
)

1/175 - Collecting: mt_839332876
2/175 - Collecting: mt_743222403
3/175 - Collecting: mt_978666711
4/175 - Collecting: mt_839444363
5/175 - Collecting: mt_250999560
6/175 - Collecting: mt_199160671
7/175 - Collecting: mt_744759506
8/175 - Collecting: mt_833805066
9/175 - Collecting: mt_366318160
10/175 - Collecting: mt_622693953
11/175 - Collecting: mt_400487816
12/175 - Collecting: mt_400487854
13/175 - Collecting: mt_366318121
14/175 - Collecting: mt_977347442
15/175 - Collecting: mt_400210182
16/175 - Collecting: mt_588938344
17/175 - Collecting: mt_199879769
18/175 - Collecting: mt_255185886
19/175 - Collecting: mt_199879775
20/175 - Collecting: mt_744604004
21/175 - Collecting: mt_833763664
22/175 - Collecting: mt_011591939
23/175 - Collecting: mt_255185870
24/175 - Collecting: mt_366426283
25/175 - Collecting: mt_400210171
26/175 - Collecting: mt_977347421
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
27/175 - Collecting: mt_744604052
28/175 - Collecting: mt_833763602
29/175 - Collecting: mt_622052530
30/175 - Collecting: mt_255639030
31/175 - Collecting: mt_199043549
32/175 - Collecting: mt_744912407
33/175 - Collecting: mt_622381259
34/175 - Collecting: mt_977106801
35/175 - Collecting: mt_744912312
36/175 - Collecting: mt_977106737
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['odds']
37/175 - Collecting: mt_199043984
38/175 - Collecting: mt_833524367
39/175 - Collecting: mt_366850622
40/175 - Collecting: mt_011478192
41/175 - Collecting: mt_588267838
42/175 - Collecting: mt_255639519
43/175 - Collecting: mt_400795017
44/175 - Collecting: mt_977106746
45/175 - Collecting: mt_255639583
46/175 - Collecting: mt_199494613
47/175 - Collecting: mt_744141571
48/175 - Collecting: mt_366565824
49/175 - Collecting: mt_622828355
50/175 - Collecting: mt_400909718
51/175 - Collecting: mt_011717494
52/175 - Collecting: mt_255353651
53/175 - Collecting: mt_199494097
54/175 - Collecting: mt_977070298
55/175 - Collecting: mt_622828905
56/175 - Collecting: mt_011717354
57/175 - Collecting: mt_977070237
58/175 - Collecting: mt_255353719
59/175 - Collecting: mt_400909817
60/175 - Collecting: mt_011717392
61/175 - Collecting: mt_588686438
62/175 - Collecting: mt_588686452
63/175 - Collecting: mt_255353725
64/175 - Collecting: mt_400909828
65/175 - Collecting: mt_199494684
66/175 - Collecting: mt_744141507
67/175 - Collecting: mt_255353783
68/175 - Collecting: mt_833232006
69/175 - Collecting: mt_588686216
70/175 - Collecting: mt_833232078
71/175 - Collecting: mt_366565144
72/175 - Collecting: mt_588686491
73/175 - Collecting: mt_199494074
74/175 - Collecting: mt_622828399
75/175 - Collecting: mt_977070126
76/175 - Collecting: mt_011717441
77/175 - Collecting: mt_977070179
78/175 - Collecting: mt_833287346
79/175 - Collecting: mt_366565122
80/175 - Collecting: mt_366565111
81/175 - Collecting: mt_199494608
82/175 - Collecting: mt_011717348
83/175 - Collecting: mt_255353701
84/175 - Collecting: mt_199494657
85/175 - Collecting: mt_588686227
86/175 - Collecting: mt_366565878
87/175 - Collecting: mt_833232067
88/175 - Collecting: mt_622828959
89/175 - Collecting: mt_744141590
90/175 - Collecting: mt_833232095
91/175 - Collecting: mt_744141957
92/175 - Collecting: mt_366565881
93/175 - Collecting: mt_622828333
94/175 - Collecting: mt_011717428
95/175 - Collecting: mt_622828993
96/175 - Collecting: mt_400909886
97/175 - Collecting: mt_622828934
98/175 - Collecting: mt_744141535
99/175 - Collecting: mt_255353673
100/175 - Collecting: mt_833232556
101/175 - Collecting: mt_255353602
102/175 - Collecting: mt_400909760
103/175 - Collecting: mt_977070246
104/175 - Collecting: mt_199494661
105/175 - Collecting: mt_255353762
106/175 - Collecting: mt_833232050
107/175 - Collecting: mt_588686426
108/175 - Collecting: mt_977070289
109/175 - Collecting: mt_744141930
110/175 - Collecting: mt_833232590
111/175 - Collecting: mt_400909865
112/175 - Collecting: mt_011717327
113/175 - Collecting: mt_366565812
114/175 - Collecting: mt_400909787
115/175 - Collecting: mt_011717432
116/175 - Collecting: mt_588686248
117/175 - Collecting: mt_622828344
118/175 - Collecting: mt_744141556
119/175 - Collecting: mt_011717331
120/175 - Collecting: mt_588686447
121/175 - Collecting: mt_977070220
122/175 - Collecting: mt_366565188
123/175 - Collecting: mt_400909870
124/175 - Collecting: mt_255353758
125/175 - Collecting: mt_833232039
126/175 - Collecting: mt_199494696
127/175 - Collecting: mt_744141549
128/175 - Collecting: mt_366565166
129/175 - Collecting: mt_622828921
130/175 - Collecting: mt_400909809
131/175 - Collecting: mt_011717380
132/175 - Collecting: mt_588686479
133/175 - Collecting: mt_977070264
134/175 - Collecting: mt_588686485
135/175 - Collecting: mt_977070273
136/175 - Collecting: mt_255353689
137/175 - Collecting: mt_833232507
138/175 - Collecting: mt_199494001
139/175 - Collecting: mt_744141996
140/175 - Collecting: mt_400909776
141/175 - Collecting: mt_199494058
142/175 - Collecting: mt_405409875
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
143/175 - Collecting: mt_742741539
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
144/175 - Collecting: mt_259116915
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
145/175 - Collecting: mt_193194607
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
146/175 - Collecting: mt_742741595
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
147/175 - Collecting: mt_259297776
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
148/175 - Collecting: mt_834758882
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
149/175 - Collecting: mt_742741099
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
150/175 - Collecting: mt_834832099
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
151/175 - Collecting: mt_834840004
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
152/175 - Collecting: mt_976969873
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
153/175 - Collecting: mt_742697697
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
154/175 - Collecting: mt_018080447
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
155/175 - Collecting: mt_193880383
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
156/175 - Collecting: mt_976970727
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
157/175 - Collecting: mt_587575185
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
158/175 - Collecting: mt_259292058
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
159/175 - Collecting: mt_834775468
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
160/175 - Collecting: mt_742669261
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
161/175 - Collecting: mt_018080227
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
162/175 - Collecting: mt_360401471
163/175 - Collecting: mt_834734848
164/175 - Collecting: mt_259159255
165/175 - Collecting: mt_976376978
166/175 - Collecting: mt_193893193
167/175 - Collecting: mt_018583521
168/175 - Collecting: mt_834740796
169/175 - Collecting: mt_360460304
170/175 - Collecting: mt_018583350
171/175 - Collecting: mt_405205458
172/175 - Collecting: mt_587974499
173/175 - Collecting: mt_621021615
174/175 - Collecting: mt_018518084
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
175/175 - Collecting: mt_976362234

In [226]:
saved_europa_2022_23 = list(
    EUROPA_LEAGUE_SEASON_DIRS["2022_23"].glob("*.json")
)

print("Saved Europa League 2022/23 files:", len(saved_europa_2022_23))

Saved Europa League 2022/23 files: 175

In [227]:
# Collect 2021/22 Europa League season

europa_2021_22_matches = get_all_season_matches(
    EUROPA_LEAGUE_ID,
    EUROPA_LEAGUE_SEASONS["2021_22"]
)

print("Total matches returned:", len(europa_2021_22_matches))

Total matches returned: 175

In [228]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in europa_2021_22_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in europa_2021_22_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in europa_2021_22_matches
)))

Statuses:
Counter({'finished': 175})

Stages:
Counter({None: 97, 'qualifying': 35, 'round_of_16': 30, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 175

In [229]:
collect_europa_league_baseline_data(
    "2021_22",
    europa_2021_22_matches
)

1/175 - Collecting: mt_742331991
2/175 - Collecting: mt_976746621
3/175 - Collecting: mt_259589970
4/175 - Collecting: mt_193973369
5/175 - Collecting: mt_742402252
6/175 - Collecting: mt_193378500
7/175 - Collecting: mt_742206393
8/175 - Collecting: mt_587739113
9/175 - Collecting: mt_834467953
10/175 - Collecting: mt_360024780
11/175 - Collecting: mt_621150438
12/175 - Collecting: mt_018895225
13/175 - Collecting: mt_405512664
14/175 - Collecting: mt_621181398
15/175 - Collecting: mt_193343005
16/175 - Collecting: mt_018878429
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
17/175 - Collecting: mt_742212953
18/175 - Collecting: mt_587767223
19/175 - Collecting: mt_742212994
20/175 - Collecting: mt_405595762
21/175 - Collecting: mt_834424503
22/175 - Collecting: mt_405595774
23/175 - Collecting: mt_834424554
24/175 - Collecting: mt_621181346
25/175 - Collecting: mt_259939666
26/175 - Collecting: mt_976606112
27/175 - Collecting: mt_360050885
28/175 - Collecting: mt_628036320
29/175 - Collecting: mt_409274701
30/175 - Collecting: mt_017540413
31/175 - Collecting: mt_970319178
32/175 - Collecting: mt_409274762
33/175 - Collecting: mt_017540429
34/175 - Collecting: mt_970319181
35/175 - Collecting: mt_741697932
36/175 - Collecting: mt_253162600
37/175 - Collecting: mt_194801059
38/175 - Collecting: mt_365483863
39/175 - Collecting: mt_586925282
40/175 - Collecting: mt_365483885
41/175 - Collecting: mt_628036346
42/175 - Collecting: mt_586925214
43/175 - Collecting: mt_832758592
44/175 - Collecting: mt_741344534
45/175 - Collecting: mt_586188484
46/175 - Collecting: mt_253055795
47/175 - Collecting: mt_194599633
48/175 - Collecting: mt_628422985
49/175 - Collecting: mt_628422369
50/175 - Collecting: mt_741344966
51/175 - Collecting: mt_832933576
52/175 - Collecting: mt_628422910
53/175 - Collecting: mt_586188472
54/175 - Collecting: mt_409600898
55/175 - Collecting: mt_970877207
56/175 - Collecting: mt_741344977
57/175 - Collecting: mt_586188258
58/175 - Collecting: mt_409600726
59/175 - Collecting: mt_970877130
60/175 - Collecting: mt_628422926
61/175 - Collecting: mt_017211319
62/175 - Collecting: mt_741344521
63/175 - Collecting: mt_832933028
64/175 - Collecting: mt_017211402
65/175 - Collecting: mt_365766841
66/175 - Collecting: mt_628422303
67/175 - Collecting: mt_194599655
68/175 - Collecting: mt_832933094
69/175 - Collecting: mt_741344542
70/175 - Collecting: mt_017211383
71/175 - Collecting: mt_017211374
72/175 - Collecting: mt_253055739
73/175 - Collecting: mt_194599644
74/175 - Collecting: mt_409600747
75/175 - Collecting: mt_253055623
76/175 - Collecting: mt_365766175
77/175 - Collecting: mt_832933032
78/175 - Collecting: mt_970877268
79/175 - Collecting: mt_365766154
80/175 - Collecting: mt_832933587
81/175 - Collecting: mt_365766832
82/175 - Collecting: mt_970877196
83/175 - Collecting: mt_017211451
84/175 - Collecting: mt_253055750
85/175 - Collecting: mt_194599699
86/175 - Collecting: mt_365766103
87/175 - Collecting: mt_409600851
88/175 - Collecting: mt_586188461
89/175 - Collecting: mt_194599081
90/175 - Collecting: mt_586188297
91/175 - Collecting: mt_253055682
92/175 - Collecting: mt_194599078
93/175 - Collecting: mt_365766828
94/175 - Collecting: mt_628422354
95/175 - Collecting: mt_253055668
96/175 - Collecting: mt_832933559
97/175 - Collecting: mt_409600779
98/175 - Collecting: mt_970877172
99/175 - Collecting: mt_832933534
100/175 - Collecting: mt_970877129
101/175 - Collecting: mt_194599067
102/175 - Collecting: mt_741344955
103/175 - Collecting: mt_586188225
104/175 - Collecting: mt_365766870
105/175 - Collecting: mt_628422316
106/175 - Collecting: mt_741344944
107/175 - Collecting: mt_586188219
108/175 - Collecting: mt_586188236
109/175 - Collecting: mt_253055671
110/175 - Collecting: mt_832933505
111/175 - Collecting: mt_409600785
112/175 - Collecting: mt_970877184
113/175 - Collecting: mt_628422348
114/175 - Collecting: mt_253055656
115/175 - Collecting: mt_409600752
116/175 - Collecting: mt_409600802
117/175 - Collecting: mt_970877271
118/175 - Collecting: mt_970877113
119/175 - Collecting: mt_194599006
120/175 - Collecting: mt_741344999
121/175 - Collecting: mt_365766886
122/175 - Collecting: mt_741344933
123/175 - Collecting: mt_365766865
124/175 - Collecting: mt_017211498
125/175 - Collecting: mt_365766817
126/175 - Collecting: mt_017211437
127/175 - Collecting: mt_628422331
128/175 - Collecting: mt_194599050
129/175 - Collecting: mt_017211415
130/175 - Collecting: mt_586188283
131/175 - Collecting: mt_741344900
132/175 - Collecting: mt_832933560
133/175 - Collecting: mt_409600710
134/175 - Collecting: mt_628422392
135/175 - Collecting: mt_017211420
136/175 - Collecting: mt_253055607
137/175 - Collecting: mt_832933593
138/175 - Collecting: mt_409600704
139/175 - Collecting: mt_194599095
140/175 - Collecting: mt_832357474
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
141/175 - Collecting: mt_253565968
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
142/175 - Collecting: mt_365686086
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
143/175 - Collecting: mt_741494299
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
144/175 - Collecting: mt_409070579
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
145/175 - Collecting: mt_832357524
146/175 - Collecting: mt_365684855
147/175 - Collecting: mt_365684045
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
148/175 - Collecting: mt_253561916
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
149/175 - Collecting: mt_017145899
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
150/175 - Collecting: mt_628230156
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
151/175 - Collecting: mt_409072512
152/175 - Collecting: mt_628232131
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
153/175 - Collecting: mt_194908385
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
154/175 - Collecting: mt_586829734
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
155/175 - Collecting: mt_741496914
156/175 - Collecting: mt_832353459
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
157/175 - Collecting: mt_017141820
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
158/175 - Collecting: mt_628230466
159/175 - Collecting: mt_194909306
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
160/175 - Collecting: mt_832323484
161/175 - Collecting: mt_194949315
162/175 - Collecting: mt_970707692
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
163/175 - Collecting: mt_253535926
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
164/175 - Collecting: mt_586868753
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
165/175 - Collecting: mt_365656035
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
166/175 - Collecting: mt_741414274
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
167/175 - Collecting: mt_017171744
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
168/175 - Collecting: mt_628282106
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
169/175 - Collecting: mt_017171859
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
170/175 - Collecting: mt_253535910
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
171/175 - Collecting: mt_409090522
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
172/175 - Collecting: mt_586868794
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
173/175 - Collecting: mt_194949389
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
174/175 - Collecting: mt_970707631
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
175/175 - Collecting: mt_365656351
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']

In [230]:
saved_europa_2021_22 = list(
    EUROPA_LEAGUE_SEASON_DIRS["2021_22"].glob("*.json")
)

print("Saved Europa League 2021/22 files:", len(saved_europa_2021_22))

Saved Europa League 2021/22 files: 175

In [ ]:
# Collect 2020/21 Europa League season

europa_2020_21_matches = get_all_season_matches(
    EUROPA_LEAGUE_ID,
    EUROPA_LEAGUE_SEASONS["2020_21"]
)

print("Total matches returned:", len(europa_2020_21_matches))

Total matches returned: 361

In [232]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in europa_2020_21_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in europa_2020_21_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in europa_2020_21_matches
)))

Statuses:
Counter({'finished': 361})

Stages:
Counter({'qualifying': 157, None: 143, 'round_of_32': 32, 'round_of_16': 16, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 361

In [235]:
collect_europa_league_baseline_data(
    "2020_21",
    europa_2020_21_matches
)

1/361 - Skipping existing: mt_454496751
2/361 - Skipping existing: mt_292108666
3/361 - Skipping existing: mt_727630994
4/361 - Skipping existing: mt_131857005
5/361 - Skipping existing: mt_848796554
6/361 - Skipping existing: mt_303272587
7/361 - Skipping existing: mt_616545832
8/361 - Skipping existing: mt_454161975
9/361 - Skipping existing: mt_575313615
10/361 - Skipping existing: mt_131757407
11/361 - Skipping existing: mt_727030195
12/361 - Skipping existing: mt_848696255
13/361 - Skipping existing: mt_080929747
14/361 - Skipping existing: mt_303114004
15/361 - Skipping existing: mt_616990115
16/361 - Skipping existing: mt_616990810
17/361 - Skipping existing: mt_575449672
18/361 - Skipping existing: mt_575439964
19/361 - Skipping existing: mt_292771955
20/361 - Skipping existing: mt_848007448
21/361 - Skipping existing: mt_080335884
22/361 - Skipping existing: mt_131668393
23/361 - Skipping existing: mt_727556241
24/361 - Skipping existing: mt_969223667
25/361 - Skipping existing: mt_454882951
26/361 - Skipping existing: mt_727556270
27/361 - Skipping existing: mt_454882558
28/361 - Skipping existing: mt_303114503
29/361 - Skipping existing: mt_080335783
30/361 - Skipping existing: mt_575117692
31/361 - Skipping existing: mt_292009315
32/361 - Skipping existing: mt_131553483
33/361 - Skipping existing: mt_848994268
34/361 - Skipping existing: mt_616441855
35/361 - Skipping existing: mt_454665918
36/361 - Skipping existing: mt_575117631
37/361 - Skipping existing: mt_292009389
38/361 - Skipping existing: mt_616441800
39/361 - Skipping existing: mt_454665921
40/361 - Skipping existing: mt_969886038
41/361 - Skipping existing: mt_727332161
42/361 - Skipping existing: mt_303770524
43/361 - Skipping existing: mt_080228794
44/361 - Skipping existing: mt_131553474
45/361 - Skipping existing: mt_080228753
46/361 - Skipping existing: mt_848994207
47/361 - Skipping existing: mt_303770512
48/361 - Skipping existing: mt_616441899
49/361 - Skipping existing: mt_454665987
50/361 - Skipping existing: mt_080228732
51/361 - Skipping existing: mt_575117648
52/361 - Skipping existing: mt_727332129
53/361 - Skipping existing: mt_727332172
54/361 - Skipping existing: mt_848994282
55/361 - Skipping existing: mt_303770543
56/361 - Skipping existing: mt_969886047
57/361 - Skipping existing: mt_292009373
58/361 - Skipping existing: mt_080228728
59/361 - Skipping existing: mt_131553436
60/361 - Skipping existing: mt_575117669
61/361 - Skipping existing: mt_969886004
62/361 - Skipping existing: mt_292321567
63/361 - Skipping existing: mt_575659813
64/361 - Skipping existing: mt_303534675
65/361 - Skipping existing: mt_131418999
66/361 - Skipping existing: mt_303534603
67/361 - Skipping existing: mt_616860210
68/361 - Skipping existing: mt_454942051
69/361 - Skipping existing: mt_080705174
70/361 - Skipping existing: mt_969093707
71/361 - Skipping existing: mt_131418944
72/361 - Skipping existing: mt_727176277
73/361 - Skipping existing: mt_080705197
74/361 - Skipping existing: mt_969093723
75/361 - Skipping existing: mt_575659829
76/361 - Skipping existing: mt_080705125
77/361 - Skipping existing: mt_080705119
78/361 - Skipping existing: mt_575659884
79/361 - Skipping existing: mt_292321550
80/361 - Skipping existing: mt_727176442
81/361 - Skipping existing: mt_848287332
82/361 - Skipping existing: mt_575659861
83/361 - Skipping existing: mt_292321539
84/361 - Skipping existing: mt_848287487
85/361 - Skipping existing: mt_575747465
86/361 - Skipping existing: mt_080705802
87/361 - Skipping existing: mt_969093696
88/361 - Skipping existing: mt_292321923
89/361 - Skipping existing: mt_848287476
90/361 - Skipping existing: mt_616860103
91/361 - Skipping existing: mt_969093630
92/361 - Skipping existing: mt_131418378
93/361 - Skipping existing: mt_303534028
94/361 - Skipping existing: mt_454942510
95/361 - Skipping existing: mt_292321971
96/361 - Skipping existing: mt_131418367
97/361 - Skipping existing: mt_303534616
98/361 - Skipping existing: mt_454942064
99/361 - Skipping existing: mt_454942002
100/361 - Skipping existing: mt_969093771
101/361 - Skipping existing: mt_080705183
102/361 - Skipping existing: mt_575659872
103/361 - Skipping existing: mt_727176266
104/361 - Skipping existing: mt_454942526
105/361 - Skipping existing: mt_575659797
106/361 - Skipping existing: mt_848287460
107/361 - Skipping existing: mt_727176255
108/361 - Skipping existing: mt_454942585
109/361 - Skipping existing: mt_303534041
110/361 - Skipping existing: mt_969093629
111/361 - Skipping existing: mt_303534017
112/361 - Skipping existing: mt_454942579
113/361 - Skipping existing: mt_575659719
114/361 - Skipping existing: mt_454942552
115/361 - Skipping existing: mt_616860180
116/361 - Skipping existing: mt_080705873
117/361 - Skipping existing: mt_575659762
118/361 - Skipping existing: mt_969093608
119/361 - Skipping existing: mt_727176211
120/361 - Skipping existing: mt_616860169
121/361 - Skipping existing: mt_575659758
122/361 - Skipping existing: mt_131418381
123/361 - Skipping existing: mt_080705851
124/361 - Skipping existing: mt_292321982
125/361 - Skipping existing: mt_727176200
126/361 - Skipping existing: mt_616860154
127/361 - Skipping existing: mt_080705898
128/361 - Skipping existing: mt_575659736
129/361 - Skipping existing: mt_848287405
130/361 - Skipping existing: mt_616860192
131/361 - Skipping existing: mt_969093672
132/361 - Skipping existing: mt_616860116
133/361 - Skipping existing: mt_131418343
134/361 - Skipping existing: mt_303534070
135/361 - Skipping existing: mt_454942504
136/361 - Skipping existing: mt_575659783
137/361 - Skipping existing: mt_292321956
138/361 - Skipping existing: mt_848287434
139/361 - Skipping existing: mt_303534065
140/361 - Skipping existing: mt_080705889
141/361 - Skipping existing: mt_575659774
142/361 - Skipping existing: mt_969093661
143/361 - Skipping existing: mt_292321990
144/361 - Skipping existing: mt_292321935
145/361 - Skipping existing: mt_131418350
146/361 - Skipping existing: mt_727176233
147/361 - Skipping existing: mt_848287493
148/361 - Skipping existing: mt_616860148
149/361 - Skipping existing: mt_080705815
150/361 - Skipping existing: mt_131418395
151/361 - Skipping existing: mt_727176244
152/361 - Skipping existing: mt_131418339
153/361 - Skipping existing: mt_727176222
154/361 - Skipping existing: mt_848287442
155/361 - Skipping existing: mt_303534053
156/361 - Skipping existing: mt_454942591
157/361 - Skipping existing: mt_616860865
158/361 - Skipping existing: mt_080705704
159/361 - Skipping existing: mt_575659651
160/361 - Skipping existing: mt_969093097
161/361 - Skipping existing: mt_727176167
162/361 - Skipping existing: mt_848287277
163/361 - Skipping existing: mt_454942927
164/361 - Skipping existing: mt_575659698
165/361 - Skipping existing: mt_969093036
166/361 - Skipping existing: mt_292321313
167/361 - Skipping existing: mt_303534521
168/361 - Skipping existing: mt_454942916
169/361 - Skipping existing: mt_454942948
170/361 - Skipping existing: mt_292321329
171/361 - Skipping existing: mt_131418414
172/361 - Skipping existing: mt_303534542
173/361 - Skipping existing: mt_616860809
174/361 - Skipping existing: mt_080705752
175/361 - Skipping existing: mt_131418471
176/361 - Skipping existing: mt_727176106
177/361 - Skipping existing: mt_848287266
178/361 - Skipping existing: mt_616860853
179/361 - Skipping existing: mt_080705791
180/361 - Skipping existing: mt_575659637
181/361 - Skipping existing: mt_969094877
182/361 - Skipping existing: mt_292328059
183/361 - Skipping existing: mt_131417594
184/361 - Skipping existing: mt_727170327
185/361 - Skipping existing: mt_848286947
186/361 - Skipping existing: mt_303532702
187/361 - Skipping existing: mt_616865419
188/361 - Skipping existing: mt_454941657
189/361 - Skipping existing: mt_969094866
190/361 - Skipping existing: mt_292328093
191/361 - Skipping existing: mt_131417541
192/361 - Skipping existing: mt_727170316
193/361 - Skipping existing: mt_848286926
194/361 - Skipping existing: mt_303532751
195/361 - Skipping existing: mt_454941696
196/361 - Skipping existing: mt_080709271
197/361 - Skipping existing: mt_575653167
198/361 - Skipping existing: mt_969094800
199/361 - Skipping existing: mt_292328522
200/361 - Skipping existing: mt_131417918
201/361 - Skipping existing: mt_727170470
202/361 - Skipping existing: mt_848286380
203/361 - Skipping existing: mt_969094724
204/361 - Skipping existing: mt_292328577
205/361 - Skipping existing: mt_610666169
206/361 - Skipping existing: mt_579555758
207/361 - Skipping existing: mt_963999696
208/361 - Skipping existing: mt_291222923
209/361 - Skipping existing: mt_610666103
210/361 - Skipping existing: mt_847888487
211/361 - Skipping existing: mt_847888476
212/361 - Skipping existing: mt_085000851
213/361 - Skipping existing: mt_085000802
214/361 - Skipping existing: mt_452444526
215/361 - Skipping existing: mt_963999630
216/361 - Skipping existing: mt_138111378
217/361 - Skipping existing: mt_726777200
218/361 - Skipping existing: mt_726777266
219/361 - Skipping existing: mt_304333032
220/361 - Skipping existing: mt_452444547
221/361 - Skipping existing: mt_138111381
222/361 - Skipping existing: mt_304333041
223/361 - Skipping existing: mt_579555797
224/361 - Skipping existing: mt_847888460
225/361 - Skipping existing: mt_291222982
226/361 - Skipping existing: mt_138174700
227/361 - Skipping existing: mt_726701500
228/361 - Skipping existing: mt_452419847
229/361 - Skipping existing: mt_610658552
230/361 - Skipping existing: mt_579536329
231/361 - Skipping existing: mt_726701577
232/361 - Skipping existing: mt_963940230
233/361 - Skipping existing: mt_726672054
234/361 - Skipping existing: mt_085097373
235/361 - Skipping existing: mt_726701005
236/361 - Skipping existing: mt_847862665
237/361 - Skipping existing: mt_963940414
238/361 - Skipping existing: mt_291283867
239/361 - Skipping existing: mt_610658538
240/361 - Skipping existing: mt_291283839
241/361 - Skipping existing: mt_138174744
242/361 - Skipping existing: mt_304325141
243/361 - Skipping existing: mt_610658903
244/361 - Skipping existing: mt_963940423
245/361 - Skipping existing: mt_610658365
246/361 - Skipping existing: mt_291283878
247/361 - Skipping existing: mt_138174766
248/361 - Skipping existing: mt_726701093
249/361 - Skipping existing: mt_579536458
250/361 - Skipping existing: mt_138174681
251/361 - Skipping existing: mt_452419826
252/361 - Skipping existing: mt_138174678
253/361 - Skipping existing: mt_452419891
254/361 - Skipping existing: mt_579536462
255/361 - Skipping existing: mt_610658309
256/361 - Skipping existing: mt_085097302
257/361 - Skipping existing: mt_579957343
258/361 - Skipping existing: mt_291283723
259/361 - Skipping existing: mt_847862076
260/361 - Skipping existing: mt_304325227
261/361 - Skipping existing: mt_304441020
262/361 - Skipping existing: mt_726665231
263/361 - Skipping existing: mt_452228529
264/361 - Skipping existing: mt_304441015
265/361 - Skipping existing: mt_138886309
266/361 - Skipping existing: mt_452228561
267/361 - Skipping existing: mt_963332688
268/361 - Skipping existing: mt_138886370
269/361 - Skipping existing: mt_291117976
270/361 - Skipping existing: mt_452469940
271/361 - Skipping existing: mt_138141965
272/361 - Skipping existing: mt_610009101
273/361 - Skipping existing: mt_726665203
274/361 - Skipping existing: mt_085553835
275/361 - Skipping existing: mt_726665292
276/361 - Skipping existing: mt_579994712
277/361 - Skipping existing: mt_138886353
278/361 - Skipping existing: mt_847770463
279/361 - Skipping existing: mt_847830435
280/361 - Skipping existing: mt_963332633
281/361 - Skipping existing: mt_291117918
282/361 - Skipping existing: mt_085553890
283/361 - Skipping existing: mt_579994739
284/361 - Skipping existing: mt_610009158
285/361 - Skipping existing: mt_579994724
286/361 - Skipping existing: mt_847770452
287/361 - Skipping existing: mt_847770438
288/361 - Skipping existing: mt_304441046
289/361 - Skipping existing: mt_579994743
290/361 - Skipping existing: mt_726665269
291/361 - Skipping existing: mt_726665254
292/361 - Skipping existing: mt_963332611
293/361 - Skipping existing: mt_610009140
294/361 - Skipping existing: mt_291117905
295/361 - Skipping existing: mt_291117960
296/361 - Skipping existing: mt_847770479
297/361 - Skipping existing: mt_085550158
298/361 - Skipping existing: mt_291117987
299/361 - Skipping existing: mt_138886365
300/361 - Skipping existing: mt_610009136
301/361 - Skipping existing: mt_963332622
302/361 - Skipping existing: mt_963332644
303/361 - Skipping existing: mt_085553849
304/361 - Skipping existing: mt_085553823
305/361 - Skipping existing: mt_452228572
306/361 - Skipping existing: mt_847770404
307/361 - Skipping existing: mt_304441658
308/361 - Skipping existing: mt_610009284
309/361 - Skipping existing: mt_452816780
310/361 - Skipping existing: mt_452816775
311/361 - Skipping existing: mt_847069599
312/361 - Skipping existing: mt_452816754
313/361 - Skipping existing: mt_085993299
314/361 - Skipping existing: mt_291887080
315/361 - Skipping existing: mt_138776579
316/361 - Skipping existing: mt_610954394
317/361 - Skipping existing: mt_847069533
318/361 - Skipping existing: mt_452118612
319/361 - Skipping existing: mt_579334134
320/361 - Skipping existing: mt_847069555
321/361 - Skipping existing: mt_304127887
322/361 - Skipping existing: mt_963248183
323/361 - Skipping existing: mt_085392485
324/361 - Skipping existing: mt_579431289
325/361 - Skipping existing: mt_963248119
326/361 - Skipping existing: mt_304127860
327/361 - Skipping existing: mt_610954328
328/361 - Skipping existing: mt_610508695
329/361 - Skipping existing: mt_847069500
330/361 - Skipping existing: mt_579431246
331/361 - Skipping existing: mt_291780661
332/361 - Skipping existing: mt_138675007
333/361 - Skipping existing: mt_726503995
334/361 - Skipping existing: mt_579431215
335/361 - Skipping existing: mt_452816769
336/361 - Skipping existing: mt_085392410
337/361 - Skipping existing: mt_138675090
338/361 - Skipping existing: mt_726503950
339/361 - Skipping existing: mt_963248174
340/361 - Skipping existing: mt_963248213
341/361 - Skipping existing: mt_304127876
342/361 - Skipping existing: mt_610954341
343/361 - Skipping existing: mt_291780657
344/361 - Skipping existing: mt_726503943
345/361 - Skipping existing: mt_138788857
346/361 - Skipping existing: mt_304127818
347/361 - Skipping existing: mt_452816885
348/361 - Skipping existing: mt_085392337
349/361 - Skipping existing: mt_579431425
350/361 - Skipping existing: mt_085392438
351/361 - Skipping existing: mt_291780608
352/361 - Skipping existing: mt_963442841
353/361 - Skipping existing: mt_138675056
354/361 - Skipping existing: mt_963233600
355/361 - Skipping existing: mt_847077426
356/361 - Skipping existing: mt_610900183
357/361 - Skipping existing: mt_085355871
358/361 - Skipping existing: mt_610903124
359/361 - Skipping existing: mt_304144051
360/361 - Skipping existing: mt_452822596
361/361 - Skipping existing: mt_579499767

In [236]:
saved_europa_2020_21 = list(
    EUROPA_LEAGUE_SEASON_DIRS["2020_21"].glob("*.json")
)

print("Saved Europa League 2020/21 files:", len(saved_europa_2020_21))

Saved Europa League 2020/21 files: 361

In [237]:
# Collecting 2024/25 Europa League season

europa_2024_25_matches = get_all_season_matches(
    EUROPA_LEAGUE_ID,
    EUROPA_LEAGUE_SEASONS["2024_25"]
)

print("Total matches returned:", len(europa_2024_25_matches))

Total matches returned: 269

In [238]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in europa_2024_25_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in europa_2024_25_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in europa_2024_25_matches
)))

Statuses:
Counter({'finished': 269})

Stages:
Counter({None: 144, 'round_of_16': 56, 'qualifying': 56, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 269

In [239]:
collect_europa_league_baseline_data(
    "2024_25",
    europa_2024_25_matches
)

1/269 - Collecting: mt_973106364
2/269 - Collecting: mt_251639197
3/269 - Collecting: mt_746366930
4/269 - Collecting: mt_402622760
5/269 - Collecting: mt_015255428
6/269 - Collecting: mt_837977590
7/269 - Collecting: mt_364744878
8/269 - Collecting: mt_620400344
9/269 - Collecting: mt_589199216
10/269 - Collecting: mt_589199269
11/269 - Collecting: mt_973833104
12/269 - Collecting: mt_251011637
13/269 - Collecting: mt_198588040
14/269 - Collecting: mt_620403369
15/269 - Collecting: mt_589192258
16/269 - Collecting: mt_746369966
17/269 - Collecting: mt_198580078
18/269 - Collecting: mt_620403985
19/269 - Collecting: mt_973831207
20/269 - Collecting: mt_589192297
21/269 - Collecting: mt_402627710
22/269 - Collecting: mt_015254374
23/269 - Collecting: mt_746369977
24/269 - Collecting: mt_973831130
25/269 - Collecting: mt_015254498
26/269 - Collecting: mt_402627747
27/269 - Collecting: mt_251016623
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Odds not found for this match","status_code":404}}
Saving with missing sections: ['odds']
28/269 - Collecting: mt_620403303
29/269 - Collecting: mt_837975560
30/269 - Collecting: mt_589878887
31/269 - Collecting: mt_364606608
32/269 - Collecting: mt_015181188
33/269 - Collecting: mt_746424415
34/269 - Collecting: mt_251595592
35/269 - Collecting: mt_746424420
36/269 - Collecting: mt_589878876
37/269 - Collecting: mt_198939947
38/269 - Collecting: mt_198939938
39/269 - Collecting: mt_837343340
40/269 - Collecting: mt_251595531
41/269 - Collecting: mt_837343325
42/269 - Collecting: mt_973767770
43/269 - Collecting: mt_620212214
44/269 - Collecting: mt_973767709
45/269 - Collecting: mt_364606657
46/269 - Collecting: mt_836245545
47/269 - Collecting: mt_401957755
48/269 - Collecting: mt_258396075
49/269 - Collecting: mt_197430563
50/269 - Collecting: mt_740129346
51/269 - Collecting: mt_401957695
52/269 - Collecting: mt_401957049
53/269 - Collecting: mt_258396532
54/269 - Collecting: mt_197430370
55/269 - Collecting: mt_019784849
56/269 - Collecting: mt_625813125
57/269 - Collecting: mt_836245447
58/269 - Collecting: mt_362508547
59/269 - Collecting: mt_197430460
60/269 - Collecting: mt_836245254
61/269 - Collecting: mt_362507348
62/269 - Collecting: mt_625814610
63/269 - Collecting: mt_197435144
64/269 - Collecting: mt_362508814
65/269 - Collecting: mt_019784233
66/269 - Collecting: mt_401957056
67/269 - Collecting: mt_258396921
68/269 - Collecting: mt_362508051
69/269 - Collecting: mt_258396355
70/269 - Collecting: mt_974068982
71/269 - Collecting: mt_258390123
72/269 - Collecting: mt_836245530
73/269 - Collecting: mt_583672187
74/269 - Collecting: mt_740129479
75/269 - Collecting: mt_974061734
76/269 - Collecting: mt_362508674
77/269 - Collecting: mt_362508020
78/269 - Collecting: mt_258396322
79/269 - Collecting: mt_836249853
80/269 - Collecting: mt_836245940
81/269 - Collecting: mt_197430903
82/269 - Collecting: mt_197430064
83/269 - Collecting: mt_836245596
84/269 - Collecting: mt_362508046
85/269 - Collecting: mt_258396388
86/269 - Collecting: mt_740129132
87/269 - Collecting: mt_258396333
88/269 - Collecting: mt_019782040
89/269 - Collecting: mt_583671572
90/269 - Collecting: mt_362507441
91/269 - Collecting: mt_019784222
92/269 - Collecting: mt_401957071
93/269 - Collecting: mt_197430954
94/269 - Collecting: mt_974061760
95/269 - Collecting: mt_362508658
96/269 - Collecting: mt_836245404
97/269 - Collecting: mt_836245426
98/269 - Collecting: mt_197435199
99/269 - Collecting: mt_197430341
100/269 - Collecting: mt_625813324
101/269 - Collecting: mt_019784200
102/269 - Collecting: mt_974061793
103/269 - Collecting: mt_583672743
104/269 - Collecting: mt_258396960
105/269 - Collecting: mt_197430394
106/269 - Collecting: mt_583672671
107/269 - Collecting: mt_740123705
108/269 - Collecting: mt_583671584
109/269 - Collecting: mt_362507432
110/269 - Collecting: mt_740129302
111/269 - Collecting: mt_836245997
112/269 - Collecting: mt_625813449
113/269 - Collecting: mt_974061809
114/269 - Collecting: mt_836245373
115/269 - Collecting: mt_974061742
116/269 - Collecting: mt_258396918
117/269 - Collecting: mt_625813820
118/269 - Collecting: mt_740129364
119/269 - Collecting: mt_362508761
120/269 - Collecting: mt_583672833
121/269 - Collecting: mt_836245302
122/269 - Collecting: mt_401957529
123/269 - Collecting: mt_019784729
124/269 - Collecting: mt_625813815
125/269 - Collecting: mt_836245227
126/269 - Collecting: mt_362508882
127/269 - Collecting: mt_401957766
128/269 - Collecting: mt_974061180
129/269 - Collecting: mt_625813490
130/269 - Collecting: mt_362508662
131/269 - Collecting: mt_836245346
132/269 - Collecting: mt_740129275
133/269 - Collecting: mt_197430353
134/269 - Collecting: mt_836249894
135/269 - Collecting: mt_401957650
136/269 - Collecting: mt_362508745
137/269 - Collecting: mt_401957678
138/269 - Collecting: mt_740129320
139/269 - Collecting: mt_401957007
140/269 - Collecting: mt_019784181
141/269 - Collecting: mt_583672656
142/269 - Collecting: mt_019784730
143/269 - Collecting: mt_197435166
144/269 - Collecting: mt_019782074
145/269 - Collecting: mt_740129315
146/269 - Collecting: mt_625813296
147/269 - Collecting: mt_583672781
148/269 - Collecting: mt_258396993
149/269 - Collecting: mt_583672649
150/269 - Collecting: mt_836249809
151/269 - Collecting: mt_401956402
152/269 - Collecting: mt_197430969
153/269 - Collecting: mt_362508073
154/269 - Collecting: mt_362508730
155/269 - Collecting: mt_258396092
156/269 - Collecting: mt_362508757
157/269 - Collecting: mt_974061721
158/269 - Collecting: mt_401957090
159/269 - Collecting: mt_625813119
160/269 - Collecting: mt_583671513
161/269 - Collecting: mt_974068907
162/269 - Collecting: mt_401956247
163/269 - Collecting: mt_401957612
164/269 - Collecting: mt_258396003
165/269 - Collecting: mt_625813208
166/269 - Collecting: mt_197430386
167/269 - Collecting: mt_625813140
168/269 - Collecting: mt_583672778
169/269 - Collecting: mt_401957919
170/269 - Collecting: mt_974061081
171/269 - Collecting: mt_974068923
172/269 - Collecting: mt_258396663
173/269 - Collecting: mt_197430317
174/269 - Collecting: mt_740129231
175/269 - Collecting: mt_197430476
176/269 - Collecting: mt_625813898
177/269 - Collecting: mt_974068914
178/269 - Collecting: mt_740123734
179/269 - Collecting: mt_197430931
180/269 - Collecting: mt_401957596
181/269 - Collecting: mt_019784244
182/269 - Collecting: mt_974061817
183/269 - Collecting: mt_583672176
184/269 - Collecting: mt_401957082
185/269 - Collecting: mt_019784124
186/269 - Collecting: mt_197430948
187/269 - Collecting: mt_740129141
188/269 - Collecting: mt_974061169
189/269 - Collecting: mt_401957545
190/269 - Collecting: mt_257233597
191/269 - Collecting: mt_745711423
192/269 - Collecting: mt_745711125
193/269 - Collecting: mt_361433308
194/269 - Collecting: mt_629688812
195/269 - Collecting: mt_972331118
196/269 - Collecting: mt_830822343
197/269 - Collecting: mt_629688218
198/269 - Collecting: mt_745677720
199/269 - Collecting: mt_361355507
200/269 - Collecting: mt_629061808
201/269 - Collecting: mt_745663270
202/269 - Collecting: mt_830822245
203/269 - Collecting: mt_257233989
204/269 - Collecting: mt_745711140
205/269 - Collecting: mt_629066614
206/269 - Collecting: mt_196144498
207/269 - Collecting: mt_408244450
208/269 - Collecting: mt_830779480
209/269 - Collecting: mt_972900702
210/269 - Collecting: mt_408499955
211/269 - Collecting: mt_830788840
212/269 - Collecting: mt_745672104
213/269 - Collecting: mt_257110559
214/269 - Collecting: mt_361231004
215/269 - Collecting: mt_830683329
216/269 - Collecting: mt_408141097
217/269 - Collecting: mt_196716360
218/269 - Collecting: mt_830680270
219/269 - Collecting: mt_745070293
220/269 - Collecting: mt_013909897
221/269 - Collecting: mt_972494623
222/269 - Collecting: mt_361208513
223/269 - Collecting: mt_013909172
224/269 - Collecting: mt_408141589
225/269 - Collecting: mt_972492090
226/269 - Collecting: mt_013950289
227/269 - Collecting: mt_745075253
228/269 - Collecting: mt_745075160
229/269 - Collecting: mt_408124652
230/269 - Collecting: mt_361231651
231/269 - Collecting: mt_408148096
232/269 - Collecting: mt_257827312
233/269 - Collecting: mt_629569804
234/269 - Collecting: mt_013981880
235/269 - Collecting: mt_830680326
236/269 - Collecting: mt_257827922
237/269 - Collecting: mt_196716488
238/269 - Collecting: mt_408124080
239/269 - Collecting: mt_361231548
240/269 - Collecting: mt_745571161
241/269 - Collecting: mt_196614550
242/269 - Collecting: mt_745571333
243/269 - Collecting: mt_584139442
244/269 - Collecting: mt_361724003
245/269 - Collecting: mt_361135524
246/269 - Collecting: mt_257081775
247/269 - Collecting: mt_408612881
248/269 - Collecting: mt_830082993
249/269 - Collecting: mt_408612551
250/269 - Collecting: mt_830967432
251/269 - Collecting: mt_013295883
252/269 - Collecting: mt_257723035
253/269 - Collecting: mt_408849691
254/269 - Collecting: mt_745571311
255/269 - Collecting: mt_629450110
256/269 - Collecting: mt_408849918
257/269 - Collecting: mt_830082268
258/269 - Collecting: mt_972823001
259/269 - Collecting: mt_745356124
260/269 - Collecting: mt_013235779
261/269 - Collecting: mt_196568449
262/269 - Collecting: mt_408682992
263/269 - Collecting: mt_629495660
264/269 - Collecting: mt_361714505
265/269 - Collecting: mt_972824998
266/269 - Collecting: mt_830907222
267/269 - Collecting: mt_408681441
268/269 - Collecting: mt_013239003
269/269 - Collecting: mt_584143552

In [240]:
saved_europa_2024_25 = list(
    EUROPA_LEAGUE_SEASON_DIRS["2024_25"].glob("*.json")
)

print("Saved Europa League 2024/25 files:", len(saved_europa_2024_25))

Saved Europa League 2024/25 files: 269

In [241]:
# Collect 2025/26 Europa League season

europa_2025_26_matches = get_all_season_matches(
    EUROPA_LEAGUE_ID,
    EUROPA_LEAGUE_SEASONS["2025_26"]
)

print("Total matches returned:", len(europa_2025_26_matches))

Total matches returned: 271

In [242]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in europa_2025_26_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in europa_2025_26_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in europa_2025_26_matches
)))

Statuses:
Counter({'finished': 271})

Stages:
Counter({None: 144, 'qualifying': 58, 'round_of_16': 56, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 271

In [243]:
collect_europa_league_baseline_data(
    "2025_26",
    europa_2025_26_matches
)

1/271 - Collecting: mt_642459643
2/271 - Collecting: mt_460618466
3/271 - Collecting: mt_021293021
4/271 - Collecting: mt_518134517
5/271 - Collecting: mt_987842980
6/271 - Collecting: mt_205087252
7/271 - Collecting: mt_159576198
8/271 - Collecting: mt_893960830
9/271 - Collecting: mt_734305740
10/271 - Collecting: mt_376721368
11/271 - Collecting: mt_642459624
12/271 - Collecting: mt_460618400
13/271 - Collecting: mt_021293018
14/271 - Collecting: mt_518132932
15/271 - Collecting: mt_205086185
16/271 - Collecting: mt_159570873
17/271 - Collecting: mt_376728414
18/271 - Collecting: mt_021294593
19/271 - Collecting: mt_987841348
20/271 - Collecting: mt_893965708
21/271 - Collecting: mt_734309601
22/271 - Collecting: mt_460617288
23/271 - Collecting: mt_021294534
24/271 - Collecting: mt_159570864
25/271 - Collecting: mt_376728482
26/271 - Collecting: mt_642453095
27/271 - Collecting: mt_518132941
28/271 - Collecting: mt_987841327
29/271 - Collecting: mt_893965757
30/271 - Collecting: mt_518638451
31/271 - Collecting: mt_987047297
32/271 - Collecting: mt_205385713
33/271 - Collecting: mt_376526121
34/271 - Collecting: mt_734104011
35/271 - Collecting: mt_893263077
36/271 - Collecting: mt_734104506
37/271 - Collecting: mt_376526118
38/271 - Collecting: mt_376526187
39/271 - Collecting: mt_021791347
40/271 - Collecting: mt_376526176
41/271 - Collecting: mt_518638489
42/271 - Collecting: mt_460910880
43/271 - Collecting: mt_518638446
44/271 - Collecting: mt_205385708
45/271 - Collecting: mt_987047274
46/271 - Collecting: mt_516197714
47/271 - Collecting: mt_980836678
48/271 - Collecting: mt_375740004
49/271 - Collecting: mt_203019999
50/271 - Collecting: mt_731362176
51/271 - Collecting: mt_892974270
52/271 - Collecting: mt_516197696
53/271 - Collecting: mt_648401852
54/271 - Collecting: mt_892974209
55/271 - Collecting: mt_731362193
56/271 - Collecting: mt_203019306
57/271 - Collecting: mt_203019350
58/271 - Collecting: mt_731362121
59/271 - Collecting: mt_731361777
60/271 - Collecting: mt_648408692
61/271 - Collecting: mt_469629404
62/271 - Collecting: mt_731361744
63/271 - Collecting: mt_980830908
64/271 - Collecting: mt_731362232
65/271 - Collecting: mt_203019933
66/271 - Collecting: mt_027258701
67/271 - Collecting: mt_648401826
68/271 - Collecting: mt_731361766
69/271 - Collecting: mt_203013207
70/271 - Collecting: mt_516196583
71/271 - Collecting: mt_154584139
72/271 - Collecting: mt_154584143
73/271 - Collecting: mt_648401146
74/271 - Collecting: mt_027258884
75/271 - Collecting: mt_648401189
76/271 - Collecting: mt_731362105
77/271 - Collecting: mt_027258740
78/271 - Collecting: mt_027258783
79/271 - Collecting: mt_516197661
80/271 - Collecting: mt_203013223
81/271 - Collecting: mt_027257089
82/271 - Collecting: mt_469625562
83/271 - Collecting: mt_892974448
84/271 - Collecting: mt_027258872
85/271 - Collecting: mt_375740548
86/271 - Collecting: mt_892974265
87/271 - Collecting: mt_892974253
88/271 - Collecting: mt_892974232
89/271 - Collecting: mt_203019395
90/271 - Collecting: mt_469629491
91/271 - Collecting: mt_892974492
92/271 - Collecting: mt_154583334
93/271 - Collecting: mt_375740531
94/271 - Collecting: mt_980836090
95/271 - Collecting: mt_469625915
96/271 - Collecting: mt_203019378
97/271 - Collecting: mt_516197629
98/271 - Collecting: mt_516197684
99/271 - Collecting: mt_203013256
100/271 - Collecting: mt_980836681
101/271 - Collecting: mt_027258813
102/271 - Collecting: mt_731362241
103/271 - Collecting: mt_469625597
104/271 - Collecting: mt_469625920
105/271 - Collecting: mt_731362134
106/271 - Collecting: mt_892972887
107/271 - Collecting: mt_892972893
108/271 - Collecting: mt_731361722
109/271 - Collecting: mt_980836639
110/271 - Collecting: mt_648401810
111/271 - Collecting: mt_648401885
112/271 - Collecting: mt_980830996
113/271 - Collecting: mt_892972805
114/271 - Collecting: mt_375745365
115/271 - Collecting: mt_516196574
116/271 - Collecting: mt_027257073
117/271 - Collecting: mt_731361711
118/271 - Collecting: mt_731362217
119/271 - Collecting: mt_892974427
120/271 - Collecting: mt_469625902
121/271 - Collecting: mt_469625951
122/271 - Collecting: mt_469625998
123/271 - Collecting: mt_154584181
124/271 - Collecting: mt_375745317
125/271 - Collecting: mt_648408648
126/271 - Collecting: mt_892972842
127/271 - Collecting: mt_648401120
128/271 - Collecting: mt_648401115
129/271 - Collecting: mt_892974286
130/271 - Collecting: mt_516197657
131/271 - Collecting: mt_731362159
132/271 - Collecting: mt_154583400
133/271 - Collecting: mt_648408669
134/271 - Collecting: mt_980830984
135/271 - Collecting: mt_027257015
136/271 - Collecting: mt_516197771
137/271 - Collecting: mt_516197768
138/271 - Collecting: mt_980836049
139/271 - Collecting: mt_203019381
140/271 - Collecting: mt_469625989
141/271 - Collecting: mt_154583455
142/271 - Collecting: mt_154583499
143/271 - Collecting: mt_892972834
144/271 - Collecting: mt_469629452
145/271 - Collecting: mt_892972788
146/271 - Collecting: mt_027258829
147/271 - Collecting: mt_154583359
148/271 - Collecting: mt_203019955
149/271 - Collecting: mt_154583488
150/271 - Collecting: mt_154583433
151/271 - Collecting: mt_027257002
152/271 - Collecting: mt_892972876
153/271 - Collecting: mt_154584150
154/271 - Collecting: mt_203019900
155/271 - Collecting: mt_980836606
156/271 - Collecting: mt_648401863
157/271 - Collecting: mt_027258758
158/271 - Collecting: mt_203019367
159/271 - Collecting: mt_892974294
160/271 - Collecting: mt_892974228
161/271 - Collecting: mt_980830961
162/271 - Collecting: mt_516196562
163/271 - Collecting: mt_375740085
164/271 - Collecting: mt_154583393
165/271 - Collecting: mt_375740052
166/271 - Collecting: mt_731362160
167/271 - Collecting: mt_027258797
168/271 - Collecting: mt_731362142
169/271 - Collecting: mt_375740503
170/271 - Collecting: mt_516196558
171/271 - Collecting: mt_375745434
172/271 - Collecting: mt_375740063
173/271 - Collecting: mt_980836667
174/271 - Collecting: mt_648401891
175/271 - Collecting: mt_027258719
176/271 - Collecting: mt_731361755
177/271 - Collecting: mt_731361733
178/271 - Collecting: mt_203013290
179/271 - Collecting: mt_516197782
180/271 - Collecting: mt_154584195
181/271 - Collecting: mt_469625558
182/271 - Collecting: mt_203019312
183/271 - Collecting: mt_154583477
184/271 - Collecting: mt_375745332
185/271 - Collecting: mt_375745341
186/271 - Collecting: mt_375745370
187/271 - Collecting: mt_980830972
188/271 - Collecting: mt_154583466
189/271 - Collecting: mt_027258774
190/271 - Collecting: mt_469999516
191/271 - Collecting: mt_027777891
192/271 - Collecting: mt_154444371
193/271 - Collecting: mt_648888153
194/271 - Collecting: mt_375555018
195/271 - Collecting: mt_648888194
196/271 - Collecting: mt_731111206
197/271 - Collecting: mt_375555021
198/271 - Collecting: mt_516666746
199/271 - Collecting: mt_892222466
200/271 - Collecting: mt_516666737
201/271 - Collecting: mt_203333961
202/271 - Collecting: mt_154444307
203/271 - Collecting: mt_027777838
204/271 - Collecting: mt_980000619
205/271 - Collecting: mt_648888132
206/271 - Collecting: mt_375555087
207/271 - Collecting: mt_203333908
208/271 - Collecting: mt_731111295
209/271 - Collecting: mt_469999575
210/271 - Collecting: mt_516666715
211/271 - Collecting: mt_892222455
212/271 - Collecting: mt_980000683
213/271 - Collecting: mt_027777847
214/271 - Collecting: mt_747642176
215/271 - Collecting: mt_363460516
216/271 - Collecting: mt_363472816
217/271 - Collecting: mt_404261789
218/271 - Collecting: mt_979384114
219/271 - Collecting: mt_626021891
220/271 - Collecting: mt_010529440
221/271 - Collecting: mt_626045391
222/271 - Collecting: mt_252159367
223/271 - Collecting: mt_747642193
224/271 - Collecting: mt_979376014
225/271 - Collecting: mt_252108667
226/271 - Collecting: mt_191857000
227/271 - Collecting: mt_404205989
228/271 - Collecting: mt_585987629
229/271 - Collecting: mt_585987645
230/271 - Collecting: mt_191893400
231/271 - Collecting: mt_191837438
232/271 - Collecting: mt_191893466
233/271 - Collecting: mt_626021852
234/271 - Collecting: mt_010518740
235/271 - Collecting: mt_363460580
236/271 - Collecting: mt_838746240
237/271 - Collecting: mt_626021838
238/271 - Collecting: mt_838734286
239/271 - Collecting: mt_838734253
240/271 - Collecting: mt_838904400
241/271 - Collecting: mt_191563307
242/271 - Collecting: mt_747352295
243/271 - Collecting: mt_747352250
244/271 - Collecting: mt_363710018
245/271 - Collecting: mt_838904455
246/271 - Collecting: mt_010238838
247/271 - Collecting: mt_404198518
248/271 - Collecting: mt_626435296
249/271 - Collecting: mt_363710087
250/271 - Collecting: mt_838956364
251/271 - Collecting: mt_363782625
252/271 - Collecting: mt_838904499
253/271 - Collecting: mt_404671082
254/271 - Collecting: mt_979826619
255/271 - Collecting: mt_747390404
256/271 - Collecting: mt_585448732
257/271 - Collecting: mt_838907082
258/271 - Collecting: mt_191505109
259/271 - Collecting: mt_626434619
260/271 - Collecting: mt_404682821
261/271 - Collecting: mt_626490900
262/271 - Collecting: mt_363714143
263/271 - Collecting: mt_747393792
264/271 - Collecting: mt_585121578
265/271 - Collecting: mt_252060293
266/271 - Collecting: mt_747393716
267/271 - Collecting: mt_404676457
268/271 - Collecting: mt_747393727
269/271 - Collecting: mt_979818966
270/271 - Collecting: mt_838959847
271/271 - Collecting: mt_191505141

In [244]:
saved_europa_2025_26 = list(
    EUROPA_LEAGUE_SEASON_DIRS["2025_26"].glob("*.json")
)

print("Saved Europa League 2025/26 files:", len(saved_europa_2025_26))

Saved Europa League 2025/26 files: 271

In [ ]:
# Set Up UEFA Conference League seasons

CONFERENCE_LEAGUE_ID = "comp_408698"

CONFERENCE_LEAGUE_SEASONS = {
    "2026_27": "sn_7250309",
    "2025_26": "sn_1397633",
    "2024_25": "sn_8429027",
    "2023_24": "sn_343450",
    "2022_23": "sn_092013",
    "2021_22": "sn_033592"
}

In [246]:
# Create folder for UEFA Conference League matches

CONFERENCE_LEAGUE_DIR = RAW_MATCH_DIR / "conference_league"

CONFERENCE_LEAGUE_SEASON_DIRS = {}

for season_name in CONFERENCE_LEAGUE_SEASONS:
    season_dir = CONFERENCE_LEAGUE_DIR / season_name
    season_dir.mkdir(parents=True, exist_ok=True)
    CONFERENCE_LEAGUE_SEASON_DIRS[season_name] = season_dir

In [247]:
# Create a collector for UEFA Conference League seasons

def collect_conference_league_baseline_data(season_name, matches):
    season_dir = CONFERENCE_LEAGUE_SEASON_DIRS[season_name]
    total_matches = len(matches)

    for i, match in enumerate(matches, start=1):
        match_id = match["id"]
        file_path = season_dir / f"{match_id}.json"

        if file_path.exists():
            print(f"{i}/{total_matches} - Skipping existing: {match_id}")
            continue

        print(f"{i}/{total_matches} - Collecting: {match_id}")

        match_data = get_baseline_match_data(match_id)

        if match_data is None:
            print("Skipped:", match_id)
            continue

        save_match_data(match_id, match_data, season_dir)

        time.sleep(1)

In [248]:
# Collect 2021/22 Conference League season

conference_2021_22_matches = get_all_season_matches(
    CONFERENCE_LEAGUE_ID,
    CONFERENCE_LEAGUE_SEASONS["2021_22"]
)

print("Total matches returned:", len(conference_2021_22_matches))

Total matches returned: 423

In [249]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in conference_2021_22_matches))

print("\nStages:")
print(Counter(match.get("stage_name") for match in conference_2021_22_matches))

print("\nUnique IDs:", len(set(
    match["id"] for match in conference_2021_22_matches
)))

Statuses:
Counter({'finished': 423})

Stages:
Counter({'qualifying': 282, None: 112, 'round_of_16': 16, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 423

In [250]:
conference_2021_22_filtered = [
    match
    for match in conference_2021_22_matches
    if match.get("stage_name") != "qualifying"
]

print("Matches before filtering:", len(conference_2021_22_matches))
print("Matches after filtering:", len(conference_2021_22_filtered))

Matches before filtering: 423
Matches after filtering: 141

In [251]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in conference_2021_22_filtered))

print("\nStages:")
print(Counter(match.get("stage_name") for match in conference_2021_22_filtered))

print("\nUnique IDs:", len(set(
    match["id"] for match in conference_2021_22_filtered
)))

Statuses:
Counter({'finished': 141})

Stages:
Counter({None: 112, 'round_of_16': 16, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 141

In [252]:
collect_conference_league_baseline_data(
    "2021_22",
    conference_2021_22_filtered
)

1/141 - Collecting: mt_834992598
2/141 - Collecting: mt_018198735
3/141 - Collecting: mt_587837643
4/141 - Collecting: mt_193973465
5/141 - Collecting: mt_742402154
6/141 - Collecting: mt_976643341
7/141 - Collecting: mt_360024413
8/141 - Collecting: mt_405512281
9/141 - Collecting: mt_018895533
10/141 - Collecting: mt_742206740
11/141 - Collecting: mt_621150090
12/141 - Collecting: mt_976643328
13/141 - Collecting: mt_587739942
14/141 - Collecting: mt_587767235
15/141 - Collecting: mt_742212909
16/141 - Collecting: mt_018878430
17/141 - Collecting: mt_587767249
18/141 - Collecting: mt_018878457
19/141 - Collecting: mt_976606143
20/141 - Collecting: mt_405595719
21/141 - Collecting: mt_976606124
22/141 - Collecting: mt_621181302
23/141 - Collecting: mt_360050826
24/141 - Collecting: mt_621181351
25/141 - Collecting: mt_259939677
26/141 - Collecting: mt_405595725
27/141 - Collecting: mt_259939688
28/141 - Collecting: mt_193343076
29/141 - Collecting: mt_834424569
30/141 - Collecting: mt_017554700
31/141 - Collecting: mt_409289918
32/141 - Collecting: mt_365415512
33/141 - Collecting: mt_017537794
34/141 - Collecting: mt_970320047
35/141 - Collecting: mt_194864474
36/141 - Collecting: mt_628098899
37/141 - Collecting: mt_586946675
38/141 - Collecting: mt_741651161
39/141 - Collecting: mt_832702268
40/141 - Collecting: mt_628098855
41/141 - Collecting: mt_832702207
42/141 - Collecting: mt_409227599
43/141 - Collecting: mt_365415524
44/141 - Collecting: mt_586946631
45/141 - Collecting: mt_253173389
46/141 - Collecting: mt_253055176
47/141 - Collecting: mt_409600272
48/141 - Collecting: mt_970877311
49/141 - Collecting: mt_832933752
50/141 - Collecting: mt_017211523
51/141 - Collecting: mt_586188912
52/141 - Collecting: mt_628422025
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
53/141 - Collecting: mt_017211514
54/141 - Collecting: mt_741344654
55/141 - Collecting: mt_017211549
56/141 - Collecting: mt_409600119
57/141 - Collecting: mt_586188349
58/141 - Collecting: mt_586188323
59/141 - Collecting: mt_832933654
60/141 - Collecting: mt_741344032
61/141 - Collecting: mt_832933692
62/141 - Collecting: mt_253055159
63/141 - Collecting: mt_365766402
64/141 - Collecting: mt_194599776
65/141 - Collecting: mt_253055877
66/141 - Collecting: mt_017211945
67/141 - Collecting: mt_017211913
68/141 - Collecting: mt_194599865
69/141 - Collecting: mt_194599809
70/141 - Collecting: mt_970877388
71/141 - Collecting: mt_253055105
72/141 - Collecting: mt_365766464
73/141 - Collecting: mt_409600208
74/141 - Collecting: mt_586188981
75/141 - Collecting: mt_586188314
76/141 - Collecting: mt_586188924
77/141 - Collecting: mt_365766285
78/141 - Collecting: mt_970877322
79/141 - Collecting: mt_365766415
80/141 - Collecting: mt_741344692
81/141 - Collecting: mt_194599853
82/141 - Collecting: mt_970877377
83/141 - Collecting: mt_017211930
84/141 - Collecting: mt_628422040
85/141 - Collecting: mt_628422019
86/141 - Collecting: mt_586188978
87/141 - Collecting: mt_970877366
88/141 - Collecting: mt_832933669
89/141 - Collecting: mt_628422546
90/141 - Collecting: mt_970877481
91/141 - Collecting: mt_253055800
92/141 - Collecting: mt_017211582
93/141 - Collecting: mt_741344094
94/141 - Collecting: mt_253055160
95/141 - Collecting: mt_194599894
96/141 - Collecting: mt_741344627
97/141 - Collecting: mt_832933747
98/141 - Collecting: mt_586188335
99/141 - Collecting: mt_365766226
100/141 - Collecting: mt_832933704
101/141 - Collecting: mt_628422036
102/141 - Collecting: mt_409600261
103/141 - Collecting: mt_741344631
104/141 - Collecting: mt_832933738
105/141 - Collecting: mt_409600257
106/141 - Collecting: mt_628422551
107/141 - Collecting: mt_409600174
108/141 - Collecting: mt_628422520
109/141 - Collecting: mt_194599759
110/141 - Collecting: mt_194599841
111/141 - Collecting: mt_741344616
112/141 - Collecting: mt_832933726
113/141 - Collecting: mt_628422083
114/141 - Collecting: mt_970877300
115/141 - Collecting: mt_832933680
116/141 - Collecting: mt_365766238
117/141 - Collecting: mt_409600140
118/141 - Collecting: mt_253055822
119/141 - Collecting: mt_741344070
120/141 - Collecting: mt_741344009
121/141 - Collecting: mt_194599760
122/141 - Collecting: mt_970877412
123/141 - Collecting: mt_253055866
124/141 - Collecting: mt_365766263
125/141 - Collecting: mt_409600101
126/141 - Collecting: mt_253055193
127/141 - Collecting: mt_365766451
128/141 - Collecting: mt_970877424
129/141 - Collecting: mt_741344053
130/141 - Collecting: mt_194599705
131/141 - Collecting: mt_409600296
132/141 - Collecting: mt_017211571
133/141 - Collecting: mt_586188967
134/141 - Collecting: mt_628422564
135/141 - Collecting: mt_586188356
136/141 - Collecting: mt_970877439
137/141 - Collecting: mt_409600162
138/141 - Collecting: mt_741344017
139/141 - Collecting: mt_194599718
140/141 - Collecting: mt_017211908
141/141 - Collecting: mt_194599734

In [253]:
saved_conference_2021_22 = list(
    CONFERENCE_LEAGUE_SEASON_DIRS["2021_22"].glob("*.json")
)

print("Saved Conference League 2021/22 files:", len(saved_conference_2021_22))

Saved Conference League 2021/22 files: 141

In [254]:
# Collect 2022/23 Conference League season

conference_2022_23_matches = get_all_season_matches(
    CONFERENCE_LEAGUE_ID,
    CONFERENCE_LEAGUE_SEASONS["2022_23"]
)

print("Total matches returned:", len(conference_2022_23_matches))

Total matches returned: 415

In [255]:
conference_2022_23_filtered = [
    match
    for match in conference_2022_23_matches
    if match.get("stage_name") != "qualifying"
]

print("Matches before filtering:", len(conference_2022_23_matches))
print("Matches after filtering:", len(conference_2022_23_filtered))

Matches before filtering: 415
Matches after filtering: 141

In [256]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in conference_2022_23_filtered))

print("\nStages:")
print(Counter(match.get("stage_name") for match in conference_2022_23_filtered))

print("\nUnique IDs:", len(set(
    match["id"] for match in conference_2022_23_filtered
)))

Statuses:
Counter({'finished': 141})

Stages:
Counter({None: 96, 'round_of_16': 32, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 141

In [257]:
collect_conference_league_baseline_data(
    "2022_23",
    conference_2022_23_filtered
)

1/141 - Collecting: mt_406005964
2/141 - Collecting: mt_581777843
3/141 - Collecting: mt_978666722
4/141 - Collecting: mt_250999576
5/141 - Collecting: mt_195333965
6/141 - Collecting: mt_011034915
7/141 - Collecting: mt_199160795
8/141 - Collecting: mt_977921472
9/141 - Collecting: mt_255276856
10/141 - Collecting: mt_833805634
11/141 - Collecting: mt_366318265
12/141 - Collecting: mt_622693516
13/141 - Collecting: mt_744759044
14/141 - Collecting: mt_400210212
15/141 - Collecting: mt_011591599
16/141 - Collecting: mt_977347341
17/141 - Collecting: mt_255185180
18/141 - Collecting: mt_366426445
19/141 - Collecting: mt_622052056
20/141 - Collecting: mt_588938934
21/141 - Collecting: mt_366426307
22/141 - Collecting: mt_622052612
23/141 - Collecting: mt_833763762
24/141 - Collecting: mt_366426413
25/141 - Collecting: mt_011591533
26/141 - Collecting: mt_744604602
27/141 - Collecting: mt_400210281
28/141 - Collecting: mt_588938942
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
29/141 - Collecting: mt_622052090
30/141 - Collecting: mt_255639008
31/141 - Collecting: mt_199043556
32/141 - Collecting: mt_833524999
33/141 - Collecting: mt_366850776
34/141 - Collecting: mt_011478247
35/141 - Collecting: mt_588267115
36/141 - Collecting: mt_977106883
37/141 - Collecting: mt_744912339
38/141 - Collecting: mt_622381441
39/141 - Collecting: mt_400795669
40/141 - Collecting: mt_011478210
41/141 - Collecting: mt_255639057
42/141 - Collecting: mt_588267189
43/141 - Collecting: mt_977106874
44/141 - Collecting: mt_199043590
45/141 - Collecting: mt_744912343
46/141 - Collecting: mt_588686165
47/141 - Collecting: mt_833232929
48/141 - Collecting: mt_400909699
49/141 - Collecting: mt_255353527
50/141 - Collecting: mt_199494910
51/141 - Collecting: mt_744141473
52/141 - Collecting: mt_744141325
53/141 - Collecting: mt_833232945
54/141 - Collecting: mt_622828412
55/141 - Collecting: mt_977070803
56/141 - Collecting: mt_255353038
57/141 - Collecting: mt_011717100
58/141 - Collecting: mt_588686859
59/141 - Collecting: mt_366565630
60/141 - Collecting: mt_622828481
61/141 - Collecting: mt_833232383
62/141 - Collecting: mt_833232930
63/141 - Collecting: mt_366565768
64/141 - Collecting: mt_366565707
65/141 - Collecting: mt_400909655
66/141 - Collecting: mt_199494546
67/141 - Collecting: mt_744141319
68/141 - Collecting: mt_366565756
69/141 - Collecting: mt_977070794
70/141 - Collecting: mt_622828268
71/141 - Collecting: mt_400909024
72/141 - Collecting: mt_977070880
73/141 - Collecting: mt_199494598
74/141 - Collecting: mt_400909600
75/141 - Collecting: mt_199494537
76/141 - Collecting: mt_011717287
77/141 - Collecting: mt_011717155
78/141 - Collecting: mt_744141336
79/141 - Collecting: mt_366565771
80/141 - Collecting: mt_400909666
81/141 - Collecting: mt_588686117
82/141 - Collecting: mt_622828424
83/141 - Collecting: mt_588686186
84/141 - Collecting: mt_977070869
85/141 - Collecting: mt_744141451
86/141 - Collecting: mt_833232996
87/141 - Collecting: mt_622828443
88/141 - Collecting: mt_011717221
89/141 - Collecting: mt_255353052
90/141 - Collecting: mt_744141340
91/141 - Collecting: mt_011717218
92/141 - Collecting: mt_255353091
93/141 - Collecting: mt_833232358
94/141 - Collecting: mt_977070732
95/141 - Collecting: mt_622828256
96/141 - Collecting: mt_588686834
97/141 - Collecting: mt_255353580
98/141 - Collecting: mt_199494979
99/141 - Collecting: mt_366565613
100/141 - Collecting: mt_255353575
101/141 - Collecting: mt_199494963
102/141 - Collecting: mt_588686893
103/141 - Collecting: mt_366565645
104/141 - Collecting: mt_833232362
105/141 - Collecting: mt_622828290
106/141 - Collecting: mt_400909081
107/141 - Collecting: mt_011717133
108/141 - Collecting: mt_588686842
109/141 - Collecting: mt_588686821
110/141 - Collecting: mt_255353516
111/141 - Collecting: mt_400909012
112/141 - Collecting: mt_011717199
113/141 - Collecting: mt_977070741
114/141 - Collecting: mt_744141402
115/141 - Collecting: mt_977070717
116/141 - Collecting: mt_011717122
117/141 - Collecting: mt_366565661
118/141 - Collecting: mt_744141464
119/141 - Collecting: mt_833232374
120/141 - Collecting: mt_833232397
121/141 - Collecting: mt_366565672
122/141 - Collecting: mt_622828249
123/141 - Collecting: mt_400909067
124/141 - Collecting: mt_588686818
125/141 - Collecting: mt_977070786
126/141 - Collecting: mt_833232535
127/141 - Collecting: mt_199494985
128/141 - Collecting: mt_977070728
129/141 - Collecting: mt_366565684
130/141 - Collecting: mt_622828235
131/141 - Collecting: mt_400909078
132/141 - Collecting: mt_255353569
133/141 - Collecting: mt_744141437
134/141 - Collecting: mt_011717144
135/141 - Collecting: mt_199494904
136/141 - Collecting: mt_255353503
137/141 - Collecting: mt_199494991
138/141 - Collecting: mt_744141446
139/141 - Collecting: mt_833232336
140/141 - Collecting: mt_622828223
141/141 - Collecting: mt_400909006

In [258]:
saved_conference_2022_23 = list(
    CONFERENCE_LEAGUE_SEASON_DIRS["2022_23"].glob("*.json")
)

print("Saved Conference League 2022/23 files:", len(saved_conference_2022_23))

Saved Conference League 2022/23 files: 141

In [259]:
# Collect 2023/24 Conference League season

conference_2023_24_matches = get_all_season_matches(
    CONFERENCE_LEAGUE_ID,
    CONFERENCE_LEAGUE_SEASONS["2023_24"]
)

print("Total matches returned:", len(conference_2023_24_matches))

Total matches returned: 417

In [260]:
conference_2023_24_filtered = [
    match
    for match in conference_2023_24_matches
    if match.get("stage_name") != "qualifying"
]

print("Matches before filtering:", len(conference_2023_24_matches))
print("Matches after filtering:", len(conference_2023_24_filtered))

Matches before filtering: 417
Matches after filtering: 185

In [261]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in conference_2023_24_filtered))

print("\nStages:")
print(Counter(match.get("stage_name") for match in conference_2023_24_filtered))

print("\nUnique IDs:", len(set(
    match["id"] for match in conference_2023_24_filtered
)))

Statuses:
Counter({'finished': 185})

Stages:
Counter({None: 96, 'round_of_16': 76, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 185

In [263]:
collect_conference_league_baseline_data(
    "2023_24",
    conference_2023_24_filtered
)

1/185 - Skipping existing: mt_835849894
2/185 - Skipping existing: mt_623614626
3/185 - Skipping existing: mt_368307375
4/185 - Skipping existing: mt_407456402
5/185 - Collecting: mt_014082019
6/185 - Collecting: mt_582571584
7/185 - Collecting: mt_971968971
8/185 - Collecting: mt_256290250
9/185 - Collecting: mt_190135199
10/185 - Collecting: mt_835787858
11/185 - Collecting: mt_256121269
12/185 - Collecting: mt_190818163
13/185 - Collecting: mt_014505044
14/185 - Collecting: mt_835688905
15/185 - Collecting: mt_368233717
16/185 - Collecting: mt_623566492
17/185 - Collecting: mt_407144685
18/185 - Collecting: mt_014900237
19/185 - Collecting: mt_582355125
20/185 - Collecting: mt_971499813
21/185 - Collecting: mt_256822068
22/185 - Collecting: mt_835675895
23/185 - Collecting: mt_407127465
24/185 - Collecting: mt_014954027
25/185 - Collecting: mt_835675843
26/185 - Collecting: mt_256816201
27/185 - Collecting: mt_623503642
28/185 - Collecting: mt_749069749
29/185 - Collecting: mt_971431964
30/185 - Collecting: mt_623499935
31/185 - Collecting: mt_014233344
32/185 - Collecting: mt_971822217
33/185 - Collecting: mt_256077769
34/185 - Collecting: mt_407688878
35/185 - Collecting: mt_190566604
36/185 - Collecting: mt_749355537
37/185 - Collecting: mt_582144421
38/185 - Collecting: mt_256077792
39/185 - Collecting: mt_582144476
40/185 - Collecting: mt_835900025
41/185 - Collecting: mt_190566016
42/185 - Collecting: mt_749355520
43/185 - Collecting: mt_749355515
44/185 - Collecting: mt_014233377
45/185 - Collecting: mt_368711836
46/185 - Collecting: mt_195865506
47/185 - Collecting: mt_743653399
48/185 - Collecting: mt_581941889
49/185 - Collecting: mt_250170557
50/185 - Collecting: mt_195865990
51/185 - Collecting: mt_743653443
52/185 - Collecting: mt_839709333
53/185 - Collecting: mt_012532185
54/185 - Collecting: mt_406286685
55/185 - Collecting: mt_012532237
56/185 - Collecting: mt_581941125
57/185 - Collecting: mt_978328813
58/185 - Collecting: mt_250170068
59/185 - Collecting: mt_367417786
60/185 - Collecting: mt_624094431
61/185 - Collecting: mt_406286679
62/185 - Collecting: mt_581941136
63/185 - Collecting: mt_978328829
64/185 - Collecting: mt_250170071
65/185 - Collecting: mt_195865567
66/185 - Collecting: mt_743653355
67/185 - Collecting: mt_367417717
68/185 - Collecting: mt_839709905
69/185 - Collecting: mt_624094492
70/185 - Collecting: mt_839709959
71/185 - Collecting: mt_012532220
72/185 - Collecting: mt_978328774
73/185 - Collecting: mt_624094228
74/185 - Collecting: mt_406286054
75/185 - Collecting: mt_581941873
76/185 - Collecting: mt_012532110
77/185 - Collecting: mt_367417660
78/185 - Collecting: mt_835449062
79/185 - Collecting: mt_195865539
80/185 - Collecting: mt_367417634
81/185 - Collecting: mt_406286048
82/185 - Collecting: mt_743653207
83/185 - Collecting: mt_839709467
84/185 - Collecting: mt_978328620
85/185 - Collecting: mt_367417088
86/185 - Collecting: mt_012532215
87/185 - Collecting: mt_839709934
88/185 - Collecting: mt_624094416
89/185 - Collecting: mt_581941174
90/185 - Collecting: mt_250170090
91/185 - Collecting: mt_012532273
92/185 - Collecting: mt_743653311
93/185 - Collecting: mt_250170530
94/185 - Collecting: mt_743653412
95/185 - Collecting: mt_581941183
96/185 - Collecting: mt_195865595
97/185 - Collecting: mt_743653344
98/185 - Collecting: mt_978328861
99/185 - Collecting: mt_367417753
100/185 - Collecting: mt_978328808
101/185 - Collecting: mt_012532104
102/185 - Collecting: mt_012532803
103/185 - Collecting: mt_250170056
104/185 - Collecting: mt_581941162
105/185 - Collecting: mt_624094265
106/185 - Collecting: mt_195865949
107/185 - Collecting: mt_839709406
108/185 - Collecting: mt_581941747
109/185 - Collecting: mt_250170962
110/185 - Collecting: mt_367417770
111/185 - Collecting: mt_367417765
112/185 - Collecting: mt_406286652
113/185 - Collecting: mt_839709942
114/185 - Collecting: mt_624094480
115/185 - Collecting: mt_406286691
116/185 - Collecting: mt_195865914
117/185 - Collecting: mt_743653467
118/185 - Collecting: mt_250170035
119/185 - Collecting: mt_195865543
120/185 - Collecting: mt_367417033
121/185 - Collecting: mt_195865361
122/185 - Collecting: mt_743653256
123/185 - Collecting: mt_195865308
124/185 - Collecting: mt_839709450
125/185 - Collecting: mt_839709322
126/185 - Collecting: mt_839709388
127/185 - Collecting: mt_581941851
128/185 - Collecting: mt_624094160
129/185 - Collecting: mt_406286541
130/185 - Collecting: mt_250170983
131/185 - Collecting: mt_367417011
132/185 - Collecting: mt_624094134
133/185 - Collecting: mt_839709993
134/185 - Collecting: mt_624094448
135/185 - Collecting: mt_406286604
136/185 - Collecting: mt_978328872
137/185 - Collecting: mt_012532289
138/185 - Collecting: mt_743653322
139/185 - Collecting: mt_978328797
140/185 - Collecting: mt_250170529
141/185 - Collecting: mt_743653290
142/185 - Collecting: mt_195765780
143/185 - Collecting: mt_624594596
144/185 - Collecting: mt_250870865
145/185 - Collecting: mt_581341344
146/185 - Collecting: mt_978428421
147/185 - Collecting: mt_367217283
148/185 - Collecting: mt_406186149
149/185 - Collecting: mt_743053063
150/185 - Collecting: mt_839609673
151/185 - Collecting: mt_978428442
152/185 - Collecting: mt_367217225
153/185 - Collecting: mt_624594530
154/185 - Collecting: mt_012932943
155/185 - Collecting: mt_581341322
156/185 - Collecting: mt_012932950
157/185 - Collecting: mt_406186182
158/185 - Collecting: mt_250870870
159/185 - Collecting: mt_978428418
160/185 - Collecting: mt_839603064
161/185 - Collecting: mt_367217240
162/185 - Collecting: mt_624594508
163/185 - Collecting: mt_743053052
164/185 - Collecting: mt_406180882
165/185 - Collecting: mt_624592930
166/185 - Collecting: mt_012931343
167/185 - Collecting: mt_367216183
168/185 - Collecting: mt_839609664
169/185 - Collecting: mt_978427218
170/185 - Collecting: mt_250875765
171/185 - Collecting: mt_839603098
172/185 - Collecting: mt_624592996
173/185 - Collecting: mt_978427221
174/185 - Collecting: mt_743054552
175/185 - Collecting: mt_839603002
176/185 - Collecting: mt_406180871
177/185 - Collecting: mt_581348422
178/185 - Collecting: mt_195769603
179/185 - Collecting: mt_406180849
180/185 - Collecting: mt_195769669
181/185 - Collecting: mt_012931339
182/185 - Collecting: mt_367216125
183/185 - Collecting: mt_581348444
184/185 - Collecting: mt_743054591
185/185 - Collecting: mt_250875770

In [264]:
saved_conference_2023_24 = list(
    CONFERENCE_LEAGUE_SEASON_DIRS["2023_24"].glob("*.json")
)

print("Saved Conference League 2023/24 files:", len(saved_conference_2023_24))

Saved Conference League 2023/24 files: 185

In [265]:
# Collect 2024/25 Europa League season

conference_2024_25_matches = get_all_season_matches(
    CONFERENCE_LEAGUE_ID,
    CONFERENCE_LEAGUE_SEASONS["2024_25"]
)

print("Total matches returned:", len(conference_2024_25_matches))

Total matches returned: 407

In [266]:
conference_2024_25_filtered = [
    match
    for match in conference_2024_25_matches
    if match.get("stage_name") != "qualifying"
]

print("Matches before filtering:", len(conference_2024_25_matches))
print("Matches after filtering:", len(conference_2024_25_filtered))

Matches before filtering: 407
Matches after filtering: 201

In [267]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in conference_2024_25_filtered))

print("\nStages:")
print(Counter(match.get("stage_name") for match in conference_2024_25_filtered))

print("\nUnique IDs:", len(set(
    match["id"] for match in conference_2024_25_filtered
)))

Statuses:
Counter({'finished': 201})

Stages:
Counter({None: 108, 'round_of_16': 80, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 201

In [270]:
collect_conference_league_baseline_data(
    "2024_25",
    conference_2024_25_filtered
)

1/201 - Skipping existing: mt_973106302
2/201 - Skipping existing: mt_837977734
3/201 - Skipping existing: mt_015255573
4/201 - Skipping existing: mt_364744465
5/201 - Skipping existing: mt_402622291
6/201 - Skipping existing: mt_973833497
7/201 - Skipping existing: mt_251011829
8/201 - Skipping existing: mt_015255589
9/201 - Skipping existing: mt_364744234
10/201 - Skipping existing: mt_589199351
11/201 - Skipping existing: mt_198588714
12/201 - Skipping existing: mt_746366067
13/201 - Skipping existing: mt_402622252
14/201 - Skipping existing: mt_589194765
15/201 - Skipping existing: mt_251017938
16/201 - Skipping existing: mt_364741056
17/201 - Skipping existing: mt_198586485
18/201 - Skipping existing: mt_746365219
19/201 - Skipping existing: mt_251017327
20/201 - Skipping existing: mt_837970283
21/201 - Skipping existing: mt_837970274
22/201 - Skipping existing: mt_837970429
23/201 - Skipping existing: mt_198586410
24/201 - Skipping existing: mt_364741530
25/201 - Skipping existing: mt_015253799
26/201 - Skipping existing: mt_973832603
27/201 - Skipping existing: mt_198586346
28/201 - Skipping existing: mt_402628599
29/201 - Skipping existing: mt_746365164
30/201 - Skipping existing: mt_740737925
31/201 - Skipping existing: mt_401464755
32/201 - Skipping existing: mt_583515265
33/201 - Skipping existing: mt_836898529
34/201 - Skipping existing: mt_197151037
35/201 - Skipping existing: mt_836898545
36/201 - Skipping existing: mt_258202638
37/201 - Skipping existing: mt_401464799
38/201 - Skipping existing: mt_740737373
39/201 - Skipping existing: mt_258202080
40/201 - Skipping existing: mt_019020233
41/201 - Skipping existing: mt_583515142
42/201 - Skipping existing: mt_740737364
43/201 - Skipping existing: mt_019020299
44/201 - Skipping existing: mt_740737302
45/201 - Skipping existing: mt_625646490
46/201 - Skipping existing: mt_019783387
47/201 - Skipping existing: mt_401958767
48/201 - Skipping existing: mt_974062186
49/201 - Skipping existing: mt_836240525
50/201 - Skipping existing: mt_583674155
51/201 - Skipping existing: mt_583674133
52/201 - Skipping existing: mt_974062821
53/201 - Skipping existing: mt_974062818
54/201 - Skipping existing: mt_974062860
55/201 - Skipping existing: mt_197436965
56/201 - Skipping existing: mt_197436909
57/201 - Skipping existing: mt_836240326
58/201 - Skipping existing: mt_401958525
59/201 - Skipping existing: mt_362501010
60/201 - Skipping existing: mt_258397900
61/201 - Skipping existing: mt_625819120
62/201 - Skipping existing: mt_974062678
63/201 - Skipping existing: mt_740125160
64/201 - Skipping existing: mt_258397692
65/201 - Skipping existing: mt_258397009
66/201 - Skipping existing: mt_197436531
67/201 - Skipping existing: mt_197436917
68/201 - Skipping existing: mt_362501637
69/201 - Skipping existing: mt_583674824
70/201 - Skipping existing: mt_019783758
71/201 - Skipping existing: mt_362501168
72/201 - Skipping existing: mt_625819349
73/201 - Skipping existing: mt_625819408
74/201 - Skipping existing: mt_258397053
75/201 - Skipping existing: mt_974062777
76/201 - Skipping existing: mt_258397922
77/201 - Skipping existing: mt_836240403
78/201 - Skipping existing: mt_362501063
79/201 - Skipping existing: mt_583674768
80/201 - Skipping existing: mt_740125431
81/201 - Skipping existing: mt_974062170
82/201 - Skipping existing: mt_836240998
83/201 - Skipping existing: mt_583674188
84/201 - Skipping existing: mt_974062711
85/201 - Skipping existing: mt_258397560
86/201 - Skipping existing: mt_401958008
87/201 - Skipping existing: mt_836240427
88/201 - Skipping existing: mt_019783444
89/201 - Skipping existing: mt_401958750
90/201 - Skipping existing: mt_583674276
91/201 - Skipping existing: mt_019783239
92/201 - Skipping existing: mt_401958671
93/201 - Skipping existing: mt_625819445
94/201 - Skipping existing: mt_197436986
95/201 - Skipping existing: mt_583674839
96/201 - Skipping existing: mt_197436387
97/201 - Skipping existing: mt_258397988
98/201 - Skipping existing: mt_583674812
99/201 - Skipping existing: mt_740125232
100/201 - Skipping existing: mt_258397669
101/201 - Skipping existing: mt_197436516
102/201 - Skipping existing: mt_019783278
103/201 - Skipping existing: mt_583674843
104/201 - Skipping existing: mt_019783845
105/201 - Skipping existing: mt_836240454
106/201 - Skipping existing: mt_401958501
107/201 - Skipping existing: mt_019783813
108/201 - Skipping existing: mt_019783701
109/201 - Skipping existing: mt_197436488
110/201 - Skipping existing: mt_740125946
111/201 - Skipping existing: mt_362501808
112/201 - Skipping existing: mt_401958607
113/201 - Skipping existing: mt_583674895
114/201 - Skipping existing: mt_258397593
115/201 - Skipping existing: mt_258397977
116/201 - Collecting: mt_197436477
117/201 - Collecting: mt_401958706
118/201 - Collecting: mt_625819323
119/201 - Collecting: mt_625819314
120/201 - Collecting: mt_625819429
121/201 - Collecting: mt_401958045
122/201 - Collecting: mt_401958057
123/201 - Collecting: mt_019783182
124/201 - Collecting: mt_019783884
125/201 - Collecting: mt_836240597
126/201 - Collecting: mt_740125915
127/201 - Collecting: mt_019783477
128/201 - Collecting: mt_974062887
129/201 - Collecting: mt_401958656
130/201 - Collecting: mt_836240920
131/201 - Collecting: mt_019783149
132/201 - Collecting: mt_197436360
133/201 - Collecting: mt_401958562
134/201 - Collecting: mt_401958915
135/201 - Collecting: mt_583674287
136/201 - Collecting: mt_362501736
137/201 - Collecting: mt_583674199
138/201 - Collecting: mt_197436503
139/201 - Collecting: mt_836240379
140/201 - Collecting: mt_583674782
141/201 - Collecting: mt_362501052
142/201 - Collecting: mt_625819863
143/201 - Collecting: mt_836240270
144/201 - Collecting: mt_836240540
145/201 - Collecting: mt_258397017
146/201 - Collecting: mt_362501646
147/201 - Collecting: mt_625819236
148/201 - Collecting: mt_740125492
149/201 - Collecting: mt_362501673
150/201 - Collecting: mt_583674867
151/201 - Collecting: mt_974062612
152/201 - Collecting: mt_625819258
153/201 - Collecting: mt_836240492
154/201 - Collecting: mt_257236300
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
155/201 - Collecting: mt_584562682
156/201 - Collecting: mt_584566754
157/201 - Collecting: mt_408497901
158/201 - Collecting: mt_408499521
159/201 - Collecting: mt_361358563
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
160/201 - Collecting: mt_408499542
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
161/201 - Collecting: mt_361358585
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
162/201 - Collecting: mt_745719132
163/201 - Collecting: mt_361355655
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
164/201 - Collecting: mt_196144319
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
165/201 - Collecting: mt_257233915
166/201 - Collecting: mt_408499518
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
167/201 - Collecting: mt_830825292
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
168/201 - Collecting: mt_972901012
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
169/201 - Collecting: mt_972901081
170/201 - Collecting: mt_196140459
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
171/201 - Collecting: mt_972900638
172/201 - Collecting: mt_629683820
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
173/201 - Collecting: mt_830822468
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
174/201 - Collecting: mt_584566731
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
175/201 - Collecting: mt_629688100
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
176/201 - Collecting: mt_013074713
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
177/201 - Collecting: mt_408499094
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
178/201 - Collecting: mt_584566863
179/201 - Collecting: mt_013077853
180/201 - Collecting: mt_361355024
181/201 - Collecting: mt_196144374
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
182/201 - Collecting: mt_830822324
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
183/201 - Collecting: mt_830822407
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
184/201 - Collecting: mt_013077809
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
185/201 - Collecting: mt_196144945
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
186/201 - Collecting: mt_745711414
187/201 - Collecting: mt_257233920
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
188/201 - Collecting: mt_745711272
189/201 - Collecting: mt_972900647
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
190/201 - Collecting: mt_013077175
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
191/201 - Collecting: mt_972900691
192/201 - Collecting: mt_584566792
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
193/201 - Collecting: mt_196144383
194/201 - Collecting: mt_745711261
195/201 - Collecting: mt_745711257
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
196/201 - Collecting: mt_629688155
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
197/201 - Collecting: mt_629688166
198/201 - Collecting: mt_361355043
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
199/201 - Collecting: mt_013077894
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
200/201 - Collecting: mt_830822482
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']
201/201 - Collecting: mt_257233536
Request failed: 404
{"error":{"code":"STATS_NOT_AVAILABLE_AT_SOURCE","message":"Detailed statistics for this match do not exist at the data source","status_code":404}}
Saving with missing sections: ['statistics']

In [271]:
saved_conference_2024_25 = list(
    CONFERENCE_LEAGUE_SEASON_DIRS["2024_25"].glob("*.json")
)

print("Saved Conference League 2024/25 files:", len(saved_conference_2024_25))

Saved Conference League 2024/25 files: 201

In [272]:
# Collect 2025/26 Conference League season

conference_2025_26_matches = get_all_season_matches(
    CONFERENCE_LEAGUE_ID,
    CONFERENCE_LEAGUE_SEASONS["2025_26"]
)

print("Total matches returned:", len(conference_2025_26_matches))

Total matches returned: 411

In [273]:
conference_2025_26_filtered = [
    match
    for match in conference_2025_26_matches
    if match.get("stage_name") != "qualifying"
]

print("Matches before filtering:", len(conference_2025_26_matches))
print("Matches after filtering:", len(conference_2025_26_filtered))

Matches before filtering: 411
Matches after filtering: 201

In [275]:
from collections import Counter

print("Statuses:")
print(Counter(match["status"] for match in conference_2025_26_filtered))

print("\nStages:")
print(Counter(match.get("stage_name") for match in conference_2025_26_filtered))

print("\nUnique IDs:", len(set(
    match["id"] for match in conference_2025_26_filtered
)))

Statuses:
Counter({'finished': 201})

Stages:
Counter({None: 108, 'round_of_16': 80, 'quarter_final': 8, 'semi_final': 4, 'final': 1})

Unique IDs: 201

In [276]:
collect_conference_league_baseline_data(
    "2025_26",
    conference_2025_26_filtered
)

1/201 - Collecting: mt_734305701
2/201 - Collecting: mt_893960808
3/201 - Collecting: mt_376721314
4/201 - Collecting: mt_642459695
5/201 - Collecting: mt_460618488
6/201 - Collecting: mt_021293034
7/201 - Collecting: mt_518134541
8/201 - Collecting: mt_987842927
9/201 - Collecting: mt_205087279
10/201 - Collecting: mt_159576164
11/201 - Collecting: mt_893960857
12/201 - Collecting: mt_376721382
13/201 - Collecting: mt_734305797
14/201 - Collecting: mt_159576356
15/201 - Collecting: mt_376721076
16/201 - Collecting: mt_642459141
17/201 - Collecting: mt_460618569
18/201 - Collecting: mt_734305239
19/201 - Collecting: mt_893960499
20/201 - Collecting: mt_021293810
21/201 - Collecting: mt_518134789
22/201 - Collecting: mt_205087957
23/201 - Collecting: mt_159576390
24/201 - Collecting: mt_642459128
25/201 - Collecting: mt_460618554
26/201 - Collecting: mt_987842674
27/201 - Collecting: mt_734305243
28/201 - Collecting: mt_893960433
29/201 - Collecting: mt_376721060
30/201 - Collecting: mt_894854693
31/201 - Collecting: mt_028048989
32/201 - Collecting: mt_986916461
33/201 - Collecting: mt_209269890
34/201 - Collecting: mt_370380265
35/201 - Collecting: mt_641631516
36/201 - Collecting: mt_465475152
37/201 - Collecting: mt_517527374
38/201 - Collecting: mt_641631965
39/201 - Collecting: mt_465475848
40/201 - Collecting: mt_028048304
41/201 - Collecting: mt_986916297
42/201 - Collecting: mt_517527451
43/201 - Collecting: mt_209269729
44/201 - Collecting: mt_153103614
45/201 - Collecting: mt_732792567
46/201 - Collecting: mt_469625899
47/201 - Collecting: mt_731362964
48/201 - Collecting: mt_375740813
49/201 - Collecting: mt_516197242
50/201 - Collecting: mt_154583004
51/201 - Collecting: mt_648401323
52/201 - Collecting: mt_154583038
53/201 - Collecting: mt_027258488
54/201 - Collecting: mt_203019631
55/201 - Collecting: mt_516197155
56/201 - Collecting: mt_469625649
57/201 - Collecting: mt_980836834
58/201 - Collecting: mt_892974973
59/201 - Collecting: mt_648401408
60/201 - Collecting: mt_648401496
61/201 - Collecting: mt_648401430
62/201 - Collecting: mt_980836818
63/201 - Collecting: mt_731362391
64/201 - Collecting: mt_469625800
65/201 - Collecting: mt_980836269
66/201 - Collecting: mt_027258455
67/201 - Collecting: mt_731362951
68/201 - Collecting: mt_375740884
69/201 - Collecting: mt_731362937
70/201 - Collecting: mt_731362946
71/201 - Collecting: mt_731362379
72/201 - Collecting: mt_892974902
73/201 - Collecting: mt_731362525
74/201 - Collecting: mt_027258387
75/201 - Collecting: mt_203019738
76/201 - Collecting: mt_154583085
77/201 - Collecting: mt_469625712
78/201 - Collecting: mt_203019680
79/201 - Collecting: mt_027258433
80/201 - Collecting: mt_203019692
81/201 - Collecting: mt_469625668
82/201 - Collecting: mt_516197234
83/201 - Collecting: mt_648401390
84/201 - Collecting: mt_154583063
85/201 - Collecting: mt_154583091
86/201 - Collecting: mt_980836170
87/201 - Collecting: mt_892974540
88/201 - Collecting: mt_203019028
89/201 - Collecting: mt_469625682
90/201 - Collecting: mt_648401445
91/201 - Collecting: mt_648401924
92/201 - Collecting: mt_469625855
93/201 - Collecting: mt_516197293
94/201 - Collecting: mt_892974562
95/201 - Collecting: mt_980836117
96/201 - Collecting: mt_731362915
97/201 - Collecting: mt_154583516
98/201 - Collecting: mt_027258243
99/201 - Collecting: mt_154583503
100/201 - Collecting: mt_516197486
101/201 - Collecting: mt_154583646
102/201 - Collecting: mt_648401981
103/201 - Collecting: mt_203019616
104/201 - Collecting: mt_892974597
105/201 - Collecting: mt_027258250
106/201 - Collecting: mt_203019017
107/201 - Collecting: mt_469625614
108/201 - Collecting: mt_731362352
109/201 - Collecting: mt_203019791
110/201 - Collecting: mt_892974574
111/201 - Collecting: mt_648401356
112/201 - Collecting: mt_203019675
113/201 - Collecting: mt_469625778
114/201 - Collecting: mt_027258411
115/201 - Collecting: mt_980836109
116/201 - Collecting: mt_731362363
117/201 - Collecting: mt_516197122
118/201 - Collecting: mt_892974536
119/201 - Collecting: mt_375740168
120/201 - Collecting: mt_648401912
121/201 - Collecting: mt_027258499
122/201 - Collecting: mt_731362902
123/201 - Collecting: mt_375740872
124/201 - Collecting: mt_516197276
125/201 - Collecting: mt_980836893
126/201 - Collecting: mt_516197199
127/201 - Collecting: mt_731362519
128/201 - Collecting: mt_980836132
129/201 - Collecting: mt_980836141
130/201 - Collecting: mt_469625781
131/201 - Collecting: mt_980836128
132/201 - Collecting: mt_731362920
133/201 - Collecting: mt_375740783
134/201 - Collecting: mt_203019065
135/201 - Collecting: mt_892974998
136/201 - Collecting: mt_027258318
137/201 - Collecting: mt_469625724
138/201 - Collecting: mt_375740845
139/201 - Collecting: mt_892974558
140/201 - Collecting: mt_469625706
141/201 - Collecting: mt_375740740
142/201 - Collecting: mt_375740725
143/201 - Collecting: mt_469625671
144/201 - Collecting: mt_375740774
145/201 - Collecting: mt_154583637
146/201 - Collecting: mt_375740156
147/201 - Collecting: mt_648401335
148/201 - Collecting: mt_203019669
149/201 - Collecting: mt_516197287
150/201 - Collecting: mt_154583047
151/201 - Collecting: mt_892974989
152/201 - Collecting: mt_648401461
153/201 - Collecting: mt_027258295
154/201 - Collecting: mt_469970878
155/201 - Collecting: mt_154409604
156/201 - Collecting: mt_731194537
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
157/201 - Collecting: mt_516628418
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
158/201 - Collecting: mt_375552037
159/201 - Collecting: mt_648832935
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
160/201 - Collecting: mt_731110203
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
161/201 - Collecting: mt_154405675
162/201 - Collecting: mt_027741344
163/201 - Collecting: mt_648832949
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
164/201 - Collecting: mt_469970867
165/201 - Collecting: mt_027741322
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
166/201 - Collecting: mt_980004622
167/201 - Collecting: mt_154444137
168/201 - Collecting: mt_516628421
169/201 - Collecting: mt_375586172
170/201 - Collecting: mt_648885101
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
171/201 - Collecting: mt_980017217
172/201 - Collecting: mt_892253097
173/201 - Collecting: mt_154447370
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
174/201 - Collecting: mt_027779807
175/201 - Collecting: mt_731110269
176/201 - Collecting: mt_027779890
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
177/201 - Collecting: mt_203365769
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
178/201 - Collecting: mt_516663795
179/201 - Collecting: mt_203338918
180/201 - Collecting: mt_980004644
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
181/201 - Collecting: mt_980000969
182/201 - Collecting: mt_892226404
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
183/201 - Collecting: mt_648885162
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
184/201 - Collecting: mt_154447386
185/201 - Collecting: mt_648885208
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
186/201 - Collecting: mt_469991545
187/201 - Collecting: mt_892226479
188/201 - Collecting: mt_469991529
189/201 - Collecting: mt_375552020
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
190/201 - Collecting: mt_648885158
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
191/201 - Collecting: mt_203338976
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
192/201 - Collecting: mt_154447365
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
193/201 - Collecting: mt_375552015
194/201 - Collecting: mt_648885136
195/201 - Collecting: mt_027777018
196/201 - Collecting: mt_980004633
197/201 - Collecting: mt_375552046
198/201 - Collecting: mt_203338987
199/201 - Collecting: mt_892226463
Request failed: 404
{"error":{"code":"NOT_FOUND","message":"Match statistics not found","status_code":404}}
Saving with missing sections: ['statistics']
200/201 - Collecting: mt_027779835
201/201 - Collecting: mt_516663739

In [277]:
saved_conference_2025_26 = list(
    CONFERENCE_LEAGUE_SEASON_DIRS["2025_26"].glob("*.json")
)

print("Saved Conference League 2025/26 files:", len(saved_conference_2025_26))

Saved Conference League 2025/26 files: 201

In [278]:
PREMIER_LEAGUE_DIR = RAW_MATCH_DIR / "premier_league"

SEASON_DIRS = {}

for season_name in SEASONS:
    season_dir = PREMIER_LEAGUE_DIR / season_name
    season_dir.mkdir(parents=True, exist_ok=True)
    SEASON_DIRS[season_name] = season_dir

In [279]:
for season_name, season_dir in SEASON_DIRS.items():
    print(season_name, "->", season_dir)

2026_27 -> ..\data\raw\matches\premier_league\2026_27
2025_26 -> ..\data\raw\matches\premier_league\2025_26
2024_25 -> ..\data\raw\matches\premier_league\2024_25
2023_24 -> ..\data\raw\matches\premier_league\2023_24
2022_23 -> ..\data\raw\matches\premier_league\2022_23
2021_22 -> ..\data\raw\matches\premier_league\2021_22
2020_21 -> ..\data\raw\matches\premier_league\2020_21

In [298]:
# Updating get_stat for the matches with no available statistics

def get_stat(stats, stat_name, side):
    if stats is None:
        return None

    stats = stats.get("data")

    if stats is None:
        return None
    
    overview = stats.get("overview")

    if overview is None:
        return None

    stat = overview.get(stat_name)

    if stat is None or stat.get("all") is None:
        return None

    return stat["all"].get(side)

In [291]:
# Update historical match extractor so every processed row includes both season and competition 

def extract_historical_match(match_data, season, competition, match_id):
    details = match_data["details"]["data"]
    stats = match_data.get("statistics")

    return {
        "match_id": match_id,
        "date": details["utc_date"],
        "season": season,
        "competition": competition,
        "matchday": details.get("matchday"),

        "home_team": details["home_team"]["name"],
        "away_team": details["away_team"]["name"],

        "home_goals": details["score"]["home"],
        "away_goals": details["score"]["away"],

        "home_xg": get_stat(stats, "expected_goals", "home"),
        "away_xg": get_stat(stats, "expected_goals", "away"),

        "home_shots": get_stat(stats, "total_shots", "home"),
        "away_shots": get_stat(stats, "total_shots", "away"),

        "home_shots_on_target": get_stat(stats, "shots_on_target", "home"),
        "away_shots_on_target": get_stat(stats, "shots_on_target", "away"),

        "home_possession": get_stat(stats, "ball_possession", "home"),
        "away_possession": get_stat(stats, "ball_possession", "away"),

        "home_passes": get_stat(stats, "passes", "home"),
        "away_passes": get_stat(stats, "passes", "away"),

        "home_corners": get_stat(stats, "corner_kicks", "home"),
        "away_corners": get_stat(stats, "corner_kicks", "away"),

        "winner": details["score"].get("winner")
    }

In [282]:
# Create a map telling Python which folder belongs to which competition.

COMPETITION_DIRS = {
    "premier_league": RAW_MATCH_DIR / "premier_league",
    "championship": RAW_MATCH_DIR / "championship",
    "champions_league": RAW_MATCH_DIR / "champions_league",
    "fa_cup": RAW_MATCH_DIR / "fa_cup",
    "efl_cup": RAW_MATCH_DIR / "efl_cup",
    "europa_league": RAW_MATCH_DIR / "europa_league",
    "conference_league": RAW_MATCH_DIR / "conference_league"
}

In [283]:
for competition, directory in COMPETITION_DIRS.items():
    print(competition, "->", directory.exists(), "->", directory)

premier_league -> True -> ..\data\raw\matches\premier_league
championship -> True -> ..\data\raw\matches\championship
champions_league -> True -> ..\data\raw\matches\champions_league
fa_cup -> True -> ..\data\raw\matches\fa_cup
efl_cup -> True -> ..\data\raw\matches\efl_cup
europa_league -> True -> ..\data\raw\matches\europa_league
conference_league -> True -> ..\data\raw\matches\conference_league

In [ ]:
# Separate current season (2026/27) from historical seasons

COMPLETED_SEASONS = {
    "premier_league": ["2020_21", "2021_22", "2022_23", "2023_24", "2024_25", "2025_26"],
    "championship": ["2020_21", "2021_22", "2022_23", "2023_24", "2024_25", "2025_26"],
    "champions_league": ["2020_21", "2021_22", "2022_23", "2023_24", "2024_25", "2025_26"],
    "fa_cup": ["2020_21", "2021_22", "2022_23", "2023_24", "2024_25", "2025_26"],
    "efl_cup": ["2020_21", "2021_22", "2022_23", "2023_24", "2024_25", "2025_26"],
    "europa_league": ["2020_21", "2021_22", "2022_23", "2023_24", "2024_25", "2025_26"],
    "conference_league": ["2021_22", "2022_23", "2023_24", "2024_25", "2025_26"]
}

for competition, seasons in COMPLETED_SEASONS.items():
    print(competition, "->", len(seasons), "seasons")

premier_league -> 6 seasons
championship -> 6 seasons
champions_league -> 6 seasons
fa_cup -> 6 seasons
efl_cup -> 6 seasons
europa_league -> 6 seasons
conference_league -> 5 seasons

In [300]:
# Build loop that reads every historical JSON file and sends it through the extractor

all_historical_matches = []

for competition, seasons in COMPLETED_SEASONS.items():
    competition_dir = COMPETITION_DIRS[competition]

    for season in seasons:
        season_dir = competition_dir / season

        for file_path in season_dir.glob("*.json"):
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    match_data = json.load(f)

                match_id = file_path.stem

                match_row = extract_historical_match(
                    match_data,
                    season,
                    competition,
                    match_id
                )

                all_historical_matches.append(match_row)

            except Exception as e:
                print("Error processing:", file_path)
                print("Error:", e)

print("Total completed historical matches processed:", len(all_historical_matches))

Total completed historical matches processed: 10653

In [301]:
# Turn the list into a DataFrame

historical_df = pd.DataFrame(all_historical_matches)

print(historical_df.shape)
print()
print(historical_df.head())
print()
print(historical_df["competition"].value_counts())

(10653, 22)

       match_id                      date   season     competition  matchday  \
0  mt_085997104  2020-12-16T18:00:00.000Z  2020_21  premier_league      13.0
1  mt_085997110  2020-10-04T15:30:00.000Z  2020_21  premier_league       4.0
2  mt_085997138  2020-09-20T11:00:00.000Z  2020_21  premier_league       2.0
3  mt_085997147  2020-12-27T12:00:00.000Z  2020_21  premier_league      15.0
4  mt_085997152  2020-09-12T16:30:00.000Z  2020_21  premier_league       1.0

           home_team          away_team  home_goals  away_goals  home_xg  ...  \
0     Leicester City            Everton           0           2      NaN  ...
1  Manchester United  Tottenham Hotspur           1           6      NaN  ...
2        Southampton  Tottenham Hotspur           2           5      NaN  ...
3       Leeds United            Burnley           1           0      NaN  ...
4          Liverpool       Leeds United           4           3      NaN  ...

   away_shots  home_shots_on_target  away_shots_on_target  home_possession  \
0        11.0                   2.0                   6.0             61.0
1        22.0                   2.0                   8.0             38.0
2         9.0                   7.0                   6.0             53.0
3        14.0                   4.0                   6.0             51.0
4         6.0                   6.0                   3.0             49.0

   away_possession  home_passes  away_passes  home_corners  away_corners  \
0             39.0        547.0        344.0           4.0           6.0
1             62.0        416.0        672.0           2.0           4.0
2             47.0        460.0        419.0           3.0           2.0
3             49.0        424.0        378.0           4.0          12.0
4             51.0        432.0        459.0           9.0           0.0

   winner
0    away
1    away
2    away
3    home
4    home

[5 rows x 22 columns]

competition
championship         3342
premier_league       2280
europa_league        1426
champions_league     1383
conference_league     869
fa_cup                798
efl_cup               555
Name: count, dtype: int64

In [304]:
# Check which columns are complete and which ones are sparse before saving into CSV

missing_summary = historical_df.isna().sum().sort_values(ascending=False)

print(missing_summary)

away_xg                 5435
home_xg                 5435
home_passes             1232
away_passes             1232
away_possession         1147
home_possession         1147
away_shots_on_target     966
home_shots_on_target     966
home_shots               966
away_shots               966
away_corners             862
home_corners             862
matchday                 444
match_id                   0
home_team                  0
competition                0
season                     0
date                       0
home_goals                 0
away_team                  0
away_goals                 0
winner                     0
dtype: int64

In [305]:
historical_df.to_csv(
    "../data/processed/historical_matches.csv",
    index=False
)

print("Saved:", historical_df.shape)

Saved: (10653, 22)

In [306]:
import json
from pathlib import Path

sample_file = next(
    (
        Path("../data/raw/matches/premier_league/2024_25")
    ).glob("*.json")
)

with open(
    sample_file,
    "r",
    encoding="utf-8"
) as f:
    sample_match = json.load(f)

print("Match file:", sample_file.name)
print()
print(
    json.dumps(
        sample_match.get("odds"),
        indent=2
    )[:5000]
)

Match file: mt_013233107.json

{
  "data": {
    "match_id": "mt_013233107",
    "bookmakers": [
      {
        "bookmaker": "Bet365",
        "markets": {
          "match_odds": {
            "home": {
              "opening": null,
              "last_seen": "4.100"
            },
            "draw": {
              "opening": null,
              "last_seen": "3.400"
            },
            "away": {
              "opening": null,
              "last_seen": "1.950"
            }
          },
          "btts": {
            "yes": {
              "opening": null,
              "last_seen": "1.910"
            },
            "no": {
              "opening": null,
              "last_seen": "1.910"
            }
          },
          "total_goals": {
            "0.5": {
              "over": {
                "opening": null,
                "last_seen": "1.060"
              },
              "under": {
                "opening": null,
                "last_seen": "10.000"
              }
            },
            "1.5": {
              "over": {
                "opening": null,
                "last_seen": "1.300"
              },
              "under": {
                "opening": null,
                "last_seen": "3.500"
              }
            },
            "2.5": {
              "over": {
                "opening": null,
                "last_seen": "2.000"
              },
              "under": {
                "opening": null,
                "last_seen": "1.800"
              }
            },
            "3.5": {
              "over": {
                "opening": null,
                "last_seen": "3.500"
              },
              "under": {
                "opening": null,
                "last_seen": "1.300"
              }
            },
            "4.5": {
              "over": {
                "opening": null,
                "last_seen": "6.500"
              },
              "under": {
                "opening": null,
                "last_seen": "1.110"
              }
            },
            "5.5": {
              "over": {
                "opening": null,
                "last_seen": "15.000"
              },
              "under": {
                "opening": null,
                "last_seen": "1.030"
              }
            },
            "6.5": {
              "over": {
                "opening": null,
                "last_seen": "29.000"
              },
              "under": {
                "opening": null,
                "last_seen": "1.010"
              }
            }
          },
          "match_corners": {
            "9.5": {
              "over": {
                "opening": null,
                "last_seen": "1.910"
              },
              "under": {
                "opening": null,
                "last_seen": "1.800"
              }
            }
          },
          "total_cards": {
            "4.5": {
              "over": {
                "opening": null,
                "last_seen": "2.100"
              },
              "under": {
                "opening": null,
                "last_seen": "1.670"
              }
            }
          },
          "asian_handicap": {
            "home": {
              "+0.5": {
                "opening": null,
                "last_seen": "1.980"
              }
            },
            "away": {
              "-0.5": {
                "opening": null,
                "last_seen": "1.950"
              }
            }
          },
          "draw_no_bet": {
            "home": {
              "opening": null,
              "last_seen": "2.750"
            },
            "away": {
              "opening": null,
              "last_seen": "1.400"
            }
          },
          "double_chance": {
            "home_draw": {
              "opening": null,
              "last_seen": "1.830"
            },
            "home_away": {
              "opening": null,
              "last_seen": "1.290"
            },
            "draw_away": {
              "opening": null,
              "last_seen": "1.220"
            }
          },
          "first_half_result": {
            "home": {
              "opening": null,
              "last_seen": "4.500"
            },
            "draw": {
              "opening": null,
              "last_seen": "2.100"
            },
            "away": {
              "opening": null,
              "last_seen": "2.600"
            }
          },
          "first_team_to_score": {
            "home": {
              "opening": null,
              "last_seen": "2.630"
            },
            "away": {
              "opening": null,
              "last_seen": "1.570"
            },
            "none": {
              "opening": null,
              "last_seen": "10.000"
            }
          }
        }
      }
    ]
  }
}

In [307]:
def extract_bet365_match_odds(match_data, match_id):

    odds_data = match_data.get("odds")

    if odds_data is None:
        return None

    odds_data = odds_data.get("data")

    if odds_data is None:
        return None

    bookmakers = odds_data.get("bookmakers", [])

    bet365 = None

    for bookmaker in bookmakers:
        if bookmaker.get("bookmaker") == "Bet365":
            bet365 = bookmaker
            break

    if bet365 is None:
        return None

    match_odds = (
        bet365
        .get("markets", {})
        .get("match_odds")
    )

    if match_odds is None:
        return None

    try:
        home_odds = float(
            match_odds["home"]["last_seen"]
        )

        draw_odds = float(
            match_odds["draw"]["last_seen"]
        )

        away_odds = float(
            match_odds["away"]["last_seen"]
        )

    except (TypeError, ValueError, KeyError):
        return None

    return {
        "match_id": match_id,
        "bet365_home_odds": home_odds,
        "bet365_draw_odds": draw_odds,
        "bet365_away_odds": away_odds
    }

In [308]:
sample_odds = extract_bet365_match_odds(
    sample_match,
    sample_file.stem
)

print(sample_odds)

{'match_id': 'mt_013233107', 'bet365_home_odds': 4.1, 'bet365_draw_odds': 3.4, 'bet365_away_odds': 1.95}

In [309]:
# See how much Bet365 coverage we have across 6 completed PL seasons

bet365_odds_rows = []

for season in COMPLETED_SEASONS["premier_league"]:

    season_dir = (
        COMPETITION_DIRS["premier_league"]
        / season
    )

    season_total = 0
    season_with_odds = 0

    for file_path in season_dir.glob("*.json"):

        season_total += 1

        with open(
            file_path,
            "r",
            encoding="utf-8"
        ) as f:
            match_data = json.load(f)

        odds_row = extract_bet365_match_odds(
            match_data,
            file_path.stem
        )

        if odds_row is not None:

            odds_row["season"] = season

            bet365_odds_rows.append(
                odds_row
            )

            season_with_odds += 1

    print(
        f"{season}: "
        f"{season_with_odds}/{season_total} "
        f"matches with Bet365 odds"
    )

print()
print(
    "Total Bet365 matches:",
    len(bet365_odds_rows)
)

2020_21: 380/380 matches with Bet365 odds
2021_22: 380/380 matches with Bet365 odds
2022_23: 380/380 matches with Bet365 odds
2023_24: 380/380 matches with Bet365 odds
2024_25: 380/380 matches with Bet365 odds
2025_26: 380/380 matches with Bet365 odds

Total Bet365 matches: 2280

In [310]:
# Turn these 2,280 rows into a DataFrame and calculate fair market probabilities by removing Bet365 margin

bet365_df = pd.DataFrame(
    bet365_odds_rows
)

# Raw implied probabilities
bet365_df["raw_prob_H"] = (
    1 / bet365_df["bet365_home_odds"]
)

bet365_df["raw_prob_D"] = (
    1 / bet365_df["bet365_draw_odds"]
)

bet365_df["raw_prob_A"] = (
    1 / bet365_df["bet365_away_odds"]
)

# Bookmaker overround
bet365_df["overround"] = (
    bet365_df["raw_prob_H"]
    + bet365_df["raw_prob_D"]
    + bet365_df["raw_prob_A"]
)

# Normalize to remove bookmaker margin
bet365_df["fair_prob_H"] = (
    bet365_df["raw_prob_H"]
    / bet365_df["overround"]
)

bet365_df["fair_prob_D"] = (
    bet365_df["raw_prob_D"]
    / bet365_df["overround"]
)

bet365_df["fair_prob_A"] = (
    bet365_df["raw_prob_A"]
    / bet365_df["overround"]
)

print(bet365_df.shape)

print()

print(
    bet365_df[
        [
            "bet365_home_odds",
            "bet365_draw_odds",
            "bet365_away_odds",
            "overround",
            "fair_prob_H",
            "fair_prob_D",
            "fair_prob_A"
        ]
    ].head()
)

print()

print(
    "Average overround:",
    bet365_df["overround"].mean()
)

print(
    "Average fair probability sum:",
    (
        bet365_df["fair_prob_H"]
        + bet365_df["fair_prob_D"]
        + bet365_df["fair_prob_A"]
    ).mean()
)

(2280, 12)

   bet365_home_odds  bet365_draw_odds  bet365_away_odds  overround  \
0              2.10               3.4               3.5   1.056022
1              2.00               3.7               3.6   1.048048
2              3.30               3.4               2.2   1.051693
3              1.70               4.2               4.5   1.048553
4              1.25               6.0              11.0   1.057576

   fair_prob_H  fair_prob_D  fair_prob_A
0     0.450928     0.278515     0.270557
1     0.477077     0.257880     0.265043
2     0.288136     0.279661     0.432203
3     0.560997     0.227070     0.211932
4     0.756447     0.157593     0.085960

Average overround: 1.0545628863489702
Average fair probability sum: 1.0

In [311]:
# Save Bet365 data
bet365_df.to_csv(
    "../data/processed/bet365_pl_odds.csv",
    index=False
)

print(
    "Saved:",
    bet365_df.shape
)

Saved: (2280, 12)

In [322]:
# ---------------------------------------------------------
# PROCESS ONE RAW MATCH FILE
# ---------------------------------------------------------

def process_match_file(file_path):

    try:

        with open(
            file_path,
            "r",
            encoding="utf-8"
        ) as f:

            match_data = json.load(f)

    except Exception as e:

        print(
            f"Could not read {file_path}: {e}"
        )

        return None


    # -----------------------------------------------------
    # DETAILS
    # -----------------------------------------------------

    details = match_data.get(
        "details"
    )

    if details is None:
        return None

    if isinstance(details, dict):

        details = details.get(
            "data",
            details
        )

    if not isinstance(details, dict):
        return None


    # Only completed matches
    if details.get("status") != "finished":
        return None


    # -----------------------------------------------------
    # STATISTICS
    # -----------------------------------------------------

    statistics = match_data.get(
        "statistics"
    )


    # -----------------------------------------------------
    # TEAM INFORMATION
    # -----------------------------------------------------

    home_team_data = details.get(
        "home_team",
        {}
    )

    away_team_data = details.get(
        "away_team",
        {}
    )


    home_team = (
        home_team_data.get("name")
        if isinstance(home_team_data, dict)
        else None
    )

    away_team = (
        away_team_data.get("name")
        if isinstance(away_team_data, dict)
        else None
    )


    # -----------------------------------------------------
    # SCORE
    # -----------------------------------------------------

    score = details.get(
        "score",
        {}
    )

    if not isinstance(score, dict):
        score = {}


    home_goals = score.get(
        "home"
    )

    away_goals = score.get(
        "away"
    )


    # -----------------------------------------------------
    # WINNER
    # -----------------------------------------------------

    winner = None

    if (
        home_goals is not None
        and away_goals is not None
    ):

        if home_goals > away_goals:

            winner = "H"

        elif away_goals > home_goals:

            winner = "A"

        else:

            winner = "D"


    # -----------------------------------------------------
    # FOLDER INFORMATION
    # -----------------------------------------------------

    season = file_path.parent.name

    competition = (
        file_path
        .parent
        .parent
        .name
    )


    # -----------------------------------------------------
    # BUILD ROW
    # -----------------------------------------------------

    row = {

        "match_id":
            details.get("id"),

        "date":
            details.get("utc_date"),

        "season":
            season,

        "competition":
            competition,

        "matchday":
            details.get("matchday"),

        "home_team":
            home_team,

        "away_team":
            away_team,

        "home_goals":
            home_goals,

        "away_goals":
            away_goals,

        "home_xg":
            get_stat(
                statistics,
                "home",
                "expected_goals"
            ),

        "away_xg":
            get_stat(
                statistics,
                "away",
                "expected_goals"
            ),

        "home_shots":
            get_stat(
                statistics,
                "home",
                "shots"
            ),

        "away_shots":
            get_stat(
                statistics,
                "away",
                "shots"
            ),

        "home_shots_on_target":
            get_stat(
                statistics,
                "home",
                "shots_on_target"
            ),

        "away_shots_on_target":
            get_stat(
                statistics,
                "away",
                "shots_on_target"
            ),

        "home_possession":
            get_stat(
                statistics,
                "home",
                "ball_possession"
            ),

        "away_possession":
            get_stat(
                statistics,
                "away",
                "ball_possession"
            ),

        "home_passes":
            get_stat(
                statistics,
                "home",
                "passes"
            ),

        "away_passes":
            get_stat(
                statistics,
                "away",
                "passes"
            ),

        "home_corners":
            get_stat(
                statistics,
                "home",
                "corners"
            ),

        "away_corners":
            get_stat(
                statistics,
                "away",
                "corners"
            ),

        "winner":
            winner
    }


    return row

In [323]:
# ---------------------------------------------------------
# CHECK 2026/27 PROCESSING
# ---------------------------------------------------------

check_2026 = historical_df[
    (
        historical_df["competition"] == "premier_league"
    )
    &
    (
        historical_df["season"] == "2026_27"
    )
][
    [
        "date",
        "home_team",
        "away_team",
        "home_goals",
        "away_goals",
        "winner"
    ]
].sort_values("date")


print(
    check_2026
)

print()

print(
    "Missing dates:",
    check_2026["date"].isna().sum()
)

print(
    "Missing home goals:",
    check_2026["home_goals"].isna().sum()
)

print(
    "Missing away goals:",
    check_2026["away_goals"].isna().sum()
)

      date               home_team               away_team home_goals  \
850    NaT                  Fulham                 Chelsea       None
851    NaT               Liverpool       Nottingham Forest       None
852    NaT               Hull City       Manchester United       None
1328   NaT           Coventry City               Hull City       None
4259   NaT             Bournemouth                 Everton       None
5304   NaT                 Everton          Crystal Palace       None
5305   NaT             Aston Villa                 Arsenal       None
5306   NaT              Sunderland                  Fulham       None
5363   NaT                 Arsenal           Coventry City       None
5364   NaT         Manchester City             Bournemouth       None
5365   NaT       Manchester United            Ipswich Town       None
7393   NaT  Brighton & Hove Albion             Aston Villa       None
7394   NaT       Tottenham Hotspur        Newcastle United       None
7395   NaT        Newcastle United               Liverpool       None
7396   NaT            Leeds United               Brentford       None
7397   NaT            Ipswich Town              Sunderland       None
7699   NaT                 Chelsea  Brighton & Hove Albion       None
9599   NaT       Nottingham Forest            Leeds United       None
10671  NaT          Crystal Palace         Manchester City       None
10672  NaT               Brentford       Tottenham Hotspur       None

      away_goals winner
850         None   None
851         None   None
852         None   None
1328        None   None
4259        None   None
5304        None   None
5305        None   None
5306        None   None
5363        None   None
5364        None   None
5365        None   None
7393        None   None
7394        None   None
7395        None   None
7396        None   None
7397        None   None
7699        None   None
9599        None   None
10671       None   None
10672       None   None

Missing dates: 20
Missing home goals: 20
Missing away goals: 20

In [324]:
import inspect

print(
    inspect.getsource(
        process_match_file
    )
)

def process_match_file(file_path):

    try:

        with open(
            file_path,
            "r",
            encoding="utf-8"
        ) as f:

            match_data = json.load(f)

    except Exception as e:

        print(
            f"Could not read {file_path}: {e}"
        )

        return None


    # -----------------------------------------------------
    # DETAILS
    # -----------------------------------------------------

    details = match_data.get(
        "details"
    )

    if details is None:
        return None

    if isinstance(details, dict):

        details = details.get(
            "data",
            details
        )

    if not isinstance(details, dict):
        return None


    # Only completed matches
    if details.get("status") != "finished":
        return None


    # -----------------------------------------------------
    # STATISTICS
    # -----------------------------------------------------

    statistics = match_data.get(
        "statistics"
    )


    # -----------------------------------------------------
    # TEAM INFORMATION
    # -----------------------------------------------------

    home_team_data = details.get(
        "home_team",
        {}
    )

    away_team_data = details.get(
        "away_team",
        {}
    )


    home_team = (
        home_team_data.get("name")
        if isinstance(home_team_data, dict)
        else None
    )

    away_team = (
        away_team_data.get("name")
        if isinstance(away_team_data, dict)
        else None
    )


    # -----------------------------------------------------
    # SCORE
    # -----------------------------------------------------

    score = details.get(
        "score",
        {}
    )

    if not isinstance(score, dict):
        score = {}


    home_goals = score.get(
        "home"
    )

    away_goals = score.get(
        "away"
    )


    # -----------------------------------------------------
    # WINNER
    # -----------------------------------------------------

    winner = None

    if (
        home_goals is not None
        and away_goals is not None
    ):

        if home_goals > away_goals:

            winner = "H"

        elif away_goals > home_goals:

            winner = "A"

        else:

            winner = "D"


    # -----------------------------------------------------
    # FOLDER INFORMATION
    # -----------------------------------------------------

    season = file_path.parent.name

    competition = (
        file_path
        .parent
        .parent
        .name
    )


    # -----------------------------------------------------
    # BUILD ROW
    # -----------------------------------------------------

    row = {

        "match_id":
            details.get("id"),

        "date":
            details.get("utc_date"),

        "season":
            season,

        "competition":
            competition,

        "matchday":
            details.get("matchday"),

        "home_team":
            home_team,

        "away_team":
            away_team,

        "home_goals":
            home_goals,

        "away_goals":
            away_goals,

        "home_xg":
            get_stat(
                statistics,
                "home",
                "expected_goals"
            ),

        "away_xg":
            get_stat(
                statistics,
                "away",
                "expected_goals"
            ),

        "home_shots":
            get_stat(
                statistics,
                "home",
                "shots"
            ),

        "away_shots":
            get_stat(
                statistics,
                "away",
                "shots"
            ),

        "home_shots_on_target":
            get_stat(
                statistics,
                "home",
                "shots_on_target"
            ),

        "away_shots_on_target":
            get_stat(
                statistics,
                "away",
                "shots_on_target"
            ),

        "home_possession":
            get_stat(
                statistics,
                "home",
                "ball_possession"
            ),

        "away_possession":
            get_stat(
                statistics,
                "away",
                "ball_possession"
            ),

        "home_passes":
            get_stat(
                statistics,
                "home",
                "passes"
            ),

        "away_passes":
            get_stat(
                statistics,
                "away",
                "passes"
            ),

        "home_corners":
            get_stat(
                statistics,
                "home",
                "corners"
            ),

        "away_corners":
            get_stat(
                statistics,
                "away",
                "corners"
            ),

        "winner":
            winner
    }


    return row

In [326]:
# ---------------------------------------------------------
# INSPECT ONE 2026/27 RAW MATCH
# ---------------------------------------------------------

import json
from pathlib import Path
from pprint import pprint


season_dir = Path(
    "../data/raw/matches/premier_league/2026_27"
)


match_files = list(
    season_dir.glob("*.json")
)


print(
    "2026/27 raw files:",
    len(match_files)
)


with open(
    match_files[0],
    "r",
    encoding="utf-8"
) as f:

    sample_match = json.load(f)


print("\nTOP-LEVEL KEYS:")
print(
    sample_match.keys()
)


print("\nDETAILS:")
pprint(
    sample_match.get("details")
)

2026/27 raw files: 20

TOP-LEVEL KEYS:
dict_keys(['details', 'statistics', 'lineups', 'player_stats', 'odds'])

DETAILS:
{'data': {'away_team': {'id': 'tm_8531', 'name': 'Chelsea'},
          'competition_id': 'comp_3039',
          'competition_name': 'Premier League',
          'group_label': None,
          'home_team': {'id': 'tm_5290', 'name': 'Fulham'},
          'id': 'mt_022587821',
          'is_neutral': False,
          'live_odds_available': False,
          'matchday': 1,
          'odds_available': True,
          'referee': {'id': 'ref_29658200', 'name': 'Brooks, John'},
          'score': {'after_extra_time': None,
                    'away': 3,
                    'final_score': None,
                    'half_time_away': 2,
                    'half_time_home': 1,
                    'home': 2,
                    'penalty_shootout': None,
                    'regulation': {'away': 3, 'home': 2},
                    'went_to_extra_time': False,
                    'went_to_penalties': False,
                    'winner': 'away'},
          'season_id': 'sn_8406098',
          'stage_name': None,
          'status': 'finished',
          'utc_date': '2026-08-24T19:00:00.000Z',
          'venue': {'city': 'London', 'name': 'Craven Cottage'},
          'xg_available': True}}

In [327]:
# ---------------------------------------------------------
# TEST PROCESSOR ON ONE 2026/27 RAW MATCH
# ---------------------------------------------------------

sample_file = match_files[0]

print(
    "FILE:",
    sample_file
)

print()

processed_sample = process_match_file(
    sample_file
)

print(
    processed_sample
)

FILE: ..\data\raw\matches\premier_league\2026_27\mt_022587821.json

{'match_id': 'mt_022587821', 'date': '2026-08-24T19:00:00.000Z', 'season': '2026_27', 'competition': 'premier_league', 'matchday': 1, 'home_team': 'Fulham', 'away_team': 'Chelsea', 'home_goals': 2, 'away_goals': 3, 'home_xg': None, 'away_xg': None, 'home_shots': None, 'away_shots': None, 'home_shots_on_target': None, 'away_shots_on_target': None, 'home_possession': None, 'away_possession': None, 'home_passes': None, 'away_passes': None, 'home_corners': None, 'away_corners': None, 'winner': 'A'}

In [328]:
# ---------------------------------------------------------
# PROCESS ALL 20 2026/27 FILES DIRECTLY
# ---------------------------------------------------------

test_2026_rows = []

for file_path in sorted(
    Path("../data/raw/matches/premier_league/2026_27").glob("*.json")
):

    row = process_match_file(
        file_path
    )

    if row is not None:
        test_2026_rows.append(row)


test_2026_df = pd.DataFrame(
    test_2026_rows
)


print(
    "Processed matches:",
    len(test_2026_df)
)

print()

print(
    test_2026_df[
        [
            "date",
            "home_team",
            "away_team",
            "home_goals",
            "away_goals",
            "winner"
        ]
    ]
    .sort_values("date")
    .to_string(index=False)
)

print()

print(
    "Missing dates:",
    test_2026_df["date"].isna().sum()
)

print(
    "Missing home goals:",
    test_2026_df["home_goals"].isna().sum()
)

print(
    "Missing away goals:",
    test_2026_df["away_goals"].isna().sum()
)

print(
    "Missing winners:",
    test_2026_df["winner"].isna().sum()
)

Processed matches: 20

                    date              home_team              away_team  home_goals  away_goals winner
2026-08-21T19:00:00.000Z                Arsenal          Coventry City           3           0      H
2026-08-22T11:30:00.000Z              Hull City      Manchester United           2           0      H
2026-08-22T14:00:00.000Z      Nottingham Forest           Leeds United           0           1      A
2026-08-22T14:00:00.000Z           Ipswich Town             Sunderland           2           1      H
2026-08-22T14:00:00.000Z                Everton         Crystal Palace           2           0      H
2026-08-22T16:30:00.000Z              Brentford      Tottenham Hotspur           3           0      H
2026-08-23T13:00:00.000Z Brighton & Hove Albion            Aston Villa           4           0      H
2026-08-23T13:00:00.000Z        Manchester City            Bournemouth           2           1      H
2026-08-23T15:30:00.000Z       Newcastle United              Liverpool           2           2      D
2026-08-24T19:00:00.000Z                 Fulham                Chelsea           2           3      A
2026-08-28T19:00:00.000Z         Crystal Palace        Manchester City           1           4      A
2026-08-29T11:30:00.000Z              Liverpool      Nottingham Forest           2           2      D
2026-08-29T14:00:00.000Z            Bournemouth                Everton           1           1      D
2026-08-29T14:00:00.000Z          Coventry City              Hull City           0           1      A
2026-08-29T16:30:00.000Z      Tottenham Hotspur       Newcastle United           0           2      A
2026-08-30T13:00:00.000Z           Leeds United              Brentford           1           1      D
2026-08-30T13:00:00.000Z                Chelsea Brighton & Hove Albion           4           3      H
2026-08-30T13:00:00.000Z             Sunderland                 Fulham           1           0      H
2026-08-30T15:30:00.000Z      Manchester United           Ipswich Town           5           2      H
2026-08-31T19:00:00.000Z            Aston Villa                Arsenal           0           1      A

Missing dates: 0
Missing home goals: 0
Missing away goals: 0
Missing winners: 0

In [329]:
# ---------------------------------------------------------
# CLEAN REBUILD OF HISTORICAL DATASET
# ---------------------------------------------------------

rows = []


# Process every raw match again from scratch
for file_path in RAW_MATCH_DIR.rglob("*.json"):

    row = process_match_file(
        file_path
    )

    if row is not None:
        rows.append(row)


# Create completely new dataframe
historical_df = pd.DataFrame(
    rows
)


# ---------------------------------------------------------
# REMOVE DUPLICATES
# ---------------------------------------------------------

historical_df = (
    historical_df
    .drop_duplicates(
        subset="match_id",
        keep="last"
    )
    .copy()
)


# ---------------------------------------------------------
# CONVERT AND SORT DATES
# ---------------------------------------------------------

historical_df["date"] = pd.to_datetime(
    historical_df["date"],
    utc=True,
    errors="coerce"
)


historical_df = (
    historical_df
    .sort_values(
        [
            "date",
            "match_id"
        ]
    )
    .reset_index(
        drop=True
    )
)


# ---------------------------------------------------------
# SAVE FRESH CSV
# ---------------------------------------------------------

output_path = (
    PROCESSED_DIR
    / "historical_matches.csv"
)


historical_df.to_csv(
    output_path,
    index=False
)


# ---------------------------------------------------------
# VERIFY 2026/27
# ---------------------------------------------------------

check_2026 = (
    historical_df[
        (
            historical_df["competition"]
            == "premier_league"
        )
        &
        (
            historical_df["season"]
            == "2026_27"
        )
    ][
        [
            "date",
            "home_team",
            "away_team",
            "home_goals",
            "away_goals",
            "winner"
        ]
    ]
    .sort_values("date")
)


print(
    "Historical shape:",
    historical_df.shape
)

print()

print(
    "2026/27 PL matches:",
    len(check_2026)
)

print()

print(
    check_2026.to_string(
        index=False
    )
)

print()

print(
    "Missing dates:",
    check_2026["date"].isna().sum()
)

print(
    "Missing home goals:",
    check_2026["home_goals"].isna().sum()
)

print(
    "Missing away goals:",
    check_2026["away_goals"].isna().sum()
)

print(
    "Missing winners:",
    check_2026["winner"].isna().sum()
)

print()

print(
    "Saved:",
    output_path
)

Historical shape: (10673, 22)

2026/27 PL matches: 20

                     date              home_team              away_team  home_goals  away_goals winner
2026-08-21 19:00:00+00:00                Arsenal          Coventry City           3           0      H
2026-08-22 11:30:00+00:00              Hull City      Manchester United           2           0      H
2026-08-22 14:00:00+00:00                Everton         Crystal Palace           2           0      H
2026-08-22 14:00:00+00:00           Ipswich Town             Sunderland           2           1      H
2026-08-22 14:00:00+00:00      Nottingham Forest           Leeds United           0           1      A
2026-08-22 16:30:00+00:00              Brentford      Tottenham Hotspur           3           0      H
2026-08-23 13:00:00+00:00        Manchester City            Bournemouth           2           1      H
2026-08-23 13:00:00+00:00 Brighton & Hove Albion            Aston Villa           4           0      H
2026-08-23 15:30:00+00:00       Newcastle United              Liverpool           2           2      D
2026-08-24 19:00:00+00:00                 Fulham                Chelsea           2           3      A
2026-08-28 19:00:00+00:00         Crystal Palace        Manchester City           1           4      A
2026-08-29 11:30:00+00:00              Liverpool      Nottingham Forest           2           2      D
2026-08-29 14:00:00+00:00          Coventry City              Hull City           0           1      A
2026-08-29 14:00:00+00:00            Bournemouth                Everton           1           1      D
2026-08-29 16:30:00+00:00      Tottenham Hotspur       Newcastle United           0           2      A
2026-08-30 13:00:00+00:00             Sunderland                 Fulham           1           0      H
2026-08-30 13:00:00+00:00           Leeds United              Brentford           1           1      D
2026-08-30 13:00:00+00:00                Chelsea Brighton & Hove Albion           4           3      H
2026-08-30 15:30:00+00:00      Manchester United           Ipswich Town           5           2      H
2026-08-31 19:00:00+00:00            Aston Villa                Arsenal           0           1      A

Missing dates: 0
Missing home goals: 0
Missing away goals: 0
Missing winners: 0

Saved: ..\data\processed\historical_matches.csv

In [330]:
# ---------------------------------------------------------
# INSPECT RAW STATISTICS STRUCTURE
# ---------------------------------------------------------

from pprint import pprint
import json
from pathlib import Path


sample_file = Path(
    "../data/raw/matches/premier_league/2026_27/mt_022587821.json"
)


with open(
    sample_file,
    "r",
    encoding="utf-8"
) as f:

    sample_match = json.load(f)


print("STATISTICS:")
print()

pprint(
    sample_match.get("statistics")
)

STATISTICS:

{'data': {'attack': {'big_chances_missed': {'all': {'away': 1, 'home': 1},
                                            'first_half': {'away': 1,
                                                           'home': 0},
                                            'second_half': {'away': 0,
                                                            'home': 1}},
                     'fouled_in_final_third': {'all': {'away': 1, 'home': 0},
                                               'first_half': {'away': 1,
                                                              'home': 0},
                                               'second_half': {'away': 0,
                                                               'home': 0}},
                     'offsides': {'all': {'away': 3, 'home': 0},
                                  'first_half': {'away': 1, 'home': 0},
                                  'second_half': {'away': 2, 'home': 0}},
                     'touches_in_penalty_area': {'all': {'away': 38,
                                                         'home': 25},
                                                 'first_half': None,
                                                 'second_half': None}},
          'defending': {'ball_recoveries': {'all': {'away': 52, 'home': 46},
                                            'first_half': {'away': 27,
                                                           'home': 25},
                                            'second_half': {'away': 25,
                                                            'home': 21}},
                        'clearances': {'all': {'away': 22, 'home': 17},
                                       'first_half': {'away': 11, 'home': 8},
                                       'second_half': {'away': 11, 'home': 9}},
                        'interceptions': {'all': {'away': 7, 'home': 8},
                                          'first_half': {'away': 6, 'home': 4},
                                          'second_half': {'away': 1,
                                                          'home': 4}},
                        'tackles': {'all': {'away': 23, 'home': 19},
                                    'first_half': {'away': 12, 'home': 11},
                                    'second_half': {'away': 11, 'home': 8}},
                        'tackles_won_percentage': {'all': {'away': 15,
                                                           'home': 12},
                                                   'first_half': {'away': 5,
                                                                  'home': 7},
                                                   'second_half': {'away': 10,
                                                                   'home': 5}}},
          'duels': {'aerial_duels_percentage': {'all': {'away': 10, 'home': 14},
                                                'first_half': {'away': 5,
                                                               'home': 5},
                                                'second_half': {'away': 5,
                                                                'home': 9}},
                    'dispossessed': {'all': {'away': 14, 'home': 11},
                                     'first_half': {'away': 8, 'home': 4},
                                     'second_half': {'away': 6, 'home': 7}},
                    'dribbles_percentage': {'all': {'away': 14, 'home': 8},
                                            'first_half': {'away': 4,
                                                           'home': 1},
                                            'second_half': {'away': 10,
                                                            'home': 7}},
                    'duels_won_percentage': {'all': {'away': 55, 'home': 45},
                                             'first_half': {'away': 54,
                                                            'home': 46},
                                             'second_half': {'away': 55,
                                                             'home': 45}},
                    'ground_duels_percentage': {'all': {'away': 48, 'home': 34},
                                                'first_half': {'away': 20,
                                                               'home': 16},
                                                'second_half': {'away': 28,
                                                                'home': 18}}},
          'goalkeeping': {'goal_kicks': {'all': {'away': 5, 'home': 11},
                                         'first_half': {'away': 1, 'home': 4},
                                         'second_half': {'away': 4, 'home': 7}},
                          'goals_prevented': {'all': {'away': -0.83,
                                                      'home': -0.98},
                                              'first_half': None,
                                              'second_half': None},
                          'high_claims': {'all': {'away': 3, 'home': 0},
                                          'first_half': None,
                                          'second_half': None},
                          'saves': {'all': {'away': 4, 'home': 3},
                                    'first_half': {'away': 1, 'home': 3},
                                    'second_half': {'away': 3, 'home': 0}}},
          'match_id': 'mt_022587821',
          'np_expected_goals': {'all': {'away': 1.7, 'home': 1.45},
                                'first_half': {'away': 1.47, 'home': 0.43},
                                'second_half': {'away': 0.24, 'home': 1.02}},
          'overview': {'accurate_passes': {'all': {'away': 322, 'home': 553},
                                           'first_half': {'away': 180,
                                                          'home': 282},
                                           'second_half': {'away': 142,
                                                           'home': 271}},
                       'ball_possession': {'all': {'away': 38, 'home': 62},
                                           'first_half': {'away': 39,
                                                          'home': 61},
                                           'second_half': {'away': 37,
                                                           'home': 63}},
                       'big_chances': {'all': {'away': 4, 'home': 2},
                                       'first_half': {'away': 3, 'home': 0},
                                       'second_half': {'away': 1, 'home': 2}},
                       'corner_kicks': {'all': {'away': 4, 'home': 6},
                                        'first_half': {'away': 3, 'home': 4},
                                        'second_half': {'away': 1, 'home': 2}},
                       'expected_goals': {'all': {'away': 2.24, 'home': 1.33},
                                          'first_half': {'away': 1.99,
                                                         'home': 0.44},
                                          'second_half': {'away': 0.25,
                                                          'home': 0.89}},
                       'fouls': {'all': {'away': 7, 'home': 12},
                                 'first_half': {'away': 4, 'home': 4},
                                 'second_half': {'away': 3, 'home': 8}},
                       'free_kicks': {'all': {'away': 12, 'home': 7},
                                      'first_half': {'away': 4, 'home': 4},
                                      'second_half': {'away': 8, 'home': 3}},
                       'goalkeeper_saves': {'all': {'away': 4, 'home': 3},
                                            'first_half': {'away': 1,
                                                           'home': 3},
                                            'second_half': {'away': 3,
                                                            'home': 0}},
                       'passes': {'all': {'away': 394, 'home': 639},
                                  'first_half': {'away': 210, 'home': 326},
                                  'second_half': {'away': 184, 'home': 313}},
                       'red_cards': {'all': None,
                                     'first_half': None,
                                     'second_half': None},
                       'shots_on_target': {'all': {'away': 6, 'home': 6},
                                           'first_half': {'away': 5, 'home': 2},
                                           'second_half': {'away': 1,
                                                           'home': 4}},
                       'tackles': {'all': {'away': 23, 'home': 19},
                                   'first_half': {'away': 12, 'home': 11},
                                   'second_half': {'away': 11, 'home': 8}},
                       'total_shots': {'all': {'away': 18, 'home': 14},
                                       'first_half': {'away': 13, 'home': 7},
                                       'second_half': {'away': 5, 'home': 7}},
                       'yellow_cards': {'all': {'away': 3, 'home': 2},
                                        'first_half': {'away': 2, 'home': 0},
                                        'second_half': {'away': 1, 'home': 2}}},
          'passes': {'accurate_crosses': {'all': {'away': 5, 'home': 4},
                                          'first_half': {'away': 3, 'home': 3},
                                          'second_half': {'away': 2,
                                                          'home': 1}},
                     'accurate_long_balls': {'all': {'away': 24, 'home': 34},
                                             'first_half': {'away': 10,
                                                            'home': 15},
                                             'second_half': {'away': 14,
                                                             'home': 19}},
                     'accurate_passes': {'all': {'away': 322, 'home': 553},
                                         'first_half': {'away': 180,
                                                        'home': 282},
                                         'second_half': {'away': 142,
                                                         'home': 271}},
                     'final_third_entries': {'all': {'away': 57, 'home': 68},
                                             'first_half': {'away': 32,
                                                            'home': 30},
                                             'second_half': {'away': 25,
                                                             'home': 38}},
                     'throw_ins': {'all': {'away': 14, 'home': 17},
                                   'first_half': {'away': 7, 'home': 7},
                                   'second_half': {'away': 7, 'home': 10}}},
          'shots': {'blocked_shots': {'all': {'away': 7, 'home': 5},
                                      'first_half': {'away': 6, 'home': 4},
                                      'second_half': {'away': 1, 'home': 1}},
                    'hit_woodwork': {'all': {'away': 0, 'home': 0},
                                     'first_half': {'away': 0, 'home': 0},
                                     'second_half': {'away': 0, 'home': 0}},
                    'shots_inside_box': {'all': {'away': 13, 'home': 7},
                                         'first_half': {'away': 9, 'home': 4},
                                         'second_half': {'away': 4, 'home': 3}},
                    'shots_off_target': {'all': {'away': 5, 'home': 3},
                                         'first_half': {'away': 2, 'home': 1},
                                         'second_half': {'away': 3, 'home': 2}},
                    'shots_on_target': {'all': {'away': 6, 'home': 6},
                                        'first_half': {'away': 5, 'home': 2},
                                        'second_half': {'away': 1, 'home': 4}},
                    'shots_outside_box': {'all': {'away': 5, 'home': 7},
                                          'first_half': {'away': 4, 'home': 3},
                                          'second_half': {'away': 1,
                                                          'home': 4}},
                    'total_shots': {'all': {'away': 18, 'home': 14},
                                    'first_half': {'away': 13, 'home': 7},
                                    'second_half': {'away': 5, 'home': 7}}}}}

In [331]:
# ---------------------------------------------------------
# SAFE STAT EXTRACTOR
# ---------------------------------------------------------

def get_stat(statistics, team_side, stat_name):

    if statistics is None:
        return None


    # Unwrap API "data"
    if isinstance(statistics, dict):

        statistics = statistics.get(
            "data",
            statistics
        )


    if not isinstance(statistics, dict):
        return None


    # -----------------------------------------------------
    # MAP OUR DATASET NAMES TO API STAT NAMES
    # -----------------------------------------------------

    stat_name_map = {

        "expected_goals":
            "expected_goals",

        "shots":
            "total_shots",

        "shots_on_target":
            "shots_on_target",

        "ball_possession":
            "ball_possession",

        "passes":
            "passes",

        "corners":
            "corner_kicks"
    }


    api_stat_name = stat_name_map.get(
        stat_name,
        stat_name
    )


    # -----------------------------------------------------
    # NEW API STRUCTURE:
    # data -> overview -> stat -> all -> home/away
    # -----------------------------------------------------

    overview = statistics.get(
        "overview",
        {}
    )


    if isinstance(overview, dict):

        stat_data = overview.get(
            api_stat_name
        )


        if isinstance(stat_data, dict):

            all_data = stat_data.get(
                "all"
            )


            if isinstance(all_data, dict):

                value = all_data.get(
                    team_side
                )


                if value is not None:
                    return value


    # -----------------------------------------------------
    # FALLBACK FOR OLDER RAW FILE STRUCTURES
    # -----------------------------------------------------

    team_stats = statistics.get(
        team_side,
        {}
    )


    if isinstance(team_stats, dict):

        value = team_stats.get(
            stat_name
        )


        if value is not None:
            return value


    return None

In [332]:
# ---------------------------------------------------------
# TEST UPDATED STAT EXTRACTION
# ---------------------------------------------------------

processed_sample = process_match_file(
    sample_file
)


for column in [
    "home_xg",
    "away_xg",
    "home_shots",
    "away_shots",
    "home_shots_on_target",
    "away_shots_on_target",
    "home_possession",
    "away_possession",
    "home_passes",
    "away_passes",
    "home_corners",
    "away_corners"
]:

    print(
        column,
        processed_sample[column]
    )

home_xg 1.33
away_xg 2.24
home_shots 14
away_shots 18
home_shots_on_target 6
away_shots_on_target 6
home_possession 62
away_possession 38
home_passes 639
away_passes 394
home_corners 6
away_corners 4

In [333]:
# ---------------------------------------------------------
# FINAL CLEAN REBUILD WITH CORRECT STAT EXTRACTION
# ---------------------------------------------------------

rows = []


for file_path in RAW_MATCH_DIR.rglob("*.json"):

    row = process_match_file(
        file_path
    )

    if row is not None:
        rows.append(row)


historical_df = pd.DataFrame(
    rows
)


# ---------------------------------------------------------
# REMOVE DUPLICATES
# ---------------------------------------------------------

historical_df = (
    historical_df
    .drop_duplicates(
        subset="match_id",
        keep="last"
    )
    .copy()
)


# ---------------------------------------------------------
# DATE + SORT
# ---------------------------------------------------------

historical_df["date"] = pd.to_datetime(
    historical_df["date"],
    utc=True,
    errors="coerce"
)


historical_df = (
    historical_df
    .sort_values(
        [
            "date",
            "match_id"
        ]
    )
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# SAVE
# ---------------------------------------------------------

output_path = (
    PROCESSED_DIR
    / "historical_matches.csv"
)


historical_df.to_csv(
    output_path,
    index=False
)


# ---------------------------------------------------------
# CHECK 2026/27 STAT COVERAGE
# ---------------------------------------------------------

check_2026 = historical_df[
    (
        historical_df["competition"]
        == "premier_league"
    )
    &
    (
        historical_df["season"]
        == "2026_27"
    )
].copy()


print(
    "Historical shape:",
    historical_df.shape
)

print(
    "2026/27 PL matches:",
    len(check_2026)
)

print()

print("2026/27 MISSING VALUES")

for column in [
    "date",
    "home_goals",
    "away_goals",
    "home_xg",
    "away_xg",
    "home_shots",
    "away_shots",
    "home_shots_on_target",
    "away_shots_on_target",
    "home_possession",
    "away_possession",
    "home_passes",
    "away_passes",
    "home_corners",
    "away_corners"
]:

    print(
        f"{column}:",
        check_2026[column].isna().sum()
    )


print()

print(
    check_2026[
        [
            "date",
            "home_team",
            "away_team",
            "home_goals",
            "away_goals",
            "home_shots_on_target",
            "away_shots_on_target"
        ]
    ]
    .sort_values("date")
    .to_string(index=False)
)


print()

print(
    "Saved:",
    output_path
)

Historical shape: (10673, 22)
2026/27 PL matches: 20

2026/27 MISSING VALUES
date: 0
home_goals: 0
away_goals: 0
home_xg: 0
away_xg: 0
home_shots: 0
away_shots: 0
home_shots_on_target: 0
away_shots_on_target: 0
home_possession: 0
away_possession: 0
home_passes: 0
away_passes: 0
home_corners: 0
away_corners: 0

                     date              home_team              away_team  home_goals  away_goals  home_shots_on_target  away_shots_on_target
2026-08-21 19:00:00+00:00                Arsenal          Coventry City           3           0                   6.0                   1.0
2026-08-22 11:30:00+00:00              Hull City      Manchester United           2           0                   4.0                   5.0
2026-08-22 14:00:00+00:00                Everton         Crystal Palace           2           0                   5.0                   4.0
2026-08-22 14:00:00+00:00           Ipswich Town             Sunderland           2           1                   3.0                   4.0
2026-08-22 14:00:00+00:00      Nottingham Forest           Leeds United           0           1                   2.0                   3.0
2026-08-22 16:30:00+00:00              Brentford      Tottenham Hotspur           3           0                   8.0                   4.0
2026-08-23 13:00:00+00:00        Manchester City            Bournemouth           2           1                   6.0                   4.0
2026-08-23 13:00:00+00:00 Brighton & Hove Albion            Aston Villa           4           0                   6.0                   0.0
2026-08-23 15:30:00+00:00       Newcastle United              Liverpool           2           2                   4.0                   7.0
2026-08-24 19:00:00+00:00                 Fulham                Chelsea           2           3                   6.0                   6.0
2026-08-28 19:00:00+00:00         Crystal Palace        Manchester City           1           4                   1.0                   9.0
2026-08-29 11:30:00+00:00              Liverpool      Nottingham Forest           2           2                   4.0                   3.0
2026-08-29 14:00:00+00:00          Coventry City              Hull City           0           1                   3.0                   2.0
2026-08-29 14:00:00+00:00            Bournemouth                Everton           1           1                   5.0                   7.0
2026-08-29 16:30:00+00:00      Tottenham Hotspur       Newcastle United           0           2                   6.0                   2.0
2026-08-30 13:00:00+00:00             Sunderland                 Fulham           1           0                   4.0                   0.0
2026-08-30 13:00:00+00:00           Leeds United              Brentford           1           1                   2.0                   5.0
2026-08-30 13:00:00+00:00                Chelsea Brighton & Hove Albion           4           3                   6.0                   6.0
2026-08-30 15:30:00+00:00      Manchester United           Ipswich Town           5           2                  11.0                   5.0
2026-08-31 19:00:00+00:00            Aston Villa                Arsenal           0           1                   0.0                   2.0

Saved: ..\data\processed\historical_matches.csv